falcosecurity/libs

userspace/libscap/linux/scap_linux_platform.c
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
=> fix(scap): turn on cgroup namespace detection.

.circleci/config.yml, .github/workflows/ci.yml, cmake/modules/b64.cmake, userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/marathon_http.cpp, userspace/libsinsp/mesos_http.cpp, userspace/libsinsp/socket_handler.h
/kind cleanup
/area build
/area CI
No
This PR removes the usage of the libb64 library due to its incompatible license. From now on we will use a header-only implementation taken directly from:
https://raw.githubusercontent.com/istio/proxy/1.18.2/extensions/common/wasm/base64.h
```release-note
NONE
```
=> cleanup: use header only b64 library

userspace/libscap/linux/scap_userlist.c
/kind bug
/area libscap
Fixes #1312
```release-note
fix: avoid possible source of double free
```
=> fix(userspace/libscap): avoid possible double free while loading users and groups

cmake/modules/b64.cmake
/kind bug
/kind cleanup
/area build
No
This PR enforce a more safe behavior, setting the b64 include at every cmake rebuild
```release-note
NONE
```
=> chore: enforce `b64` include at every cmake build

userspace/libsinsp/container.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/syscall_async.cpp, userspace/libsinsp/user.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
/area tests
> …
=> fix(libsinsp): race condition in async event

cmake/modules/openssl.cmake
/kind feature
/area build
No
As per title. Fixes the following vulnerabilities:
* [CVE-2023-3817](http://cve.mitre.org/cgi-bin/cvename.cgi?name=2023-3817)
```release-note
chore(cmake): update OpenSSL to 3.1.2
```
=> chore(build): update OpenSSL to 3.1.2

cmake/modules/libelf.cmake
/kind feature
/area build
No.
Update libelf to version 0.189. Fixes the following (potential) vulnerabilities:
* ~[CVE-2021-33294](http://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-33294)~ (edit: my bad, no known vulnerabilities actually affect the current version)
Fixes #
```release-note
update(build): update libelf to 0.189
```
=> chore(build): update libelf to 0.189

userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/linux/scap_fds.c, userspace/libscap/scap_savefile.c, userspace/libsinsp/event.cpp, userspace/libsinsp/threadinfo.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
/area libsinsp
> /area tests
> …
=> fix(libscap,libsinsp): correctly manage memfd in scapfiles

userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/linux/scap_fds.c, userspace/libscap/scap_savefile.c, userspace/libsinsp/event.cpp, userspace/libsinsp/threadinfo.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
/area libsinsp
> /area tests
> …
=> fix(libscap,libsinsp): correctly manage pidfd in scapfiles

test/e2e/tests/commons/sinspqa/sinsp.py, test/e2e/tests/test_process/test_container.py, userspace/libsinsp/examples/test.cpp, userspace/libsinsp/examples/util.cpp, userspace/libsinsp/examples/util.h, userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/parsers.cpp
This PR all but drops the custom output code we have in sinsp-example and switches to using the same formatters as JSON output. This makes sinsp-example output actually useful to look at events (making it a usable replacement for `sysdig` in some scenarios)
It turns out our category->name mapping was incomplete (which we didn't really notice if we used our own in sinsp-example) so I updated that too.
I also added a raw output mode to almost literally dump the raw events in hex.
Sample default output:
```
16:14:39.647872382 cat=memory container=host proc=curl(13267.13267) > mmap addr=0 length=8392704 prot=3(PROT_READ|PROT_WRITE) flags=10(MAP_PRIVATE|MAP_ANONYMOUS) fd=-1(EPERM) offset=0
16:14:39.647881810 cat=memory container=host proc=curl(13267.13267) < mmap res=7F16D533D000 vm_size=0 …
```
=> new(sinsp): rework sinsp-example output

userspace/libsinsp/threadinfo.cpp
This should technically be controlled by the platform, but we're not quite there yet, so as long as we have test_input setups where threads may not have a main thread, disable this assert.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
=> fix(sinsp): disable get_cwd assert, it breaks tests with non-live platforms

driver/ppm_fillers.c
/kind bug
Leverage `get_file_rcu` being a define to use the safer version of `get_mm_exe_file`.
This will allow kernel versions prior to 4.1, but with the fix being backported don't suffer RCU violations.
Fixes #
```release-note
fix(kmod): safer ppm_get_mm_exe_file
```
=> fix(kmod): safer ppm_get_mm_exe_file

.github/workflows/ci.yml, driver/ppm_fillers.c
/kind cleanup
Backports 
from master.
Fixes #
```release-note
sync: release 0.13.x
```
=> sync: release 0.13.x

.github/workflows/release-body.yml
/kind bug
/area CI
Per https://github.com/actions/runner/issues/662, `exit 0` won't skip subsequent jobs. Instead, we will need to forcefully skip the workflow.
https://stackoverflow.com/a/75809743/6065692
`release-body` was creating releases when `kernel-tests` workflow was triggered against any branch since it failed to exit.
Fixes #
```release-note
NONE
```
=> fix(ci): properly skip release-body workflow in non-drivers tags.

.github/workflows/latest-kernel.yml, driver/bpf/fillers.h, driver/modern_bpf/definitions/missing_definitions.h, driver/modern_bpf/definitions/struct_flavors.h, driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c, driver/ppm_fillers.c
/kind bug
See https://github.com/torvalds/linux/commit/13bc24457850583a2e7203ded05b7209ab4bc5ef
Fixes #
```release-note
fix(driver): fixed build against linux v6.6.
```
=> fix(driver): fixed build against 6.6 rc kernel.

userspace/libsinsp/container_engine/docker/async_source.cpp, userspace/libsinsp/container_engine/docker/connection.h, userspace/libsinsp/container_engine/docker/connection_linux.cpp
Add an escape clause on the container lookup path to make sure we're not just constantly getting timeouts.
/kind bug
/area libsinsp
```release-note
NONE
```
=> fix(libsinsp): Don't loop forever on container api

userspace/libscap/engine/source_plugin/source_plugin.c, userspace/libscap/linux/scap_machine_info.c, userspace/libsinsp/sinsp.cpp
/kind bug
/kind cleanup
/area libscap-engine-source-plugin
/area libscap
No
This PR adds a better error message when the "/proc" folder is not available (probably a wrong env variable HOST_ROOT is passed). Moreover, it fixes a segfault in the source plugin engine
Fixes #1358
```release-note
NONE
```
=> fix(userspace): avoid a segmentation fault when `m_input_plugin` is not  initialized

CMakeLists.txt, cmake/modules/libscap.cmake, userspace/libscap/CMakeLists.txt, userspace/libscap/engine/savefile/CMakeLists.txt, userspace/libscap/libscap.pc.in, userspace/libscap/settings.h
/kind feature
/area build
Historically, the minimal build was only able to run using the kernel module driver, but since the addition of the modern probe this has also become an option for running with minimal builds. I believe there's value in allowing adopters of the libs to use the minimal build with the eBPF probe.
This change means that scap will always be linked against zlib and libelf, but I believe this is a worthwhile trade off.
Fixes #
```release-note
NONE
```
=> build(minimal-build): allow using eBPF driver with minimal builds

userspace/libpman/src/ringbuffer.c, userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/kmod/scap_kmod.c
/kind bug
Moreover, made kmod loop more robust too.
Basically, in ebpf, do not care if some `/sys/devices/system/cpu/cpuX` folders are not present, even if configured cpus state they should be present.
All we need is for the count of online CPUs to be the same as `_NPROCESSORS_ONLN` (this is the same assumption we made in kmod and modern bpf engines!).
See https://github.com/falcosecurity/falco/issues/2843
Fixes #
```release-note
NONE
```
=> fix(userspace/libscap): fixed ebpf init loop on online CPUs.

userspace/libsinsp/test/events_fspath.ut.cpp, userspace/libsinsp/test/events_net.ut.cpp, userspace/libsinsp/test/events_plugin.ut.cpp, userspace/libsinsp/test/events_proc.ut.cpp, userspace/libsinsp/test/filterchecks/proc.cpp, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind feature
/area tests
No
The actual `field_exists` helper is not checking only the field existence but also its value, more in detail it checks that its value is not NULL. Sometimes, mainly with plugins, we want only to know if the field exists or not, and right now it's not possible, actual `field_exists` returns an exception if a field is not defined.
This PR renames the actual `field_exists` helper to `field_has_value` and adds a new helper called `field_exists` that checks only the field existence …
=> new(tests): change meaning to actual `field_exists` test helper

driver/modern_bpf/CMakeLists.txt
/kind cleanup
/area build
For most use cases, bpftool version checking works fine, However, when using bpftool compiled from a kernel with backported patches, the version might not be the most reliable way to see if the required capabilities are avilable. As an example, RHEL 8.8 uses a bpftool with versions that match 4.18, but because of it having backported patches the modern probe can be compiled without errors. With this patch we move from checking a specific version to trying to catch if bpftool supports the gen command.
Fixes #
**Special notes …
=> build(modern_bpf): relax bpftool version test.

driver/bpf/fillers.h, driver/ppm_events.c, driver/ppm_fillers.c
/kind bug
/kind cleanup
No I do not think so.
Make driver code more consistent.
part of #902
Tagging @dwindsor for visibility.
```release-note
NONE
```
=> cleanup(drivers): driver inconsistencies CHECK_RES

userspace/libsinsp/filterchecks.cpp
/kind cleanup
/area libsinsp
This removes a redundant `ifndef`.
Fixes #
```release-note
NONE
```
=> cleanup(userspace/libsinsp/filterchecks.cpp): remove useless ifndef

userspace/chisel/chisel.cpp, userspace/chisel/chisel_api.cpp, userspace/chisel/chisel_table.cpp, userspace/libsinsp/eventformatter.cpp, userspace/libsinsp/eventformatter.h, userspace/libsinsp/examples/test.cpp, userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/filter_check_list.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/eventformatter.ut.cpp, userspace/libsinsp/test/filter_compiler.h, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind cleanup
/area libsinsp
This removes `g_filterlist` from the codebase. It has not been used by Falco since one year, and its existence is now effectively wrong considering the plugin system due to which filtercheck lists are now dynamic. Having a static global list is also wrong for memory allocation guarantees, is error prone, and pollutes many API methods of libsinsp.
```release-note
refactor(userspace/libsinsp): remove g_filterlist
```
=> refactor(userspace/libsinsp): remove g_filterlist

driver/bpf/fillers.h
/kind bug
See kernel testing matrix on amd64 in master: https://falcosecurity.github.io/libs/matrix_X64/#fedora-58-bpf-probe_scap-open
Fixes #
```release-note
fix(driver/bpf): fixed fedora-5.8 bpf verifier.
```
=> fix(driver/bpf): fixed fedora-5.8 bpf verifier.

README.md, driver/CMakeLists.txt, driver/feature_gates.h, driver/ppm.h, driver/syscall_compat_riscv64.h, driver/syscall_table64.c, test/drivers/test_suites/actions_suite/dynamic_snaplen.cpp, test/drivers/test_suites/generic_tracepoints_suite/sched_process_fork.cpp, test/drivers/test_suites/syscall_enter_suite/clone_e.cpp, test/drivers/test_suites/syscall_exit_suite/clone_x.cpp, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp
> /kind bug
> /kind design
/kind feature
/area build
> /area CI
/area tests
> …
=> feat(driver-kmod): Add RISC-V kernel module support

test/drivers/event_class/event_class.cpp, test/drivers/test_suites/syscall_exit_suite/mknod_e.cpp, test/libscap/helpers/engines.cpp, userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/gvisor/gvisor.cpp, userspace/libscap/engine/gvisor/gvisor.h, userspace/libscap/engine/gvisor/scap_gvisor.cpp, userspace/libscap/engine/kmod/scap_kmod.c, userspace/libscap/engine/modern_bpf/scap_modern_bpf.c, userspace/libscap/engine/nodriver/nodriver.c, userspace/libscap/engine/noop/noop.c, userspace/libscap/engine/noop/noop.h, userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/engine/source_plugin/source_plugin.c, userspace/libscap/engine/test_input/test_input.c, userspace/libscap/engine/udig/scap_udig.c, userspace/libscap/examples/01-open/scap_open.c, userspace/libscap/ringbuffer/ringbuffer.h, userspace/libscap/scap.c, userspace/libscap/scap.h, userspace/libscap/scap_vtable.h, userspace/libsinsp/event.cpp, userspace/libsinsp/event.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
The event flags are (currently) specific to the savefile engine but accessing them requires an awkward reacharound through a dedicated vtable method to a field stored on each call to next().
We can simplify this a bit and express the intent better by simply returning the flags from next() via an out pointer.
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area …
=> cleanup(scap,sinsp): return event flags directly

.github/workflows/latest-kernel.yml, driver/bpf/fillers.h, driver/modern_bpf/definitions/missing_definitions.h, driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c
/kind bug
Fixes build against linux 6.6, partly reverting https://github.com/falcosecurity/libs/pull/1349.
The kernel changes that https://github.com/falcosecurity/libs/pull/1349 addressed were dropped at the `rc3` kernel stage, and we do not need them anymore (https://www.phoronix.com/news/Linux-Revert-MG-Timestamps).
We are not at kernel rc6, therefore we expect the 6.6 release next week and no further breaking changes.
Basically, `I_CTIME_QUERIED` disappeared from kernel sources at `rc3`.
Fixes # …
=> fix(driver): fixed build against linux 6.6.

userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/kmod/scap_kmod.c, userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
/kind bug
/kind cleanup
No
Doing these checks in the init method could cause some issues. For example in the kernel module engine, an old driver with different IOCTL codes could be loaded and if we use IOCTL codes before checking the compatibility we could face a not user-friendly error. For this reason, we move this `mark_syscall` check when the `check_api_compatibility` method is already called by scap. …
=> fix(libscap/engines): move some checks in `start_capture`

userspace/libpman/src/configuration.c
/kind bug
No
This PR performs a more detailed check on the `BPF_TRACE_RAW_TP` attach type. Actual `libbpf_probe_bpf_prog_type(BPF_PROG_TYPE_TRACING, NULL)` checks for the `BPF_TRACE_FENTRY` attach type presence, while we need to check for the `BPF_TRACE_RAW_TP` one. If `BPF_TRACE_FENTRY` is defined we are sure `BPF_TRACE_RAW_TP` is defined as well, in all other cases, we need to search for it in the `vmlinux` file.
See https://github.com/falcosecurity/falco/issues/2792 …
=> fix(modern): perform an exact check on `BPF_TRACE_RAW_TP` attach type

userspace/libsinsp/sinsp.cpp
/kind bug
/area libsinsp
Avoid returning SCAP_SUCCESS without setting `*puevt` pointed data.
Refs https://github.com/falcosecurity/falco/issues/2878
```release-note
fix(userspace/libsinsp): avoid possible source of segfault in sinsp::next
```
=> fix(userspace/libsinsp): avoid a possible source of segfault in sinsp::next

cmake/modules/libscap.cmake, driver/main.c, userspace/libscap/scap.c, userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/events/sinsp_events_set.h, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_evtin.cpp, userspace/libsinsp/sinsp_filtercheck_fdlist.cpp, userspace/libsinsp/test/classes/sinsp_thread_manager.cpp, userspace/libsinsp/test/classes/sinsp_threadinfo.cpp, userspace/libsinsp/test/events_proc.ut.cpp, userspace/libsinsp/test/scap_files/kexec_arm64/kexec_arm64.cpp, userspace/libsinsp/test/scap_files/kexec_x86/kexec_x86.cpp, userspace/libsinsp/test/thread_table.ut.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind cleanup
/area libscap
/area libsinsp
NO
This is a collection of minor cleanups across the whole codebase, mostly relate to missing cmake includes, nullptr checks (peculiarly important after the recent refactor from @Andreagit97), and resolution of compilation warnings.
```release-note
NONE
```
=> update: collection of minor cleanups across the codebase

.github/workflows/ci.yml, userspace/libscap/compat/misc.h, userspace/libsinsp/test/user.ut.cpp
/kind bug
/area CI
/area libscap
In Falco our build pipeline prevents us from bumping the libs due to a failure in the MUSL static build. This PR attempts fixing that and also adds a CI job covering that compilation case for preventing future regressions.
```release-note
NONE
```
=> fix(userspace/libscap): add a CI job for musl static builds and fix issues with it

userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/test/filterchecks/evt.cpp
/kind bug
/area libsinsp
Fixes an issue preventing the print of rawarg.
Before:
```
sudo ./libsinsp/examples/sinsp-example -m -f "evt.type=setuid and evt.dir=>" -o "arg=%evt.rawarg.uid"
-- Filter AST (2) ppm sc names: setuid, setuid32
-- Try to open: 'modern_bpf' engine.
-- Engine 'modern_bpf' correctly opened.
-- Start capture
arg=
arg=
arg=
```
Because print_format is `PF_NA`.
After:
```
sudo ./libsinsp/examples/sinsp-example -m -f "evt.type=setuid and evt.dir=>" -o "arg=%evt.rawarg.uid"
-- Filter AST (2) ppm sc names: setuid, setuid32
-- Try to open: 'modern_bpf' engine.
-- Engine 'modern_bpf' correctly opened.
-- Start capture
arg=0
arg=1000
arg=1000
```
and …
=> fix(userspace/libsinsp): properly inherit rawarg PT_DYN print format.

driver/ppm.h, driver/ppm_events.c, driver/ppm_fillers.c
/kind bug
/kind cleanup
No.
Use more consistent types and standards across the dirver code base.
part of #902
Tagging @dwindsor @incertum  for visibility.
```release-note
NONE
```
=> cleanup(driver): create consistencies (syscall_arg_t)

driver/ppm_fillers.c
/kind bug
/kind cleanup
No.
Make driver code more consistent.
part of #902
Tagging @dwindsor for visibility.
```release-note
NONE
```
=> cleanup(driver/ppm_fillers.c): create consistencies (s32 to int32_t)

userspace/libpman/src/configuration.c, userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/sinsp.cpp
/kind cleanup
This PR cherry picks:
* https://github.com/falcosecurity/libs/pull/1404
* https://github.com/falcosecurity/libs/pull/1423
Also, part of https://github.com/falcosecurity/libs/pull/1428 is manually cherry picked since https://github.com/falcosecurity/libs/pull/1424 moved stuff around.
I only cherry picked 7326e56429b51dd1e72eb30e6794c3d8f2b13e96.
Fixes #
```release-note
NONE
```
=> sync: release0.13.x

driver/ppm_fillers.c
/kind bug
> /kind design
> /area build
> /area CI
> /area tests
> …
=> fix(driver): move declarations before code

driver/ppm_events.c
/kind bug
/kind cleanup
No.
Make driver code more consistent. ( All s/u int types -> int_t types)
part of #902
Fixes all integer types in this file
Tagging @dwindsor @incertum  for visibility.
```release-note
NONE
```
=> cleanup(driver/ppm_events.c): create consistencies(all integer types)

driver/ppm_fillers.c
/kind bug
/kind cleanup
No.
Make driver code more consistent. (u16 -> uint16_t)
part of #902
Going to be gradually creating integer consistency across the codebase. Best to keep the reviews small.
Tagging @dwindsor for visibility.
```release-note
NONE
```
=> cleanup(driver/ppm_fillers.c): create consistencies (u16 to uint16_t)

userspace/libsinsp/plugin.cpp
/kind bug
> /kind design
/area build
> /area CI
/area libsinsp
> /area tests
> …
=> fix(libsinsp): ignore maybe-uninitialized for valijson

driver/ppm_fillers.c
/kind bug
/kind cleanup
No.
Make driver code more consistent. ( All s/u int types -> int_t types)
Finishes ppm_fillers
part of #902
Fixes all integer types in this file
Tagging @dwindsor @incertum  for visibility.
```release-note
NONE
```
=> cleanup(driver/ppm_fillers.c): resolve inconsistent integer types

userspace/libscap/engine/bpf/scap_bpf.c
/kind bug
`alloc_handle()` doesn't initialize `engine->m_attached_progs[j].efd` to `-1`, which leads to `detach_bpf_prog()` closing those file descriptors which are equal to `0` unexpectedly.
Fixes #1448
```release-note
NONE
```
=> fix(userspace/libscap): initialize bpf_engine.m_attached_progs.efd to -1

userspace/libscap/linux/scap_procs.c
/kind bug
/area libscap
No
This PR fixes a memory leak problem.
I built `sinsp-example` from master (2d118d79e59576b2f1341798a56032b0bdf3b9cb) and tested it by following command line:
```bash
valgrind --leak-check=yes ./sinsp-example -b probe.o -f "evt.type = execve and evt.dir = < and container.id != host and proc.name = bash"
```
The output of valgrind indicated that there were some memory leaked:
```
==428618==
==428618== 346,048 (1,120 direct, 344,928 indirect) bytes in 1 blocks are definitely lost in loss record 175 of 177
==428618==    at 0x4C3BE4B: calloc (vg_replace_malloc.c:1328)
==428618==    by …
```
=> fix(userspace/libscap): fix memleak in scap_linux_get_fdlist

userspace/libsinsp/sinsp.cpp
They're not ours to free (they may be stack allocated, for example)
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /area …
=> fix(sinsp): don't free scap_threadinfo/scap_fdinfo in proc callback

userspace/libsinsp/container.cpp, userspace/libsinsp/mpsc_priority_queue.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/events_injection.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/user.cpp, userspace/plugin/plugin_api.h
/kind feature
/area libsinsp
This is effectively a new feature. A friction that we discovered having when generating async events, is not being able to control their timestamp.
Currently, async event producers are "passive" from this perspective, and are not able to specify any timestamp at all. The current behavior is to have multiple (potentially concurrent) async event producers, and one single consumer that is the inspector listening and owning the async queue. This is used for container events, user/group events, and plugin async events. When an event is popped from the queue by the inspector, it is …
=> update(userspace/libsinsp): support timestamp priority in async event injection

cmake/modules/grpc.cmake
/kind bug
/area build
Restore CMAKE_MAKE_PROGRAM for grpc, since it gets built with cmake and inherits the generator
Fixes #
```release-note
NONE
```
=> fix: grpc ninja build

test/drivers/start_tests.cpp, test/libscap/test_suites/engines/bpf/bpf.cpp, test/libscap/test_suites/engines/kmod/kmod.cpp, test/libscap/test_suites/engines/modern_bpf/modern_bpf.cpp, userspace/libscap/CMakeLists.txt, userspace/libscap/engine/savefile/savefile.h, userspace/libscap/engine/savefile/savefile_public.h, userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/examples/01-open/scap_open.c, userspace/libscap/examples/02-validatebuffer/test.c, userspace/libscap/scap-int.h, userspace/libscap/scap.c, userspace/libscap/scap.h, userspace/libscap/scap_platform_api.c, userspace/libscap/scap_platform_api.h, userspace/libsinsp/dumper.cpp, userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/threadinfo.cpp
> /kind bug
/kind cleanup
/kind design
> /area build
> /area CI
/area libscap
/area libsinsp
> /area tests
> …
=> cleanup(scap): remove platform handle from scap_t

userspace/libscap/scap.def, userspace/libscap/scap_platform_api.c, userspace/libscap/scap_platform_api.h, userspace/libscap/scap_savefile.c, userspace/libscap/scap_savefile_api.h, userspace/libsinsp/dumper.cpp, userspace/libsinsp/dumper.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/savefile.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
/area libsinsp
> /area tests
> …
=> cleanup(sinsp,scap): switch to sinsp thread table for savefiles

test/drivers/start_tests.cpp, test/libscap/test_suites/engines/modern_bpf/modern_bpf.cpp, userspace/libscap/engine/modern_bpf/modern_bpf_public.h, userspace/libscap/examples/01-open/scap_open.c, userspace/libsinsp/sinsp.cpp
/kind cleanup
/area tests
No
This PR removes the  no longer used `verbose` option from the modern bpf engine and adds 2 logs functions for tests and scap-open to avoid log pollution during debugging
```release-note
NONE
```
=> cleanup(modern_bpf): remove a no longer useful option in the modern bpf engine and introduce some logging functions

test/drivers/test_suites/syscall_exit_suite/send_x.cpp, test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
/kind bug
/area tests
No
Fixes #
- Adds semicolon after `int flags=0` in send_x.cpp
- Adds missing declaration for `int64_t errno_value = -errno;` in socketcall_x.cpp
```release-note
NONE
```
=> fix(test): Fix small bugs in send_x and socketcall_x

userspace/libscap/engine/gvisor/gvisor.cpp, userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/engine/test_input/test_input_platform.c, userspace/libscap/linux/scap_fds.c, userspace/libscap/linux/scap_linux_int.h, userspace/libscap/linux/scap_linux_platform.c, userspace/libscap/linux/scap_procs.c, userspace/libscap/scap-int.h, userspace/libscap/scap.c, userspace/libscap/scap.h, userspace/libscap/scap_fds.c, userspace/libscap/scap_platform.c, userspace/libscap/scap_platform_api.c, userspace/libscap/scap_platform_api.h, userspace/libscap/scap_platform_impl.h, userspace/libscap/scap_proc_util.c, userspace/libscap/scap_proc_util.h, userspace/libscap/scap_procs.c, userspace/libscap/scap_procs.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/threadinfo.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
/area libsinsp
> /area tests
> …
=> cleanup(scap,sinsp): Clean up proc callback handling code

userspace/libsinsp/event.cpp, userspace/libsinsp/utils.cpp
/kind cleanup
/area libsinsp
No
One (of many) changes for this: https://github.com/falcosecurity/libs/issues/1470 . In this case, we're removing a few warnings that are not concerning `get_param()`. We will be back with more refactorings there.
Fixes #
```release-note
NONE
```
=> cleanup(libsinsp): remove a few more UB warnings from integer copies

userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_tracer.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> cleanup(libsinsp): substitute static g_screen_w

cmake/modules/zlib.cmake, userspace/libscap/scap_zlib.h, userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/test/CMakeLists.txt
/kind cleanup
/area build
Since https://github.com/falcosecurity/libs/pull/1325, we now link and use zlib also when in MINIMAL_BUILD. Our windows build relies on MINIMAL_BUILD too, so now my question was: why are we not using zlib on windows too? Turns out there are some linking issues involved, which hopefully this PR will solve.
```release-note
fix(cmake): solve win32 linking issues with zlib
```
=> fix(cmake): solve win32 linking issues with zlib

cmake/modules/openssl.cmake
/kind feature
/area build
As per title. Update OpenSSL with the latest security fixes.
Fixes #
```release-note
NONE
```
=> update(build): upgrade openssl to 3.1.4

userspace/libsinsp/mpsc_priority_queue.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/events_injection.ut.cpp, userspace/libsinsp/test/mpsc_priority_queue.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind bug
/kind cleanup
The current async queue implementation introduces a data race that can cause the ordering guarantee of the queue to not be respected when using `pop_if`. Also, using a lambda for encoding the predicate can cause (depending on the compiler) an extra heap allocation for storing the lambda's closure, which would happen in the critical path every time we attempt popping from the async queue with a predicate. Unit tests have been refactored to avoid being flaky. …
=> update(userspace/libsinsp): fix data race in async event queue and avoid potential extra allocation

userspace/libsinsp/event.h
/kind cleanup
/kind feature
/area libsinsp
Adds a minor factory method for sinsp events that can be useful when crafting a new event that owns the memory of scap event mem buf.
```release-note
update(userspace/libsinsp): add factory method for sinsp_evt from a given scap buffer
```
=> update(userspace/libsinsp): add factory method for sinsp_evt from a given scap buffer

userspace/libsinsp/stats.cpp
/kind cleanup
/area libsinsp
No
Tiny refactor of the stats implementation:
* Use fixed size ints (uint64_t) when reading status files
* Use the corresponding format specifier for fixed size ints (guarding against compilation warnings)
* Remove an assert on a condition that may actually happen (it does when you run UTs, especially as non-root)
cc @incertum @jasondellaluce 
Fixes #
```release-note
NONE …
```
=> cleanup(libsinsp): add scanf formats and fixed size variables in stats.cpp

userspace/libsinsp/mpsc_priority_queue.h, userspace/libsinsp/test/mpsc_priority_queue.ut.cpp
/kind feature
/area libsinsp
The multi-producer-single-consumer queue follows the given priority order and is used for ordering by timestamp async events in the async queue (with `-1` being the dummy timestamp with max priority, representing "pop as soon as possible" events).
Elements with the same timestamp do not follow a specific order. However, this is a bug and a breaking changes compared to the previous behavior, in which all elements had `-1` timestamp and followed the order in which they were pushed in the queue. This PR fixes and tests this behavior by making sure that elements with the same …
=> fix(userspace/libsinsp): elems in mpsc queue with same priority follow push order

driver/bpf/fillers.h, driver/bpf/probe.c, driver/main.c, driver/modern_bpf/helpers/interfaces/syscalls_dispatcher.h, driver/modern_bpf/programs/attached/dispatchers/syscall_enter.bpf.c, driver/modern_bpf/programs/attached/dispatchers/syscall_exit.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/generic.bpf.c, driver/socketcall_to_syscall.h, test/drivers/test_suites/actions_suite/ia32.cpp.in, test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
/kind bug
Uniformed: modern-bpf was already doing that after all.
Moreover, properly send correct converted syscall ID for generic fillers in ia32 mode (instead of sending 32bit ID).
Fixes #
Thanks to @ZhiyuanXin that discovered the issue ( #1498)
```release-note
NONE
```
=> fix(driver,test): drop `socketcall`s called with wrong `SYS_` argument in all 3 drivers

userspace/libsinsp/test/events_injection.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind cleanup
/area libsinsp
/area tests
No
It was not possible to send async events to the inspector from the `sinsp_with_test_input` test class, as it only supported sending regular events. This PR includes a new function `add_async_event()` to do exactly this, and updates the relevant tests. This should make it easier to write tests that involve async events.
Also, this removes potential UB in the code that was generating the async event so that we get closer to solving https://github.com/falcosecurity/libs/issues/1470 …
=> update(libsinsp/tests): support async event generation from sinsp_with_test_input

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
/kind cleanup
/area libsinsp
This PR aims to ultimately have only one way in the inspector for injecting asynchronous meta-events. The only piece remaining using the old approach was the generator of internal PROCINFO events. This has now been ported to the async event queue approach.
```release-note
NONE
```
=> refactor(userspace/libsinsp): remove old meta events implementation

userspace/libsinsp/sinsp_syslog.cpp, userspace/libsinsp/sinsp_syslog.h
/kind bug
/area libsinsp
No.
In the new syslog implementation sometimes we would return references to strings that may be stack-allocated and not coming from static memory or the containing object. I propose to copy those strings directly. I don't think the performance impact is relevant in this case.
Fixes #
```release-note
NONE
```
=> fix(libsinsp): return strings in syslog when they may be stack-allocated

driver/bpf/fillers.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/dup3.bpf.c, driver/ppm_fillers.c, driver/ppm_flag_helpers.h, test/drivers/test_suites/syscall_enter_suite/dup3_e.cpp, userspace/libscap/engine/gvisor/parsers.cpp
/kind bug
/kind cleanup
I am not sure about this.
I am trying to address the issue where dup3 is handling the flag params as an unsigned integer when it should be handling it as in int.
part of #515 
(partial fix other issues still remain in 515)
```release-note
NONE
```
=> cleanup(dup3): fix flags param

userspace/chisel/chisel_api.cpp, userspace/libsinsp/event.cpp, userspace/libsinsp/event.h, userspace/libsinsp/examples/util.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin_manager.h, userspace/libsinsp/sinsp_debug/sinsp_debug.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/sinsp_filtercheck_fdlist.cpp, userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/sinsp_observer.h, userspace/libsinsp/sinsp_syslog.cpp, userspace/libsinsp/sinsp_syslog.h, userspace/libsinsp/test/events_param.ut.cpp, userspace/libsinsp/test/events_proc.ut.cpp
/kind cleanup
/area libsinsp
No
This PR continues an effort to clean up libsinsp from potential undefined behavior (see: https://github.com/falcosecurity/libs/issues/1470 ). It implements the following refactoring changes:
* Added some const correctness around the code that handles `sinsp_evt_param`s. When some raw parameter data is read from the driver it is never modified and so it should be `const` when processed.
* Modified the `sinsp_evt` class and `sinsp_evt_param`. Now `sinsp_evt_param` has more reasons to exist …
=> refactor(libsinsp): safer parameter handling part 2

userspace/libscap/engine/test_input/test_input.c
/kind bug
/area tests
No
When the engine test doesn't produce any events but receives events from an async plugin the events in the queue are never processed because the test engine in `fetch_next_event` will always return `SCAP_EOF` and so the events will be never dequeued...
```cpp
int32_t res = SCAP_SUCCESS;
if (m_delayed_scap_evt.empty())
{
res = m_delayed_scap_evt.next(m_h);
}
if (res == SCAP_TIMEOUT &&
!m_async_events_queue.empty() && m_async_events_queue.try_pop(m_async_evt))
{
evt = m_async_evt.get();
if(evt->m_pevt->ts == (uint64_t) -1)
{
evt->m_pevt->ts = get_new_ts();
}
return SCAP_SUCCESS;
}
``` …
=> fix(tests): return  `SCAP_TIMEOUT` instead of an `SCAP_EOF`

driver/bpf/fillers.h, driver/modern_bpf/helpers/extract/extract_from_kernel.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/flock.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/setns.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/unshare.bpf.c, driver/ppm_fillers.c, driver/ppm_flag_helpers.h, userspace/libscap/engine/gvisor/parsers.cpp
/kind bug
/kind cleanup
I am not sure about this.
I am trying to address the issue where **flock, unshare, and setns** is handling the flag params as an unsigned integer when it should be handling it as in int.
part of #515 
(partial fix other issues still remain in 515)
```release-note
NONE
```
=> cleanup: params inconsistencies

cmake/modules/CompilerFlags.cmake, test/libscap/test_suites/engines/gvisor/gvisor_parsers.cpp, userspace/chisel/chisel_viewinfo.cpp, userspace/chisel/chisel_viewinfo.h, userspace/libscap/engine/gvisor/gvisor.cpp, userspace/libscap/engine/gvisor/gvisor.h, userspace/libscap/engine/gvisor/parsers.cpp, userspace/libscap/engine/gvisor/runsc.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind cleanup
/area build
no
The build of this library, when performed with warnings-as-errors enabled, suppresses a number of warnings to be able to get to the end of the build successfully. Some of these suppressions are best avoided and the root cause addressed in order not to have the warnings in the first place. The rationale is that, though more restrictive, compiler warnings are a way to keep code more closely checked and, ultimately, at a higher quality.
FTR, the warnings that the PR re-enables are the following.
- `missing-field-initializers`
- `type-limits`
Fixes # …
=> build: remove some warning suppressions

userspace/libscap/linux/scap_procs.c, userspace/libsinsp/container.cpp, userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/threadinfo.cpp
/kind bug
/area libscap
/area libsinsp
I was able to run a bunch of experiments on the current mainline and came up with few bugs that caused inconsistencies or segfaults.
```release-note
NONE
```
=> fix(userspace): solving batch of recent regressions

userspace/libsinsp/test/CMakeLists.txt
/kind feature
/area tests
No
Extending the sinsp test framework allowing to link external files and add external includes could become very handy when using the libs repo as a submodule to implement some plugin e2e tests
```release-note
NONE
```
=> new(tests): extending the sinsp test framework allowing to link external files

userspace/libsinsp/dns_manager.h
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp): memleak in sinsp_dns_manager

userspace/libsinsp/container.cpp, userspace/libsinsp/container.h, userspace/libsinsp/event.h, userspace/libsinsp/eventformatter.cpp, userspace/libsinsp/eventformatter.h, userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/filter_check_list.cpp, userspace/libsinsp/filter_check_list.h, userspace/libsinsp/gen_filter.cpp, userspace/libsinsp/gen_filter.h, userspace/libsinsp/prefix_search.cpp, userspace/libsinsp/prefix_search.h, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_filtercheck_event.h, userspace/libsinsp/sinsp_filtercheck_evtin.cpp, userspace/libsinsp/sinsp_filtercheck_evtin.h, userspace/libsinsp/sinsp_filtercheck_gen_event.cpp, userspace/libsinsp/sinsp_filtercheck_gen_event.h, userspace/libsinsp/sinsp_filtercheck_tracer.cpp, userspace/libsinsp/sinsp_filtercheck_tracer.h, userspace/libsinsp/token_bucket.cpp, userspace/libsinsp/token_bucket.h
/kind bug
/kind cleanup
/area libsinsp
I noticed we have a bunch of classes inheriting from others that haven't defined their destructor as virtual. Not doing so makes it very unpredictable to know _which_ destructor is actually invoked at object disposal time. In general this causes segfaults or memory leaks. Looking at the code, I don't think this can be the cause of any time-growing memory leak in Falco, but my bet is that this eats some extra bytes when loading rules when not necessary. For other clients of the libs, this can potentially cause subtle issues.
**Special …
=> fix(userspace/libsinsp): make sure all destructors are invoked

userspace/libsinsp/parsers.cpp
/kind bug
/area libsinsp
This attempts amending a regression in the resolution logic of containers, introduced in https://github.com/falcosecurity/libs/pull/1520.
It took me a couple of hours to figure this out. @incertum can you provide some context of what was the intention of this specific change? From my understanding this has the potential of entirely disabling support to containers.
```release-note
NONE
```
=> fix(userspace/libsinsp): restore support to containers

userspace/libsinsp/utils.cpp
/kind bug
/area libsinsp
This zero-initializes a variable in the time parsing/formatting utility functions. This supposedly a regression after the recent compiler warning related cleanups (cc @federico-sysdig for visibility).
```release-note
NONE
```
=> fix(userspace/libsinsp): zero-init time before string parsing

test/drivers/test_suites/syscall_enter_suite/socketcall_e.cpp, test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area tests
> /version …
=> fix(test/drivers): correct socketcall SYS_ACCEPT failures on s390x

CMakeLists.txt, userspace/libsinsp/sinsp_filtercheck_k8s.cpp, userspace/libsinsp/test/filterchecks/k8s.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind feature
/area libsinsp
/area tests
No
This PR should address the changes required here https://github.com/falcosecurity/libs/pull/1489#pullrequestreview-1755900817 @leogr @incertum. Let me know if we want to proceed in this way. If we agree on these changes, I will close https://github.com/falcosecurity/libs/pull/1489
This should be a breaking change since we are changing the behavior of `k8s.pod.ip` and `k8s.pod.cni.json` fields. Now they return something different from `<NA>` only if we are in a k8s pod, like all the others `k8s.` …
=> update(libsinsp)!: `k8s.` fields return a value only when we are in a k8s pod

cmake/modules/libbpf.cmake, driver/modern_bpf/CMakeLists.txt, driver/modern_bpf/helpers/extract/extract_from_kernel.h, userspace/libpman/src/ringbuffer.c, userspace/libpman/src/ringbuffer_definitions.h
/kind feature
/area libpman
No
This PR bumps libbpf to `v1.3.0` and should finally fix https://github.com/falcosecurity/libs/issues/1157. Moreover, this PR removes the workaround introduced here https://github.com/falcosecurity/libs/pull/1160 for COS systems, this is no longer needed since the solution is now provided directly from libbpf
Fixes #1157
How to test:
```bash
sudo setcap CAP_PERFMON,CAP_BPF,CAP_SYS_RESOURCE=+ep ./libscap/examples/01-open/scap-open
./libscap/examples/01-open/scap-open --modern_bpf
```
should work without issues …
=> chore(libbpf): bump libbpf to `v1.3.0`

userspace/libsinsp/sinsp_filtercheck_thread.cpp
In a scap file I have here, minfo->num_cpus is 0 when sinsp_filter_check_thread::extract_exectime is called. We handle this in debug builds with an ASSERT, but need to check for this in release builds as well. Bail out early if we either have no CPUs or if minfo is NULL.
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area …
=> fix(libsinsp): Add a CPU count check

driver/bpf/fillers.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/linkat.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/unlinkat.bpf.c, driver/ppm_fillers.c, driver/ppm_flag_helpers.h
/kind bug
/kind cleanup
I am not sure about this.
I am trying to address the issue where linkat and unlinkat is handling the flag params as an unsigned integer when it should be handling it as in int.
part of #515 
(partial fix other issues still remain in 515)
```release-note
NONE
```
=> cleanup(driver): unlinkat & linkat flags

.github/workflows/ci.yml
/kind bug
/area CI
No
The current libs master is broken because in `build-shared-libs-linux-amd64` job `KERNELDIR=...` leads to a wrong path. In this PR I've tried to remove  `KERNELDIR=`  from all jobs since by default we set `KERNELDIR ?= /lib/modules/$(shell uname -r)/build` and this should be enough for all jobs... let's see what happens
```release-note
NONE
```
=> fix(CI): remove `KERNELDIR=` since the default should be enough

.github/workflows/ci.yml
/kind bug
/area CI
No
This PR partially reverts https://github.com/falcosecurity/libs/commit/404e6491b83944653b251cff29523bd2defe898e since `KERNELDIR` is still needed when using QEMU as you can see from this PR https://github.com/falcosecurity/libs/pull/1566. 
```release-note
NONE
```
=> fix(CI): partially revert `404e649`

userspace/libsinsp/dns_manager.cpp, userspace/libsinsp/dns_manager.h, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/dns_manager.ut.cpp
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(libsinsp): use smart pointer for m_resolver in sinsp_dns_manager

.circleci/config.yml, .github/workflows/ci.yml, test/libscap/test_suites/engines/modern_bpf/modern_bpf.cpp
/kind cleanup
/area tests
No
This PR allows us to debug the modern bpf probe in a more handy way adding a logging function. Moreover, this PR enforces strict checks in the CI to catch simple issues, we want to read at least 10 events before stopping the capture, in this way if we have a trivial issue in the reading phase we can catch it in CI
```release-note
NONE
```
=> update(tests): improve libscap modern bpf tests and CI checks

userspace/libsinsp/event.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/sinsp_filtercheck_fspath.cpp, userspace/libsinsp/test/sinsp_utils.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind bug
/kind cleanup
/area libsinsp
/area tests
No
This gets rid of a scary function that was operating on path strings by hand and is prone to breakage or (worse) memory error issues and replaces with a native C++ implementation.
@incertum I still have a failing test and I would like to be more certain of when we depend on specific behaviors in libs before I go through. Can you take a look? Thanks!
Fixes # …
=> refactor(libsinsp): rewrite concatenate_paths with std::filesystem

userspace/libsinsp/cri.h, userspace/libsinsp/cri.hpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(container/cri-engine): populate labels field for pod sandbox containers

userspace/libscap/scap_platform.c, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/classes/sinsp.cpp
/kind bug
/area libscap
/area libsinsp
No
This PR sets the m_platorm to `nullptr` when we free it
Fixes https://github.com/falcosecurity/falco/issues/2963
```release-note
NONE
```
=> fix(sinsp): avoid a double free when an exception is thrown

userspace/libsinsp/event.cpp
/kind bug
/area libsinsp
No
Sometimes we were saving `std::string`s formatted like `content\0` because we were including the full length of the message. This resulted in the final backslash in paths being added accidentally to `fs.path.*` fields. This fixes it.
Fixes #
```release-note
fix(libsinsp): prevent extra characters from being added to fs.path.* fields
```
=> fix(libsinsp): do not include null terminator in enter event strings

cmake/modules/compute_versions.cmake
/kind cleanup
/area build
Discovered during the development of https://github.com/falcosecurity/driverkit/pull/302; basically we don't allow the user to override `GIT_COMMIT`; but since we support `DRIVER_VERSION` explicitly set by user, i think we should let user also override the commit.
See the driverkit PR workaround: https://github.com/falcosecurity/driverkit/pull/302/files#diff-16a66a3bc20a8ec693f64ed821148f71efa386a7e942444444eb591512bf129bR51
Fixes #
```release-note
NONE
```
=> chore(cmake): allow user to override GIT_COMMIT from cmake.

userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_fspath.cpp, userspace/libsinsp/test/events_fspath.ut.cpp
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp): fix some path handling in fs.path

userspace/libsinsp/container.cpp
/kind bug
/area build
/area libsinsp
No
As per title, fixes `m_inspector` / `m_last_flush_time_ns` ordering definition
Fixes #
```release-note
NONE
```
=> fix(libsinsp): fix -Wreorder warning

userspace/libscap/linux/scap_procs.c, userspace/libsinsp/parsers.cpp, userspace/libsinsp/threadinfo.cpp
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
/area libsinsp
> /area tests
> /version …
=> fix(libscap,libsinsp): always initialize threadinfo on the stack

userspace/libsinsp/event.cpp
/kind bug
/area libsinsp
This fixes a minor bug introduced in https://github.com/falcosecurity/libs/pull/1533 and affecting event params of type `PT_FSPATH` and `PT_FSRELPATH`. The issue involves wrong path resolutions in `sinsp_evt::get_param_as_str` that can cause the returned value to contain the resolved absolute path instead of the relative one even when not desired.
```release-note
fix(userspace/libsinsp): fix resolved PT_FSPATH and PT_FSRELPATH evt params
```
=> fix(userspace/libsinsp): fix resolved PT_FSPATH and PT_FSRELPATH evt params

userspace/libscap/engine/gvisor/gvisor.cpp
/kind cleanup
No
It is undefined behavior to allocate memory with `calloc()` and release it with `delete()`. This fixes it. In C++, `new T();` will zero-initialize the allocated memory. Don't believe me? The standard says so and the compiler agrees (below):
Fixes #
```release-note
NONE
```
=> fix(libscap/gvisor): use consistent new/delete functions for gvisor platform

userspace/libsinsp/sinsp_suppress.cpp
/kind bug
/area libsinsp
The recent process-based event suppression refactor (cc @gnosek) added a new cache slot for better performance. However, given that the cache slots are likely initialized to zero, we can fall into the case in which we consider a zero TID to be suppressed. The issue with that is that if the zero TID is taken from a PTID of an event (execve, clone, etc...), then we also mark as suppressed the child process. We indeed set PTID to zero in our drivers when we can find no parent for a thread, which in this case would cause a whole hierarchy of processes to have their events ignored. …
=> fix(userspace/libsinsp): do not suppress zero ptids

userspace/libscap/engine/kmod/scap_kmod.c
/kind cleanup
No
These ASSERTS() look redundant since each error that they precede is handled and would make the program crash with a meaningful error either way. In addition, one test is actually throwing an error on purpose and may trigger one of these assert, aborting the test suite
```
Note: Google Test filter = sinsp.wrong_host_root
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from sinsp
[ RUN      ] sinsp.wrong_host_root …
```
=> cleanup(libscap/kmod): remove ASSERT(false) on handled errors

userspace/libsinsp/sinsp_filtercheck_container.cpp
/kind bug
/area libsinsp
On failed container info lookups, the container ID stored in each thread info can potentially be marked as empty. However, the `container.id` field currently reports empty container IDs as `host` value, thus making impossible to distinguish actual threads running on the host from threads running in containers for which the metadata lookup failed.
This attempts mitigating the issue by also checking that the thread is running outside of a namespace for `container.id`. As such, failed container ID lookups will return an empty string instead of `host`. …
=> fix(userspace/libsinsp): not report container id as host on failed lookups

userspace/libscap/debug_log_helpers.h
/kind bug
Even if nobody is using `scap_log` for now, I happened to use it with some local changes and I noticed it was wrong.
Fixes #
```release-note
NONE
```
=> fix(userspace/libscap): scap_log macro

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/threadinfo.cpp
/kind bug
/area libsinsp
No
This attempts amending few issues introduced in https://github.com/falcosecurity/libs/pull/1472 (cc @gnosek for visibility). The bug prevents thread infos to be correctly dumped in captures.
The issue consists in initializing `m_filtered_out` to `true` for each thread infos upon creation from proc scanning, and then eventually turning it to `false` at the first file descriptor passing the configured filter. The goal is to avoid dumping a thread info if it's not needed given a provided filter.
The issue with the current state of things is:
- Lack of initialization of …
=> fix(userspace/libsinsp): consistent thread info filtering while dumping

userspace/libsinsp/container_engine/docker/podman.cpp
/kind bug
/area libsinsp
No
I'm finding podman cgroup names that are suffixed with `/container`, and because we don't handle this layout pattern, processes in podman containers are being seen as running on the host. This is seen when investigating SCAP files. This patch adds this layout to the list. For example here's some output from `systemd-cgls`:
```
├─machine.slice
│ ├─libpod-conmon-a2bc7b153f034b17f358cde43a7f8c7475147e8a0d1b2573c26473244ec44ce4.scope
│ │ └─45338 /usr/bin/conmon --api-version 1 -c a2bc7b153f034b17f358cde43a7f8c7475147e8a0d1b2573c26473244ec44ce4 -u …
```
=> Add new cgroup layout for podman

cmake/modules/CompilerFlags.cmake, userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/utils.h
/kind bug
/area build
No
This PR adds `-Werror` to make the `BUILD_WARNINGS_AS_ERRORS` options work again. As you can see, we now attempt to enable that via [CMAKE_COMPILE_WARNING_AS_ERROR](https://cmake.org/cmake/help/latest/prop_tgt/COMPILE_WARNING_AS_ERROR.html) but that option requires CMake 3.24 and we use 3.13 in CI.
Also, fix resulting warnings.
Fixes #
```release-note
NONE
```
=> fix(cmake): reintroduce -Werror with BUILD_WARNINGS_AS_ERRORS

.github/workflows/drivers_ci.yml
/kind bug
/area CI
No
Honestly not sure if this is the root cause but it seems that CI has difficulties downloading kernel headers, and the `apt update` step is only executed if `needs.paths-filter.outputs.driver_changed == 'true' || needs.paths-filter.outputs.libscap_changed == 'true'`, so it seems right to always run it.
Fixes #
```release-note
NONE
```
=> fix(ci): do not install headers if drivers are not modified

userspace/libsinsp/event.cpp
/kind bug
/area libsinsp
I am not sure about this.
@dwindsor @incertum 
Noticed this while working on another issue. Shouldn't this be using the PPM socket type like the rest of the socket types in this "if/else if" case statement. You can see we are using PPM_AF_INET6 & PPM_AF_INET, so why are we not using the PPM_AF_UNIX def?
```release-note
NONE
```
=> fix(libsinsp): modify switch case

userspace/libsinsp/threadinfo.h
> /kind bug
/kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> update(libsinsp): double thread_table_absolute_max_size

test/libscap/test_suites/engines/gvisor/gvisor_parsers.cpp, test/libscap/test_suites/engines/gvisor/gvisor_platform.cpp, userspace/libscap/engine/gvisor/gvisor.cpp, userspace/libscap/engine/gvisor/gvisor.h, userspace/libscap/engine/gvisor/gvisor_public.h, userspace/libscap/engine/gvisor/parsers.cpp, userspace/libscap/engine/gvisor/parsers.h, userspace/libscap/engine/gvisor/scap_gvisor.cpp, userspace/libscap/engine/gvisor/scap_gvisor_platform.cpp, userspace/libscap/scap_platform_api.c, userspace/libsinsp/sinsp.cpp
/kind bug
No.
In the gvisor engine we handle the sandbox ID by generating a numeric value to represent it and using it in the pid/tid fields to distinguish between containers. This was initially extracted from the string itself if it was written in hex (like it is normally in containerd, docker, ...) but it is not a reliable way because it does not handle arbitrary strings or collisions.
This PR fixes it by implementing the following:
- A function in the platform that generates unique ID for …
=> fix(gvisor): handle arbitrary sandbox IDs

driver/socketcall_to_syscall.h
recent updates to the driver broke the driver build for very ancient 2.6.32 kernels on CentOS 6 (e.g. 2.6.32-71.24.1.el6):
socketcall_to_syscall.h:208:7: error: 'SYS_SENDMMSG' undeclared (first use in this function)
case SYS_SENDMMSG:
^
So add the appropriate preprocessor guards to get it to compile.
> /kind bug
> /kind design
> /area build
> /area CI
> /area …
=> fix(driver): add preprocessor guards for oldest 2.6.32 kernels

driver/modern_bpf/CMakeLists.txt, userspace/libpman/CMakeLists.txt
/kind bug
/area build
/area libpman
No.
Fix a build error that occurs under certain conditions.
Building `falcosecurity/libs` with `USE_BUNDLED_MODERN_BPF=OFF` (non-default value) removes the dependency between target `pman` and target `ProbeSkeleton`. The problem is that `ProbeSkeleton` generates a header file `bpf_probe.skel.h` that is critically needed by `pman`. The depondency must be preserved regardless of the value of `USE_BUNDLED_MODERN_BPF`.
Fixes #1623
Some cleanup in the CMake scripts affected by the fix.
**Does this PR …
=> fix(pman): missing probe skeleton header file

userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/fdinfo.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/test/user.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/user.cpp, userspace/libsinsp/user.h
/kind cleanup
/area libsinsp
No
During recent refactors of parameter handling in parsers we introduced `std::string_view`s to handle strings coming from the drivers. However, in subsequent calls that required `const char *` we relied on the fact that those string views had a NUL right after the end. This is technically an oob read (although harmless in this case) and so we just need to handle this properly by using `std::string`s when necessary. We already got rid of a few instances, this PR cleans up the rest of them.
cc …
=> cleanup(libsinsp): do not rely on null-terminated string_views

userspace/libscap/engine/bpf/CMakeLists.txt, userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/modern_bpf/CMakeLists.txt, userspace/libscap/engine/nodriver/CMakeLists.txt, userspace/libscap/engine/noop/CMakeLists.txt, userspace/libscap/engine/savefile/CMakeLists.txt, userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/engine/source_plugin/CMakeLists.txt, userspace/libscap/engine/test_input/CMakeLists.txt
/kind cleanup
/area build
/area libscap-engine-noop
no
Automates the include path seen by libraries that depend on library `scap_engine_noop`. Rather than repeating the path in each library the target `scap_engine_noop` brings now this property with itself.
Fixes #
```release-note
NONE
```
=> build: Improve scap_engine_noop dependency

userspace/libsinsp/container_info.cpp, userspace/libsinsp/filter.cpp, userspace/libsinsp/filter/parser.cpp, userspace/libsinsp/gen_filter.cpp, userspace/libsinsp/gen_filter.h, userspace/libsinsp/prefix_search.h, userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/test/filter_parser.ut.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> new(libsinsp): add iglob operator

userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_observer.h
/kind cleanup
/area libsinsp
We don't make much use of the list of colliding TIDs, and most importantly we don't clean them up although they are rare). Since we have the observer pattern implemented around the interested code area, this refactors the internal code so that tid collisions are passed to observers instead than storing them in the inspector.
```release-note
NONE
```
=> refactor(userspace/libsinsp): make tid collision a property of the observer

userspace/chisel/chisel.cpp, userspace/chisel/chisel.h, userspace/chisel/chisel_api.cpp, userspace/chisel/chisel_api.h, userspace/libsinsp/include/sinsp_external_processor.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/settings.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/external_processor.ut.cpp, userspace/libsinsp/threadinfo.cpp
/kind cleanup
/area libsinsp
This makes some steps in the direction of removing or rearranging legacy definitions and ifdefs around libsinsp. Most of the things touched here are unused, and thus removed.
```release-note
NONE
```
=> cleanup(userspace/libsinsp): remove and rearrange legacy definitions

userspace/libsinsp/container.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/container_engine/container_cache.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h, userspace/libsinsp/user.cpp, userspace/libsinsp/user.h
/kind cleanup
/kind feature
/area libsinsp
The inspector does a series of automatic routines at every iteration of the `next` event processing function, however most of them can't be controlled or customized through API. This PR makes a step forward by providing API methods for controlling the garbage collection/purging routines of threads, user/groups, and containers. Methods and variables have been uniformed in naming.
```release-note
refactor(userspae/libsinsp): api methods for …
```
=> refactor(userspae/libsinsp): api methods for controlling automatic routines

userspace/chisel/chisel_api.cpp, userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_filtercheck_container.cpp, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/sinsp_filtercheck_fdlist.cpp, userspace/libsinsp/sinsp_filtercheck_fspath.cpp, userspace/libsinsp/sinsp_filtercheck_group.cpp, userspace/libsinsp/sinsp_filtercheck_k8s.cpp, userspace/libsinsp/sinsp_filtercheck_mesos.cpp, userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/sinsp_filtercheck_user.cpp
/kind cleanup
/area libsinsp
This removes a quite old flag on filterchecks that was in place only for use cases related to chisels, which now bring little to no value.
```release-note
clenup(userspace/libsinsp)!: remove unused filter compiler flag
```
=> clenup(userspace/libsinsp)!: remove unused filter compiler flag

userspace/chisel/chisel_api.cpp, userspace/chisel/chisel_table.cpp, userspace/libsinsp/event.cpp, userspace/libsinsp/event.h, userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/fdinfo.h, userspace/libsinsp/ifinfo.cpp, userspace/libsinsp/ifinfo.h, userspace/libsinsp/ifinfo_test.cpp, userspace/libsinsp/include/sinsp_external_processor.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/settings.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/sinsp_filtercheck_fd.h, userspace/libsinsp/sinsp_filtercheck_fdlist.cpp, userspace/libsinsp/sinsp_observer.h, userspace/libsinsp/test/events_file.ut.cpp, userspace/libsinsp/test/events_net.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
/kind cleanup
/kind design
/area libsinsp
This PR attempts refactoring the data structures related to file descriptor tables on the following points:
- Most methods on fd infos could be const or inlined by currently aren't. Furthermore, some methods are currently unused and are now cleaned up
- The `sinsp_fdinfo` class has fields and methods definitions mixed with no clarity about their order and visibility (what's public and what's not?). The class has been cleanup up with reasonable ordering
- `sinsp_fdinfo` is currently a template for no good reason, if not the possibility of extending the class with a …
=> refactor(userspace/libsinsp)!: file descriptor tables for better OOP design and extensibility

driver/ppm_fillers.c
/kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(driver): fix potential deadlock

driver/bpf/fillers.h
/kind bug
No
Fixes #1639 
```release-note
NONE
```
=> fix(driver/bpf): decrease limits to support some GKE env

userspace/libsinsp/logger.cpp, userspace/libsinsp/logger.h, userspace/libsinsp/user.cpp
/kind bug
/area libsinsp
Some refactors related to the logger and the switch to string views caused this couple of issues.
```release-note
NONE
```
=> fix(userspace/libsinsp): solve data race and segfault in logger

userspace/libsinsp/test/sinsp_utils.ut.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind bug
/area libsinsp
This PR embeds a better fix for the issue found in #1530, reverting the new `std::filesystem` implementation (that was great btw, and much better edge cases coverage; see #1533 ) to the old one with some small fixes on top, for perf reasons. We found that the new impl had like a 7.5x slowdown; since it is used in hot paths, we had to revert.
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): revert to old `concatenate_paths` helper funtion for perf reasons

userspace/libsinsp/event.cpp, userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/parsers.cpp
/kind cleanup
/area build
No
Fix a recurrent warning with Clang. It complains that an `std::move` on an object that is already an rvalue reference is unneeded and could prevent optimizations to take place, i.e. force a move when direct construction could be used.
Fixes #
```release-note
NONE
```
=> fix: Clang warning pessimizing move

userspace/libsinsp/test/sinsp_utils.ut.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind cleanup
/area libsinsp
Cherry picks https://github.com/falcosecurity/libs/pull/1645 from master.
Fixes #
```release-note
NONE
```
=> sync: cherry pick for 0.14.2

driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/quotactl.bpf.c
/kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(modern_bpf): fix wrong sign when getting quotactl cmd arg

driver/modern_bpf/definitions/missing_definitions.h
/kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(modern_bpf): define MAP_RENAME only on powerpc

userspace/libsinsp/ifinfo.h, userspace/libsinsp/test/ifinfo.ut.cpp
/kind cleanup
/area libsinsp
This attempts restoring the windows build and tests, broken in my previous PR by rearranging the `ifinfo` tests.
```release-note
NONE
```
=> fix(userspace/libsinsp): restore windows build

test/e2e/tests/commons/sinspqa/event_generator.py
/kind bug
/area CI
/area tests
Fixes master CI: latest tagged event-generator added an explicit `--all` flag: https://github.com/falcosecurity/event-generator/releases/tag/v0.11.0 to enforce disabled-by-default rules.
Fixes #
```release-note
NONE
```
=> fix(test/e2e): fixed event-generator cmdline arguments.

.github/workflows/ci.yml, cmake/modules/libelf.cmake
/kind feature
/area build
No
This allows linking libelf dynamically. When not using the bundled libelf this will be the default behavior and must be tested in CI as well.
As per the CNCF Legal Committee recommendation, we are switching to dynamically linking libelf (LGPL'd) to comply with the CNCF license policy.
Fixes #
```release-note
new(build): add USE_SHARED_LIBELF option
```
=> new(build): allow building with dynamic libelf

userspace/libsinsp/test/mpsc_priority_queue.ut.cpp
/kind bug
/area libsinsp
/area tests
Nah
We're experiencing deadlocks on the concurrent tests on the MPSC priority queue, so far only on aarch64 in our CI. This may either reveal a thread-safety issue in the queue's implementation, or may just be pathological due to the scheduler being unpredictable -- the queue can order elements already pushed, but can't know if an higher-priority event is not yet pushed due to its producer being sleepy. This PR solves the issue by making the test fail with a timeout, and provides more in-depth messages about the failure. Also, the exit condition of the loop was still …
=> fix(userspace/libsinsp/test): avoid deadlocks in mpsc queue tests

userspace/libsinsp/test/thread_table.ut.cpp
/kind cleanup
/area libsinsp
/area tests
The `sinsp_with_test_input.THRD_TABLE_max_table_size` took a while to execute locally and also made my machine crash, which didn't make much sense to me. Looking closer, the max thread table size is a quite large number and it has also been increased. I changed this to set a fixed size for the sake of the test, still with a reasonably-high number so that it keeps being valuable.
```release-note
NONE
```
=> fix(userspace/libsinsp/test): put a bound to threat table max size test

driver/ppm_events_public.h, userspace/libsinsp/container.h, userspace/libsinsp/dns_manager.cpp, userspace/libsinsp/dns_manager.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/dns_manager.ut.cpp, userspace/libsinsp/utils.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> cleanup(libsinsp): remove CYGWING_AGENT feature gate

userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin.h, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/plugin_extract.cpp, userspace/plugin/plugin_api.h, userspace/plugin/plugin_loader.c
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(libsinsp): plugin dynamic reconfiguration

userspace/libscap/engine/source_plugin/source_plugin.c, userspace/libscap/scap_event.c, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/plugins/plugin_source.cpp, userspace/libsinsp/test/plugins/syscall_async.cpp, userspace/libsinsp/test/plugins/syscall_source.cpp
/kind cleanup
/area libsinsp
No
This is part of this effort: https://github.com/falcosecurity/libs/issues/1470
This current PR deals with plugins, note that it introduces a dependency from the plugin tests to the scap library in order to use the `scap_event_encode_params` function which allows the test classes to easily create events without misaligned reads or writes.
It looks like the sinsp test suite is are currently at 7 errors with UBSan.
Fixes # …
=> cleanup(libsinsp): cleanup unaligned access in plugin framework+tests

userspace/libscap/engine/savefile/scap_savefile.c
/kind cleanup
/area libscap
No
Next step in this effort: https://github.com/falcosecurity/libs/issues/1470 this brings unit/integration to 0 warnings, e2e are next.
Fixes #
```release-note
NONE
```
=> cleanup(libscap): fix unaligned memory reads

.github/workflows/reusable_kernel_tests.yaml
/kind cleanup
/area CI
Moreover, bumped the framework to v0.3.0.
Fixes #
```release-note
NONE
```
=> cleanup(ci): use new kernel-testing provided composite action.

userspace/libsinsp/filter.cpp, userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/sinsp_filtercheck.h, userspace/libsinsp/sinsp_filtercheck_container.h, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_event.h, userspace/libsinsp/sinsp_filtercheck_evtin.h, userspace/libsinsp/sinsp_filtercheck_fd.h, userspace/libsinsp/sinsp_filtercheck_fdlist.h, userspace/libsinsp/sinsp_filtercheck_fspath.h, userspace/libsinsp/sinsp_filtercheck_gen_event.h, userspace/libsinsp/sinsp_filtercheck_group.h, userspace/libsinsp/sinsp_filtercheck_k8s.h, userspace/libsinsp/sinsp_filtercheck_mesos.h, userspace/libsinsp/sinsp_filtercheck_rawstring.h, userspace/libsinsp/sinsp_filtercheck_reference.cpp, userspace/libsinsp/sinsp_filtercheck_reference.h, userspace/libsinsp/sinsp_filtercheck_syslog.h, userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/sinsp_filtercheck_thread.h, userspace/libsinsp/sinsp_filtercheck_tracer.cpp, userspace/libsinsp/sinsp_filtercheck_tracer.h, userspace/libsinsp/sinsp_filtercheck_user.h, userspace/libsinsp/sinsp_filtercheck_utils.h, userspace/libsinsp/test/plugins/plugin_source.cpp
/kind cleanup
/area libsinsp
This should save us some MBs used at runtime for large rulesets. In general, this cleans-up the filtercheck classes by:
- Having explicit virtual destructors
- Remove unused state variables
- Allocating storage variables only on-demand
```release-note
NONE
```
=> cleanup(userspace/libsinsp): reduce allocations in filtercheck classes

driver/modern_bpf/helpers/store/auxmap_store_params.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/accept.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/accept4.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/connect.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvfrom.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvmsg.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendmsg.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendto.bpf.c, test/drivers/test_suites/syscall_enter_suite/sendmsg_e.cpp, test/drivers/test_suites/syscall_enter_suite/sendto_e.cpp
/kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(modern_bpf): null destination address in `sendto` and `sendmsg` syscalls

userspace/libsinsp/container_engine/sinsp_container_type.h, userspace/libsinsp/container_info.h
/kind cleanup
/area libsinsp
No
Part of https://github.com/falcosecurity/libs/issues/1470 , fixes an issue identified in https://github.com/falcosecurity/libs/pull/1685 . This fixes the uninitialized `m_type` member in `container_info` when the default constructor is used.
This is a simple patch but could be potentially catastrophic so that's why it needs a bit more thought for the review.
Fixes # …
=> cleanup(libsinsp): add CT_UNKNOWN as container_type zero value

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp_filtercheck.cpp
/kind cleanup
/area libsinsp
No
Part of #1470 . This cleans up more accesses and uses the appropriate function when creating events not coming from the drivers
Fixes #
```release-note
NONE
```
=> cleanup(libsinsp): cleanup more memory read/writes in filterchecks

userspace/libscap/scap-int.h, userspace/libscap/scap_platform.c, userspace/libscap/scap_procs.c
/kind bug
/area libscap
No
There appears to be a potential memory leak happening when we allocate proclist info in `m_driver_procinfo` because it seems like we never free that variable: https://github.com/falcosecurity/libs/blob/3d5d2d3d4534c23e1bb69b72bddca9406e917ff2/userspace/libscap/scap_platform_api.c#L148
Add a function to do it and call on platform close.
cc @gnosek , I am not entirely sure this is the right thing to do with the platform design
Fixes # …
=> fix(libscap): fix memleak by freeing proclist info upon platform close

.github/workflows/ci.yml, CMakeLists.txt
Set CMAKE_MSVC_RUNTIME_LIBRARY to "MultiThreaded" unless it was set externally or if we're building shared libs. This
- uses CMake's documented variable to control CRT linking.
- ensures that we use the static CRT by default.
- allows the CRT setting to be overridden.
Add a Windows shared CRT CI job.
> /kind bug
/kind cleanup
> /kind design
/area build
/area CI
> /area …
=> update(cmake): Use the static CRT on Windows by default

userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> cleanup(libsinsp): remove unused functions from utils.cpp

.github/workflows/ci.yml
/kind feature
/area CI
No
This enables UBSan for tests. Please note that it's a work in progress until we are sure it works.
EDIT: it works with no warnings with the current state of the repo, so it's out of wip!
Fixes #1470
```release-note
NONE
```
=> new(gha): enable UndefinedBehaviorSanitizer

userspace/libsinsp/fdinfo.h, userspace/libsinsp/sinsp_filtercheck_event.cpp
/kind cleanup
/area libsinsp
No
As usual, the more test coverage we get the easier it is to catch these instances.
Fixes #
```release-note
NONE
```
=> cleanup(libsinsp): remove some more misaligned accesses

test/libsinsp_e2e/vtidcollision.c, userspace/libsinsp/parsers.cpp
/kind cleanup
/area libsinsp
/area tests
No
This is necessary to add sanitizers and warnings enabled for our new e2e tests
Fixes #
```release-note
NONE
```
=> cleanup(libsinsp): fix warnings on e2e tests

userspace/libpman/src/maps.c, userspace/libpman/src/state.c, userspace/libpman/src/state.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libpman
> /area tests
> …
=> Silence missing BPF program error

userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/parsers.cpp
/kind bug
/area libsinsp
This fixes a recently-introduced issue where we could invoke `lookup_device` with an invalid thread ID, either uninitialized or simply not set to the proper value. This causes both performance issues and file descriptor info consistency problems.
```release-note
NONE
```
=> fix(userspace/libsinsp): make sure fd table's tid is set

driver/ppm_fillers.c, driver/ppm_flag_helpers.h, test/drivers/test_suites/syscall_exit_suite/poll_x.cpp, test/drivers/test_suites/syscall_exit_suite/process_vm_readv_x.cpp
> /kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(driver/kmod): always send fds to userspace in poll/ppoll syscall exit

userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/engine/test_input/test_input_platform.c, userspace/libscap/linux/scap_linux_platform.c, userspace/libscap/ringbuffer/devset.c, userspace/libscap/scap_platform.c
/kind cleanup
/area build
No
I tried building the library with gcc 14 and a few warnings came up. In a scenario where warnings are treated as errors this would be a blocker. The warnings are a tad picky as they lament that fuction `calloc` is being used with the element size first and the number of elements after, when it should be the opposite. Regardless of the check being extra meticulous, the fix is easy and prepares the code for future compiler upgrades.
```c++
calloc(sizeof(int), N); // raises the warning
calloc(N, sizeof(int)); // ok
```
Fixes #
**Special notes for …
=> fix: Some warnings when compiling with GCC 14

userspace/libsinsp/container.cpp, userspace/libsinsp/container.h, userspace/libsinsp/parsers.cpp
/kind cleanup
/area libsinsp
No
* `container_to_sinsp_event` was never returning false or error, now it has a reason to (issues during serialization)
* some network args were copied in the old way
Fixes #
```release-note
NONE
```
=> cleanup(libsinsp): scap_evt cleanups

driver/CMakeLists.txt, driver/Makefile.in, driver/README.configure.md, driver/configure/ACCESS_OK_2/test.c, driver/configure/DEVNODE_ARG1_CONST/test.c, driver/configure/Makefile, driver/configure/Makefile.inc.in, driver/configure/build.sh, driver/main.c, driver/ppm_events.c
/kind feature
Introduce a new mechanism for conditional build in the kernel module, documented in driver/README.configure.md
Apply such mechanism to `ppm_access_ok`, easily detecting if `access_ok` is the old version with 3 parameters or the new one with just two.
Fixes #
```release-note
NONE
```
=> new(driver): kmod configure system

driver/configure/CLASS_CREATE_1/test.c, driver/main.c
/kind bug
Address RHEL 9 backport of class_create signature change introduced in kernel 6.4 git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1aaba11da9aa7d7d6b52a74d45b31cac118295a1
Fixes #
```release-note
fix(driver-kmod): error: too many arguments to function ‘class_create’
```
=> fix(driver): use configure system to build class_create with a single parameter

userspace/libsinsp/test/async_key_value_source.ut.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area tests
> /version …
=> new(libsinsp/test): add new async_key_value_source tests

driver/CMakeLists.txt
/kind bug
Fixes #
```release-note
NONE
```
=> fix(driver): properly use DRIVER_KMOD_COMPONENT_NAME when installing kmod configure modules

userspace/libsinsp/container.cpp, userspace/libsinsp/container_info.h, userspace/libsinsp/cri.h, userspace/libsinsp/cri.hpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_filtercheck_container.cpp, userspace/libsinsp/sinsp_filtercheck_k8s.cpp, userspace/libsinsp/test/container_engine/container_parser_cri_containerd.ut.cpp, userspace/libsinsp/test/container_engine/container_parser_cri_crio.ut.cpp, userspace/libsinsp/test/filterchecks/k8s.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(cri): restructure CRI API (improve robustness, clarity and maintainability)

userspace/libsinsp/sinsp_filtercheck.h, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_evtin.cpp, userspace/libsinsp/sinsp_filtercheck_gen_event.cpp, userspace/libsinsp/sinsp_filtercheck_rawstring.cpp, userspace/libsinsp/sinsp_filtercheck_reference.cpp, userspace/libsinsp/sinsp_filtercheck_syslog.cpp, userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/sinsp_filtercheck_tracer.cpp
/kind bug
/area libsinsp
In one of the refactor series I took on, it seems like some field classes (`evt.*` and `syslog.*`) have been marked as "hidden", meaning that Falco skips them when printing the list of available fields. This PR solves the problem by making sure that the flags of every filter field class are properly initialized.
```release-note
fix(userspace/libsinsp): field lists are hidden by mistake
```
=> fix(userspace/libsinsp): field lists are hidden by mistake

userspace/libsinsp/plugin_table_api.cpp, userspace/libsinsp/test/plugins/sample_table.h, userspace/plugin/plugin_api.h
The fields returned by a plugin can be a static string and the plugin framework doesn't have any business in modifying it so let's make it const (to avoid a copy for plugins that can return a static string).
Note: I only bump the plugin API version by 0.0.1 since the changes in this PR do not affect binary compatibility in any way.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
=> fix(plugins): make list_fields return a const pointer

driver/configure/Makefile.inc.in
/kind bug
/area build
Fixes latest-kernel CI: https://github.com/falcosecurity/libs/actions/runs/8184781555/job/22379860975
Basically, driverkit vanilla builder [exports](https://github.com/falcosecurity/driverkit/blob/master/pkg/driverbuilder/builder/templates/vanilla.sh#L57) `KBUILD_MODPOST_WARN=1` to correctly build. Since #1452 , that env variable was not passed to sub-modules makefiles when configuring driver features, therefore it result in broken CI.
Fixes #
Nothing changes when the var is not set.
**Does this PR …
=> fix(driver): properly pass KBUILD_MODPOST_WARN env variable to configure makefile if set

driver/Makefile.in, driver/bpf/CMakeLists.txt, driver/bpf/Makefile, driver/bpf/configure/Makefile, driver/bpf/configure/Makefile.inc.in, driver/bpf/configure/RSS_STAT_ARRAY/test.c, driver/bpf/configure/build.sh, driver/bpf/fillers.h, driver/bpf/probe.c, driver/bpf/types.h
/kind bug
/kind feature
This is the corrispettive of #1452  for bpf.
Moreover, it also adds a fix for rss_stat becoming an array in kernel 6.2 (this was backported in centos 5.14: https://falcosecurity.github.io/libs/matrix_X64/#centos-514-bpf-probe_build).
Fixes #
While we could somehow reuse same code used for kmod, i preferred to duplicate it a bit but at the same time making the code driver-dependent since we might have to add very specific/different test cases in the future (imagine if eg: some kernel backported …
=> new(driver/bpf): added bpf configure system similar to the kmod one.

test/drivers/event_class/event_class.cpp, test/drivers/event_class/event_class.h, test/drivers/helpers/file_opener.cpp, test/drivers/test_suites/syscall_exit_suite/dup3_x.cpp, test/drivers/test_suites/syscall_exit_suite/newfstatat_x.cpp
/kind bug
/area tests
We cannot call GTEST_SKIP() in a sub-routine of a test, but only in the test body.
I kept the changes at the bare minumum to avoid touching all of the test cases...i had to introduce a simple macro though.
Fixes #
```release-note
NONE
```
=> fix(test/drivers): fix ENOSYS check and test skipping.

userspace/libsinsp/procfs_utils.h
/kind bug
/area libsinsp
Fixes #1741
```release-note
NONE
```
=> fix: missing cstdint include to fix build on Alpine

driver/configure/Makefile.inc.in
/kind bug
In Debian 12 we happen to have `CC= gcc-12`, so we have to wrap it in quotes when setting it to the configure system env
Fixes #
```release-note
NONE
```
=> fix(driver): CC variable for debian

driver/bpf/Makefile
/kind bug
`error: unknown argument: '-fmacro-prefix-map=./='` appeared again. Move `IS_CLANG_OLDER_THAN_10` close to `probe.o` target to fix it.
Fixes #
```release-note
NONE
```
=> fix(driver/bpf): KBUILD_CPPFLAGS

driver/bpf/Makefile
/kind cleanup
Fixes #
```release-note
NONE
```
=> sync(release/0.15.x): cherry-pick c6715dd3e86968c85c6282af54975322cd8979ea

.github/workflows/ci.yml, .github/workflows/e2e_ci.yml, test/libsinsp_e2e/container/container.cpp, test/libsinsp_e2e/event_capture.cpp, test/libsinsp_e2e/event_capture.h
/kind cleanup
/area tests
Also, this fixes recent CI issues; see https://github.com/actions/runner-images/issues/9524 and https://github.com/actions/runner-images/issues/9491.
Fixes #
```release-note
NONE
```
=> chore(test/libsinsp_e2e): use unique ptr e2e tests inspector

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp_suppress.cpp, userspace/libsinsp/sinsp_suppress.h
The cache implementation was broken (a no-op, effectively) but even after fixing it doesn't provide noticeable performance wins.
Revert it and save a bit of complexity.
This reverts commit 6a9a0ec14d647ad3d73b65f9eb99a33fa1a14eb3.
Fixes: #1724
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area …
=> Revert "update(sinsp): implement suppressed tid cache in sinsp_suppress"

.github/workflows/e2e_ci.yml
/kind feature
/area CI
This adds build caching in libsinsp e2e CI jobs.
Fixes #
```release-note
NONE
```
=> chore(ci): libsinsp e2e CI caching

driver/bpf/fillers.h, driver/modern_bpf/helpers/store/auxmap_store_params.h, test/drivers/test_suites/syscall_exit_suite/execve_x.cpp
/kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(driver/bpf): not sending all arguments on execve fail

test/libsinsp_e2e/CMakeLists.txt, test/libsinsp_e2e/container/container.cpp, test/libsinsp_e2e/event_capture.cpp, test/libsinsp_e2e/event_capture.h, test/libsinsp_e2e/main.cpp, test/libsinsp_e2e/paths.cpp, test/libsinsp_e2e/sys_call_test.cpp, userspace/libsinsp/container.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area tests
> /version …
=> feat(tests): new e2e tests [3/N]

test/libsinsp_e2e/CMakeLists.txt, test/libsinsp_e2e/event_capture.cpp, test/libsinsp_e2e/fs.cpp, test/libsinsp_e2e/process.cpp, test/libsinsp_e2e/threadinfo.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area tests
> /version …
=> feat(tests): new e2e tests [4/N]

driver/bpf/fillers.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvfrom.bpf.c, driver/ppm_events.c, driver/ppm_fillers.c, test/drivers/test_suites/syscall_exit_suite/recvfrom_x.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area tests
> /version …
=> fix(driver): avoid sending a NULL tuple in `recvfrom` syscall

driver/bpf/configure/Makefile.inc.in
the configure subsystem currently relies on
clang and llc being available.
However, building drivers in a containerized
environment might actually want to leverage
a specific CLANG version.
So just like we did for CC on the kmod driver,
have those variables passed over to the
configure subsystem.
/kind bug
> /kind design
/area build
> /area CI
> …
=> fix(driver/bpf) honor CLANG and LLC from the env

test/libscap/test_suites/engines/gvisor/gvisor_parsers.cpp, userspace/libscap/engine/gvisor/parsers.cpp
/kind bug
No
Sometimes gVisor events would show duplicated command name (e.g. `cat cat` instead of `cat`). This fixes it.
Fixes #
```release-note
fix(gvisor): fix duplicated command names
```
=> fix(gvisor): fix duplicated command names

userspace/libsinsp/sinsp_filtercheck_fd.cpp
/kind bug
/area libsinsp
When using the `fd.types` field for output formats, only when using it without `[]` arguments, we currently any character following the field due to a length parsing error. So we have:
- `SAMPLE fd.types=%fd.types` -> `SAMPLE fd.types=(...)`
- `fd.types=%fd.types SAMPLE` -> `fd.types=(...)`
```release-note
fix(userspace/libsinsp): solve formatts being cropped with fd.types
```
=> fix(userspace/libsinsp): solve formatts being cropped with fd.types

test/libscap/test_suites/engines/gvisor/gvisor_parsers.cpp
/kind bug
/area tests
No
As per title. It was exiting with errors in my local environment.
Fixes #
```release-note
NONE
```
=> fix(tests/gvisor): fix build and sanitizer exec in gvisor parser tests

test/libsinsp_e2e/forking.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area tests
> /version …
=> fix(libsinsp_e2e): make forking_clone_fs more reliable

userspace/libsinsp/test/eventformatter.ut.cpp, userspace/libsinsp/test/events_net.ut.cpp, userspace/libsinsp/test/filter_compiler.h, userspace/libsinsp/test/filter_compiler.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h, userspace/libsinsp/test/test_utils.h
/kind cleanup
/area tests
I realized that we don't have coverage in our output formatting system, which is also the construct used by Falco for formatting output strings and fields when security rules are triggered. This PR achieves decent coverage, and also adds minor improvements to the test suite for what concerns filters.
```release-note
NONE
```
=> test(userspace/libsinsp): add cases for formatters and minor improvements

userspace/libscap/linux/scap_fds.c, userspace/libsinsp/parsers.cpp, userspace/libsinsp/threadinfo.cpp
/kind bug
/area libsinsp
No
I was able to hit all these assertions in a reliable way using Falco + stress-ng... so something like
```bash
sudo ./userspace/falco/falco -c ../falco.yaml -r ../rules/falco_rules.yaml -o engine.kind=modern_ebpf 
```
+ on another terminal
```bash
stress-ng --exec 4
```
In case of many drops these situation can happen so we shouldn't use assertions
```release-note
NONE
```
=> fix(userspace): remove some wrong asserts

userspace/libsinsp/container_engine/bpm.cpp, userspace/libsinsp/container_engine/docker/base.cpp, userspace/libsinsp/container_engine/libvirt_lxc.cpp, userspace/libsinsp/container_engine/lxc.cpp, userspace/libsinsp/container_engine/mesos.cpp, userspace/libsinsp/container_engine/rkt.cpp, userspace/libsinsp/container_info.h, userspace/libsinsp/test/container_engine/container_parser_cri_containerd.ut.cpp, userspace/libsinsp/test/container_engine/container_parser_cri_crio.ut.cpp, userspace/libsinsp/test/events_plugin.ut.cpp
/kind bug
/kind cleanup
/kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(libsinsp/container_info): change default / init lookup state to `FAILED`

userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/base64.h, userspace/libsinsp/sinsp_filter_transformer.cpp, userspace/libsinsp/sinsp_filter_transformer.h, userspace/libsinsp/sinsp_filtercheck.h, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/filter_transformer.ut.cpp
/kind feature
/area libsinsp
/area tests
As part of https://github.com/falcosecurity/libs/issues/1789, this PR adds the base constructs through which field transformers will be implemented in the first rollout of the proposed feature. This does not wire any of the new functionalities to the current filter field classes, but rather just adding an implementation to be used in subsequent changes.
This implements the `toupper`, `tolower`, and `b64` operations as defined in the proposal. There will be an opportunity to add more later on through the same building blocks.
Tests have been added for decent coverage …
=> new(userspace/libsinsp): add building blocks for filter field transformers

userspace/libsinsp/metrics_collector.cpp, userspace/libsinsp/test/sinsp_metrics.ut.cpp
/kind cleanup
/area libsinsp
A bit tedious but i quite like how it looks now. Basically, refactored metrics_collector in libsinsp to enforce that every declared metric MUST be actually used.
Fixes #
```release-note
NONE
```
=> cleanup(userspace/libsinsp): improved sinsp metrics_collector to make it more future proof

driver/modern_bpf/helpers/store/auxmap_store_params.h, test/e2e/tests/test_event_generator/test_db_program_spawned_process.py, test/e2e/tests/test_event_generator/test_file_writes.py, test/e2e/tests/test_event_generator/test_make_binary_dirs.py, test/e2e/tests/test_event_generator/test_modify_binary_dirs.py, test/e2e/tests/test_event_generator/test_network_activity.py, test/e2e/tests/test_event_generator/test_non_sudo_setuid.py, test/e2e/tests/test_event_generator/test_read_sensitive_file.py, test/e2e/tests/test_network/test_network.py, test/e2e/tests/test_process/test_container.py, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/filterchecks/evt.cpp, userspace/libsinsp/test/parsers/parse_connect.cpp, userspace/libsinsp/test/test_utils.cpp, userspace/libsinsp/test/test_utils.h
/kind feature
/area libsinsp
/area tests
No
This PR adds some tests in sinsp and fixes a little bug with `m_strstorage`. This PR incorporates tests from https://github.com/falcosecurity/libs/pull/1609
```release-note
NONE
```
=> new(tests): add some libsinsp tests

userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind cleanup
/area libsinsp
Doing some benchmarks, I noticed that the `endswith` operator is usually one of the least performing one we support because the current implementation may involve occasional allocation and string copies due to a `const char*` to `const std::string&` conversion. If used extensively in a filter or in Falco rules, that can have noticeable performance and memory impact.
/milestone 0.16.0
I think this should be something to consider for the upcoming release, as quite minimal but useful. Will let the release …
=> refactor(userspace/libsinsp): improve performance of endswith filter operator

userspace/libsinsp/test/events_proc.ut.cpp
/kind bug
/area tests
Some proc tests related variadic arguments were missing explicit cast.
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): fixed multiple proc related tests variadic arguments types

.github/workflows/e2e_ci.yml, test/libsinsp_e2e/forking.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area tests
> /version …
=> fix(libsinsp_e2e): disable flaky sys_call_test.forking_clone_fs e2e test

userspace/libscap/scap.c
/kind bug
/area libscap
No
We now may attempt calling sinsp's `stop_capture()` from Falco before a capture has started and a scap handle was initialized but with an inspector present. This is a no-op, not a segfault! Also, some of those functions did handle a null scap handler, some did not so I added the check to all of them.
Fixes #
```release-note
fix(libscap): fix libscap crashing if scap functions …
```
=> fix(libscap): handle NULL scap handle pointer

userspace/libsinsp/base64.h, userspace/libsinsp/test/events_evt.ut.cpp, userspace/libsinsp/test/events_file.ut.cpp, userspace/libsinsp/test/events_net.ut.cpp, userspace/libsinsp/test/events_param.ut.cpp, userspace/libsinsp/test/filterchecks/evt.cpp, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind feature
/area tests
Levearaging c++ variadic templates, ensure that variadic arguments are properly sized (at least for integer-like types, that are the most common mistaken ones).
Fixes #
```release-note
NONE
```
=> new(userspace/libsinsp): check usage of wrong-sized variadic arguments in sinsp tests

userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_filtercheck_group.cpp, userspace/libsinsp/sinsp_filtercheck_group.h, userspace/libsinsp/sinsp_filtercheck_user.cpp, userspace/libsinsp/sinsp_filtercheck_user.h, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h, userspace/libsinsp/user.cpp, userspace/libsinsp/user.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> Split user info

driver/bpf/fillers.h, driver/modern_bpf/helpers/base/push_data.h, driver/modern_bpf/helpers/store/auxmap_store_params.h, driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c, driver/modern_bpf/programs/attached/events/sched_process_fork.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/clone.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/clone3.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fork.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/vfork.bpf.c, driver/ppm_fillers.c, test/drivers/event_class/event_class.cpp, test/drivers/test_suites/generic_tracepoints_suite/sched_process_exec.cpp, test/drivers/test_suites/syscall_exit_suite/execve_x.cpp, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp
/kind bug
No
This PR contains multiple fixes:
* modern_bpf: related to this https://github.com/falcosecurity/libs/issues/866. Since `bpf_probe_read_user_str` returns `0` in case of an empty string we now add manually a null terminator directly in `push__charbuf`, in this case we can handle empty strings in just one place. Partially reverting this https://github.com/falcosecurity/libs/pull/1760.
* modern_bpf: handle correctly `args` and `envs` greater than the limit (`4096`). Before this fix, in the case of `args`>= 4096, they were truncated without adding a `\0` at …
=> fix(drivers): add always a null terminator after `args` and `envs`

driver/modern_bpf/definitions/missing_definitions.h, test/drivers/event_class/event_class.cpp, test/drivers/event_class/event_class.h, test/drivers/test_suites/syscall_exit_suite/clone3_x.cpp, test/drivers/test_suites/syscall_exit_suite/clone_x.cpp, test/drivers/test_suites/syscall_exit_suite/creat_x.cpp, test/drivers/test_suites/syscall_exit_suite/fork_x.cpp, test/drivers/test_suites/syscall_exit_suite/open_by_handle_at_x.cpp, test/drivers/test_suites/syscall_exit_suite/open_x.cpp, test/drivers/test_suites/syscall_exit_suite/openat2_x.cpp, test/drivers/test_suites/syscall_exit_suite/openat_x.cpp, test/drivers/test_suites/syscall_exit_suite/sendmsg_x.cpp, test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
/kind bug
/area tests
This PR tries to address multiple drivers_test failures on ppc64le. 
Remaining failures (for modern bpf):
```
[  FAILED  ] 12 tests, listed below:
[  FAILED  ] SyscallExit.clone3X_child
[  FAILED  ] SyscallExit.clone3X_child_clone_parent_flag
[  FAILED  ] SyscallExit.clone3X_child_new_namespace_from_child
[  FAILED  ] SyscallExit.cloneX_child
[  FAILED  ] SyscallExit.creatX_success
[  FAILED  ] SyscallExit.forkX_child
[  FAILED  ] SyscallExit.getrlimitX_success
[  FAILED  ] SyscallExit.openX_success
[  FAILED  ] SyscallExit.openatX_success
[  FAILED  ] …
```
=> fix(driver/modern_bpf,test/drivers): fixed drivers_test on ppc64le

userspace/libsinsp/event.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/test/sinsp_utils.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind cleanup
/area libsinsp
No
After https://github.com/falcosecurity/libs/pull/1800 we want to make sure that what we receive from the drivers is actually what we expect. So, I've changed the way we parse those kind of parameters to check for the NUL terminator, and added a shorthand helper to convert the parameter from buffer to vector.
Fixes #
```release-note
NONE
```
=> cleanup(libsinsp): throw exception for invalid parsed string vectors

userspace/libscap/engine/savefile/scap_reader_gzfile.c
Call gzclearerr if gzread returns fewer bytes than expected. This lets us "tail" a file being written by another process.
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area …
=> cleanup(libscap): Allow retries after encountering SCAP_EOF

userspace/libsinsp/threadinfo.cpp
/kind bug
/area libsinsp
Small fixup on top of https://github.com/falcosecurity/libs/pull/1765.
cc @erthalion 
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): properly use `strlen` instead of `sizeof` when assigning user/group string infos

userspace/libsinsp/parsers.cpp
/kind bug
/area libsinsp
This PR fixups a small bug indirectly caused by the changes in https://github.com/falcosecurity/libs/pull/1707.
Default at successful lookup state when `lookup_state` is not part of the container json event.
Fixes #
Falco CI uses very very old container events in scap files (prior to https://github.com/falcosecurity/libs/commit/58a546a1b5b435caf94dadcefeea4f78363bdcbd changes) thus one event was expected but not received becase it had no `lookup_state` field.
See …
=> fix(userspace/libsinsp): properly set successful lookup state when parsing old container json events

userspace/libscap/engine/savefile/scap_savefile.c, userspace/libsinsp/parsers.cpp, userspace/libsinsp/threadinfo.cpp
/kind cleanup
Cherry picks recent fixes from master:
* https://github.com/falcosecurity/libs/pull/1811
* https://github.com/falcosecurity/libs/pull/1812
* https://github.com/falcosecurity/libs/pull/1813
Fixes #
```release-note
NONE
```
=> sync: release 0.16.x

userspace/libscap/linux/scap_procs.c, userspace/libsinsp/test/sinsp_utils.ut.cpp, userspace/libsinsp/utils.cpp
/kind bug
/area libscap
/area libsinsp
No
The checks in this PR were probably too strict https://github.com/falcosecurity/libs/pull/1810. Our codebase at the moment is not ready to throw an exception when a vector of strings is not null-terminated. For example, when scanning proc this is something that could still happen, in this PR we fixed a possible case but who knows how many corner cases there are... a more conservative solution is to log a warning and enforce the null terminator in release mode. In debug mode, we keep the exception so it's easier to figure out the root cause with a backtrace.
**Which …
=> fix(sinsp): set a null terminator instead of throwing an exception

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
/kind cleanup
/area libsinsp
No
This PR attempts improving performance in the hot path by inlining few methods that are simple wrappers of the `sinsp` class to other subclasses, which are currently not inlined if not in the `sinsp.cpp` compilation unit. By profiling with valgrind, I discovered that few operations involving shared_ptrs (e.g. statsv2, add_thread, ...) have an additional useless CPU cost when not inlined.
```release-note
NONE
```
=> fix(userspace/libsinsp): make sure simple sinsp wrapper methods are inlined

test/drivers/test_suites/syscall_exit_suite/fork_x.cpp, userspace/libsinsp/container_engine/docker/podman.cpp, userspace/libsinsp/container_engine/docker/podman.h, userspace/libsinsp/fdinfo.h, userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/mpsc_priority_queue.h, userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/test/filter_compiler.ut.cpp, userspace/libsinsp/test/filterchecks/mock.cpp, userspace/libsinsp/test/helpers/scoped_pipe.cpp, userspace/libsinsp/test/mpsc_priority_queue.ut.cpp, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/state.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
/kind cleanup
No specific area. This is a general cleanup refactoring.
No
There are some usages of smart pointers that can be simplified a but and, occasionally, made more efficient.
1. Use the overloaded dereference operator directly on the smart pointer without invoking `get()`, i.e. prefer `*ptr` rather than `*(ptr.get())`.
2. Create objects stored in smart pointers with `make_unique` or `make_shared` rather than using `new`. For `shared_ptr`s this has the performance advantage of storing the pointer's control block with the object itself, improving memory locality, beneficial for cache reasons, and using …
=> refactor: smart pointer usage

userspace/libsinsp/event.cpp, userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/logger.cpp, userspace/libsinsp/sinsp_filtercheck.cpp
/kind bug
/kind cleanup
/area libsinsp
/area tests
When running the unit tests with a debug build, I found a bunch of ASSERTs that trigger systematically and that prevent the tests from running properly, so this PR attempts cleaning up a bit those cases.
/milestone 0.17.0
**Does this PR introduce a user-facing change?**
```release-note
NONE
```
=> fix(userspace/libsinsp): remove wrong ASSERTs

userspace/libsinsp/event.h, userspace/libsinsp/sinsp.cpp
/kind cleanup
/area libsinsp
No
This is a little simplification in defining a `unique_ptr` to an array. For example:
```c++
std::unique_ptr<uint8_t, std::default_delete<uint8_t[]>> buffer;
```
Can be written more easily as this.
```c++
std::unique_ptr<uint8_t[]> buffer;
```
Fixes #
```release-note
refactor: Function sinsp_evt::from_scap_evt takes a slightly different parameter.
This function in file libsinsp/event.h:
static std::unique_ptr<sinsp_evt> from_scap_evt(
std::unique_ptr<uint8_t, …
```
=> refactor: unique_ptr to arrays

userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/filter/ast.cpp, userspace/libsinsp/filter/ast.h, userspace/libsinsp/filter/parser.cpp, userspace/libsinsp/filter/parser.h, userspace/libsinsp/filter/ppm_codes.cpp, userspace/libsinsp/test/filter_compiler.ut.cpp, userspace/libsinsp/test/filter_parser.ut.cpp, userspace/libsinsp/test/filter_ppm_codes.ut.cpp, userspace/libsinsp/test/plugins.ut.cpp
/kind feature
/area libsinsp
Moving forward with https://github.com/falcosecurity/libs/issues/1789, this PR:
- Updates the grammar of libsinsp filters to support field transformers as documented in https://github.com/falcosecurity/libs/issues/1789
- Note: as for all the checks, analysis, and tests, this is not expected to be a breaking change. The grammar is backward compatible, and all the newly introduced notations used to be rejected by previous versions of the grammar and its parser
- Refactors the AST definitions used for parsing the filtering grammar to represent field transformers, fields, and also …
=> update(userspace/libsinsp)!: support field transformers in filter grammar, ast, parser, and data structures

userspace/libsinsp/plugin_table_api.cpp, userspace/libsinsp/state/dynamic_struct.h, userspace/libsinsp/state/static_struct.h, userspace/libsinsp/state/table.h, userspace/libsinsp/state/type_info.h, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/state.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
/kind cleanup
/kind feature
/area libsinsp
This is the first PR related to solving https://github.com/falcosecurity/libs/issues/1712, contributing the following:
* Optimize memory allocations for static fields
* Ground work for supporting subtable access and complex state types
* Inlining functions wherever possible
* Improve checks in static and dynamic state fields definitions
* Expose new fields in thread infos
/milestone 0.17.0
```release-note
refactor(userspace/libsinsp): minor …
```
=> refactor(userspace/libsinsp): minor changes in state API, expose new threadinfo fields

userspace/libscap/examples/01-open/scap_open.c
/kind feature
No
This PR adds stats for syscalls received in userspace and splits the console output in userspace and kernel side. Let me know if you like it, the new output is something like this:
```
----------------------------- STATS ------------------------------
------------> Kernel stats
Seen by driver (kernel side events): 225250
Rate of kernel side events (events/second): 56312
Stats v2: 18 metrics in total
[1] kernel-side counters
[Notice]: `/proc/sys/kernel/bpf_stats_enabled` not enabled, no `libbpf` stats retrieved.
[1] n_evts: 225250
[1] n_drops_buffer_total: 0
[1] …
```
=> new(scap-open): add stats for syscalls received in userspace

userspace/libsinsp/eventformatter.cpp, userspace/libsinsp/eventformatter.h, userspace/libsinsp/test/eventformatter.ut.cpp
/kind feature
/area libsinsp
/area tests
This is the (hopefully) last PR on libs for the series of https://github.com/falcosecurity/libs/issues/1789. This lastly adds support to field transformers in libsinsp's formatters, which are also used to produce Falco rules outputs. Tests are included. This takes the chance for polishing a bit the implementation of sinsp_evt_formatter, which hasn't been touched for years.
After consulting with other maintainers and some product experts the UX decision has been that, whenever transformers are used in an output, the output field map (and the JSON output) will include …
=> refactor(userspace/libsinsp): support field transformers in formatters

test/drivers/helpers/ia32.c, test/drivers/test_suites/actions_suite/ia32.cpp.in, test/drivers/test_suites/syscall_exit_suite/clock_gettime_x.cpp, test/drivers/test_suites/syscall_exit_suite/getcpu_x.cpp, test/drivers/test_suites/syscall_exit_suite/gettimeofday_x.cpp, test/drivers/test_suites/syscall_exit_suite/time_x.cpp
/kind feature
/area tests
Here i'm trying to reproduce this issue https://github.com/falcosecurity/falco/issues/3181 related to VSYSCALL addresses. 
```
[17285552.983963] BUG: unable to handle page fault for address: ffffffffff6000c7
```
The idea is to check if an unmanaged page fault is triggered when we use one of these syscalls. Syscalls involved in the vsyscall-vdso logic are the following:
*  __NR_clock_gettime
* __NR_getcpu
* __NR_gettimeofday
* __NR_time
Unfortunately, I didn't reproduce the issue but these tests are still valuable IMO. …
=> new(tests): check vdso-vsyscalls involved syscalls on 32/64 bits

.github/workflows/drivers_ci.yml
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> fix(ci): fixed drivers_ci `if` condition for kernel headers install steps

userspace/libscap/linux/scap_cgroup.c, userspace/libscap/linux/scap_cgroup.h, userspace/libsinsp/sinsp_cgroup.cpp, userspace/libsinsp/sinsp_cgroup.h
/kind feature
Make some scap_cgroup information available from `sinsp_cgroup`.
- update(sinsp_cgroup): expose in_cgroupns
- update(sinsp_cgroup): expose self_v2
- update(sinsp_cgroup): add with_self_cg to the ctors
Fixes #
```release-note
NONE
```
=> sinsp_cgroup goodies

userspace/libsinsp/parsers.cpp
/kind bug
/area libsinsp
This PR removes a wrong parsing logic for the connect_e event. Probably this was a wrong copy&paste from the connect_x parser. In the enter event, we don't have the tuple but just the family + path. So the function `set_unix_info` is reading random memory...
```cpp
inline void set_unix_info(uint8_t* packed_data)
{
memcpy(&m_sockinfo.m_unixinfo.m_fields.m_source, packed_data + 1, sizeof(uint64_t));
memcpy(&m_sockinfo.m_unixinfo.m_fields.m_dest, packed_data + 9, sizeof(uint64_t));
}
``` …
=> fix(sinsp): remove wrong unix parsing logic

driver/modern_bpf/definitions/missing_definitions.h, driver/modern_bpf/helpers/base/common.h, driver/modern_bpf/helpers/base/maps_getters.h, driver/modern_bpf/helpers/extract/extract_from_kernel.h, driver/modern_bpf/helpers/store/auxmap_store_params.h, driver/modern_bpf/helpers/store/ringbuf_store_params.h, driver/modern_bpf/maps/maps.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/accept.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/accept4.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/socket.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/socketpair.bpf.c, driver/modern_bpf/shared_definitions/struct_definitions.h, driver/syscall_compat.h, driver/syscall_table64.c, userspace/libpman/include/libpman.h, userspace/libpman/src/maps.c, userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
/kind bug
We recently saw some issues with modern_ebpf driver -> https://github.com/falcosecurity/falco/issues/3181.
Analyzing the call trace it seems the issue is related to the `accept4_x` filler.
```
[17285553.068504] Call Trace:
[17285553.074274]  <TASK>
[17285553.079218]  ? show_regs.cold.14+0x1a/0x1f
[17285553.084320]  ? __die_body+0x1f/0x70
[17285553.089309]  ? __die+0x2a/0x35
[17285553.094284]  ? _end+0x7b5da0c7/0x0
[17285553.099340]  ? page_fault_oops+0xaf/0x270
[17285553.104379]  ? bpf_probe_read_kernel+0x1d/0x50
[17285553.109575]  ? bpf_ringbuf_submit+0x10/0x20 …
```
=> fix(modern): try to address a page fault caused by `bpf_probe_read_kernel`

userspace/libsinsp/mpsc_priority_queue.h
> /kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> new(libsinsp): async event queue capacity setter

userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin.h, userspace/libsinsp/plugin_table_api.cpp, userspace/libsinsp/state/dynamic_struct.h, userspace/libsinsp/state/type_info.h, userspace/libsinsp/test/plugins/tables.cpp, userspace/plugin/plugin_api.h, userspace/plugin/plugin_types.h
/kind feature
/area libsinsp
Second contribution step of https://github.com/falcosecurity/libs/issues/1712#issuecomment-2095568407. This PR introduces the notion of "substable" in the state field types supported by libsinsp and the plugin API.
By subtable, here we mean a state tables that are owned by the entries of another table. The first use case we have is the file descriptor tables, which in our model are owned by individual thread infos (that are part of the threads table). File descriptor tables will be tables with an `int64_t` key and entries represented by `sinsp_fdinfo`. Imitating other …
=> update(userspace): define subtable field type in plugin API and sinsp state API

.github/workflows/drivers_ci.yml, README.md, driver/bpf/fillers.h, driver/ppm_fillers.c, test/drivers/test_suites/syscall_exit_suite/execve_x.cpp, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp
/kind feature
/area CI
Adds a ppc64le drivers_test CI.
It leverages https://github.com/appleboy/ssh-action since ppc64le is currently unsupported by github actions self-hosted runner: https://github.com/actions/runner/issues/2365 (https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#architectures).
There are of course some security implications: we are giving ssh access to our ppc64le node to a gha, that, while being of course open source, can be victim of attacks.
While i can see that this is quite a big issue, we:
* only use this node to test …
=> new(ci): add a test-drivers-ppc64le workflow.

userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/fdinfo.h, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/syscall_subtables.cpp, userspace/libsinsp/test/plugins/syscall_tables.cpp, userspace/libsinsp/test/plugins/test_plugins.h, userspace/libsinsp/test/state.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
/kind feature
/area libsinsp
Follows up https://github.com/falcosecurity/libs/pull/1838 as part of https://github.com/falcosecurity/libs/issues/1712. This PR updates the file descriptor info definitions to be exposed through both the sinsp state API and the plugin API. Tests are provided (500+ lines of code) covering access through both APIs, which supposedly also provide extra/complete coverage for the changes of https://github.com/falcosecurity/libs/pull/1838, as promised. With this, all the fields of file descriptor infos should be accessible. …
=> update(userspace/libsinsp): expose file descriptors as state subtable fields compatible with plugins

userspace/libscap/metrics_v2.h, userspace/libsinsp/metrics_collector.cpp, userspace/libsinsp/metrics_collector.h, userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin.h, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/metrics.cpp, userspace/libsinsp/test/plugins/test_plugins.h, userspace/plugin/plugin_api.h, userspace/plugin/plugin_types.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
/area tests
> /version …
=> new(plugin_api): add plugin metrics support

driver/modern_bpf/helpers/extract/extract_from_kernel.h, driver/modern_bpf/helpers/interfaces/syscalls_dispatcher.h, driver/modern_bpf/helpers/store/auxmap_store_params.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/accept.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/accept4.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/bind.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/connect.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/getsockopt.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/listen.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recv.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvfrom.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvmsg.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/send.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendmsg.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendto.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/setsockopt.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/shutdown.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/socket.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/socketpair.bpf.c
/kind cleanup
No
Clear some arrays before using them
```release-note
NONE
```
=> cleanup(modern): clear some arrays before using them

test/drivers/CMakeLists.txt, test/drivers/helpers/ia32.c, test/drivers/test_suites/actions_suite/ia32.cpp.in
/kind feature
/area tests
No
add some tests for ia32 syscalls
```release-note
NONE
```
=> test(drivers): add some tests for ia32 syscalls

driver/configure/build.sh
/kind bug
Some distros (namely ubuntu and debian as far as i know) do not accept `CC` being passed from env.
Instead, they want it to be passed as `make` argument.
Make sure to pass it both way in the configure modules for kmod (`CC` is already passed as env, therefore we just add it to `make` argument too !)
`falco-driver-loader` building of drivers on ubuntu.
Fixes #
I already saw something similar on driverkit a couple of months ago: https://github.com/falcosecurity/driverkit/pull/322#issuecomment-1983940164
**Does …
=> fix(driver/configure): properly pass `CC` variable as make argument.

driver/bpf/fillers.h
/kind bug
Fixes old probe bpf verifier when built with clang-18.
Fixes #
```release-note
fix(driver/bpf): fixed old bpf probe with clang-18.
```
=> fix(driver/bpf): fixed old bpf probe with clang-18.

userspace/libsinsp/plugin.cpp
/kind bug
/area libsinsp
This PR fixes a possible source of buffer overflow in the recently-added `sinsp_plugin::get_metrics` API (https://github.com/falcosecurity/libs/pull/1828).
Fixes #
Output on master:
```
[ RUN      ] sinsp_with_test_input.plugin_metrics
*** buffer overflow detected ***: terminated
Annullato (core dump creato)
```
Full trace (courtesy of valgrind massif (?)):
```
[ RUN      ] sinsp_with_test_input.plugin_metrics
*** buffer overflow detected ***: terminated
==311913== 
==311913== Process terminating with default …
```
=> fix(userspace/libsinsp): fixed possible buffer overflow in `sinsp_plugin::get_metrics`

userspace/libsinsp/container_engine/lxc.cpp
/kind feature
/area libsinsp
LXC 4.0 uses a new cgroup prefix/layout: https://linuxcontainers.org/lxc/news/2020_03_25_13_03.html
This PR adds support for it.
Fixes #
See https://github.com/falcosecurity/falco/issues/3213
```release-note
new(userspace/libsinsp): support lxc 4.0 cgroup layout.
```
=> new(userspace/libsinsp): support lxc 4.0 cgroup layout.

userspace/libsinsp/container_engine/lxc.cpp, userspace/libsinsp/plugin.cpp
/kind cleanup
/area libsinsp
Cherry picks 2 PRs from master for the 0.17.1 release:
* https://github.com/falcosecurity/libs/pull/1879
* https://github.com/falcosecurity/libs/pull/1880
Fixes #
```release-note
NONE
```
=> sync: release 0.17.1

driver/modern_bpf/helpers/store/auxmap_store_params.h, test/drivers/event_class/event_class.cpp
No
This PR fixes some comments
```release-note
NONE
```
=> doc(driver): fix some comments

userspace/libsinsp/metrics_collector.cpp, userspace/plugin/plugin_api.h, userspace/plugin/plugin_loader.c, userspace/plugin/plugin_types.h
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(plugin_api): wrong metric type enums

driver/main.c, driver/ppm_fillers.c, userspace/libscap/engine/gvisor/gvisor.cpp
/kind cleanup
/area build
No
Remove some compiler warnings on functions being defined without a prior declaration.
This happens with newer compilers that have more in-depth static code checks. In this case it is enough to define the functions as static, they are used only within the compilation unit anyway.
Fixes #
```release-note
NONE
```
=> fix: some compiler warnings (func def. w/o decl.)

userspace/libsinsp/container.cpp
Include cri.hpp in container.cpp in order to avoid
```
/usr/bin/ld: /usr/lib/aarch64-linux-gnu/libsinsp.so: undefined reference to `libsinsp::cri::cri_interface<libsinsp::cri::cri_api_v1>::get_cri_runtime_type() const'
collect2: error: ld returned 1 exit status
```
when building with shared libs on Linux.
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area …
=> fix(userspace/libsinsp): Include cri.hpp in container.cpp

cmake/modules/CompilerFlags.cmake
/kind bug
/area CI
This PR workarounds an issue with the github windows runner: https://github.com/actions/runner-images/issues/10004
Fixes #
```release-note
NONE
```
=> chore(cmake): workaround CI issue for windows.

userspace/libsinsp/filter_compare.cpp, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/filter_op_numeric_compare.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind bug
/area libsinsp
No
Libs 0.17.0 had some changes in numeric compare and casting. However, it looks like we are now doing unsigned comparison even if the data is signed, meaning that sinsp is thinking that `-1 > 10000`. This requires a bit of testing to see if it is the case but we need to fix it for the next patch release. Also cover comparisons with tests.
See: https://github.com/falcosecurity/falco/issues/3245
/milestone 0.17.2
Fixes #
**Does …
=> fix(libsinsp): fix regression in signed comparison

driver/bpf/fillers.h
/kind bug
https://github.com/falcosecurity/libs/pull/1814 and https://github.com/falcosecurity/libs/pull/1767 introduced 2 old bpf verifier regressions.
This PR aims at fixing them.
Fixes #1890 
Already tested against our kernel matrix (https://github.com/falcosecurity/libs/actions/runs/9386047428):
AMD64:
|        KERNEL        | CMAKE-CONFIGURE | KMOD BUILD | KMOD SCAP-OPEN |            BPF-PROBE BUILD             |            BPF-PROBE SCAP-OPEN             |             MODERN-BPF SCAP-OPEN             | …
=> fix(driver/bpf): fixed a couple of verifier issues.

userspace/libsinsp/test/user.ut.cpp, userspace/libsinsp/user.cpp
/kind bug
/area libsinsp
No
NSS (Named Service Switch) users can be listed in `/etc/passwd` with a name starting with a `+` or `-` sign and an empty _uid_ field (the same idea applies to groups in `/etc/group`). For instance a line in `/etc/passwd` can take the form `+@r_unix::::::` and, when parsed by function `fgetpwent()`, it translates the empty _uid_ field in a zero. This _uid_ is then used as key to an internal map, effectively overwriting the data of the root user, which typically gets _uid_ equal to zero.
This PR aims at ignoring such users and groups (the ones with a `+` or `-` prefix) that cannot …
=> fix: Ignore NSS user and group entries

cmake/modules/CompilerFlags.cmake, cmake/modules/cares.cmake, userspace/libsinsp/filter_compare.cpp, userspace/libsinsp/metrics_collector.cpp, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/filter_op_numeric_compare.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h, userspace/libsinsp/test/user.ut.cpp, userspace/libsinsp/user.cpp, userspace/plugin/plugin_api.h, userspace/plugin/plugin_loader.c, userspace/plugin/plugin_types.h
/kind cleanup
/area build
Cherry picks:
* https://github.com/falcosecurity/libs/pull/1885
* https://github.com/falcosecurity/libs/pull/1900
* https://github.com/falcosecurity/libs/pull/1902
* https://github.com/falcosecurity/libs/pull/1905
* https://github.com/falcosecurity/libs/pull/1909
Fixes #
https://github.com/falcosecurity/libs/pull/1900 needed a manual fix since master had also changes from https://github.com/falcosecurity/libs/pull/1878 that caused a conflict.
```release-note
NONE …
```
=> sync: 0.17.2

userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/filter_op_contains.ut.cpp
/kind feature
/area tests
No
A file that covers another operator.
Fixes #
```release-note
NONE
```
=> new(tests): add tests for contains/icontains

userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/test/state.ut.cpp
/kind bug
/kind feature
/area libsinsp
I discovered that the `type` field exposed by the fd tables through the state & plugin API is returning wrong/unrelated data since it's been available. Unfortunately, IMO the safest fix is to turn its type into uint8, which is essentially a breaking change for whoever was accessing it (the type change will cause errors to be returned). However, considering the information returned has never been valid I think this is something we can afford, specially considering that the latest libs version has been released just few weeks ago.
I also noted that we're not exporting the …
=> fix(userspace/libsinsp): solve fdtables 'type' field returning random data

userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/test/events_evt.ut.cpp
/kind feature
/area tests
No
While writing other tests I noticed how `evt.res` and related fields work, so I added coverage for those as well.
Fixes #
```release-note
NONE
```
=> new(tests): add tests for event result

userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/gvisor_config.ut.cpp
/kind feature
/area tests
No
As per title. I had this test locally, I think from the latest gvisor fix, and I needed to fix it up and subimit it.
Fixes #
```release-note
NONE
```
=> new(test): add test for gvisor config generator

userspace/libsinsp/event.cpp
/kind bug
/area libsinsp
No
Resize the param storage in case of a long path
```release-note
NONE
```
=> fix(libsinsp): resize the param storage in case of a long path

userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/sinsp_filtercheck_thread.h, userspace/libsinsp/test/filterchecks/proc.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> new: introduce `proc.{stdin,stdout,stderr}.{name,type}` fields

userspace/libsinsp/prefix_search.h
/kind bug
/area libsinsp
No
As per title. It is used in the file.
Fixes #
```release-note
fix(libsinsp): add missing #include <map>
```
=> fix(libsinsp): add missing #include <map>

.github/workflows/create-comment.yml, .github/workflows/perf.yml
/kind feature
/area CI
Split from #1910. Added a CI around `perf` tool.
For now, we only run libsinsp unit tests with perf. In the future we might want to add:
* a run of sinsp-example against some scap files
* tests with `valgrind massif` tool
Also, the new `perf-libs-linux-amd64` check needs to be added to required status checks once we find a good enough threshold.
The CI will fail because it expects master CI to upload perf reports.
I will rebase #1910 once this is merged and expect the PR comment to be created. 
Fixes #
**Does this …
=> new(ci): added an initial perf-related CI.

userspace/libsinsp/threadinfo.h
/kind bug
/area libsinsp
No
When a thread is "invalid" it has a `vtid = -1 ` so when we check `m_tid != m_vtid` in `is_in_pid_namespace` we will always return true. we need to perform the check only if both identifiers are valid
```release-note
NONE
```
=> fix(sinsp): invalid threads shoudln't be in a pid namespace

userspace/libsinsp/event.h, userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/filter_cache.h, userspace/libsinsp/filter_field.h, userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin_filtercheck.cpp, userspace/libsinsp/plugin_filtercheck.h, userspace/libsinsp/sinsp_filter_transformer.h, userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/sinsp_filtercheck.h, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/sinsp_filtercheck_fd.h, userspace/libsinsp/test/filter_compiler.ut.cpp, userspace/libsinsp/test/filterchecks/mock.cpp, userspace/libsinsp/test/plugins/syscall_extract.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind cleanup
/kind feature
/area libsinsp
/area tests
The usage of caching in sinsp filters (and thus, Falco rules) has been a shy experiment from some time ago that was never finalized. I think this is generally something that could be useful and could help saving few CPU % points on high loads, even though from my synthetic measurements this could account for a max of 1-2% savings.
This PR refactors the code area involved, and enables caching in filters. It does so by introducing an abstract interface that can be used as-is or customized by the different adopters, and the whole installation into filters …
=> refactor(userspace/libsinsp): polish and enable filter caching

.github/actions/composite-perf/action.yml, .github/generate_inline_svg_md.py, .github/workflows/pages.yml, .github/workflows/perf.yml, docs/index.md, docs/perf.md, mkdocs.yml
/kind feature
/area CI
It will be ran by perf CI on PRs and pages CI on master. 
Also, add a new gh pages section with flamegraphs (svgs) built from master.
Fixes #
```release-note
NONE
```
=> new(ci): move perf CI to a composite action.

userspace/libsinsp/event.cpp, userspace/libsinsp/event.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/test/events_param.ut.cpp
/kind cleanup
/area libsinsp
No
Addressing feedback received.
A contributor tried to set up a test with something like `evt->get_param(1)->as<std::string>()` and was confused by the fact that (1) `std::string` was not directly supported and (2) this did not result in a compilation error but in a runtime error which was hard to understand, as the engine tried to reinterpret a char string as an `std::string` basically setting the raw bytes of the string object and then erroring out because of the wrong size.
So to make it …
=> cleanup(libsinsp): introduce param->as<std::string>(), add error for unsupported types

.github/actions/composite-perf/action.yml, .github/workflows/pages.yml, .github/workflows/perf.yml
/kind bug
/area CI
Small fix.
Also, i updated running linux kernel on our cncf x64 node to 5.19.0 to incorporate linux perf patch: https://github.com/torvalds/linux/commit/be8ecc57f180415e8a7c1cc5620c5236be2a7e56
See: https://eighty-twenty.org/2021/09/09/perf-addr2line-speed-improvement; basically without the patch,  `perf script` is basically unusable on large files.
Fixes #
```release-note
NONE
```
=> fix(ci): fixed deploy-pages job needs.

userspace/libpman/src/configuration.c, userspace/libpman/src/lifecycle.c, userspace/libpman/src/state.h
/kind bug
/area libpman
No
Without this fix, verifier logs are almost always truncated...we are using a buffer of 4096 bytes but this is not enough for long verifier logs. We need to use the same dimension provided by libbpf `(UINT32_MAX >> 8)`. This is ~16 MB so when we are sure the verifier is passed we probably want to free this memory...if libbpf wants to log again we provide a smaller buffer (8192) that should be enough for normal logs. @Molter73 
```release-note
NONE
```
=> fix(libpman): avoid truncated verifier logs

userspace/libsinsp/test/plugins/metrics.cpp, userspace/libsinsp/test/plugins/plugin_extract.cpp, userspace/libsinsp/test/plugins/plugin_source.cpp, userspace/libsinsp/test/plugins/syscall_async.cpp, userspace/libsinsp/test/plugins/syscall_extract.cpp, userspace/libsinsp/test/plugins/syscall_parse.cpp, userspace/libsinsp/test/plugins/syscall_source.cpp, userspace/libsinsp/test/plugins/syscall_subtables.cpp, userspace/libsinsp/test/plugins/syscall_subtables_array.cpp, userspace/libsinsp/test/plugins/syscall_tables.cpp
/kind cleanup
/area build
No
The struct `plugin_state` is defined several times with different definitions in different compilation units. This would not be a problem, but if you try to apply link-time optimization (LTO) the linker complains and raises an error because the one-definition rule (ODR) has been broken. The fix is easy, the duplicate definitions are only used within their .cpp file and can be enclosed in an anonymous namespace, so that they'll have internal linkage.
This is one of several changes to make `falcosecurity-libs` (and its client code) amenable to LTO, should one want to experiment …
=> fix: class definitions with duplicate names

.github/actions/composite-perf/action.yml, .github/workflows/pages.yml, .github/workflows/perf.yml, docs/perf.md, mkdocs.yml, userspace/libsinsp/test/sinsp_utils.ut.cpp
/kind feature
/area CI
Adds [`heaptrack`](https://github.com/KDE/heaptrack) support to the new perf-related CI.
Also, this improves threshold checks for `perf`: they now run against sum of diffs, that is more stable and useful. Ie: if part of logic gets moved from one method to another, we expect eg: `method_A -> -7%`, `method_B -> +7%`. Before, this triggered the CI error; now it does not, since the sum is 0.
Fixes #
Heaptrack only tracks heap allocations; it cannot track stack allocations. Note this is the same default behavior as …
=> new(ci,docs): added heaptrack to our new perf related CI.

.github/workflows/perf.yml, userspace/libsinsp/container.cpp, userspace/libsinsp/container.h, userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/fdinfo.h, userspace/libsinsp/metrics_collector.cpp, userspace/libsinsp/metrics_collector.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/sinsp_metrics.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h, userspace/libsinsp/utils.cpp
/kind cleanup
/area libsinsp
This PR keeps a reference on m_sinsp_stats_v2 where needed, instead of fetching it every time.
Fixes #
```release-note
chore!(userspace/libsinsp): keep a reference on m_sinsp_stats_v2 where needed 
```
=> chore(userspace/libsinsp): keep a reference on m_sinsp_stats_v2 where needed

.github/workflows/create-comment-kernel-testing.yml, .github/workflows/drivers_ci.yml
/kind feature
/area CI
This PR enables kernel-testing framework on PRs.
I discovered that, for self hosted runners, there is no parallelism: each job's request is enqueued. 
The only parallelism would happen if we had multiple self hosted runners under same tags, then the jobs would be distributed among them.
See https://github.com/orgs/community/discussions/26769#discussioncomment-3253321
Fixes #
```release-note
NONE
```
=> new(ci): enable kernel testing on PRs.

userspace/libsinsp/metrics_collector.cpp, userspace/libsinsp/metrics_collector.h, userspace/libsinsp/test/sinsp_metrics.ut.cpp
This is an alternative to the original implementation. Instead of using capturing lambdas that get called back after some additional work is done, we use classes and gather data during instantiation of the object. This approach should be a lot more straight forward and it also doesn't create unneeded objects when there's no need to do so. Another benefit of this approach is that metrics are bundled together in a very specific way, rather than depending on the ordering of definitions in an enum, which is a C idiom.
/kind cleanup
/area libsinsp
Fixes # …
=> chore(metrics): refactor metrics v2 so it uses classes

userspace/libsinsp/metrics_collector.cpp
/kind bug
/area libsinsp
No
This fixes a warning/error when compiling with warnings as errors
Fixes #
```release-note
NONE
```
=> chore(libsinsp): fix unused value for fscanf

userspace/libsinsp/sinsp_filter_transformer.cpp, userspace/libsinsp/test/filter_transformer.ut.cpp
/kind bug
/area libsinsp
No
Fix a potential crash in string transformers when attempting to read an empty output buffer.
Also, lightly refactor tests and cover the empty string case.
Fixes #
```release-note
fix(libsinsp): fix crash in string transformers when called on an empty string
```
=> fix(libsinsp): fix crash in string transformers when called on an empty string

userspace/libsinsp/filter/parser.cpp, userspace/libsinsp/filter/parser.h, userspace/libsinsp/sinsp_filter_transformer.cpp, userspace/libsinsp/sinsp_filter_transformer.h, userspace/libsinsp/test/filter_parser.ut.cpp, userspace/libsinsp/test/filter_transformer.ut.cpp
/kind feature
/area libsinsp
No
Introduce `basename()` as transformer. This allows, for instance, to write expressions like `basename(proc.exepath) = cat` to match against the original executable name even if it has been symlinked without knowing the full path, or any other file name based detection.
Fixes #1927
```release-note
new(libsinsp): add basename() string transformer
```
=> new(libsinsp): add basename() string transformer

userspace/libsinsp/sinsp_filter_transformer.cpp
/kind bug
/area libsinsp
No
As per title
Fixes #
```release-note
fix(libsinsp): use size_type in basename transformer, fix build on Windows
```
=> fix(libsinsp): use size_type in basename transformer

driver/main.c
/kind bug
https://github.com/torvalds/linux/commit/c4aab26253cd1f302279b8d6b5b66ccf1b120520, included in linux 6.10-rc1, moved `fd_is_open` away from an header we can include.
Therefore the proposed patch is to implement ourself the one-liner.
Fixes #
Keeping it as `wip` until linux 6.10 is nearly released.
I'll use this PR for tests if more changes are needed.
```release-note
fix(driver): fix build of kmod on linux 6.10.
```
=> fix(driver): fix build of kmod on linux 6.10.

userspace/libsinsp/filter/ast.h, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/ast_exprs.ut.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
/area tests
> /version …
=> Fix binary check expr is equal

userspace/libsinsp/filter/ast.h, userspace/libsinsp/filter_compare.cpp
/kind bug
/area libsinsp
Our comparison logic in the filters introduced a regression that misinterprets checks such as `fd.ip != "0:0:0:0:0:0:0:1"` and `not fd.ip = "0:0:0:0:0:0:0:1"`. Those are supposed to be functionally equal, however when the underlying comparison involves ip addresses of different sizes (ipv4, ipv6) the two expressions diverge.
/milestone 0.18.0
```release-note
fix(userspace/libsinsp): solve issues with negate comparisons on ip and ipnet checks
```
=> fix(userspace/libsinsp): solve issues with negate comparisons on ip and ipnet checks

userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/filter/parser.cpp, userspace/libsinsp/filter_compare.cpp, userspace/libsinsp/filter_compare.h, userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/sinsp_filtercheck.h, userspace/libsinsp/test/filter_compiler.ut.cpp, userspace/libsinsp/test/filter_parser.ut.cpp
/kind feature
/area libsinsp
/area tests
This has been requested by the community since a long time (~6 years) both publicly and in private channels. The main concern of supporting regular expressions is the potential performance impact on high events throughput such as the one of syscalls. However, I consider the project mature enough and in need of serving a multitude of different use cases, so I'm proposing to support this feature and empowering the user with the choice and wisdom on how best using it.
The contribution implements a new `regex` operator that can be used with string fields such as `fd.name …
=> new(userspace/libsinsp): support regular expression operator in sinsp filters

userspace/libscap/engine/bpf/scap_bpf.c
/kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(driver/bpf): close maps on cleanup

.github/workflows/drivers_ci.yml, test/vm/containers/modern-falco-builder.Dockerfile
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> fix(ci,test): fixed centos:7 related CI by using vault.centos.org.

.github/workflows/test_coverage_ci.yml
/kind feature
/area CI
No
Add code coverage reports for libsinsp unit tests via [codecov](https://about.codecov.io/)
Part of: https://github.com/falcosecurity/libs/issues/1784
Fixes #
```release-note
NONE
```
=> new(ci): add libsinsp unit test code coverage

.github/workflows/ci.yml, .github/workflows/create-comment-kernel-testing.yml, .github/workflows/create-comment-perf.yml, .github/workflows/drivers_ci.yml, .github/workflows/e2e_ci.yml, .github/workflows/perf.yml, .github/workflows/reusable_kernel_tests.yaml
/kind cleanup
/area CI
As per title. According to supply chain security standards we currently employ.
Fixes #
```release-note
NONE
```
=> cleanup(ci): pin deps to hashes

.github/workflows/test_coverage_ci.yml, codecov.yml
/kind bug
/area CI
No
It seems like we can specify a "component" in this case `libsinsp` so we can have coverage there. The actual line coverage computed locally is about 74% but codecov seems to compute percentages a bit differently, probably because it factors in branch coverage somehow. Anyhow, let's add the `libsinsp` component
Fixes #
```release-note
NONE
```
=> fix(ci): introduce "libsinsp" component for test coverage

userspace/libsinsp/event.cpp, userspace/libsinsp/filter_compare.cpp, userspace/libsinsp/memmem.h, userspace/libsinsp/test/events_param.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind feature
/area libsinsp
No
For https://github.com/falcosecurity/falco/issues/3275 , one option is to add a debug print when we find this kind of issue. This can help us debug the driver in case something unexpected happen. Also, add a test for a corrupted string in an event.
Fixes #
```release-note
new(libsinsp): add debug information for corrupted (mismatched len) events
```
=> new(libsinsp): add debug information for corrupted (mismatched len) events

.github/workflows/reusable_kernel_tests.yaml
/kind bug
/area CI
Images are not pushed under the hash name.
Fixes #
```release-note
NONE
```
=> fix(ci): use semver tag version for kernel-testing action.

userspace/libsinsp/metrics_collector.h
/kind bug
/area libsinsp
No
Fixes the following when building Falco:
```
/home/ubuntu/dev/falcosecurity/libs/userspace/libsinsp/metrics_collector.h: In instantiation of ‘metrics_v2 libs::metrics::libs_metrics_collector::new_metric(const char*, uint32_t, metrics_v2_value_type, metrics_v2_value_unit, metrics_v2_metric_type, T) [with T = long unsigned int; metrics_v2 = metrics_v2; uint32_t = unsigned int; metrics_v2_value_type = metrics_v2_value_type; metrics_v2_value_unit = metrics_v2_value_unit; metrics_v2_metric_type = …
```
=> fix(libsinsp): fix Falco compilation error on libsinsp_metrics::set_metric_value

userspace/libsinsp/sinsp.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp): pass shared_ptr by reference

driver/bpf/fillers.h, driver/bpf/missing_definitions.h, driver/modern_bpf/definitions/missing_definitions.h, driver/modern_bpf/definitions/struct_flavors.h, driver/modern_bpf/helpers/extract/extract_from_kernel.h, driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c, driver/ppm_fillers.c, test/drivers/test_suites/syscall_exit_suite/execve_x.cpp
/kind bug
/kind cleanup
No
This PR provides a fix for https://github.com/falcosecurity/falco/issues/3276.
The page fault was due to a backport in RHEL9. 
More in detail this commit https://github.com/torvalds/linux/commit/0af950f57fefabab628f1963af881e6b9bfe7f38 was backported to kernel versions older than 6.5.
So when our drivers run this code:
```c
#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 16, 0)
has_upper = oe->has_upper;
#elif LINUX_VERSION_CODE < KERNEL_VERSION(6, 5, 0)
has_upper = test_bit(OVL_E_UPPER_ALIAS, &(oe->flags));
#else
has_upper = …
```
=> fix(driver): simplify exe_upper_layer extraction

userspace/libsinsp/event.h, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/sinsp_utils.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind cleanup
/area libsinsp
No
* Optimize `sinsp_split` by not using a string stream and `getline` but a simple loop insteadl.
* Simplify it and remove an exception that may or may not be thrown
* Handle both null and non-null terminated cases depending on the code path
Fixes #
```release-note
fix(libsinsp): simplify sinsp_split, modify set_env/args
```
=> fix(libsinsp): optimize sinsp_split, modify set_env/args

cmake/modules/zlib.cmake
The debug versions of zlib have a "d" in their name, e.g. zlibstaticd.lib.
> /kind bug
/kind cleanup
> /kind design
/area build
> /area CI
> /area tests
**Does this …
=> update(cmake): Use the correct zlib debug library name on Windows

.github/workflows/ci.yml
Pass `--parallel` to `cmake --build`. This requires CMake 3.12, but that shouldn't be a problem on the affected runners.
> /kind bug
/kind cleanup
> /kind design
> /area build
/area CI …
=> update(ci): Build more jobs in parallel

userspace/libsinsp/test/ifinfo.ut.cpp
/area tests
No
We need to ensure the same byte order for all architectures, so added the Byte order modifiers.
Fixes #
```release-note
NONE
```
=> tests(sinsp): Fix infer_defaults_to_first_non_loopback TC

userspace/libsinsp/utils.h
/kind cleanup
/area libsinsp
No
In some setups (Windows, for instance) the `isprint()` check might fail in debug mode for chars outside of that range.
Fixes #
```release-note
cleanup(libsinsp): do not crash on g_invalidchar in windows debug builds
```
=> cleanup(libsinsp): update g_invalidchar for windows

userspace/libsinsp/utils.cpp
/kind cleanup
/area libsinsp
/milestone 0.18.0
No
As per title
Fixes #
```release-note
NONE
```
=> cleanup(libsinsp): remove unreachable code

userspace/libsinsp/metrics_collector.h
/kind cleanup
/area libsinsp
This change was meant to go in as part of #1920, but somehow got lost in translation. Compilation of Falco will be fixed by falcosecurity/falco#3265.
Fixes #
```release-note
NONE
```
=> cleanup(metrics): remove duplicated new_metric method

userspace/libscap/engine/bpf/scap_bpf.h
/kind cleanup
No
This PR adds some docs and renames some variables in the bpf engine
```release-note
NONE
```
=> docs(bpf_engine): add some docs and rename some variables

userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/filter_op_net_compare.ut.cpp
/kind bug
/area libsinsp
No
Very similar to https://github.com/falcosecurity/libs/pull/1953 but in the "fd.net" part of the filterchecks. In this case we could get a type confusion for the parameter value, leading to an incorrect comparison (ipv4 vs ipv6).
We still need tests for these cases because they are very tricky.
cc @jasondellaluce , can you think of other places where this may happen?
Fixes # …
=> fix(libsinsp): check ipvXnet size before comparing

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> /version …
=> fix(libsinsp): add function to set compiler filter and filter string

userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/filter_op_net_compare.ut.cpp
/kind feature
/area libsinsp
No
sync release 0.17.x branch
Fixes #
```release-note
NONE
```
=> sync release 0.17.x branch

.github/workflows/test_coverage_ci.yml, codecov.yml
/kind cleanup
/area CI
No
Trying to get codecov to behave even if not all tests are computing coverage at this point.
Fixes #
```release-note
NONE
```
=> update(ci): use codecov flag for libsinsp

userspace/libscap/CMakeLists.txt, userspace/libscap/ringbuffer/ringbuffer.h, userspace/libscap/ringbuffer/ringbuffer_dump.c, userspace/libscap/ringbuffer/ringbuffer_dump.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libscap
> /area tests
> /version …
=> new(libscap): dump ringbuffer contents after detecting corruption

.github/actions/composite-perf/action.yml
/kind cleanup
/area CI
Add a step where the scap file gets loaded (read by sinsp-example) before `perf`ing it, so that we get more stable results.
Also, removed /dev/shm tmpfs workaround introduced in #1975 
Fixes #
```release-note
NONE
```
=> chore(ci): add an empty run for scap file before perf'ing it.

userspace/libscap/linux/scap_cgroup.c
Fix the issue of cgroup subsystem controller files not being present when Calico is present
> /kind bug
Environmental: 
K8s installed, there is calico present
The system information is as follows
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
There will be no files in the/proc/1/root/run/calico/cgroup/directory
Will cause the following fd issues
06-19 05:30:06.012043 total threads in the table:86, total fds in all …
=> FixTheCompatibilityIssueWithCgroupv2

.github/workflows/ci.yml
/kind cleanup
/area CI
No
Some linters/IDEs (e.g. Visual Studio 2022) complain about this statement and mark it as error, remove this. The issue is that it's missing the "matrix" (which we don't use here so it's ok)
Fixes #
```release-note
NONE
```
=> fix(ci): remove spurious strategy statement

.github/workflows/semgrep_checks.yml
/kind cleanup
/area CI
No
As per title. It seems to be working fine now.
Fixes #
```release-note
NONE
```
=> cleanup(ci): update semgrep to 1.84.0

driver/main.c
/kind bug
No
This PR provides 2 fixes:
* The preemptions are now taken into consideration and we don't increment the `n_evts` since the event is always dropped.
* In case of some unknown error we had just an `ASSERT(false)` but not a `n_drops_buffer` increment. This means that in production we were not able to detect if we fell into the wrong branch or not. Now we increment the `n_drops_buffer` metric.
```release-note
NONE
```
=> fix(driver/kmod): count the right number of events and drops

test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp
/kind feature
/area tests
No
This PR adds a new test for execveat with AT_EMPTY_PATH flag
```release-note
NONE
```
=> new(tests): add a new test for execveat with `AT_EMPTY_PATH`

userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/gvisor/gvisor.cpp, userspace/libscap/engine/kmod/scap_kmod.c, userspace/libscap/engine/modern_bpf/scap_modern_bpf.c, userspace/libscap/engine/nodriver/nodriver.c, userspace/libscap/engine/noop/noop.c, userspace/libscap/engine/noop/noop.h, userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/engine/source_plugin/source_plugin.c, userspace/libscap/engine/test_input/test_input.c, userspace/libscap/engine_handle.h, userspace/libscap/linux/scap_linux_platform.h, userspace/libscap/scap-int.h, userspace/libscap/scap.c, userspace/libscap/scap_api_version.h, userspace/libscap/scap_engines.h, userspace/libscap/scap_open.h, userspace/libscap/scap_platform.h, userspace/libscap/scap_platform_impl.h, userspace/libscap/scap_vtable.h
/kind cleanup
/area build
No
Class `scap_engine_handle` is defined once in its header file, but has a single pointer data member `SCAP_HANDLE_T* m_handle` that contains a macro that changes depending on what source file is including it. This is by design, the idea being that it is a sort of hierarchy of classes that share the same functions. However this is not without problems as if one tries to enable link-time optimization (LTO) the linker presents an error that the one-definition rule (ODR) has been broken.
This PR solves the issue by using a generic `void*` for the data member and using a cast to the …
=> fix: multiple definitions for scap_engine_handle

userspace/libsinsp/ifinfo.cpp, userspace/libsinsp/ifinfo.h, userspace/libsinsp/test/ifinfo.ut.cpp
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> update(sinsp/ifinfo): add new public addr_to_string methods

test/libscap/test_suites/engines/bpf/bpf.cpp, test/libscap/test_suites/engines/kmod/kmod.cpp, test/libscap/test_suites/engines/modern_bpf/modern_bpf.cpp, userspace/libpman/src/configuration.c, userspace/libpman/src/lifecycle.c, userspace/libpman/src/state.h, userspace/libpman/src/stats.c, userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/kmod/kmod.h, userspace/libscap/engine/kmod/scap_kmod.c, userspace/libscap/metrics_v2.h
/kind feature
/area libscap
/area libpman
/area tests
No
This PR introduces new per-CPU stats for our drivers. When collecting some metrics about drops in our drivers, it could be useful to understand where we are dropping. It could be useful to know how drops and events are distributed between our CPUs, whether it is just one CPU under pressure or if the whole system is having a hard time.
This is an example of the output on 8 CPUs with `scap-open`
```
[1] n_evts: 88939
[1] n_drops: 0
[1] n_evts_cpu_0: 10326
[1] …
```
=> new(scap,pman): add new per-CPU driver metrics

userspace/libscap/engine/kmod/scap_kmod.c
/kind bug
/area libscap
No
Fix build error
Fixes #
```release-note
NONE
```
=> fix(libscap): fix scap_kmod build with HANDLE() macro

userspace/libsinsp/filter/ast.h
/kind bug
/area build
/area libsinsp
No
Fixes build with gcc-15
Fixes #2012 
You're welcome :)
Not sure if this needs a release note.
```release-note
NONE
```
=> fix(userspace/libsinsp): explicitly include <cstdint> to fix build with gcc-15

userspace/libsinsp/metrics_collector.cpp, userspace/libsinsp/test/sinsp_metrics.ut.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> cleanup(sinsp/metrics): assorted cleanups for robustness

userspace/libsinsp/container.cpp, userspace/libsinsp/container.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/sinsp_with_test_input.h
/kind cleanup
/area libsinsp
This change splits configuration of the static container data away from the sinsp constructor and into a separate set_static_container method. 
The motivation behind this change is two fold:
- Configuration of other container engines is handled by a call to set_container_engine_mask() before starting the inspector, the new method is closer to this implementation.
- Enabling metrics collection should not require adopters to pass in 4 unrelated arguments to the sinsp constructor.
These changes will require some modifications into the Falco main repo, as far as I can tell they …
=> cleanup(sinsp): add set_static_container method

.github/workflows/create-comment-perf.yml, .github/workflows/perf.yml
/kind cleanup
/area CI
It disables the flaky scap-related perf test; moreover, it avoids polluting PRs with perf-related bot comments, instead editing existing one.
Fixes #
```release-note
NONE
```
=> chore(ci): disable unstable scap-related perf test from perf PR comment and check

userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/test/filterchecks/proc.cpp
/kind bug
/area libsinsp
#1904 had a small refactor of the management of `CO_IN` comparison for `PT_CHARBUF` fields: https://github.com/falcosecurity/libs/pull/1904/files#diff-1058cd2ebabb1fdd8503ea762a0f06f33af56cf993b3eae8a5f1919f9ef2f5d2L1026
Basically, `craft_filter_value` is now responsible of returning a correctly-sized `item` for `PT_CHARBUF`, but L1041 (https://github.com/falcosecurity/libs/pull/1904/files#diff-1058cd2ebabb1fdd8503ea762a0f06f33af56cf993b3eae8a5f1919f9ef2f5d2L1041) was not updated to use the newly-computed operator len.
Special thanks to @LucaGuerra for spotting the issue and working …
=> fix(userspace/libsinsp): fixed CO_IN filter crafted value.

userspace/libpman/src/ringbuffer.c, userspace/libpman/src/ringbuffer_debug_macro.h
/kind bug
/kind cleanup
/area libpman
No
This PR reduces the possibility of facing out-of-order events with the modern ebpf probe. When we reach the producer the right thing to do is to insist on the same CPU to check if the producer has pushed some new events instead of skipping the current buffer returning a NULL event. Otherwise, there is the risk that we skip some events with a lower timestamp with respect to the others in the other buffers.
Added also some handy debug print. Example
```
-----------------------------
Iterate over all the buffers
[NULL Event] buf: 0
[NULL Event] buf: 1
[NULL Event] buf: 2 …
```
=> fix(libpman): try to get a new event on the same CPU after increasing the producer

CMakePresets.json
/kind feature
/area build
No
These days I'm building scap drivers tests over several machines and every time I need to type an infinite cmake to configure them (getting it wrong every time). If you are like me this `CMakePresets.json` file should help you. Configure drivers test should be as simple as:
```bash
cmake --presets scap-drivers
```
Then to build different targets you should enter the directory created for you by the preset and run the `make` command`
```bash
cd build-scap-drivers
make drivers_test
make scap-open
make libscap_test
...
```
Here I provide just 2 presets that I often use while …
=> chore: add CMakePresets.json file

.github/workflows/ci.yml, CMakeLists.txt, benchmark/CMakeLists.txt, benchmark/README.md, benchmark/libsinsp/utils.cpp, benchmark/main.cpp, cmake/modules/googleBenchmark.cmake
/kind feature
/area tests
This PR introduces the first Google benchmark. This is just the scaffolding we should add more tests to it. For example, a good candidate could be the scap-file benchmark that we are running today in our perf CI @FedeDP 
```release-note
NONE
```
=> new(tests): introduce the first google benchmark

userspace/libsinsp/container_engine/cri.cpp
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> update(cri): `cri-dockerd` support

.github/actions/composite-perf/action.yml, .github/workflows/pages.yml, .github/workflows/perf.yml, benchmark/libsinsp/utils.cpp, userspace/libsinsp/utils.cpp
/kind feature
/area CI
Adds some more benchmarks (around sinsp `concatenate_paths` and `split_container_image` utils).
Moreover, it adds support for benchmark results in our perf CI.
Fixes #
```release-note
NONE
```
=> new(ci,benchmarks): added more benchmarks and make use of them in perf CI

userspace/libsinsp/state/dynamic_struct.h, userspace/libsinsp/state/table.h, userspace/libsinsp/state/table_adapters.h, userspace/libsinsp/test/state.ut.cpp
/kind bug
/area libsinsp
/area tests
With some random tests I figured that dynamic structs implemented shallow copy semantics, whereas the intended behavior was deep copy of the allocated values. For example, storing a dynamic field in the file descriptor subtable would end up having lost information when cloning file descriptor infos during the parsing phase of fork-family syscalls.
Tests have been added.
```release-note
fix(libsinsp/state): ensure deep copy semantics and proper memory …
```
=> fix(libsinsp/state): ensure deep copy semantics and proper memory ownership in dynamic structs

.github/workflows/ci.yml, .github/workflows/perf.yml
/kind cleanup
/area CI
Fixes #
```release-note
NONE
```
=> fix(ci): only account for mean values in google benchmarks perf CI checks

driver/modern_bpf/CMakeLists.txt
/kind cleanup
/area build
This is a very small change that should have no major impact on how the build works. However, when using ccache, having the clang executable resolve to the real path completely breaks compilation for the modern probe.
I know there are other ways to configure ccache that would potentially be possible to have it working, but I would rather not have a custom configuration just for this component.
Fixes #
**Special notes for your reviewer**: I can't think of a particular reason to use the real versus the absolute path for clang …
=> Use absolute path for clang executable in modern_bpf driver

driver/bpf/filler_helpers.h, driver/capture_macro.h, driver/modern_bpf/helpers/store/auxmap_store_params.h, driver/ppm_events.c, test/drivers/event_class/event_class.cpp, test/drivers/event_class/event_class.h, test/drivers/event_class/network_utils.h, test/drivers/test_suites/syscall_enter_suite/sendmsg_e.cpp, test/drivers/test_suites/syscall_enter_suite/sendto_e.cpp, test/drivers/test_suites/syscall_exit_suite/read_x.cpp, test/drivers/test_suites/syscall_exit_suite/recvfrom_x.cpp, test/drivers/test_suites/syscall_exit_suite/recvmsg_x.cpp, test/drivers/test_suites/syscall_exit_suite/sendmsg_x.cpp, test/drivers/test_suites/syscall_exit_suite/sendto_x.cpp, test/drivers/test_suites/syscall_exit_suite/write_x.cpp
/kind feature
See the payload of DNS query/response could be usually interesting. This patch increases the dynamic snaplen when the DNS PORT (53) is detected. It is disabled by default if `do_dynamic_snaplen` is not enabled.
This PR continues the reactor of network drivers tests
```release-note
NONE
```
=> new(drivers): add dns dynamic snaplen

driver/bpf/fillers.h, driver/modern_bpf/definitions/struct_flavors.h, driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c
/kind bug
Fixes build against latest linux 6.11-rc{1...4}; the breaking commit is: https://github.com/torvalds/linux/commit/3aa63a569c64e708df547a8913c84e64a06e7853
Fixes #
```release-note
fix(driver): fixed build against linux 6.11.
```
/hold for now, until we are at least at rc6, as always.
=> fix(driver): fixed build against linux 6.11.

.github/workflows/drivers_ci.yml
/kind cleanup
/area CI
Fixes #
```release-note
NONE
```
=> cleanup(ci): don't run drivers CI job that use secrets on forks.

driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/quotactl.bpf.c
/kind bug
No
When `CONFIG_QUOTACTL` is not defined we need to avoid relocations on structs that are not defined like `struct if_dqblk`.
Running `bpftool btf dump file /sys/kernel/btf/vmlinux format c | grep if_dqblk ` against a kernel compiled without `CONFIG_QUOTACTL` will show the absence of `struct if_dqblk` and so we cannot relocate against it.
Fixes #2033 
```release-note
NONE
```
=> fix(modern): prevent CO-RE relocations when CONFIG_QUOTACTL is not defined

userspace/libscap/engine/source_plugin/source_plugin.c, userspace/libsinsp/threadinfo.cpp
/kind bug
/area libsinsp
Fixes #
This is part of the work to support `zig` compiled Falco binaries. See https://github.com/falcosecurity/falco/pull/3307.
```release-note
NONE
```
=> fix(userspace/libsinsp): fixed a couple of UBs

test/libscap/test_suites/engines/bpf/bpf.cpp, test/libscap/test_suites/engines/kmod/kmod.cpp, test/libscap/test_suites/engines/modern_bpf/modern_bpf.cpp, userspace/libpman/src/stats.c, userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/kmod/scap_kmod.c, userspace/libscap/examples/01-open/scap_open.c, userspace/libscap/metrics_v2.h, userspace/libscap/scap.c, userspace/libsinsp/metrics_collector.cpp, userspace/libsinsp/metrics_collector.h
/kind cleanup
No
As explained in issue #2028, it is better to split the per-CPU counters from the global counters for verbosity reasons. 
More in detail when the per-CPU counters are enabled, libscap under the hood also enables the global counters. This is done to avoid a double loop over all the CPUs and to keep the code simpler without duplications. The idea behind this choice is that usually, a user should enable the per-cpu stats to obtain more insights with respect to the global ones so the global ones should be already …
=> cleanup(engines): detach per-cpu kernel metrics from global kernel metrics

userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_filtercheck_fspath.cpp, userspace/libsinsp/sinsp_filtercheck_fspath.h, userspace/libsinsp/test/events_fspath.ut.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(sinsp): fix `fs.path` filterchecks for relative paths (add `dirfd` concept)

.github/workflows/semgrep_checks.yml
> /kind bug
/kind cleanup
> /kind design
> /area build
/area CI
> /area tests
> /version …
=> ci(semgrep): update semgrep docker image

userspace/libsinsp/sinsp.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(sinsp): plugin capture listen capability exception

.github/workflows/drivers_ci.yml, test/drivers/event_class/event_class.h, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp, test/drivers/test_suites/syscall_exit_suite/sendto_x.cpp
/kind bug
> /kind design
/area build
> /area CI
/area tests
> /version …
=> fix(build): fix tests build warnings (fatal with -Werror)

test/drivers/event_class/network_utils.h, test/drivers/helpers/proc_parsing.h, test/drivers/test_suites/generic_tracepoints_suite/sched_process_exec.cpp, test/drivers/test_suites/generic_tracepoints_suite/sched_process_fork.cpp, test/drivers/test_suites/syscall_enter_suite/connect_e.cpp
/kind bug
> /kind design
/area build
/area CI
> /area tests
> /version …
=> fix(ci): fix some warnings as error

.github/workflows/drivers_ci.yml
/kind bug
/area CI
The current solution is not working because `github.repository` resolves to the target github repository that is always `falcosecurity/libs`.
That trick is needed to avoid run a github action on forks.
Instead, we need to avoid running a github action on PRs coming from forks; we need to rely on `github.event.pull_request.head.repo.full_name`.
Fixes #
```release-note
NONE
```
=> fix(ci): avoid running drivers CI jobs that need secrets in PR coming from forks

userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/filter_field.h, userspace/libsinsp/plugin.cpp, userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/test/filter_compiler.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp
/kind bug
/area libsinsp
Internal tests demonstrated that field-to-field comparisons and/or filter caching can't just be broken with plugin fields (for which we enforced a STORAGE transformer layer in the compiler), but also with other fields were pointer stability between subsequent extractions on the same events (even on different fields) is not guaranteed.
```release-note
fix(libsinsp): solve field-field comparison pointer instability issues 
```
=> fix(libsinsp): solve field-field comparison pointer instability issues 

driver/configure/CLASS_CREATE_1/test.c
/kind bug
/area build
No
otherwise test will give wrong result if compiler has -Werror flags, complained with:
error: unused variable 'g_ppm_class' [-Werror=unused-variable]
No
```release-note
NONE
```
=> chore(libs): fix -Werror=unused-variable

userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_thread_pool.h, userspace/libsinsp/sinsp_thread_pool_bs.cpp, userspace/libsinsp/sinsp_thread_pool_bs.h
> /kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> chore(sinsp): rename `thread_pool` to `sinsp_thread_pool` to avoid symbol conflicts

test/drivers/test_suites/syscall_enter_suite/socketcall_e.cpp, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp, test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
/kind bug
/area tests
Extracted from #2064 .
Fixes #
```release-note
NONE
```
=> fix(test/drivers): fixed s390x `Werror` related failures for drivers tests

userspace/libpman/src/ringbuffer_definitions.h, userspace/libscap/engine/bpf/scap_bpf.h, userspace/libscap/linux/barrier.h
/kind bug
/area libpman
No
This PR should fix https://github.com/falcosecurity/libs/issues/2061. 
Today `smp_load_acquire` and `smp_store_release` use the synchronization primitives of x86 also on other architectures... but thanks to the nature of our code we never noticed it until this PR https://github.com/falcosecurity/libs/pull/2009.
More detail in the addition of 
```c
if(g_state.cons_pos[pos] == g_state.prod_pos[pos]) {
return NULL;
}
```
caused the `g_state.prod_pos[pos]` value to be used immediately after the fetch. So if it was a wrong value we …
=> fix(libscap): use the correct memory barrier for ARM64

.github/workflows/drivers_ci.yml, .github/workflows/format.yml, driver/configure/CLASS_CREATE_1/test.c, test/drivers/event_class/network_utils.h, test/drivers/helpers/proc_parsing.h, test/drivers/test_suites/generic_tracepoints_suite/sched_process_exec.cpp, test/drivers/test_suites/generic_tracepoints_suite/sched_process_fork.cpp, test/drivers/test_suites/syscall_enter_suite/connect_e.cpp, test/drivers/test_suites/syscall_enter_suite/socketcall_e.cpp, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp, test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp, userspace/libpman/src/ringbuffer_definitions.h, userspace/libscap/engine/bpf/scap_bpf.h, userspace/libscap/linux/barrier.h, userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/filter_field.h, userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_thread_pool.h, userspace/libsinsp/sinsp_thread_pool_bs.cpp, userspace/libsinsp/sinsp_thread_pool_bs.h, userspace/libsinsp/test/filter_compiler.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp
/kind cleanup
Cherry picks:
* https://github.com/falcosecurity/libs/pull/2062
* https://github.com/falcosecurity/libs/pull/2060
* https://github.com/falcosecurity/libs/pull/2063
* https://github.com/falcosecurity/libs/pull/2058
* https://github.com/falcosecurity/libs/pull/2065
* https://github.com/falcosecurity/libs/pull/2066
* https://github.com/falcosecurity/libs/pull/2055
* https://github.com/falcosecurity/libs/pull/2067
from master.
Fixes #
```release-note
NONE
```
=> update: sync release 0.18.x

.github/workflows/e2e_ci.yml, test/libsinsp_e2e/resources/unix_client_server.py, test/libsinsp_e2e/unix_client_server.cpp
/kind cleanup
/area CI
/area tests
Extracted from #2064 
Fixes #
```release-note
NONE
```
=> chore(test/libsinsp_e2e,ci): port libsinsp_e2e tests to use python3.

cmake/modules/cares.cmake
/kind cleanup
/area build
Also, now c-ares supports cmake, therefore make use of it.
Fixes #
This should help resolving a build issue in https://github.com/falcosecurity/falco/pull/3307.
While not fundamental for now, it is a nice to have.
```release-note
NONE
```
=> update(cmake): updated c-ares to latest 1.33.1 version.

.clang-tidy, CMakePresets.json
/kind cleanup
/area build
> /area CI
> /area tests
> …
=> chore: update presets and add a basic clang-tidy config

cmake/modules/grpc.cmake, cmake/modules/libelf.cmake
/kind bug
/area build
Moreover, patch grpc cmake module to patch its abseil-cpp submodule to be compatible with gcc-13.
Fixes #
Last patch for https://github.com/falcosecurity/falco/pull/3307.
Actually, extracted from it.
```release-note
NONE
```
/milestone 0.19.0
=> fix(cmake): added zig workarounds for libelf and grpc cmake modules.

userspace/libscap/engine/gvisor/runsc.cpp
/kind cleanup
Using the glibc specific `__gnu_cxx::stdio_filebuf` breaks while trying to build Falco/libs with zig compiler (see https://github.com/falcosecurity/falco/pull/3307).
In this specific case, we can make use of POSIX standard `popen`.
Fixes #
There are a couple more usages of `__gnu_cxx::stdio_filebuf`; both are inside libsinsp_e2e tests framework, but we don't really need to build libs tests when we build Falco (with zig) therefore i am skipping them for now. …
=> cleanup(userspace/libscap): avoid the usage of non-portable (glibc specific) `__gnu_cxx::stdio_filebuf`

.github/actions/install-zig/action.yml, .github/workflows/ci.yml, userspace/libsinsp/test/CMakeLists.txt
/kind feature
/area CI
This PR adds a composite action to setup zig (stolen by my Falco PR: https://github.com/falcosecurity/falco/pull/3307, that will be of course updated to use the libs provided action once this gets merged), and adds a CI job to test build of sinsp-example with zig.
Fixes #
```release-note
NONE
```
=> new(ci): add a zig build job plus a composite action to setup zig.

test/libsinsp_e2e/event_capture.cpp
/kind bug
/area tests
No
I have noticed some tests from the e2e suite hanging on my machine, after some `hours_wasted_here++` I noticed that it looks like `event_capture::stop_capture()` was not stopping the capture, but it was acquiring the inspector lock so I believe deep in its heart it really wanted to stop the capture. I wonder how this ever worked or if it will fully work after this patch.
Fixes # …
=> fix(libsinsp-e2e-tests): stop capture upon stop_capture()

userspace/libsinsp/parsers.cpp
/kind bug
/area libsinsp
Cherry picks https://github.com/falcosecurity/libs/pull/2081 from master.
Fixes #
```release-note
NONE
```
=> sync: release 0.18.1

benchmark/libsinsp/utils.cpp
/kind cleanup
/area tests
See https://github.com/google/benchmark/blob/main/docs/user_guide.md#preventing-optimization.
Fixes #
```release-note
NONE
```
=> fix(benchmark): avoid compiler optimizations in benchmarks loops.

driver/bpf/probe.c, driver/bpf/types.h
/kind cleanup
Per #2086 it might happen that none of the include before `types.h` does provide `TASK_COMM_LEN` declaration, ie: that `linux/sched.h` is not included by any of the `linux/` headers included by `quirks.h`.
Since `types.h` needs `TASK_COMM_LEN`, make it directly include `sched.h` and avoid implicitly hoping for the inclusion of that macro.
Fixes #2086
```release-note
NONE
```
=> chore(driver/bpf): properly include sched.h in types.h since it uses `TASK_COMM_LEN`

userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_filtercheck_fdlist.cpp, userspace/libsinsp/sinsp_filtercheck_fspath.cpp
/kind bug
/area libsinsp
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): avoid possible UB when calling `back` or `front` without checking string emptiness

.github/workflows/format.yml
/kind cleanup
/area CI
The provided patch is great to fix large formatting errors, however, it would be nice for CI to also show the diff for smaller changes that could be directly typed without having to download the patch.
Fixes #
```release-note
NONE
```
=> chore(ci): show diff on failed format

userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h
/kind feature
/area libsinsp
No
Currently the documentation website lists field arguments as if they were regular. If they are lists of charbufs for example we would like to print `LIST(CHARBUF)` instead of `CHARBUF`. This PR does exactly that.
Fixes #2092
```release-note
new(libsinsp): print LIST() in markdown format for list fields
```
=> new(libsinsp): print LIST() in markdown format for list fields

driver/bpf/fillers.h
/kind bug
No
Fixes #2094
```release-note
fix(driver/bpf): fix sys_poll_x verifier bug on fedora 40
```
=> fix(driver/bpf): fix sys_poll_x verifier bug on fedora 40

.git-blame-ignore-revs
/kind cleanup
No
This PR removes some commits from the blame since they just convert types from u32 to uint32_t and similar. When looking for information like when a field was added to a struct it would be better to ignore these commits
```release-note
NONE
```
=> cleanup: remove some commits from the blame

userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/thread_pool.ut.cpp
> /kind bug
> /kind design
> /area build
> /area CI
/area tests
> /version …
=> fix(tests): flaky thread pool tests

.github/workflows/reusable_kernel_tests.yaml
/kind bug
/area CI
Second time it happens :/ bug added in #2096
Fixes #
```release-note
NONE
```
=> fix(ci): fix kernel testing action by using proper tag name.

.github/workflows/drivers_ci.yml, .github/workflows/pages.yml, .github/workflows/release-body.yml
/kind cleanup
/area CI
Since we do not rely upon centos7 anymore, drop it.
Moreover, bump actions/download-artifact to latest release to be able to communicate correctly with actions/upload-artifact.
Fixes #
```release-note
NONE
```
=> fix(ci): fix build-scap-open-w-extern-bpf-skeleton job

userspace/libscap/engine/gvisor/CMakeLists.txt
/kind bug
Since gvisor sources use jsoncpp, it must depend upon it. Most probably that was an unintentional typo.
See https://github.com/falcosecurity/falco/actions/runs/11324106507/job/31488703414?pr=3380 for a failing CI, where scap_engine_gvisor gets build before jsoncpp and therefore gvisor cannot find `json/json.h` include.
This is something purely time-based, ie: i am pretty sure that if we compile with a different `-jX` it would pass the build. 
I think the time issue got somewhat exacerbated by https://github.com/falcosecurity/libs/pull/2005 changes.
In the end:
* scap …
=> fix(userspace/libscap): scap-gvisor does need to depend upon jsoncpp.

userspace/libsinsp/cri.hpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(userspace/libsinsp): disable HTTP proxy for CRI connection

.github/workflows/latest-kernel.yml, driver/bpf/fillers.h
/kind bug
Fixes #
```release-note
NONE
```
=> fix(driver/bpf): fixed a typo in old ebpf probe code for linux >= 6.11.

userspace/libsinsp/container_engine/libvirt_lxc.cpp
/kind bug
Building with Red Hat g++ 11.2.1-9 we get the following error on string assignment:
```
[ 34%] Building CXX object libsinsp/CMakeFiles/sinsp.dir/container_engine/libvirt_lxc.cpp.o
In file included from /opt/rh/devtoolset-11/root/usr/include/c++/11/ios:40,
from /opt/rh/devtoolset-11/root/usr/include/c++/11/ostream:38,
from /opt/rh/devtoolset-11/root/usr/include/c++/11/bits/unique_ptr.h:42,
from /opt/rh/devtoolset-11/root/usr/include/c++/11/memory:76,
from /code/agent/deps/agent-libs/userspace/libsinsp/container_engine/container_engine_base.h:21,
from …
```
=> fix(userspace/libsinsp): stringop-overflow on libvirt_lxc

driver/modern_bpf/helpers/extract/extract_from_kernel.h
/kind bug
No
See https://github.com/falcosecurity/libs/issues/2118. Even if this is a possible fix to the issue I don't want to close the issue since we need to investigate more and maybe report it to COS or the upstream kernel if we notice something weird.
Since the bug doesn't depend on us I would suggest fixing it in this way (so we work again on GKE) and report it when we have enough info
See https://github.com/falcosecurity/libs/issues/2118
```release-note
NONE …
```
=> fix(modern): check `cred` field is not NULL before the access

.github/workflows/latest-kernel.yml
/kind bug
/area CI
Fixed small issues introduced in https://github.com/falcosecurity/libs/pull/2114: properly use `.outputs` for steps/jobs outputs in latest-kernel CI.
Fixes #
```release-note
NONE
```
=> fix(ci): fixed latest-kernel CI usage of steps/jobs outputs.

.github/workflows/create-comment-kernel-testing.yml, .github/workflows/create-comment-perf.yml
/kind cleanup
/area CI
Avoids all the failings like: https://github.com/falcosecurity/libs/actions/workflows/create-comment-kernel-testing.yml
Fixes #
```release-note
NONE
```
=> fix(ci): avoid create comment workflows failing when required worfklows did not run

.github/workflows/create-comment-kernel-testing.yml, .github/workflows/create-comment-perf.yml
/kind bug
/area CI
Fixes bug after https://github.com/falcosecurity/libs/pull/2121
Fixes #
```release-note
NONE
```
=> fix(ci): use `process.exit();` to leave node script in github/action-script

userspace/libsinsp/filter_field.h, userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin.h, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/plugin_extract.cpp, userspace/libsinsp/test/plugins/syscall_extract.cpp, userspace/plugin/plugin_api.h
/kind feature
/area libsinsp
The new field suggests to the agent that some fields should be enforced to all compatible sources output by default.
It is up to the agent to implement the logic to actually use these suggested fields.
PR contains also updated tests.
For example, k8smeta plugin could expose eg: `k8smeta.pod.name` and `k8smeta.pod.uid` as `addOutput` fields; this way for `syscall` event source (see `get_extract_event_sources`: https://github.com/falcosecurity/plugins/blob/main/plugins/k8smeta/src/plugin.h#L154) those fields will always be appended to the output with no further intervention.
Idea …
=> new(userspace): added new `addOutput` json entry for plugin `get_field()` API

.github/workflows/create-comment-kernel-testing.yml, .github/workflows/create-comment-perf.yml
/kind bug
/area CI
Fix after https://github.com/falcosecurity/libs/pull/2123.
This time properly tested in online IDE :/ 
Fixes #
```release-note
NONE
```
=> fix(ci): create-comment workflows array length check.

.github/actions/install-zig/action.yml, .github/workflows/latest-kernel.yml
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> fix(ci): use local zig folder instead of `/usr/local`.

userspace/libsinsp/filter/parser.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(libsinsp): use correct regex for hex numbers

.github/workflows/ci.yml, .github/workflows/drivers_ci.yml, .github/workflows/e2e_ci.yml, .github/workflows/latest-kernel.yml, test/libsinsp_e2e/container/container.cpp
/kind cleanup
/area CI
Depends upon #2073 and #2049 that were partially split from this one.
Will eventually rebase once they get merged.
Fixes #
```release-note
NONE
```
=> update(ci): use cncf provided runners for arm64

userspace/libsinsp/state/dynamic_struct.h
> /kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(libsinsp): invalid field_info check

userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
/kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp): expose main thread fd table

userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_event.h, userspace/libsinsp/test/filterchecks/evt.cpp
/kind bug
/area libsinsp
Firstly, properly refresh m_arginfo and m_customfield type and print format given current event while extracting rawarg values.
Secondly, properly support PT_FLAGS, PT_ENUMFLAGS, PT_UID and PT_GID types in `rawval_to_json` and `rawval_to_string`.
Lastly, honor PF_HEX print format for 8,16,32bits types.
Also, added a test.
Fixes #
These issues were found by @Andreagit97 while working on the syscall enter dropping (https://github.com/falcosecurity/libs/pull/2068)  …
=> fix(userspace/libsinsp): multiple fixes related to rawargs.

userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
/kind cleanup
/area libsinsp
No
improve perf `populate_cmdline`
```release-note
NONE
```
=> cleanup: improve perf `populate_cmdline`

userspace/libsinsp/filter/parser.cpp, userspace/libsinsp/filter/parser.h, userspace/libsinsp/sinsp_filter_transformer.cpp, userspace/libsinsp/sinsp_filter_transformer.h, userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/sinsp_filtercheck.h, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/test/filter_parser.ut.cpp, userspace/libsinsp/test/filter_transformer.ut.cpp
/kind feature
/area libsinsp
No
This introduces a new `len()` transformer which acts like you'd expect:
* `len(some_list)` evaluates to the number of elements in the list
* `len(some_string)` evaluates to the length of the string (excluding null terminator of course)
* `len(some_buffer)` evaluates to the number of bytes in the buffer
This is also a handy way to check if lists are empty, since we couldn't do it before, which was apparent after a discussion with @leogr and @jasondellaluce . …
=> new(libsinsp): add len() filter transformer

driver/ppm_cputime.c
The prototype for `nsec_to_clock_t` is in `<linux/jiffies.h>`, which is not included by `ppm_cputime.c`. `jiffies.h` includes `time.h` so we can just switch the import.
/kind cleanup
no
Fixes #2142 
```release-note
NONE
```
=> fix(driver): include jiffies.h to prevent warning about missing prototype

userspace/libscap/scap_event.c, userspace/libsinsp/test/sinsp_with_test_input.cpp
/kind cleanup
/area tests
No
add some exceptions in sinsp test framework
```release-note
NONE
```
=> cleanup(tests): add some exceptions in sinsp test framework

test/libsinsp_e2e/CMakeLists.txt
/kind bug
/area build
When compiling without bundled deps the e2e sinsp tests failed because gtest is not a dependency. Example of cmake variables provided
```
"CMAKE_BUILD_TYPE": "Release",
"BUILD_BPF": "ON",
"BUILD_DRIVER": "ON",
"USE_BUNDLED_DEPS": "OFF",
"MODERN_BPF_DEBUG_MODE": "ON",
"BUILD_LIBSCAP_MODERN_BPF": "ON",
"BUILD_LIBSCAP_GVISOR": "OFF",
"CREATE_TEST_TARGETS": "ON",
"USE_BUNDLED_VALIJSON": "ON",
"USE_BUNDLED_OPENSSL": "ON",
"USE_BUNDLED_RE2": "ON",
"USE_BUNDLED_LIBBPF": "ON",
"SCAP_FILES_SUITE_ENABLE": "ON",
"BUILD_WARNINGS_AS_ERRORS": "Off",
"ENABLE_DRIVERS_TESTS": "ON", …
```
=> chore(e2e): fix e2e build without bundled deps

driver/ppm_fillers.c, test/drivers/test_suites/generic_tracepoints_suite/sched_process_exec.cpp, test/drivers/test_suites/syscall_exit_suite/execve_x.cpp, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/test/classes/sinsp_threadinfo.cpp, userspace/libsinsp/test/filterchecks/proc.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
/kind cleanup
/area libsinsp
No
Before this patch, the ` (deleted)` suffix was removed only in the kernel module since it was the unique driver that was able to generate a path with this suffix. But this is a sort of inconsistent approach because also from /proc scan we could receive a path terminating with ` (deleted)`. Since many users probably write rules like `proc.exepath endswith ...` seems reasonable to clean the exepath directly in userspace.
```release-note
NONE …
```
=> update(sinsp): handle ` (deleted)` in userspace

userspace/libsinsp/test/async_key_value_source.ut.cpp, userspace/libsinsp/utils.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> chore(libsinsp): avoid useless allocation

cmake/modules/tbb.cmake, userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/dns_manager.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> /version …
=> fix(deps): bump tbb and enable its compilation with emscripten

userspace/libsinsp/test/async_key_value_source.ut.cpp
/kind cleanup
/area CI
No
This test is required and blocks the CI on almost all the PRs, moreover, we always have a red X on all PRs so since this has been broken for a while without a fix I would suggest disabling it until we can figure out the real cause behind the issue.
```release-note
NONE
```
=> ci: disable a flaky test

userspace/libsinsp/threadinfo.cpp
> /kind bug
`m_n_proc_lookups` was incremented before doing the proc lookup, causing `Reached max process lookup number, duration=0ms` logs when max is configured to 1.
Fixes #
```release-note
NONE
```
=> fix(libsinsp): max proc lookup number logging

userspace/libsinsp/threadinfo.cpp
/kind cleanup
/area libsinsp
Lower _Reached max process/socket lookup number_ log severity.
Fixes #
```release-note
NONE
```
=> chore(libsinsp): reduce max proc lookup number log severity

userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/test/filterchecks/evt.cpp
/kind cleanup
/area libsinsp
No
Remove some duplicated code and add some tests
```release-note
NONE
```
=> cleanup(sinsp): remove some duplicated code

test/libsinsp_e2e/sys_call_test.cpp, userspace/libsinsp/test/events_file.ut.cpp, userspace/libsinsp/test/sinsp_utils.ut.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
/kind cleanup
/area libsinsp
No
Today in case of path is too long we return `/PATH_TOO_LONG`. This means:
* `fd_directory`  = "/"
* `fd_filename` = "PATH_TOO_LONG"
The directory is definitely wrong and misleading as a workaround I propose something like this `/DIR_TOO_LONG/FILENAME_TOO_LONG`, so:
* `fd_directory`  = "/DIR_TOO_LONG"
* `fd_filename` = "FILENAME_TOO_LONG"
We probably need to find something better but at least we remove the wrong dir
```release-note
NONE
```
=> cleanup(sinsp): handle path too long in a better way

userspace/libsinsp/sinsp_suppress.cpp, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/suppress.ut.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp): don't filter out procexit events

userspace/libsinsp/dumper.cpp, userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp_cycledumper.cpp, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/syscall_async.cpp, userspace/plugin/plugin_api.h, userspace/plugin/plugin_loader.c, userspace/plugin/plugin_loader.h
/kind feature
/area libsinsp
This PR adds a new `dump()` API under the `async events` plugin capability.
It is used to dump plugin state (as list of `PPME_ASYNCEVENT_E` events) when a scap file dump is requested.
Note:
* only `PPME_ASYNCEVENT_E` can be dumped
* `PPME_ASYNCEVENT_E` dumped must have a name supported by the plugin (see `get_async_events()` API)
Moreover, enable initialstate consuming of `PPME_ASYNCEVENT_E` events while opening the inspector.
Fixes #
```release-note …
```
=> new(userspace): plugin api to dump async events

userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_filtercheck_group.cpp, userspace/libsinsp/sinsp_filtercheck_user.cpp, userspace/libsinsp/test/parsers/parse_setregid.cpp, userspace/libsinsp/test/parsers/parse_setreuid.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h, userspace/libsinsp/user.cpp
/kind cleanup
/area libsinsp
Only store `uid`, `gid` and `loginuid` info.
Storing full info was done to workaround scenarios like:
* thread X starts with user 1000 "foo"
* user 1000 gets deleted while thread X runs
* user 1000 gets recreated with name "bar"
* extracting user from thread now will give "bar"; with previous impl it would have given "foo".
Basically, we are now respecting what unix expects us to do, since user 1000 will now be mapped to "bar".
Moreover, since threadinfo is used many times, not embedding those bytes saves us lots of memory.
Fixes #
**Special …
=> cleanup(userspace/libsinsp): drop user and group infos embedded in threadinfo

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/filterchecks/user.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h, userspace/libsinsp/user.cpp, userspace/libsinsp/user.h
/kind bug
/area libsinsp
/area tests
Fixed a possible case were the `root`, `/root` default values for uid 0 users and gid 0 groups were not set (after https://github.com/falcosecurity/libs/pull/2165).
Moreover, properly use different `static` members for `threadinfo::get_user()` and `threadinfo::get_loginuser`.
Also, added tests to avoid future failures.
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): user id 0 or group id 0 default values

userspace/libsinsp/test/filterchecks/evt.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind cleanup
/area tests
This PR introduces a new test helper. I had this helper in an old branch and it will become really useful when sinsp won't need any more `OPEN_E` event to populate the state.
```release-note
NONE
```
=> new(tests): introduce a new test helper

userspace/libsinsp/examples/test.cpp
/kind feature
/area libsinsp
Expands sinsp-example to support plugins.
This will be useful to test plugins; moreover in the future when container metadata support will become a plugin(https://github.com/falcosecurity/falco/issues/3403), this will be needed to run tests in CI (like for example e2e tests).
To pass init config/open params, i chose to use a single string following this pattern:
`filepath.so|{initconfig}|{openParams}`, eg:
```
./libsinsp/examples/sinsp-example -p "/home/federico/Scaricati/dummy-0.11.4-linux-x86_64/libdummy.so|{\"jitter\": 10}" -f dummy.divisible[4]=1
```
**Which issue(s) this PR …
=> new(userspace/libsinsp): support plugins in sinsp-example.

userspace/libsinsp/test/filterchecks/evt.cpp
/area tests
```release-note
NONE
```
=> update(tests): fix emscripten build

userspace/libsinsp/filter/parser.cpp, userspace/libsinsp/filter/parser.h, userspace/libsinsp/test/filter_parser.ut.cpp
/kind bug
/kind feature
/area libsinsp
/area tests
No
The parser for filter expressions (used in Falco rules conditions) has historically been a bit strict with the way it accepts whitespaces when required between a comparison operator and right-hand values. This now supports also line breaks, which has been reported being rejected in some corner cases.
Additionally, the parser tests has been updated to "fuzz" a bit the whitespaces handled by each of the existing test cases, with the purpose of extending our coverage from this perspective. …
=> update(libsinsp/filter): parse wider whitespace combinations in filter expressions

userspace/libscap/engine/gvisor/CMakeLists.txt, userspace/libsinsp/examples/test.cpp
/kind feature
/area libsinsp
no
This PR adds Gvisor support to sinsp-example
```release-note
NONE
```
=> new(sinsp-example): add gvisor support

test/libscap/test_suites/userspace/event_table.cpp, userspace/libsinsp/event.h, userspace/libsinsp/parsers.cpp
/kind cleanup
/area libsinsp
No
if i don't miss something all the syscall exit event should have at least the return value so i don't see why we need the additional manual check on the parameter names
Fixes #
```release-note
NONE
```
=> cleanup: remove some extra code

userspace/libscap/engine/savefile/converter/CMakeLists.txt
/kind bug
No
fix windows build using OBJECT instead of STATIC
Fixes #
```release-note
NONE
```
=> chore: fix windows build

userspace/libsinsp/event.cpp
/kind bug
/area libsinsp
This also fixes a bug where using sinsp `m_filter` on a plugin-exposed field in scap replay mode would SIGABRT. 
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): always initialize sinsp_evt with a proper source_idx and source_name

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
/kind cleanup
/area libsinsp
Fixes #
```release-note
NONE
```
=> cleanup(userspace/libsinsp): drop sinsp `m_suppressed_comms` unused field

userspace/libsinsp/test/state.ut.cpp, userspace/libsinsp/threadinfo.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(sinsp/threadinfo): expose thread uid and gid as static fields

userspace/libscap/linux/scap_procs.c, userspace/libsinsp/sinsp_filtercheck_thread.cpp
/kind bug
/area libscap
When scanning proc from scap, make sure to use `comm` file to parse threadinfo comm field, instead of using `status` file and grepping for `Name:%1024s`. Also, using `sscanf` in that way  does not support strings with spaces, ie: if a status file was like
```
Name: foo bar
```
we would only load `foo`. 
Fixes #
```release-note
fix(userspace/libsinsp): use `comm` file instead of `status` to get proc comm
```
=> fix(userspace/libsinsp): use `comm` file instead of `status` to get proc comm

CMakePresets.json, test/drivers/test_suites/syscall_exit_suite/getcwd_x.cpp, test/drivers/test_suites/syscall_exit_suite/readv_x.cpp, userspace/libscap/linux/scap_cgroup.c, userspace/libsinsp/filter_check_list.cpp, userspace/libsinsp/filter_check_list.h
/kind bug
/kind cleanup
/area build
No
Fix a few warnings and errors that came up during a build with Clang 18.
In addition, I've been working with a simplified version of `CMakePresets.json` where parameters common to several presets are factored out in a base preset. I took the liberty of adding these minor changes here.
Compilation errors and warnings with recent compilers.
Fixes #
n/a
No
```release-note
NONE
```
=> fix: some issues with Clang 18

cmake/modules/CompilerFlags.cmake, userspace/libscap/scap_print_event.c, userspace/libsinsp/event.cpp, userspace/libsinsp/filter_compare.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_inet.h
/kind cleanup
/area build
We define `NOMINMAX` in multiple places to avoid `windows.h` re-defining `min` and `max` macros under the hood.
Since this is super error prone because windows headers can be included in so many places (even by included headers from deps), i though it was a good idea to just add a compile definition for it.
Another (possibly better) solution would have been to drop `NOMINMAX` and use `std::min<type>` (and same for `max`); in that case, the macro would not be able to replace our code. But, there is always a but, at least `re2` uses `std::min()` without the small trick to avoid the replacement, therefore we cannot do that.
**Which issue(s) …
=> cleanup(build): move NOMINMAX definition at compile time for windows builds

.github/workflows/ci.yml
/area CI
```release-note
NONE
```
=> chore(ci): fix shared-libs and emscripten CI

test/libscap/test_suites/userspace/event_table.cpp, userspace/libscap/engine/savefile/converter/converter.cpp, userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/scap.h, userspace/libscap/scap_event.c, userspace/libsinsp/event.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/test/events_net.ut.cpp, userspace/libsinsp/test/parsers/parse_brk.cpp, userspace/libsinsp/test/parsers/parse_pread.cpp, userspace/libsinsp/test/parsers/parse_read.cpp, userspace/libsinsp/test/scap_files/converter_tests.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind bug
/area libscap
/area libsinsp
/area tests
No
This PR provides 2 main fixes:
* today sinsp skip the event reset phase if the enter event is dropped. Sometimes this is dangerous because we are not able to associate the fd to the event. See the `connect` or the `close` case.
* before this PR enter events for pread and read were skipped by the scap file converter but this is probably not what we want, with scap-file we want to emulate the same behavior of the live capture, so populate the state only with exit events but always send the enter ones... This PR reintroduce the …
=> fix: send enter events also with scap files not only in live captures

userspace/libsinsp/dumper.cpp, userspace/libsinsp/event.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/filterchecks/evt.cpp, userspace/libsinsp/test/filterchecks/user.cpp, userspace/libsinsp/test/sinsp_with_test_input.h, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/user.cpp, userspace/libsinsp/user.h
/kind cleanup
/area libsinsp
If a way similar to #2182, move logic to refresh user/group info upon container_id changes to a RAII object instantiated by `sinsp::next()`.
This allows to take into consideration eventual "container_id" changes made by plugin parsers.
While right now there is no need for this, it will be mandatory for the container plugin, since it will be responsible to actually write the `container_id` state entry for threadinfo.
Also, avoid relying upon container manager `on_remove_container` callback; instead check if a `procexit` event was received on container's init pid.
Fixes # …
=> chore(userspace/libsinsp): move user group manager on container_id changed refresh to a RAII object

.github/workflows/test_coverage_ci.yml
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> fix(ci): run apt-get update in coverage ci.

userspace/libsinsp/container.cpp, userspace/libsinsp/container.h, userspace/libsinsp/container_engine/cri.cpp, userspace/libsinsp/container_engine/cri.h, userspace/libsinsp/cri.h, userspace/libsinsp/cri_settings.cpp
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> new(userspace/libsinsp): support multiple CRI engines simultaneously

userspace/libsinsp/parsers.cpp
/kind cleanup
/area libsinsp
No
This _does_ happen. The reasons for it may be a normal operation on UNIX sockets or a potential issue in the driver (or an expected failure if the userspace buffer could not be retrieved) but it's unconfirmed. Since the assert wasn't specific and nothing bad happens I think it can be safely removed, otherwise debug builds will be useless for everyone.
Fixes # …
=> cleanup(libsinsp): remove assert that may trigger under normal circumstances

userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(userspace/libsinsp): keep event thread after execve

userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/test/filterchecks/evt.cpp
/kind bug
/area libsinsp
No
See https://github.com/falcosecurity/falco/issues/3437 for a description of the effect of this issue on Falco. Filters should not be affected by the output format.
Fixes #
```release-note
fix(libsinsp): do not reformat input buffer strings while applying arg filters
```
=> fix(libsinsp): do not reformat input buffer strings while applying arg filters

test/drivers/event_class/event_class.cpp, userspace/libscap/engine/savefile/converter/converter.cpp
/kind cleanup
/area build
/area tests
No
Fixes an error when taking the address of a temporary string and a warning about mixed sign integer comparison with clang 18.
None
```release-note
NONE
```
=> fix: dangling pointer and mixed-signedness warning

test/drivers/test_suites/syscall_exit_suite/connect_x.cpp
/kind cleanup
/area tests
No
This PR should fix the powerpc CI
```release-note
NONE
```
=> cleanup: avoid including libscap/strl.h in connect_x

cmake/modules/libelf.cmake
/kind cleanup
/area build
No
See: https://github.com/falcosecurity/evolution/issues/421 . Also, upgrade to latest upstream revision.
Fixes #
```release-note
update(elftoolchain/libelf): update to r4073-0
```
=> update(cmake): update libelf repo location and revision

userspace/libscap/engine/bpf/bpf.h, userspace/libscap/engine/bpf/scap_bpf.c
/kind bug
/area API-version
Not sure, maybe we want to bump a major in the API just to be sure we always enforce the new check?
This PR should provide a mitigation for this https://github.com/falcosecurity/libs/issues/1283#issuecomment-2578323132
```release-note
fix(driver): add a check on the SCHEMA version compatibility
```
=> fix(driver): add a check on the SCHEMA version compatibility

driver/bpf/filler_helpers.h, driver/modern_bpf/helpers/base/shared_size.h, driver/modern_bpf/helpers/store/auxmap_store_params.h, driver/ppm_events.c, test/drivers/test_suites/syscall_enter_suite/sendto_e.cpp, test/libsinsp_e2e/CMakeLists.txt, test/libsinsp_e2e/udp_client_server.cpp, test/libsinsp_e2e/unix_client_server.cpp, test/libsinsp_e2e/unix_udp_client_server.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
/area tests
> /version …
=> feat(libsinsp_e2e): add unix_udp_client_server_read test

test/libsinsp_e2e/tcp_client_server.cpp, test/libsinsp_e2e/tcp_client_server.h, test/libsinsp_e2e/tcp_client_server_ipv4_mapped.cpp, test/libsinsp_e2e/test_helper.cpp
/kind bug
/area tests
Took my time and finally fixed libsinsp_e2e tcp related tests to avoid deadlocks.
This finally turns ARM CI green :rocket: 
Fixes #
```release-note
NONE
```
=> fix(test/libsinsp_e2e): fixed tcp related libsinsp_e2e tests.

userspace/libsinsp/container.cpp, userspace/libsinsp/container_engine/containerd.cpp, userspace/libsinsp/container_engine/containerd.h, userspace/libsinsp/runc.cpp, userspace/libsinsp/test/container_engine/cri_settings.ut.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp/runc): use old logic and fallback for containerd

userspace/libsinsp/filter/parser.h
> /kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> docs(userspace/libsinsp/filter/parser): update grammar doc

userspace/libsinsp/runc.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> chore(libsinsp/runc): report correct container id with short cid

.github/workflows/ci.yml, .github/workflows/drivers_ci.yml, .github/workflows/e2e_ci.yml, .github/workflows/latest-kernel.yml
/kind cleanup
/area CI
In the end, i ported our CI to use the shiny new github provided ARM runners: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
Fixes #
```release-note
NONE
```
=> cleanup(ci): use github-provided arm runners

userspace/libsinsp/runc.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp/runc): augument containerd filter

userspace/libsinsp/runc.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp/runc): typo

userspace/libsinsp/runc.cpp, userspace/libsinsp/sinsp.cpp
/kind cleanup
Cherry picks 3 PRs from master:
* https://github.com/falcosecurity/libs/pull/2241
* https://github.com/falcosecurity/libs/pull/2242
* https://github.com/falcosecurity/libs/pull/2244
Fixes #
```release-note
NONE
```
=> sync: release/0.20.x

userspace/libsinsp/threadinfo.cpp
> /kind bug
/kind cleanup
> /kind design
/area libsinsp
No
Remove an ASSERT() that might actually trigger. This was preventing debug builds from running in case of drops.
Fixes #
```release-note
NONE
```
=> cleanup(libs): remove assert() that may trigger

userspace/libsinsp/parsers.cpp
/kind bug
/kind cleanup
/area libsinsp
Experimenting with the latest libs, I found that in some corner cases the sinsp observer callback on fd erasing can lead to use-after-free issues. This happens in cases where thread removal is less predictable, such as when main thread removal is deferred. 
```release-note
NONE
```
=> fix(libsinsp): do not postpone observing fd erasing

userspace/libsinsp/sinsp.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(sinsp): guard against uninitialized use

userspace/libsinsp/sinsp.cpp
/kind bug
/area libsinsp
Right now, when a SCAP_TIMEOUT is received from the  scap_engine, if the async queue contains any event, it gets popped and processed without further investigation about the event's timestamp.
With the proposed patch, the async queue gets scanned considering `now` as timestamp; this way, we honor the requested timestamp by the async event generator: if it is in the future, we hold the event until that time in the future has arrived.
This PR was originally made as part of the work for https://github.com/falcosecurity/libs/pull/2207, but since it could be extracted, here i am :) …
=> fix(userspace/libsinsp): do not immediately process async events whose timestamp is in the future in case a SCAP_TIMEOUT is received

userspace/libscap/engine/gvisor/gvisor.cpp, userspace/libscap/linux/scap_fds.c, userspace/libscap/linux/scap_linux_int.h, userspace/libscap/linux/scap_linux_platform.c, userspace/libscap/linux/scap_procs.c, userspace/libscap/scap_platform_api.c, userspace/libscap/scap_platform_api.h, userspace/libscap/scap_platform_impl.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libscap
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp): improve `recvmsg` `SCM_RIGHTS` cmsg handling

driver/bpf/fillers.h, driver/ppm_fillers.h
/kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> fix(bpf): add tail call to sendmmsg filler

userspace/libsinsp/container.cpp, userspace/libsinsp/container.h, userspace/libsinsp/container_engine/container_async_source.h, userspace/libsinsp/container_engine/container_async_source.tpp, userspace/libsinsp/container_engine/cri.cpp, userspace/libsinsp/cri.h, userspace/libsinsp/cri_settings.cpp, userspace/libsinsp/cri_settings.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/container_engine/cri_settings.ut.cpp
/kind feature
/area libsinsp
No
Make the CRI retry lookup configurable.
- maximum elapsed time
- number of retries
- maximum retry interval
- initial delay before the first attempt
We observed that in some environments, it may take seconds from the time a new container is detected to when it gets exposed from CRI.
Fixes #
```release-note
NONE
```
=> feat(cri): make CRI lookup retry parameters configurable

proposals/20240901-disable-support-for-syscall-enter-events.md
/kind design
No
This document proposes disabling support for syscall enter events in our codebase. The primary reason behind this proposal is to reduce the throughput of events that our userspace needs to process. As the number of syscalls increases, we are no longer able to support them, and we start dropping events. See the full proposal for more details!
I'm curious to hear some feedback on this, we talked many times about it and maybe now is the right time to tackle it!
Some related discussions:
- https://github.com/falcosecurity/falco/issues/2960
- …
=> new(proposal): disable support for syscall enter events

test/libscap/test_suites/engines/savefile/convert_event_test.h, userspace/libscap/engine/savefile/converter/converter.cpp, userspace/libscap/engine/savefile/converter/converter.h, userspace/libscap/engine/savefile/savefile.h, userspace/libscap/engine/savefile/scap_savefile.c
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> /version …
=> fix(scap): remove a static global from event converter

cmake/modules/BuildPkgConfigDependencies.cmake, cmake/modules/libbpf.cmake, cmake/modules/libelf.cmake, userspace/libsinsp/CMakeLists.txt
/kind bug
> /kind design
/area build
> /area CI
> /area tests
> /version …
=> fix(build): make pkgconfig work again

userspace/libsinsp/state/table.cpp, userspace/libsinsp/state/table.h, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
/kind bug
/kind cleanup
/area libsinsp
This is a follow up for the issues fixed in https://github.com/falcosecurity/libs/pull/2257. I discovered that due to how thread management works, there may be corner cases where the last cached thread ref or the cached fd tables pointer might become stale, thus potentially causing use after free issues.
```release-note
NONE
```
=> fix(libsinsp): cache invalidation and potential use-after-free in state table api for plugins and sinsp

.github/actions/install-zig/action.yml
/kind cleanup
/area CI
We were using a deprecated (and retired) github actions/cache version. Use the newest one. 
This should fix zig related CI.
Fixes #
```release-note
NONE
```
=> chore(ci): bump actions/cache version to latest.

driver/bpf/fillers.h
/kind bug
On my machine, the currect bpf probe code caused a verifier bug:
```
639: (85) call bpf_perf_event_output#25
R5 min value is negative, either use unsigned or 'var &= const'
processed 603 insns (limit 1000000) max_states_per_insn 0 total_states 13 peak_states 13 mark_read 7
-- END PROG LOAD LOG --
terminate called after throwing an instance of 'scap_open_exception'
what():  libscap: bpf_load_program() event=raw_tracepoint/filler/sys_sendmmsg_x_failure: Operation not permitted
Annullato
```
Fixes #
**Does this PR …
=> fix(driver/bpf): fixed small verifier bug in old bpf probe.

userspace/libpman/src/lifecycle.c
/kind bug
/area libpman
Master kernel-testing did break on multiple modern ebpf kernels since #2255. See the comment on that PR: https://github.com/falcosecurity/libs/pull/2255#issuecomment-2609374353
Checking the edits on that comment, it seems like the culprit commit is https://github.com/falcosecurity/libs/pull/2255/commits/3e0e122497898d9e72cb00c2de3941443ca9d957.
Here the issue i think lies in the usage of `BPF_PROG_TYPE_TRACING`; indeed in `pman_check_support` we have a fallback for it:
```C
res = libbpf_probe_bpf_prog_type(BPF_PROG_TYPE_TRACING, NULL) > 0;
if(!res) {
// The …
```
=> fix(userspace/libpman): fix modern ebpf failures in master kernel-testing

driver/bpf/configure/0__SANITY/test.c, driver/bpf/configure/Makefile.inc.in, driver/configure/0__SANITY/test.c, driver/configure/Makefile.inc.in
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> /version …
=> new(driver): add sanity check for kmod and ebpf configure systems

userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/fdinfo.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(libsinsp/fdinfo): simplify `lookup_device`

userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(sinsp/parsers): replace `CMSG_LEN` with custom `PPM_CMSG_LEN`

userspace/libsinsp/logger.cpp
/kind cleanup
/area libsinsp
I don't see the point of that assert. Also that is breaking tests in https://github.com/falcosecurity/falco/pull/3507.
Fixes #
```release-note
NONE
```
=> chore(userspace/libsinsp): drop useless assert from logger::add_callback_log()

userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/fdinfo.h, userspace/libsinsp/fdtable.cpp, userspace/libsinsp/state/static_struct.h, userspace/libsinsp/state/table.h, userspace/libsinsp/test/state.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(libsinsp): export static fields via static methods in `threadinfo` and `fdinfo`

userspace/plugin/plugin_loader.c
API 3.10 changed the layout of the plugin_api struct in an ABI-incompatible way. This does not matter for shared library plugins, but statically linked plugins do depend on binary compatibility between the two structs.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
=> fix(sinsp): restore binary compatibility with pre-3.10 static plugins

userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: unexpose `sinsp`'s `m_input_plugin*`

userspace/libsinsp/parsers.h
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(userspace/libsinsp): store input plugin ref in parser

test/libsinsp_e2e/thread_state.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_threadinfo_factory.h, userspace/libsinsp/test/classes/sinsp_thread_manager.cpp, userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/thread_manager.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: remove `sinsp::build_threadinfo()`

userspace/libsinsp/fdtable.cpp, userspace/libsinsp/fdtable.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(sinsp): ensure on_accept observer always gets a valid fdinfo

test/libsinsp_e2e/threadinfo.cpp, userspace/libsinsp/fdinfo.h, userspace/libsinsp/fdtable.cpp, userspace/libsinsp/fdtable.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_fdtable_factory.h, userspace/libsinsp/sinsp_threadinfo_factory.h, userspace/libsinsp/test/classes/sinsp_thread_manager.cpp, userspace/libsinsp/test/classes/sinsp_threadinfo.cpp, userspace/libsinsp/test/classes/thread_group_info.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(userspace/libsinsp): isolate fdtable and fdinfo from `sinsp`

userspace/libsinsp/sinsp.cpp
/kind cleanup
/area libsinsp
No
Some plugins may have a throughput that is a bit higher than others but still much less than our regular modern ebpf probe. Increase the queue to allow those to work.
Fixes #
```release-note
NONE
```
=> update(libsinsp): increase async event queue size

driver/Makefile.in, driver/bpf/Makefile
/kind bug
Since https://github.com/torvalds/linux/commit/13b25489b6f8bd73ed65f07928f7c27a481f1820, our driver and bpf makefile were a bit off.
Quoting the commit message:
> Currently, Kbuild always operates in the output directory of the kernel,
even when building external modules.
...
> The command for building external modules maintains backward
compatibility, but Makefiles that rely on working in the kernel
directory may break. In such cases, $(objtree) and $(srctree) should
be used to refer to the output and source directories of the kernel.
Thus, to retain old …
=> fix(driver): fix driver and bpf makefile for linux 6.13.

userspace/libsinsp/ifinfo.cpp, userspace/libsinsp/ifinfo.h, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp): isolate ifinfo from `sinsp`

userspace/libsinsp/filter/ppm_codes.cpp
/kind bug
/area libsinsp
When searching for `evt.type` comparisons in rules condition filters, we never considered the`syscall.type`. This is essentially wrong, as that field extract the same exact sets of values as `evt.type`, except for the fact that it returns NULL in case the event is not produced from a syscall. That means that it's extractable value set is a subset of the one of `evt.type`, thus meaning that it should be considered in the same way.
```release-note …
```
=> fix(libsinsp/filter): support syscall.type in event code search

driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvmmsg.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvmsg.bpf.c, userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp/modern_bpf): ancillary data improvements

userspace/libsinsp/filter_compare.cpp, userspace/libsinsp/test/filterchecks/evt.cpp
/kind bug
/area libsinsp
Edge case of the edge case here :rofl: 
Basically, `flt_cast` did not work well on big-endian systems when it was called on a source void pointer whose size was bigger than the requested type size.
This only happens for `evt.rawarg.*` filterchecks, since we do not know in advance which event we will need to extract, and thus the size of the parameter we need to extract. See https://github.com/falcosecurity/libs/issues/2333#issuecomment-2786734362 for a more formal explanation.
The second commit contains another fix, once again related to `evt.rawarg.*` fields, is to avoid copying …
=> fix(userspace/libsinsp): fixed `flt_cast` impl for big endian systems.

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/thread_manager.h, userspace/libsinsp/threadinfo.cpp
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: move server ports accounting in thread mgr

userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h, userspace/libsinsp/user.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: pass notify into `set_user` and `set_group` signatures

.github/workflows/ci.yml, userspace/libsinsp/examples/CMakeLists.txt, userspace/libsinsp/examples/cpu_usage.cpp, userspace/libsinsp/examples/test.cpp
/kind feature
/area libsinsp
This PR introduces a new mode into `sinsp-example` which will allow the profiling of event processing throughput. 
I believe this change will be useful to libs developers, as it provides a simple way to benchmark performance-related changes. A goal of this change is to be as non-intrusive as possible while still providing valuable running information on the performance of the system. 
**While running**
```
Events: 80336 Events/ms: 80.336 CPU: 8%  
```
**At the end of the run**
```
Retrieved events: 3943497
Time spent: 35955ms
Events/ms: 109.679
Max throughput observed: 472.409 events / ms
Average CPU usage: 11%
```
```release-note
NONE
```
=> feat(sinsp-example): Add throughput profiling

userspace/libsinsp/threadinfo.cpp
/kind bug
/area libsinsp
It might happen that a threadinfo has a container_id attached, but the plugin already removed the container from its cache.
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): do not throw an error while reading container's plugin IP or USER

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_threadinfo_factory.h, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: isolate `sinsp_threadinfo` from `sinsp`

userspace/libsinsp/thread_manager.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: avoid string copy in `get_field_accessor()`

userspace/libsinsp/filter_cache.h, userspace/libsinsp/plugin.cpp, userspace/libsinsp/plugin.h, userspace/libsinsp/plugin_filtercheck.cpp, userspace/libsinsp/plugin_filtercheck.h, userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/sinsp_filtercheck.h, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/sinsp_filtercheck_fd.h, userspace/libsinsp/test/filter_compiler.ut.cpp, userspace/libsinsp/test/filterchecks/mock.cpp, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/plugin_extract.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h, userspace/plugin/plugin_api.h, userspace/plugin/plugin_types.h
Add FTYPE_METADATA_SLICE, CAP_EXTRACT_METADATA, and associated routines so that plugins can provide the location of each field.
> /kind bug
> /kind design
/kind feature
/area API-version
> /area build
> /area CI
> /area …
=> new(userspace/plugin) Add support for start and end field offsets

userspace/libsinsp/parsers.cpp, userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: remove unused `m_ts` from `erase_fd_params`

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/timestamper.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(userspace/libsinsp): add `timestamper` component

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/user.ut.cpp, userspace/libsinsp/user.cpp, userspace/libsinsp/user.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)! use `timestamper` in usergroup mgr

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_fdinfo_factory.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp): use factory in evt proc's `build_fdinfo()`

userspace/libsinsp/dumper.cpp, userspace/libsinsp/dumper.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: drop unused `sinsp_dumper` APIs

test/e2e/tests/commons/sinspqa/sinsp.py
/kind bug
/area tests
Will fix `test_curl_nginx` spurious failures.
Fixes #
```release-note
NONE
```
=> fix(test/e2e): properly flush remaining queue once sinsp process leaves.

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libs)!: clean some sinsp APIs and replace `NULL` with `nullptr` 

driver/modern_bpf/helpers/base/shared_size.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvmmsg.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendmmsg.bpf.c
/kind cleanup
We noticed that on some kernels, it seems like `bpf_loop` `sendmmsg/recvmmsg` programs are slowing down the machine (possibly some kernel bugs?), leading to issues with multiple programs.
Limit `bpf_loop` iterations to 16 instead of 1024 to mitigate the issue (that will need proper investigation).
Fixes #
```release-note
NONE
```
=> chore(driver/modern_bpf): limit `bpf_loop` helper to 16 iterations.

userspace/libscap/engine/source_plugin/source_plugin.c
/kind bug
/area libscap-engine-source-plugin
Fixes #
```release-note
NONE
```
=> fix(userspace/libscap): avoid a possible read past end of buffer.

driver/modern_bpf/helpers/base/maps_getters.h, driver/modern_bpf/helpers/interfaces/syscalls_dispatcher.h, driver/modern_bpf/maps/maps.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/socket.bpf.c, userspace/libpman/include/libpman.h, userspace/libpman/src/maps.c, userspace/libpman/src/sc_set.c
/kind cleanup
No
Our ebpf probe is saving many things, including the interesting syscall set, into the `.bss` section which is set by libbpf as mmapable. It is a best practice not to include security sensitive settings in an mmapable fd, so we are separating these, plus the general ebpf probe settings into their own maps; in addition, we are setting variables that are never written to read-only (by using `.rodata`).
Credits to @mouadk for looking at the maps permissions and suggesting this …
=> cleanup(modern_bpf): r/w ro ebpf maps best practices

userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/sinsp.cpp
> /kind bug
/kind cleanup
/kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: make `sinsp_parser::reset()` const

userspace/libsinsp/examples/test.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp/examples): add -c and -A options in example

userspace/libscap/scap_event.c
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> /version …
=> fix(userspace/libscap): avoid field access to possibly NULL struct

userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/plugin_extract.cpp, userspace/plugin/plugin_api.h, userspace/plugin/plugin_types.h
The docs (and a unit test) specified `value_offsets` to be an array of `ss_plugin_extract_value_offsets` structs, while the code in plugin_filtercheck.cpp expected it to be a struct of arrays. Things worked out only because we never extract multiple fields in one go (at least in libsinsp itself).
Keep the plugin_filtercheck.cpp behavior and adapt the documentation and tests to match.
Additionally, clarify that the offsets are counted from the start of the event buffer (including the header).
/kind bug
> /kind design
/kind test …
=> fix(plugin): fix and clarify extract offsets docs/tests

userspace/libsinsp/test/scap_files/converter_tests.cpp, userspace/libsinsp/test/scap_files/scap_file_test.h
> /kind bug
> /kind design
/kind test
> /area build
> /area CI
/area tests
> /version …
=> test(userspace/libsinsp/scap_files): add `assert_num_event_types()`

test/drivers/event_class/event_class.cpp
> /kind bug
> /kind design
> /kind test
> /area build
> /area CI
/area tests
> /version …
=> fix(test/drivers): ignore `SO_REUSEPORT` setsockopt syscall error

userspace/libsinsp/settings.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/user.cpp, userspace/libsinsp/user.h
/kind bug
/kind cleanup
/area libsinsp
Since we now do not store users and groups full info inside each threadinfo, we would lose users and groups info for host processes after 1 minute.
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): avoid clearing host users and groups tables every minute

driver/bpf/fillers.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/dup2.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/dup3.bpf.c, driver/ppm_fillers.c
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> fix(driver): cast fds to 32 bits before sending them in dup2 and dup3

userspace/libsinsp/examples/test.cpp
Select the SOURCE_PLUGIN_ENGINE only if SAVEFILE_ENGINE hasn't been previously selected. This lets us process .scap files with a plugin.
This makes the "-s" and "-p" command line flags sensitive to order, so document that behavior.
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area …
=> fix(userspace/libsinsp/example): Allow processing scaps with plugins

driver/bpf/fillers.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/dup.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/dup2.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/dup3.bpf.c, driver/ppm_fillers.c
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> fix(driver): cast rets and fds to 32 bits before sending them in dup*

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp_threadinfo_factory.h
> /kind bug
/kind cleanup
> /kind design
> /kind test
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat!(userspace/libsinsp): remove unused sinsp ptr in tinfo factory

userspace/libsinsp/examples/CMakeLists.txt, userspace/libsinsp/examples/test.cpp, userspace/libsinsp/state/table_adapters.h, userspace/libsinsp/state/type_info.h, userspace/libsinsp/test/state.ut.cpp
/kind feature
/area libsinsp
Introduce `table_input_adapter` to be able to access sub-tables.
Update sinsp-example `-T` switch to be able to print the contents of the available tables.
Fixes #
```release-note
NONE
```
=> table_input_adapter

test/libscap/test_suites/engines/savefile/converter.cpp, userspace/libsinsp/test/scap_files/converter_tests.cpp
> /kind bug
/kind cleanup
> /kind design
> /kind test
> /area build
> /area CI
/area tests
> /version …
=> refactor: clean scap converter tests

test/libscap/test_suites/engines/savefile/converter.cpp, userspace/libscap/engine/savefile/converter/converter.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
/area libsinsp
/area tests
> /version …
=> fix: fix scap converter `PT_UID` parameters default value

.github/workflows/ci.yml
/kind bug
> /kind design
> /kind test
> /area build
/area CI
> /area tests
> /version …
=> ci: switch `debian:buster` apt debian repository URL to snapshot URL

test/libscap/test_suites/engines/savefile/convert_event_test.h, test/libscap/test_suites/engines/savefile/converter.cpp, userspace/libscap/engine/savefile/converter/converter.cpp, userspace/libscap/engine/savefile/converter/table.cpp, userspace/libscap/engine/savefile/converter/types.h, userspace/libsinsp/event.cpp, userspace/libsinsp/event.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h
> /kind bug
> /kind design
> /kind test
/kind feature
> /area build
> /area CI
/area libscap
/area libsinsp
/area tests
> /version …
=> feat(userspace/libscap): add capability to push empty parameters to scap-converter

test/libscap/test_suites/engines/gvisor/gvisor_parsers.cpp
https://github.com/falcosecurity/libs/pull/2544 implements conversion of the exceve_x event which increases the number of parameters to 30.
Adjust the number of expected parameters from 27 to 30 for execve_x events with the gvisor engine.
> /kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area …
=> fix(testing): adjust gvisor testing for execve

test/libscap/test_suites/engines/savefile/convert_event_test.h, test/libscap/test_suites/engines/savefile/converter.cpp, test/libscap/test_suites/userspace/scap_event.cpp, userspace/libscap/CMakeLists.txt, userspace/libscap/scap.h, userspace/libscap/scap_empty_params_set.c, userspace/libscap/scap_event.c, userspace/libsinsp/test/events_fspath.ut.cpp, userspace/libsinsp/test/scap_files/scap_file_test.h, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
> /kind bug
> /kind design
/kind test
/kind feature
> /area build
> /area CI
/area libscap
/area libsinsp
/area tests
> /version …
=> feat: add support for creating events with empty parameters

userspace/libscap/scap_event.c
The function extracting `fd` parameter's location from the exit event is missing information for the dup syscalls.
Add location of the `fd` parameter in the exit event for all dup syscalls.
> /kind bug
> /kind design
> /kind test
/kind feature
> /area build
> /area CI
> /area …
=> fix(libscap): add missing fd locations for dup exit events

userspace/libscap/linux/scap_fds.c
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
/area libscap
> /area tests
> /version …
=> fix(userspace/libscap): populate error in case of failing `stat` on fd

test/libscap/test_suites/engines/savefile/converter.cpp, userspace/libscap/scap.h, userspace/libsinsp/event.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/filter_eval_test.cpp, userspace/libsinsp/test/filter_eval_test.h, userspace/libsinsp/test/filterchecks/evt.cpp, userspace/libsinsp/test/filterchecks/evt/arg.cpp, userspace/libsinsp/test/filterchecks/evt/rawarg.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind bug
> /kind design
/kind test
> /area build
> /area CI
/area libsinsp
/area tests
> /version …
=> fix(userspace/libsinsp): partially fix filterchecks for empty params

test/libscap/test_suites/engines/savefile/converter.cpp, userspace/libscap/engine/savefile/converter/table.cpp, userspace/libsinsp/parsers.cpp
Support for empty parameters was added with https://github.com/falcosecurity/libs/pull/2550.
This update adds empty parameter support for `PPME_SYSCALL_SETPGID_X` and `PPME_SYSCALL_SETNS_X`.
> /kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area …
=> feat(savefile): add empty parameter support

cmake/modules/zlib.cmake
/kind bug
/area build
N/A
Fixes CFLAG qoting with bundled `zlib` dep so the command doesn't error if more than one CFLAG is defined.
Before, adding `-DENABLE_PIC` broke `zlib` dep builds (key flags are `-DUSE_BUNDLED_DEPS=ON -DENABLE_PIC=ON`):
> cmake -DUSE_BUNDLED_DEPS=ON -DBUILD_LIBSCAP_GVISOR=OFF -DENABLE_PIC=ON -DCREATE_TEST_TARGETS=OFF -DBUILD_LIBSCAP_MODERN_BPF=ON -DMODERN_BPF_DEBUG_MODE=ON scap ..
> [ 26%] Built target elf
> [ 26%] Performing configure step for 'zlib'
> /bin/sh: line 1: CFLAGS=-O3 -fPIC: command not found
> make[3]: *** [libscap/CMakeFiles/zlib.dir/build.make:92: …
=> fix(cmake): Fix zlib PIC build flag handling

driver/modern_bpf/programs/attached/events/toctou_mitigation/sys_enter_connect.bpf.c, driver/modern_bpf/programs/attached/events/toctou_mitigation/sys_enter_creat.bpf.c, driver/modern_bpf/programs/attached/events/toctou_mitigation/sys_enter_open.bpf.c, driver/modern_bpf/programs/attached/events/toctou_mitigation/sys_enter_openat.bpf.c, driver/modern_bpf/programs/attached/events/toctou_mitigation/sys_enter_openat2.bpf.c
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> fix(driver/modern_bpf): remove retval from ttm kprobe signatures

userspace/libscap/debug_log_helpers.h, userspace/libscap/linux/scap_cgroup.c, userspace/libscap/linux/scap_cgroup.h, userspace/libscap/linux/scap_linux_platform.c
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> /version …
=> fix(libscap): cgroupv2 path discovery with empty cgroup2 mountpoint

driver/modern_bpf/helpers/store/auxmap_store_params.h, test/libsinsp_e2e/sys_call_test.cpp
/kind bug
> /kind design
/kind test
> /area build
> /area CI
/area tests
> /version …
=> fix(driver/modern_bpf): fix iovec size eval for emulated ia32 syscalls

driver/event_table.c, test/libscap/test_suites/engines/savefile/converter.cpp, userspace/libscap/engine/savefile/converter/converter.cpp, userspace/libscap/engine/savefile/converter/table.cpp, userspace/libscap/scap_event.c, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp_filtercheck_user.cpp
> /kind bug
> /kind design
/kind test
/kind feature
> /area build
> /area CI
/area libscap
/area libsinsp
/area tests
> /version …
=> feat(userspace/libscap)!: add large payload support to scap converter

userspace/libsinsp/sinsp_filtercheck_event.cpp
> /kind bug
/kind cleanup
> /kind design
> /kind test
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> chore(userspace/libsinsp): mark `evt.dir` as deprecated

userspace/libscap/engine/savefile/converter/README.md, userspace/libscap/engine/savefile/converter/converter.cpp, userspace/libscap/engine/savefile/converter/converter.h, userspace/libscap/engine/savefile/converter/results.h, userspace/libscap/engine/savefile/scap_savefile.c, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/scap_files/scap_file_test.h
> /kind bug
> /kind design
/kind test
/kind feature
> /area build
> /area CI
/area libsinsp
/area tests
> /version …
=> feat!: drop scap files' enter events not eligible for scap conversion

userspace/libscap/engine/savefile/converter/converter.cpp, userspace/libscap/scap_event.c, userspace/libsinsp/sinsp_filtercheck.cpp
> /kind bug
> /kind design
> /kind test
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat!: don't reserve any byte for empty parameters values

test/libsinsp_e2e/fs.cpp, test/libsinsp_e2e/paths.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/events_evt.ut.cpp, userspace/libsinsp/test/events_file.ut.cpp, userspace/libsinsp/test/events_fspath.ut.cpp, userspace/libsinsp/test/events_param.ut.cpp, userspace/libsinsp/test/events_proc.ut.cpp, userspace/libsinsp/test/filter_op_numeric_compare.ut.cpp, userspace/libsinsp/test/filter_transformer.ut.cpp, userspace/libsinsp/test/filterchecks/evt.cpp, userspace/libsinsp/test/filterchecks/evt/rawarg.cpp, userspace/libsinsp/test/filterchecks/fd.cpp, userspace/libsinsp/test/filterchecks/static.cpp, userspace/libsinsp/test/filterchecks/user.cpp, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/metrics.cpp, userspace/libsinsp/test/plugins/routines.cpp, userspace/libsinsp/test/plugins/syscall_subtables.cpp, userspace/libsinsp/test/plugins/syscall_subtables_array.cpp, userspace/libsinsp/test/plugins/syscall_subtables_array_pair.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
> /kind bug
/kind design
/kind test
/kind feature
> /area build
> /area CI
/area libsinsp
/area tests
> /version …
=> feat(userspace/libsinsp)!: filter out `PPME_SYSCALL_OPEN_E` events

driver/bpf/fillers.h, driver/event_stats.h, driver/event_table.c, driver/fillers_table.c, driver/main.c, driver/modern_bpf/definitions/events_dimensions.h, driver/ppm_fillers.c, driver/ppm_fillers.h, userspace/libscap/engine/nodriver/nodriver.c, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/public_sinsp_API/ppm_sc_codes.cpp
/kind bug
/kind cleanup
> /kind design
> /kind test
> /area build
> /area CI
/area libscap-engine-nodriver
/area libsinsp
/area tests
/version …
=> chore!: replace unusable `SCAPEVENT_X` usage with `SCAPEVENT_E`

userspace/libsinsp/plugin.cpp, userspace/libsinsp/test/plugins.ut.cpp, userspace/libsinsp/test/plugins/schema_version_test.cpp
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(sinsp): disallow having a plugin with extract CAP with zero fields

userspace/plugin/plugin_loader.c
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(userspace/plugin): resolve `get_required_event_schema_version()`
