- OWNERS
- README.md
As per the [proposal](https://github.com/falcosecurity/falco/blob/master/proposals/2021019-libraries-donation.md), the owners are chosen from the current major contributors (considering the past two years) to this project, given their availability and commitment.
> Initial OWNERS file

- CMakeLists.txt
> /kind bug
/kind cleanup
> /kind design
/area build
> /area tests
This PR trivially changes the download URLs of some dependencies so that the build system can fetch them from their original repositories. 
This PR also renames to `common/sysdig_types.h` to `common/types.h` since the sysdig prefix is not needed anymore.
N.B.
This PR will not address all dependencies since some need care (see above, under the "special note" section).
**Which issue(s) …
> build: update deps upstream URLs

- userspace/libsinsp/container.cpp
replace NULLs with empty strings to stop the std::string construction from throwing an exception
Signed-off-by: Daniel Karagory <danielbatterystapler@gmail.com>
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Stops ``sinsp_container_manager::get_container_name()`` from causing an exception by attempting to return NULL when it is unable to find container info. It does this by instead returning an empty string. More information can …
> fix(sinsp/container.cpp): remove NULL

- driver/bpf/builtins.h
- driver/bpf/filler_helpers.h
- driver/bpf/fillers.h
- driver/bpf/maps.h
- driver/bpf/plumbing_helpers.h
- driver/bpf/probe.c
- driver/bpf/types.h
- userspace/libscap/scap_bpf.c
Signed-off-by: Lorenzo Fontana <lo@linux.com>
/kind bug
Fixes #4
This is another attempt to fix the issue reported by many users on Falco where you can't have a working BPF probe when compiling with Clang >= 10.0.0
Systems where to test before merging
In particular, we want to make sure the probe still works under systems where it was working before the changes made here.
For faster iteration with newer kernels I created a bpf-harness test suite for our probe. You can find it here https://github.com/fntlnz/bpf-harness
If you can, please test this under your environment and …
> fix(driver/bpf): probe compilation fixes

- userspace/libsinsp/settings.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/threadinfo.h
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
This PR exposes two aspects of libsinsp thread table management to libsinsp consumers:
* Make thread table size configurable at runtime
API change: sinsp::set_max_thread_table_size() is removed, use
m_thread_manager->set_max_thread_table_size() directly.
A build-time absolute maximum is still maintained and respected.
* Configurable thread table purging
Exited threads are not removed …
> More flexible thread table management

- driver/bpf/CMakeLists.txt
/kind bug
> /kind design
/area build
> /area tests
`builtins.h` was recently added and it's required to build the bpf probe.
So, just add the missing file to the cmake install command.
Fixes #
```release-note
NONE
```
> fix(driver/bpf): add missing builtins.h to the install files list

- .gitignore
- userspace/libscap/scap_bpf.c
- userspace/libscap/scap_bpf.h
/kind bug
/kind feature
/area libscap
While it is indeed correct that the license section is in the BPF probe source code (see https://github.com/falcosecurity/libs/commit/8918b9579cd5a3828df6c57652dd38ea92875b11), 
our custom BPF loader should read it by parsing the ELF and then accordingly use the read value in the `bpf_attr` instance.
Rather than always enforcing the license in the libscap loader - like the #37 attempt does - this PR reads the actual value from the ELF and then uses it in our custom loading phases (see `load_tracepoint` > `bpf_load_program`) 
Supersedes #37 …
> read BPF license from ELF

- cmake/modules/grpc.cmake
/kind bug
> /kind design
/area build
> /area tests
When embedding gRPC, its installation files are only needed at build time. So we have to keep them into `${GRPC_INSTALL_DIR}`, the local build directory for gRCP.
This change achieves that by manually overriding `DESTDIR`, since the resulting installation path is computed by `DESTDIR` + `CMAKE_INSTALL_PREFIX`.
Fixes #
This fix is …
> build(cmake/modules): keep gRCP installation files into local dir

- userspace/libsinsp/container_engine/cri.cpp
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
We can get two things from containerd-specific data that save
us more effort later:
- resource limits
- IP address
Unfortunately, cri-o now passes the parse_containerd checks
as well, which makes us skip the extra CRI queries (e.g. cri-o
1.20 supports the JSON in the info field, but that does not
contain all the data containerd reports).
Make parse_containerd return true only when we …
> Run extra CRI queries even when parse_containerd succeeds

- userspace/libsinsp/k8s_api_handler.cpp
- userspace/libsinsp/k8s_api_handler.h
- userspace/libsinsp/k8s_handler.cpp
- userspace/libsinsp/k8s_handler.h
- userspace/libsinsp/settings.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/socket_handler.h
This commit adds a new sinsp public API (set_metadata_download_params), allowing the user modify some of the key parameters that determine the behavior of metadata download from orchestrators like Kubernetes or Mesos.
The commit also changes the default value of some of the metadata download parameters. Specifically, the maximum startup download size goes from 30MB to 100MB, and the chunck wait delay goes from 10ms to 1ms.
Signed-off-by: Loris Degioanni <loris@sysdig.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area …
> Parametrize the metadata download

- userspace/libsinsp/k8s.cpp
- userspace/libsinsp/k8s.h
- userspace/libsinsp/k8s_net.cpp
- userspace/libsinsp/k8s_net.h
- userspace/libsinsp/k8s_pod_handler.cpp
- userspace/libsinsp/k8s_pod_handler.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
/kind feature
/area libsinsp
See #43
Fixes #43 
```release-note
new: ability to filter by a node when fetching K8S metadata
BREAKING CHANGE: `sinsp::init_k8s_client()` signature has changed since the new argument `node_name` has been introduced
```
> new: ability to filter by a node when fetching K8S metadata

- userspace/libscap/scap_procs.c
- userspace/libsinsp/container_engine/cri.cpp
/kind bug
/area libscap
/area libsinsp
In the linked issue, there was a cgroup layout in `/proc/[pid]/cgroup` which was not supported in libscap and libsinsp. It took the form `/system.slice/containerd.service/kubepods-burstable-podb4f3dfaf_f987_499d_a04c_2c60eb01958c.slice:cri-containerd:f659de946112140fd722cddfd24015a8c9fce51b7ab7f007ac30612b6f9acfc9` and was only observed when `SystemdCgroup` is not configured in containerd.
The libscap change makes it so we always read the cgroup to the end of the line when reading from `/proc/[pid]/cgroup`. With the cgroup layout observed in the issue, the previous behavior would only read up to the first `:` and drop the …
> Detect containerd containers when SystemdCgroup is not configured

- driver/bpf/Makefile
Kbuild does not successfully compile our probe anymore with always.
This was also necessary for samples/bpf in the kernel [0]
[0] https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=5f2fb52fac15a8a8e10ce020dd532504a8abfc4e
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
/kind bug
Compiling the probe against newer 5.11/5.12 kernels is now not working at all because the Makefile cannot pick the target. This PR fixes that.
Compiling for now only works with Clang 7 until this is fixed too https://github.com/falcosecurity/libs/issues/58
Fixes …
> fix(driver/bpf): use always-y instead of always

- proposals/20210818-driver-semver.md
> /kind bug
/kind design
> /area build
> /area tests
This proposal introduces semver-compatible version checks for the user/kernel boundary,
i.e. between the kernel driver/eBPF probe and the userspace components.
Fixes #
```release-note
NONE
```
> new(proposals): API versioning for user/kernel boundary

- userspace/libsinsp/container_engine/cri.cpp
- userspace/libsinsp/cri.cpp
- userspace/libsinsp/cri.h
/kind bug
/area libsinsp
Currently `container.privileged` flag does not always work when container runtime is `containerd` or `crio`.  This is because `userspace/libsinsp/cri.cpp` gets `container.privileged` flag from an out-of-date location.  
Since CRI doesn't define where the flag should be stored, `containerd` and `crio` both implement their own version.
- containerd: info/config/linux/security_context/privileged
https://github.com/containerd/containerd/blob/main/pkg/cri/server/container_status.go#L153
- crio: info/privileged
https://github.com/cri-o/cri-o/blob/master/server/container_status.go#L125
This PR creates a fallback logic.  When the existing logic …
> fix: container.privileged in containerd and crio

- driver/bpf/filler_helpers.h
- driver/bpf/fillers.h
```
Co-authored-by: Jason Dellaluce <jasondellaluce@gmail.com>
```
/kind bug
So far, the eBPF probe needs to be compiled with clang 7. Although newer versions of clang can successfully compile the probe, it then gets rejected by the kernel verifier. This has been an open issue for a while.
This PR applies a small set of fixes that allow our eBPF probe to be accepted by the kernel verifier even when compiled with recent versions of clang.  
So far, we tested this on various versions of the linux kernel and of clang.  
These are the results of our test grid, which we ran on amd64 architecture:
| …
> fix(driver): fix bpf probe verifier on linux 5.14 and llvm 12.0.1

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
Signed-off-by: lucklypse <lucklypse@gmail.com>
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Fix variable passing when attempting to format rawarg type values. This is in general not a very smart thing to do and is not really used in Falco but could be used in other clients, (if they tried they would incur in a segfault, this pr fixes that).
Fixes # …
> fix(libsinsp): fix formatter for bytebuf types

- cmake/modules/libsinsp.cmake
- userspace/libsinsp/mesos_http.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/socket_handler.h
Signed-off-by: lucklypse <lucklypse@gmail.com>
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libsinsp
> /area tests
Add a compile-time option to define the user agent that will be used in requests issued by libsinsp.
Fixes #60
We could also hard-code the user-agent, or better yet, add the library version as well to it. I'm not sure about the cases where we would …
> cleanup(libsinsp): make user agent string parametrized

- cmake/modules/openssl.cmake
/kind bug
/area build
This PR aims to work around the problem described by #89 so that we can unblock the release process of the [upcoming Falco version](https://github.com/falcosecurity/falco/issues/1741).
This PR addresses the problem described by #89 but does not solve the issue with OpenSSL 1.1.x. 
A separate fix will be needed to fix the issue definitively.
```release-note
build: downgrade openssl to 1.0.2u
```
> fix(cmake): downgrade openssl to 1.0.2u

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
- userspace/libsinsp/gen_filter.cpp
- userspace/libsinsp/gen_filter.h
- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/evttype_filter.ut.cpp
Add ability to return event types used by a filter
Add the ability to return the event types used by a filter. For
example, if a filter was "evt.type=open and fd.name=/tmp/foo", the
event types would be PPME_SYSCALL_OPEN*_{E,X}.
By default, an empty set is returned, meaning no specific events are
used.
Event types PPME_GENERIC_{E,X} are not included and it's assumed the
code using this will handle those event types directly.
This is used in programs like falco to provide a quick external test
against an event to see if it makes sense to evaluate the filter at
all. This can speed up event processing when falco has a large number
of loaded rules. Prior to this change, this was handled solely in
falco's lua code for loading rules. Moving responsibility to the
filter significantly simplifies …
> Add ability to return event types used by a filter

- userspace/chisel/lua_parser.cpp
- userspace/chisel/lua_parser.h
- userspace/chisel/lua_parser_api.cpp
Clean up the interface for lua_parser/lua_parser_api so it doesn't
rely on a single object.
Context--the lua_parser object simply holds some intermediate
state (e.g. nesting level) and builds up a gen_filter as the lua side
traverses the ast of a filter expression. The lua_parser_api class
just has static methods that are registered into lua.
lua_parser used to be a single object that was reset for each
filter. Now, it's an object that is created as a single filter is
parsed and deleted afterward. The callbacks always pass the lua_parser
object as a first argument and the state/filter in the object is
updated.
Also, registering the lua callbacks is now done via a static method
instead of in the constructor.
> …
> Update lua parser to be short-lived for a single filter

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filter.h
- userspace/libsinsp/gen_filter.h
Add the ability to return all fields exported by a factory. This is
important for programs like falco that need to validate rule filter
expressions for various event sources, as well as print out sets of
supported fields.
Previously, falco did direct calls to
sinsp::get_filtercheck_fields_info but we're trying to standardize
everything to work through factories, to make it easier to support new
event sources. This PR supports that work.
> /kind bug
> /kind design
/kind feature
> /area build
> …
> Add ability to return all fields exported by a factory

- userspace/libsinsp/eventformatter.cpp
- userspace/libsinsp/eventformatter.h
- userspace/libsinsp/gen_filter.cpp
- userspace/libsinsp/gen_filter.h
Add the notion of "generic" event formatters and formatter factories
that can create a formatter for a given format string:
- gen_filter.h defines two new classes: gen_event_formatter provides
the interface to format events:
- set_format(): set the output format and format string
- tostring(): resolve the format with info from a gen_event,
populating a resolved string.
- tostring_withformat(): like tostring() but with a one-off output
format.
- get_field_values(): return all templated field names and values
from the configured format string.
- get_output_format(): get the current output format.
- gen_event_formatter_factory performs a similar role as the existing
sinsp_evt_formatter_cache, in that it maintains a cache of previously
used format strings/formatters, to avoid the overhead of …
> Add notion of generic formatters/formatter factories

- userspace/chisel/lua_parser_api.cpp
Instead of returning errors in lua callbacks via lua_error(), which
stops the lua interpreter, return the error explicitly as a string
error or nil.
This allows for more graceful error handling on the lua side.
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libsinsp
> /area tests
Fixes # …
> Use error value over lua_error() in lua callbacks

- userspace/libscap/scap.c
Now that strings are being returned as const char*, make sure the
variable holding the returned value is const char*.
/kind bug
> /kind design
> /area build
/area libscap
> /area tests
Fixes #
```release-note
NONE
```
> Fix const warnings in libscap

- CMakeLists.txt
- userspace/common/strlcpy.h
Falco has a build variant that uses musl libc, and musl libc already
defines strlcpy, so we don't want strlcpy when compiling with musl
libc.
Unfortunately, musl doesn't have a define like _MUSL_SOURCE that we
could use to detect when compiling with musl libc. So instead, use
MINIMAL_BUILD, which when set always means compiling with musl libc.
/kind bug
> /kind design
/area build
/area libscap
> /area tests
**What this PR …
> Don't define strlcpy on musl libc

- userspace/libsinsp/plugin.cpp
Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
/kind bug
/area libsinsp
This checks that a plugin-extracted field is present before copying its value in an internal struct. This caused spurious segmentation faults, because generally there is no guarantee that the plugin sets `res_str` to `NULL` if `field_present` is set to false.
```release-note
NONE
```
> fix: check that extracted field is present before copying it

- userspace/libsinsp/container_engine/cri.cpp
In environments using CRI imageID can be recovered in 2 ways,
by reading it from the container info or by doing an extra query.
Due to the extra query not working in gke environments, it's safer
to check whether imageID has already been found instead of
unconditionally overwrite it.
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
imageID is not reported in GKE.
None
**Special …
> Do not overwrite imageID if it's already set

- README.md
> /area build
> /area tests
Fixes #
```release-note
NONE
```
> Fix link for libraries contibutions in README.md

- userspace/libscap/scap_savefile.c
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libscap
> /area tests
Building libscap with GCC 8+ generates a warning on this. The variable use seems to have been removed in https://github.com/falcosecurity/libs/commit/f557172cd77717a0268a8358f6cc4b57482431a0 .
Fixes #
```release-note
NONE
```
> chore(libscap): remove unused variable sh from scap_read_init

- userspace/libsinsp/plugin.cpp
/kind bug
/area libsinsp
Use dlerror() in place of strerror(errno) when catching dlopen errors.
Fixes #
```release-note
NONE
```
> fix(userspace/libsinsp): properly use dlerror() instead of errno when catching dlopen errors

- driver/bpf/filler_helpers.h
- driver/ppm_events.c
/kind bug
This PR adds support for AF_UNIX abstract socket addresses path, as specified https://man7.org/linux/man-pages/man7/unix.7.html:
>  abstract: an abstract socket address is distinguished (from a
>          pathname socket) by the fact that sun_path[0] is a null byte
>          ('\0').  The socket's address in this namespace is given by
>          the additional bytes in sun_path that are covered by the
>          specified length of the address structure.  (Null bytes in the
>          name have no special significance.) …
> fix(driver): properly support AF_UNIX abstract socket addresses

- userspace/libsinsp/parsers.cpp
`container_engine/docker/async_source.h` includes curl, which is not included in the minimal build.
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
The issue was introduced by https://github.com/falcosecurity/libs/pull/66 and we noticed it when added a specific CI check (see https://github.com/falcosecurity/test-infra/pull/555) for testing the minimal build …
> fix(libsinsp): correct `MINIMAL_BUILD` gate for docker

- driver/bpf/bpf_helpers.h
- driver/bpf/plumbing_helpers.h
- userspace/libscap/compat/bpf.h
- userspace/libscap/scap_bpf.c
/kind bug
/kind feature
/area libscap
The PR fixes a bug when using eBPF probe: events generated have wrong timestamp if computer gets suspended.  
This was caused by the usage of `bpf_ktime_get_ns` that internally use a CLOCK_MONOTONIC like timer.  
Instead, new API (introduced in linux 5.8: https://github.com/torvalds/linux/commit/71d19214776e61b33da48f7c1b46e522c7f78221) `bpf_ktime_get_boot_ns` uses CLOCK_BOOTTIME, thus accounting for suspended time.
Moreover, the PR introduces the concept of bpf maps freezing: BPF_MAP_FREEZE cmd was introduced in linux 5.2, and allows to freeze a map (ie: nobody can write to it anymore).
We froze the …
> fix: eBPF events ts after suspension

- userspace/libsinsp/fields_info.cpp
- userspace/libsinsp/fields_info.h
- userspace/libsinsp/filter_check_list.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/utils.cpp
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
- Change the way falco libs automatically document their supported events and fields in Markdown format
- Add a description field for field classes so they can be documented
- Change the order of addition of the field classes so they're displayed in the right order upon documentation request
Fixes # …
> refactor(libsinsp): update format for events and fields self-documentation

- cmake/modules/openssl.cmake
- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/socket_handler.h
```
Co-authored-by: Jason Dellaluce <jasondellaluce@gmail.com>
Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
Co-authored-by: lucklypse <lucklypse@gmail.com>
```
/kind bug
/area libsinsp
This PR fixes a bug introduced with the openssl version bump from 1.0.2 to 1.1.1, that broke socket_handler::get_all_data() https path.
Fixes #89 
```release-note
build: upgrade openssl to 1.1.1l
```
> fix(userspace/libsinsp): remote data fetching with openssl 1.1.1 

- userspace/libsinsp/plugin.cpp
When including inttypes.h, define __STDC_FORMAT_MACROS to ensure that
the PRIu32 defines are included.
With newer g++ versions this happens automatically, but with older g++
versions, it's still required.
> /kind bug
> /kind design
> /area build
> /area tests
Fixes # …
> Define __STDC_FORMAT_MACROS for inttypes.h (older g++)

- driver/bpf/filler_helpers.h
/kind bug
Most probably, amznlinux2 kernels are somewhat patched, and the verifier rejects our eBPF probe.  
I could reproduce the issue using the amznlinux2 vbox image.  
Together with @leogr and @jasondellaluce we made sure that it was not a clang/llvm issue (we built the kernel using https://github.com/falcosecurity/driverkit, thus using the clang/llvm on the builder image); it still failed.  
In the end, it seems like kernel verifier **is** patched.  
This PR addresses the issue on these kernels.
Fixes #130 
**Does this …
> fix(driver): small fix for eBPF probe on amznlinux2 kernels

- .gitignore
- userspace/libscap/scap_userlist.c
- userspace/libsinsp/event.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
/kind bug
/area libscap
/area libsinsp
Fix weird edge cases where users/groups where added while libscap was loading them, potentially causing a segfault.
Moreover, a sinsp::get_group() api is added, following  sinsp::get_user(), and used where needed. 
Interesting fact: libscap only loads the list of users once, during startup; thus the list of users is static, and not dynamically updated. 
This means that when filtering on a user {name,homedir,shell,loginname} (and the same goes for a group name), events for new users won't be actually managed.
Steps to reproduce the abort in …
> Users and groups loading code fixes

- driver/CMakeLists.txt
- driver/bpf/CMakeLists.txt
This affects downstream packaging (the cmake component name
ends up in package names) so make this configurable instead
of forcing `scap-driver`.
> /kind bug
> /kind design
/kind feature
/area build
> /area tests
Have scap-driver cmake component configurable as other scap-driver related stuff.
Fixes # …
> Make the `scap-driver` component name configurable

- cmake/modules/protobuf.cmake
Signed-off-by: Mujahid-Dandoti <Mujahid.Dandoti@ibm.com>
/kind bug
/area build
Updated protobuf version from 3.5.0 to 3.17.3 in protobuf.cmake for s390x.
Fixes #
```release-note
build: updated protobuf version from 3.5.0 to 3.17.3 for s390x
```
> Updated protobuf version for s390x

- driver/bpf/probe.c
- driver/main.c
- driver/ppm.h
- driver/ppm_events_public.h
- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libscap/scap.h
- userspace/libscap/scap_bpf.c
- userspace/libscap/scap_bpf.h
- userspace/libsinsp/filter.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
/kind feature
/area build
/area libscap
/area libsinsp
The PR introduces kernel side support (both kmod and eBPF) for filtering syscalls; right now, simple consumer mode can be enabled directly kernel side, instead of filtering in userspace.  
In details:
* a new dep was added for linux builds: libaudit. It is needed to fetch syscall number given syscall name
* kmod g_events_mask is now per-consumer
* eBPF will mark syscalls as uninteresting while building the shared syscall map
* libsinsp expose a new API `sinsp::set_simple_consumer()` to enable kernel side simple consumer
* falco will be updated using the new api
The changes …
> new: add support for kernel side simple consumers

- userspace/libscap/scap_savefile.c
/kind bug
/area libscap
The PR fixes a small bug in scap_fseek() that breaks the build on old gcc (centos7 on Falco CI).
Fixes #
```release-note
NONE
```
> fix(userspace/libscap): do not return any value from void scap_fseek() function

- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/token_bucket.ut.cpp
> /kind bug
> /kind design
/kind feature
> /area build
/area tests
This PR reintroduces the `token_bucket` unit test that previously belonged to the `falco` repository. As `token_bucket` was moved from there to this repository, its unit tests must be adapted to use `gtest`, since this is the testing framework that `libs` uses. 
Fixes https://github.com/falcosecurity/libs/issues/137
**Special notes …
> Reintroducing the token_bucket unit test adapted to gtest

- userspace/libscap/plugin_info.h
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libscap
> /area tests
Change missed int32_t (f48b7bd) to ss_plugin_rc
Fixes #
```release-note
NONE
```
> chore(libscap): change missed int32_t to ss_plugin_rc

- userspace/libsinsp/fields_info.cpp
- userspace/libsinsp/fields_info.h
- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filter.h
- userspace/libsinsp/filter_check_list.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
- userspace/libsinsp/gen_filter.cpp
- userspace/libsinsp/gen_filter.h
- userspace/libsinsp/plugin.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libsinsp
> /area tests
Fixes #
```release-note
Add built-in support for pretty-printing fields that can be used across programs.
```
> Cleanup list fields

- userspace/libscap/scap_procs.c
- userspace/libscap/unixid.h
/kind bug
> /kind design
> /area build
/area libscap
> /area tests
During computation of `is_exe_writable` via scap we need to perform access checks with the user that is running the program. Using the standard seteuid/setegid functions would affect all the threads in the current application, which would generate signals, change permissions and do bad things to everything else that may be …
> fix(libscap): perform seteuid/setegid only for the current thread

- driver/bpf/filler_helpers.h
- driver/bpf/quirks.h
Signed-off-by: Joseph Pittman <joseph.pittman@sysdig.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area tests
Use #ifdef to isolate x86-specific code, for ARM and other non-x86 builds.
Fixes #
```release-note
Support eBPF probe on ARM and other non-x86 processors.
```
> Support ARM processor: use proper x86 #ifdefs to isolate x86-specific code

- userspace/libscap/scap_procs.c
/kind bug
> /kind design
> /area build
/area libscap
> /area tests
In `scap_proc_fill_exe_writable`, we change the effective uid/gid but we switch back to original *real* uid/gid values. This causes issues when the real and effective uids are different.
Since we're switching the *effective* uid and gid, we should switch back to the original *effective* uid and gid as well, not the *real* one. …
> (fix) Use euid/egid instead of uid/gid in scap_proc_fill_exe_writable

- userspace/libsinsp/plugin.cpp
/kind bug
/kind feature
/area libsinsp
Currently, errors arising during plugins initialization are lost. This can become troublesome for debugging and development purposes. The reason is that, if initialization fails, the framework assumes that an invalid state is returned.
This PR fixes this by allowing plugins to return a non-NULL state in case of failure. If so, the initialization error could later be retrived through the `get_last_error` symbol. The state is then disposed with `destroy` as usual. …
> fix(libsinsp): catch errors during plugin initialization

- userspace/libscap/plugin_info.h
- userspace/libsinsp/plugin.cpp
- userspace/libsinsp/plugin.h
/kind design
/kind feature
/area libscap
/area libsinsp
This adds support to an optional function symbol for source plugins named `list_open_params`. Its purpose is to allow source plugins to return a list of suggested parameters that would be accepted as valid arguments to `open()`.
An example use case might be to list the resources openable by the plugin. This can also act as a self-documentation measure to improve the UX of plugin users. Moreover, this can make the plugin more suitable for automatic tooling by obtaining valid `open()` parameters from the plugin itself without requiring human intervention. …
> update: add source plugin symbol to list suggested open parameters

- driver/ppm_fillers.c
/kind bug
> /kind design
> /area build
> /area tests
In order to get details about the executable file of a process we query the `mm->exe_file` field. In order to access this field cleanly various kernel versions have different mechanisms, and the function is only exported in some cases. To normalize this, add our own function.
Fixes # …
> fix(driver): add ppm_get_mm_exe_file to abstract differences between kernel versions

- driver/ppm_fillers.c
/kind bug
> /kind design
> /area build
> /area tests
When looking up a file inode it is tempting to just write `->f_inode` because that's how it's done in current Linux kernel versions. However, older versions have a slightly different way to do this. Fortunately we already have a function that we use to deal with this difference. Remove `f_inode` uses and use `file_inode()` …
> fix(driver): use file_inode() for file inode operations

- userspace/libsinsp/plugin.cpp
- userspace/libsinsp/plugin.h
/kind feature
/area libsinsp
This improve the UX of the init config schema automatic validation as follows:
- Parse the schema before the config string. This way, users will not get confused
about errors coming from their configuration if the plugin has development issues.
- Stubbing empty configurations as empty json objects. This way, a default JSON value
is always provided, and is possible to pass empty configs to plugins with all-optional
schemas.
```release-note
NONE
```
> chore(libsinsp): improve UX of plugin init schema validation

- userspace/libsinsp/threadinfo.cpp
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
If threads_from_sinsp is set when creating the capture file,
the thread list is generated by libsinsp. Calculating the length
of each entry is the responsibility of the caller
of `scap_write_proclist_header` and this we need to update both
callers.
Fixes # …
> fix: Include exe_writable in the length of dumped threadinfos

- driver/bpf/fillers.h
/kind bug
Compiling our probe with `clang11` on `Kernel 5.8` we noticed that compiler optimizations introduce a back-edge. The back-edge is the result of the clang compilation, it can never be executed, however, the verifier detects the back-edge and rejects the probe. The change proposed in this PR prevents the compiler from generating this back-edge. 
**Future steps**
Understand which clang optimizations can cause verifier problems and remove them.
```release-note
NONE …
```
> fix(probe): fix clang optimization problem

- driver/ppm_fillers.c
Co-authored-by: Lorenzo Susini <susinilorenzo1@gmail.com>
/kind bug
> /kind design
> /area build
> /area tests
`PPME_PROCEXIT_1_E` requires four params ( https://github.com/falcosecurity/libs/blob/5f457a366916a96aff816b809eb0b8e8a5e4961e/driver/event_table.c#L201
). UDIG does not really require/use them yet and so is using placeholders, but it had only 3 of them instead of …
> fix(udig): add fourth argument placeholder for PPME_PROCEXIT_1_E

- driver/bpf/fillers.h
- driver/ppm_fillers.h
/kind bug
Extracting the `exe_writable` flag requires several inline functions and a number of loops unrolling which lead to a bpf stack overflow in old kernels (like 4.14). The scap loader gives us this error message:
```
bpf_load_program() err=7
```  
`err 7` corresponds to the errno `E2BIG`, i.e. the bpf program is too large to be loaded, as confirmed [here](https://man7.org/linux/man-pages/man2/bpf.2.html#ERRORS) 
To solve the problem, a new bpf program `execve_family_flags` has been introduced. This is called in tail call by `proc_startupdate_3` when we need to extract flags from …
> fix(probe): extend support for execve flags in old kernels

- driver/bpf/fillers.h
- driver/bpf/maps.h
- driver/bpf/plumbing_helpers.h
- driver/bpf/probe.c
- driver/bpf/ring_helpers.h
- driver/bpf/types.h
- driver/main.c
- userspace/libscap/scap_bpf.c
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libscap
> /area tests
Removing useless references to Sysdig in kernel module, bpf probe and libscap
Fixes #
```release-note
NONE
```
> cleanup sysdig references

- userspace/libsinsp/gen_filter.cpp
- userspace/libsinsp/gen_filter.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
This PR introduces a replacement for `void list_fields()` with markdown format, that in turn is used to format the documentation website ( https://falco.org/docs/rules/supported-fields/ ). After merging this PR we can completely remove `list_fields()` I believe since all the relevant functionality lives in `gen_event_*` and …
> new(gen_filters): port markdown function to generic filters

- driver/bpf/filler_helpers.h
When attempting to build the eBPF probe in a kernel development
environment with the config parameter CONFIG_COMPAT=no, the compile
of filler_helpers.h fails due to unknown types in net/compat.h
There is a kernel patch available to fix this problem:
- https://patches.linaro.org/project/netdev/patch/20201121214844.1488283-1-kuba@kernel.org/
But for environments where this patch is not available (such as
RHEL8 on ARM processors), we can work around this problem by
explicitly including linux/compat.h before net/compat.h, where
it is needed.
Signed-off-by: Joseph Pittman <joseph.pittman@sysdig.com>
> /kind bug
> /kind design
/kind feature
**Any specific area of …
> Include linux/compat.h before net/compat.h

- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/container.cpp
- userspace/libsinsp/container_engine/docker/async_source.cpp
- userspace/libsinsp/container_engine/docker/async_source.h
- userspace/libsinsp/container_engine/docker/docker_linux.cpp
- userspace/libsinsp/container_engine/docker/docker_win.cpp
- userspace/libsinsp/container_engine/docker/docker_win.h
- userspace/libsinsp/container_engine/docker/lookup_request.h
- userspace/libsinsp/container_engine/docker/podman.cpp
- userspace/libsinsp/container_engine/docker/podman.h
- userspace/libsinsp/container_engine/sinsp_container_type.h
- userspace/libsinsp/container_info.h
- userspace/libsinsp/procfs_utils.cpp
- userspace/libsinsp/procfs_utils.h
- userspace/libsinsp/runc.cpp
- userspace/libsinsp/runc.h
- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/procfs_utils.ut.cpp
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
This PR introduces support for the Podman container engine. It builds on top of the support for Docker, as the APIs are very similar. This PR adds support for all the known and relevant differences.
To retrieve metadata about a container, it requires the Podman API to be enabled for the user that started the container (`/run/podman/podman.sock` for root containers, …
> Support the Podman container engine

- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
This PR tries to introduce a very simple validation check on the name of the k8s node that is used as a filter when retrieving pods metadata. As discussed [here](https://github.com/falcosecurity/libs/issues/136), autodetection of the node name may fail in some edge cases. For this reason, I followed the suggestion to just check whether the node name actually …
> update(libsinsp): add k8s node name validation

- userspace/libsinsp/utils.cpp
Signed-off-by: Angelo Puglisi <angelopuglisi86@gmail.com>
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Avoid unnecessary object copy
```
/home/angelo/Projects/falcosecurity/libs/userspace/libsinsp/utils.cpp: In static member function ‘static bool sinsp_utils::find_first_env(std::string&, const std::vector<std::__cxx11::basic_string<char> >&, const …
```
> perf(sinsp): avoid copy in sinsp_utils::find_first_env

- userspace/libsinsp/test/token_bucket.ut.cpp
/kind bug
> /kind design
> /area build
/area tests
This fixes build in debian 10 for example.  
Discovered while testing https://github.com/falcosecurity/test-infra/pull/636.  
It seems like make_shared actually needs this include, otherwise failing with:
> error: 'make_shared' is not a member of 'std'
Fixes # …
> fix(userspace/libsinsp): properly include <memory> in libsinsp token_bucket unit test

- driver/ppm_events_public.h
- driver/syscall_table.c
- userspace/libscap/syscall_info_table.c
/kind bug
/area libscap
This PR adds `PPM_SC_CLONE` and `PPM_SC_CLONE3` enums. They are necessary to have correct driver instrumentation in `simpleconsumer` mode. 
```release-note
NONE
```
> fix(driver,libscap): add `PPM_SC_CLONE` and `PPM_SC_CLONE3`

- driver/bpf/filler_helpers.h
- driver/bpf/fillers.h
- driver/bpf/ring_helpers.h
- driver/bpf/types.h
- driver/ppm_events_public.h
- userspace/libscap/examples/01-open/test.c
- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libscap/scap.h
- userspace/libscap/scap_bpf.c
- userspace/libscap/scap_bpf.h
- userspace/libsinsp/sinsp.cpp
Signed-off-by: Andrea Terzolo andrea.terzolo@polito.it
/kind bug
/kind cleanup
/area libscap
/area libsinsp
This PR addresses the following points:
1. Add a new return code `PPM_FAILURE_FRAME_SCRATCH_MAP_FULL` to indicate all problems related to an event that exceeds the maximum expected size, and therefore cannot be inserted in the `frame_scratch` bpf map. Today these types of problems are marked with the slightly misleading `PPM_FAILURE_BUFFER_FULL` return code.
2. Add a new field `n_drops_scratch_map` in `scap_bpf_per_cpu_state` struct to capture drop stats due to `PPM_FAILURE_FRAME_SCRATCH_MAP_FULL` errors.
3. Use the `PPM_FAILURE_BUFFER_FULL` …
> fix: report the correct number of drops from bpf side

- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/threadinfo.h
Prefer += over +
Tested with callgrind, ~2x improvement
Signed-off-by: Angelo Puglisi <angelopuglisi86@gmail.com>
Performance enhancement
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
About 60% of the load on `falco_engine::process_event` is `sinsp_threadinfo::populate_cmdline`, improving it is definitely beneficial.
Fixes #
**Does this PR …
> perf(sinsp): optimize sinsp_threadinfo::populate_cmdline

- userspace/libscap/scap-int.h
- userspace/libscap/scap_procs.c
/kind bug
> /kind design
> /area build
/area libscap
> /area tests
This PR fixes a bug in scap procs initialization: running containers before Falco booted, were ignored until a new process spawned on them; instead, their running process were thought to be running on the host.  
Basically, cgroups v2 uses the "Unified hierarchy" for subsystems, thus the subsys list string is always empty in /proc/pid/cgroup file.
Workaround this by …
> fix(userspace/libscap): fixed cgroups v2 support in scap_proc_fill_cgroups()

- userspace/libsinsp/test/evttype_filter.ut.cpp
/kind bug
> /kind design
> /area build
/area tests
Fixes evttype_filter_ut test build:
```
/home/federico/Work/libs/userspace/libsinsp/test/evttype_filter.ut.cpp:94:31:   required from here
/usr/include/gtest/gtest-message.h:129:10: error: no match for ‘operator<<’ (operand types are ‘std::__cxx11::basic_stringstream<char>’ and ‘const std::set<short unsigned int>’)
129 |     *ss_ << val;
```
std::set has no `<<` …
> fix(userspace/libsinsp): fix evttype_filter.ut test build

- userspace/chisel/chisel.cpp
- userspace/chisel/chisel.h
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
These changes allow for simple chisels to be loaded directly from a string stored in memory. For complicated use cases, this might make much sense, but imaging your chisel looks as follows:
```lua
args = {}
function on_event()
return true
end
function on_init()
filter = "not container.id = 'host'\n"
chisel.set_filter(filter)
return true
end
```
You could create a …
> new(chisel): Allow chisels to be loaded from memory

- userspace/libsinsp/container_engine/cri.cpp
- userspace/libsinsp/container_engine/docker/base.cpp
- userspace/libsinsp/container_engine/docker/docker_linux.cpp
- userspace/libsinsp/container_engine/docker/podman.cpp
- userspace/libsinsp/runc.cpp
- userspace/libsinsp/runc.h
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
The PR fixes a problem in podman as user detection; basically, in podman we have 2 runc matching cgroups layouts:
```
/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-$ID.scope/container
/machine.slice/libpod-$ID.scope/container
```
While we were able to parse the container ID just fine, we did not checked if the cgroup belonged to an user or root. …
> fix(userspace/libsinsp): fixed podman as user detection

- userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Following the recent addition to extra parameters and their parsing to connect/open/openat (https://github.com/falcosecurity/libs/pull/235) we still want to be compatible with drivers and scap files that didn't have those params. This PR adds the relevant check.
Fixes # …
> fix(libsinsp): check param num on connect/open/openat parsing

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
- userspace/libsinsp/tuples.cpp
- userspace/libsinsp/tuples.h
- userspace/libsinsp/value_parser.cpp
Signed-off-by: vadim.zyarko <vadim.zyarko@sysdig.com>
What type of PR is this?
/kind feature
Any specific area of the project related to this PR?
/area libsinsp
What this PR does / why we need it:
The current implementation of ipv6net checks has a fixed width for the subnet checks - 48 bits, while ipv4 net allows specifying ipv4net  prefix with a standard cidr notation: 172.1.1.1/13.
This PR is to extend the ipv6net notation with cidr prefixes like BFD0::/32
The change is backward compatible meaning that if the net is specified as a standard ivp6 address like `BFD0::` then the old schema will be applied. 
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
```release-note
update: allow ipv6 filtering with normalized CIDR notation BFD0::/32
```
> new(userspace/libsinsp): ipv6net cidr filtering

- userspace/libsinsp/tuples.cpp
Signed-off-by: Andrea Bonanno <andrea@bonanno.cloud>
/kind cleanup
/area libsinsp
Addresses `is_pod` deprecation in C++20
Fixes #
```release-note
NONE
```
> chore(userspace/libsisnp): addresses is_pod deprecation in C++20

- userspace/libsinsp/plugin.cpp
- userspace/libsinsp/plugin.h
Co-authored-by: Andrea Bonanno <andrea@bonanno.cloud>
/kind bug
/area libsinsp
This fixes the init config feature of the plugin system. When an init schema is defined, the framework takes care of automatically validating the contents to match the provided schema. To improve the UX, empty config strings are turned into an empty json string `{}` when a json schema is defined.
However, the framework doesn't pass the fixed config string to the framework. As such, plugins still ended up receiving an empty string even if a json schema was defined, which is a flaw in the validator logic.
**Which issue(s) this PR …
> fix(libsinsp/plugins): fix init schema config string passing

- userspace/chisel/lua_parser_api.cpp
- userspace/libsinsp/filter.cpp
- userspace/libsinsp/gen_filter.h
- userspace/libsinsp/utils.cpp
- userspace/libsinsp/utils.h
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
This PR introduces two new operators called `bcontains` and `bstartswith`. They allow performing byte matching, accepting as input a hexadecimal string. 
I have tested them with variations of these rules: 
```
- rule: ELF magic 
desc: Detect if ELF file is being sent or received through a socket by matching on the ELF magic bytes
condition: fd.type=ipv4 and evt.type …
```
> new: add support for bcontains and bstartswith operators

- userspace/libsinsp/doxygen/conf.dox
- userspace/libsinsp/event.cpp
- userspace/libsinsp/event.h
- userspace/libsinsp/eventformatter.cpp
- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filter.h
- userspace/libsinsp/filter_check_list.cpp
- userspace/libsinsp/filter_check_list.h
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/settings.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/threadinfo.h
- userspace/libsinsp/utils.cpp
/kind cleanup
/area libsinsp
This removes the `HAS_FILTERING` and `HAS_CAPTURE_FILTERING` macros from libsinsp, which are legacy code and are not used anymore.
Fixes #
```release-note
NONE
```
> chore(libsinsp): remove unused macros HAS_FILTERING and HAS_CAPTURE_FILTERING

- userspace/libsinsp/async/async_key_value_source.h
- userspace/libsinsp/async/async_key_value_source.tpp
- userspace/libsinsp/cgroup_limits.h
- userspace/libsinsp/container_engine/cri.h
- userspace/libsinsp/container_engine/docker/async_source.h
/kind cleanup
/kind design
/area libsinsp
The `async_key_value_source` class used to reside in its own `async` base level directory. However, such a class is only used in the scope of libsinsp, and having an extra directory inside `userspace` makes the overall design of the libraries repo more confusing.
This PR cleans this up by moving the `async` directory inside `userspace/libsinsp` and by putting the `async_key_value_source` class under the `libsinsp` namespace.
Fixes #
```release-note …
```
> refactor: move async key value source into libsinsp

- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filter.h
- userspace/libsinsp/filter/ast.cpp
- userspace/libsinsp/filter/ast.h
- userspace/libsinsp/filter/parser.cpp
- userspace/libsinsp/filter/parser.h
- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/filter_compiler.ut.cpp
- userspace/libsinsp/test/filter_parser.ut.cpp
/kind bug
/kind cleanup
/kind design
/area libsinsp
/area tests
This PR attempts to **solve all the points** of #216. The approach that I tried to undertake is to **not introduce any breaking changes** and **keep supporting the legacy public interfaces** of `sinsp_filter_compiler`. As such, this **PR is a big no-op** from a user-facing point of view, **but addresses most of the problems** we have in the libsinsp filter parser. Briefly, the core changes are the following:
- **Definition of a context-free formal grammar** that regulates the filtering language
- Explicit **separation of textual filter parsing from filterchecks** compilation:
- …
> refactor(libsinsp): renovate the filter grammar, parser, and compiler

- driver/bpf/filler_helpers.h
- driver/ppm_events.c
- driver/ppm_fillers.c
/kind bug
Testing the [scap-open example](https://github.com/falcosecurity/libs/blob/master/userspace/libscap/examples/01-open/test.c) on my machine I noticed this:
```
❯ sudo BPF_PROBE=driver/bpf/probe.o ./libscap/examples/01-open/scap-open
events captured: 11086030
seen by driver: 11087536
Number of dropped events: 13
Number of dropped events caused by full buffer: 0
Number of dropped events caused by invalid memory access: 13
Number of dropped events caused by an invalid condition in the kernel instrumentation: 0
Number of preemptions: 0
Number of events skipped due to the tid being in a …
```
> fix(bpf_probe): check null buffer pointer in `PPME_SOCKET_RECVFROM_X` event

- userspace/libsinsp/fdinfo.h
This fixes a bug where invalid results appeared in parsed fdinfos,
due to random stack values for the contents of m_sockinfo.
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
This PR fixes a bug where `sinsp_fdinfo::m_sockinfo` is uninitialized, which means that it is populated with random stack data, and can make it appear that the socket information is populated when it isn't.
In particular, this corruption can …
> fix(libsinsp): Zero-initializes m_sockinfo in sinsp_fdinfo.

- userspace/libscap/scap_bpf.c
- userspace/libscap/scap_savefile.c
- userspace/libsinsp/parsers.cpp
/kind bug
/area build
/area libscap
/area libsinsp
This PR removes a bunch of warnings that prevents the libraries to be compiled with the `BUILD_WARNINGS_AS_ERRORS` flag set to ON. This is required by Falco, which has some CI jobs using that flag. At the same time, this PR fixes a variable-initialization bug inside `parsers.cpp`.
As for now, compilation seems to fail when both `BUILD_WARNINGS_AS_ERRORS` and `MINIMAL_BUILD` are set to ON.
```release-note
update: build with warnings as errors by default
```
> fix(libsinsp,libscap): fix compilation warnings

- driver/event_table.c
/kind bug
> /kind design
> /area build
/area libscap
> /area tests
I was hitting this assertion when building in debug mode:
```
falcosecurity/libs/userspace/libsinsp/event.cpp:1429: std::string sinsp_evt::get_base_dir(uint32_t, sinsp_threadinfo*): Assertion `dir_param_info->type == PT_FD' failed.
```
I traced it to an issue when parsing the openat entry event. This patch fixes it. …
> fix(libscap): set openat dirfd parameter to 0

- driver/ppm_fillers.c
Signed-off-by: akulhar <kulhar1985@gmail.com>
Fix for storage size of ‘how’ isn’t known compilation error 
/kind bug
/area build
Fixes #
```release-note
NONE
```
> Adding openat2 header file under __NR_openat2 and UDIG ifdef code block

- driver/ppm_fillers.c
Signed-off-by: Andrea Bonanno <andrea@bonanno.cloud>
/kind bug
Fixes passing the `io_uring_setup` return value. 
Fixes #
```release-note
NONE
```
> fix: fixes returning uring_setup retvalue

- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/parsers.h
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
When updating libsinsp to make sure we correctly update the fd on `connect()` events we were a bit overzealous and changed the functions to always prioritize the content that was already stored in the fdinfo object. However, this shouldn't be done in all cases. If an UDP socket issues several `sendto()`s to different …
> fix(libsinsp): overwrite fd destination address when safe to do so

- userspace/libscap/scap.h
- userspace/libscap/scap_event.c
- userspace/libsinsp/event.h
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libscap
/area libsinsp
> /area tests
This PR adds a function to libscap to decode a scap event. The PR is made out of two parts (two commits):
1. adding the function itself `scap_event_decode_params()`
2. replacing the logic inside the libsinsp function `load_params()` to use `scap_event_decode_params()`
I think this is valuable because it should be libscap's responsbility to decode an event that it …
> new(libsinsp,libscap): add scap_event_decode_params() in libscap and use it in libsinsp

- userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Safely check the version of the execve event in the exit parser by checking the number of parameters
Fixes #
```release-note
NONE
```
> fix(libsinsp): safely check number of parameters on execve exit parser

- driver/bpf/Makefile
- driver/bpf/fillers.h
/kind bug
/kind feature
/area build
This is just a couple of small fixes / additions to the BPF driver makefile:
- Fixes compilation when using clang versions older than 10, which do not support the `-fmacro-prefix-map` arg
- Automatic identification of COS builds, to enable `-DCOS_73_WORKAROUND`, rather than the current manual approach.
Fixes #
```release-note
NONE
```
> build(driver) automatic COS workaround & clang fixes in BPF driver build

- driver/ppm_fillers.c
/kind bug
> /kind design
> /area build
> /area tests
I have noticed that when handling the `open_by_handle_at` syscall we retrieve a pointer to `struct file` using `fget`. 
See here:
https://github.com/falcosecurity/libs/blob/master/driver/ppm_fillers.c#L4921
Since a reference counter is involved in this operation, we should decrement it using the `fput` …
> fix(driver): use fput in kmod when handling open_by_handle_at

- userspace/libsinsp/filter/ast.cpp
- userspace/libsinsp/filter/ast.h
- userspace/libsinsp/filter/parser.cpp
- userspace/libsinsp/filter/parser.h
- userspace/libsinsp/test/filter_parser.ut.cpp
/kind feature
/area libsinsp
/area tests
This adds a new static method to `libsinsp::filter::parser` to return all the filtering operators supported by libsinp. This is meant to be the single source of truth for sinsp clients, so that we don't have to replicate this list anywhere else (like we did in Falco so far). On top of that, this also polishes the methods definitions of the filter parser and AST classes by using better C++ practices.
```release-note
update(userspace/libsinsp): improve filter AST and parser classes and interfaces
```
> update(userspace/libsinsp): improve filter AST and parser classes and interfaces

- userspace/libsinsp/filter.cpp
/kind cleanup
/kind feature
/area libsinsp
This PR adds the ARG_ALLOWED and ARG_REQUIRED flags in the filtercheck output info format, to expand to all fields the output that Falco has for filterchecks related to k8s_audit (e.g. IDX_ALLOWED, IDX_REQUIRED).
```release-note
chore(userspace/libsinsp): print field argument flags in filtercheck format
```
> chore(userspace/libsinsp): print field argument flags in filtercheck format

- cmake/modules/CompilerFlags.cmake
Set CMAKE_POSITION_INDEPENDENT_CODE in CompilerFlags.cmake. This fixes
/usr/bin/ld: libsinsp/libsinsp.a(logger.cpp.o): relocation R_X86_64_TPOFF32 against `_ZN12_GLOBAL__N_16s_tbufE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: libsinsp/libsinsp.a(sinsp.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTV15sinsp_exception' can not be used when making a shared object; recompile with -fPIC
when linking a PIC-enabled shared library with libsinsp here on Ubuntu.
> /kind bug
/kind cleanup
> /kind design
/area build
> /area …
> update(libsinsp): Enable position-independent code.

- userspace/libsinsp/examples/test.cpp
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
Following up on #271, this PR adds a `-j` option to `sinsp-example` that should make it a lot easier to write tests based on it, since any major language has the ability of parsing JSON directly without too much extra effort.
The issue itself didn't have a very big response, but I'm a firm believer of automating tests so I'm not letting it die too easy. Would love …
> feature(sinsp-example): Add JSON format output

- userspace/libscap/scap.c
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libscap
> /area tests
This is a very simple PR that adds the error reported by `scap_proc_scan_proc_dir` to the error message returned by the `scap_open_live_int` and `scap_open_nodriver_int` functions, adding extra information on why the call failed.
Fixes # …
> chore(libscap): Improve error message when procfs scan fails

- userspace/libsinsp/parsers.cpp
When a connect enter event comes from a driver that does not
report the connection tuple argument, reset the destination
address to zero. We know the old destination is no longer valid
but don't know the new one until the exit event arrives
so a buch of zeros is the best we can have.
Signed-off-by: Grzegorz Nosek <grzegorz.nosek@sysdig.com>
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
**Which issue(s) this PR …
> fix(libsinsp): Reset destination IP on old connect enter event

- userspace/libscap/scap.h
- userspace/libscap/scap_event.c
> /kind bug
> /kind design
/kind feature
> /area build
/area libscap
> /area tests
This PR adds a function to libscap to generate a scap event given the arguments. The event will be generated from userspace but doesn't come from any ringbuffer. This is necessary to allow syscall generators that do not use a ringbuffer such as the upcoming gvisor support.
Fixes # …
> new(libscap): add scap_event_encode_params()

- userspace/libsinsp/container_engine/docker/podman.cpp
- userspace/libsinsp/container_engine/docker/podman.h
As a part of looking at the event processing path and trying to speed
it up, I started looking for all reads below /proc that are inline
with event processing.
I noticed that the podman container engine does a read of
`/proc/<pid>/cgroup` for every new process (in a container or not) as a
part of detecting new containers. I think we can eliminate those opens
by first checking to see if any podman api socket exists. It is
possible to have podman containers without the api part, but the
podman engine needs the api socket to actually look up any container
info, so there's no point in validating anything unless the socket is
there.
So track and remember whether any default or user-specific socket
exists. If neither exists, simply skip resolving potential podman
containers.
Signed-off-by: Mark …
> Skip cgroup lookups in podman if no api socket

- userspace/libsinsp/tuples.cpp
The current implementation of the libs allows specifying naked ipv6 address in place of ipv6 net: like "FD80::" while prohibiting using of naked ipv4 in place of ipv4 net.
This PR prohibits such notation for ipv6 net in favor of explicitly specifying the prefix: "FD80::/64".
Providing that this PR will make IP vs NET consistent across both ipv4 and ipv6.
/kind cleanup
/area libsinsp
The current implementation of the libs allows specifying naked ipv6 address in place of ipv6 net: like "FD80::" while prohibiting using of naked ipv4 in place of ipv4 net.
This PR prohibits such notation for ipv6 net in favor of explicitly specifying the prefix: "FD80::/64".
Providing …
> disallow-ipv6net-without-prefix

- userspace/libscap/windows_hal.c
windows_hal.c requires netapi32.dll and iphlpapi.dll.
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libscap
> /area tests
This ensures that we link with required system libraries on Windows.
Fixes #
```release-note
NONE
```
> update(userspace/libscap): Add missing Windows libraries.

- userspace/libsinsp/sinsp.cpp
/kind bug
/area libsinsp
This PR fixes the boolean check inside `sinsp::is_initialstate_event()`. This currently causes capture mode to fail due to the `sinsp::consume_initialstate_events()` method consuming all the event blocks. This is also the reason why the CI integration tests fail in https://github.com/falcosecurity/falco/pull/1982 (see: https://circleci.com/gh/falcosecurity/falco/22719?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).  …
> fix(userspace/libsinsp): restore capture mode with proper checks in is_initialstate_event()

- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Fixes #
```release-note
NONE
```
> fix(userspace/libsinsp): always import users and groups from scap to retain backward compatibility with existent scap files for host users/groups

- userspace/libscap/scap_event.c
/kind bug
> /kind design
> /area build
/area libscap
> /area tests
Fixes #
The way this function was written it would skip over params with length 0. This is a mistake as empty buffers are perfectly valid and should be added as a parameter with length 0 to the scap event. …
> fix(libscap): fix empty buffer handling

- driver/bpf/filler_helpers.h
/kind bug
Today when we are not able to catch a parameter of type  `PT_CHARBUF`, `PT_FSPATH` or `PT_FSRELPATH` we discard the entire event, counting it as a `PPM_FAILURE_INVALID_USER_MEMORY`.  For example, on my machine, some `open_e` and `openat_e` events are discarded because the instrumentation cannot correctly get the `pathname`. IMHO this is a loss of useful information, we could send to userspace just a not-available (`<NA>`) param without discarding the entire event. Let me know what do you think about this idea :smile:  …
> fix(bpf): avoid to discard useful events

- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
as sinsp is not a singleton there are cases when multiple instances of sinsp with diff lifetimes exist. Currently, each instance of sinsp destructor will kill the DNS manager refresher thread and invalidate the DNS cache, this PR introduces the instance counter to prohibit unintended and premature DNS cache destruction. 
/kind bug
/area libsinsp
Fix DNS cache unintended clearing
Fix DNS cache unintended clearing
```release-note
fix: correct DNS cache unintended clearing
```
> do not clear dns cache until last sinsp instance

- userspace/libsinsp/event.cpp
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
The `std::vector::at` function is bound checked and it is much safer to use it instead of operator `[]`, which is not. I'd like to use this function, especially when we pass indexes around like in `sinsp_evt::get_param`.
Fixes #
```release-note …
```
> fix(libsinsp): use `at` instead of `operator []` for bound checking

- README.md
- userspace/libscap/examples/01-open/test.c
/kind feature
/area libscap
This PR adds some new features to the `scap-open` example:
* enable the `kernel_simple_consumer` logic
* capture only a limited number of events (maybe also `0` to test only the BPF verifier).
* print some information about what is happening during the execution.
```release-note
NONE
```
> update(libscap): introduce new options in `scap-open` example

- driver/bpf/fillers.h
/kind bug
Loading our BPF probe on **5.11.0-1022-aws 20.04.1-Ubuntu aarch64 GNU/Linux** I faced the following verifier issue:
```
311: (bf) r2 = r6
312: (07) r2 += 16
313: (79) r5 = *(u64 *)(r2 +0)
dereference of modified ctx ptr R2 off=16 disallowed
processed 8486 insns (limit 1000000) max_states_per_insn 5 total_states 151 peak_states 143 mark_read 13
-- END PROG LOAD LOG --
libscap: bpf_load_program() err=13 event=filler/sys_autofill
```
I used `clang-13` as a compiler.
In a nutshell, the problem is that for some reason clang tries to modify the `ctx` ptr, saved in `R2` when we access the …
> fix(driver-ebpf): fix a verifier issue in `sys_autofill` filler

- userspace/libscap/scap_bpf.c
/kind bug
/area libscap
When we load a BPF program we pass also a tmp buffer to collect the verifier logs in case of failure. If the size of the buffer is not large enough to store all verifier messages, `-1` is returned and `errno` is set to `ENOSPC`.  This is what happens on my machine (**5.11.0-1022-aws 20.04.1-Ubuntu aarch64 GNU/Linux**): 
```
bpf_load_program() err=28 event=filler/sys_autofill message=0
```
Where `28` is exactly `ENOSPC`.
This PR aligns the log buffer size to the one used by `libbpf` library, avoiding this problem. Moreover, I tried to improve our debug prints in case …
> fix(libscap): increase the BPF verifier's log buffer size

- userspace/libsinsp/plugin.cpp
/kind cleanup
/area libsinsp
This PR fixes `plugin.cpp` to avoid using a designated initializer, which unnecessarily increased the C++ standard of the project up to C++20.
```release-note
fix(userspace/libsinsp): remove usage of designated initializer
```
> fix(userspace/libsinsp): remove usage of designated initializer

- driver/main.c
struct event_filler_arguments has a .is_socketcall member for
compatibility with those architectures having a single syscall
for all socket functions (bind, connect...).
When the architecture does NOT _HAS_SOCKETCALL though (e.g. arm64),
this field takes the value from whatever happens to be in the stack
(so likely non-zero), leading to fillers assuming it IS a socketcall
-- where in reality it is not -- and therefore exposing bogus
argument values.
The issue can be triggered by running the following on ARM:
```
telnet 127.0.0.1 8080
```
which results in sysdig reporting something like:
```
1187851 20:45:11.730173066 3 bash (1999317) > connect fd=1368509440 addr=NULL
```
Initialize the whole structure to all-zeroes so to have deterministic
behavior.
> …
> fix(driver): initialize event_filler_arguments to fix is_socketcall on aarch64

- driver/bpf/fillers.h
/kind bug
Fixes a verifier error on some kernels due to passing of `"<NA>"` marker directly to bpf helpers. The verifier error I've seen is somewhat confusing: `filler/sys_open_by_handle_at_x message=fd 0 is not pointing to valid bpf_map`
By putting the marker into a stack variable and then passing that through to the helper, the verifier is happy with the program. This matches other uses of the marker throughout the other filler programs.
Fixes #
```release-note
NONE
```
> fix(driver-ebpf): fixes verifier error for sys_open_by_handle_at

- userspace/libscap/engine/gvisor/CMakeLists.txt
/kind bug
> /kind design
> /area build
/area libscap
> /area tests
In some cmake versions trying to include protobuf without a guard on bundled libs might generate the following warning:
```
CMake Warning (dev) at userspace/libscap/engine/gvisor/CMakeLists.txt:13 (add_dependencies):
Policy CMP0046 is not set: Error on non-existent dependency in
add_dependencies.  Run "cmake --help-policy …
```
> fix(libscap/engine/gvisor): fix cmake without USE_BUNDLED_DEPS

- userspace/libsinsp/filter/parser.cpp
- userspace/libsinsp/filter/parser.h
- userspace/libsinsp/test/filter_compiler.ut.cpp
- userspace/libsinsp/test/filter_parser.ut.cpp
/kind feature
/area libsinsp
/area tests
This updates the filter parser inside libsinsp to accept cases where embedded expressions (starting with `(`) follow a boolean operator (`and`, `or`, `not`) without leaving a whitespace. The parser is currently very strict and always requires a whitespace after boolean operators, but that's an unnecessary constraint towards the non-ambiguity of the parsing language.
With this, filters such as `evt.num > 0 and(proc.name = 'cat')` are correctly parsed and accepted. 
```release-note …
```
> refactor(userspace/libsinsp): update filter parser and grammar to accept embedded expressions after boolean operators

- userspace/libscap/userspace_flag_helpers.h
/kind bug
> /kind design
/area build
/area libscap
> /area tests
This PR aims to fix the following build errors, with musl for alpine:
```
/build-static/release/falcosecurity-libs-repo/falcosecurity-libs-prefix/src/falcosecurity-libs/userspace/libscap/../../driver/ppm_flag_helpers.h:1279:14: error: 'LOCK_EX' was not declared in this scope
1279 |  if (flags & LOCK_EX)
| …
```
> fix(libscap): add defines in userspace_flags_helpers.h for alpine-musl/centos7 builds that don't have them

- README.md
- userspace/libscap/CMakeLists.txt
- userspace/libscap/test/CMakeLists.txt
> /kind bug
> /kind design
/kind feature
/area build
> /area tests
Currently, libscap includes library functions useful for gVisor message ingestion by default that depend on libraries that might take a long time to compile such as protobuf (which is also required by libsinsp). For some use cases, it is not necessary to build this support, for example when only a lightweight version of libscap is necessary that only interfaces with …
> update(build): allow gvisor compilation toggle -DBUILD_LIBSCAP_GVISOR

- userspace/libsinsp/filter.cpp
Signed-off-by: vadim.zyarko <vadim.zyarko@sysdig.com>
/kind feature
/area libsinsp
the change is to allow enough support for PT_INET param types so they can be serialized as strings. In debug builds, this results in a false assertion as it drops to the end of the switch in sinsp_filter_check::rawval_to_{json,string}
```release-note
update: added formatting support for PT_IPNET
```
> filters optimizer PT_IPNET

- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
/kind feature
/area libsinsp
the change adds a method to print a container's arguments as a string when debug prints filters
```release-note
chore(libsinsp): method to print a container's arguments as a string when debug prints filters
```
> filtercheck-container args string

- userspace/libsinsp/filter.h
This header file had a bunch of bare references to stl classes without
a std:: prefix. Until recently, some other header file must have had a
"using namespace std" that allowed this to compile. Bad practice to
put using namespace in header files, but it masked this problem.
Looks like the "using namespace" has been cleaned up, which causes a
compile error for some toolchains, at least.
Fix this by adding std:: to any stl classes.
Also include <string> as this header file uses std::string.
/kind bug
> /kind design
> Uncomment one (or more) …
> Add std:: namespace to stl classes, add string include

- userspace/libsinsp/filter.cpp
No filterchecks have PT_FD params, but it's possible to have an
evt.arg.fd param for many syscalls and that could be printed in output
fields.
It's a 64 bit int so just add it to the sections that work with that
underlying type.
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Fixes #
**Does this …
> Support PT_FD param types when converting to json/string

- cmake/modules/curl.cmake
/kind bug
> /kind design
/area build
/area libscap
/area libsinsp
> /area tests
Bump the libcurl version to 7.83.1. This includes the latest features, performance fixes and fixes for the following vulnerabliities:
* CVE-2018-1000007
* CVE-2022-27776
* CVE-2021-22898
* CVE-2021-22925
* CVE-2021-22924
* CVE-2021-22926
* CVE-2021-22923
* CVE-2021-22922
* CVE-2021-22945
* CVE-2021-22946
* CVE-2021-22947
* …
> update(cmake): Update libcurl to 7.83.1

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filter.h
- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/filter_op_bcontains.ut.cpp
/kind bug
/area libsinsp
This PR brings 3 contributions:
1. Fix a regression in filterchecks involving fields of type PT_BYTEBUF. After the recent refactorings of #201, the length of the right-hand bytebuf values was not passed-down in `sinsp_filter_check::compare`, which inherently ended up making all checks on bytebufs return true due to a `memcmp` being performed with length = 0.
2. Optimizes the performance of `bcontains` and `bstartswith` operators. Previously, the operator performed the hexstr <->  bytebuf conversion at each check, which is not performant and should instead be done at initialization time. Now, the hex string is converted to a bytebuf right at …
> fix(userspace/libsinsp): fix checks on PT_BYTEBUF fields and optimize bcontains/bstartswith

- userspace/libscap/CMakeLists.txt
- userspace/libscap/scap-int.h
- userspace/libscap/scap_bpf.c
/kind feature
/area libscap
This is a very small change that makes BPF_PROGS_MAX configurable at compile time. I'm currently building a custom probe that works with Falco (as outlined in #267 ) and it has more programs than libscap can currently work with. This change will allow me to define a larger limit.
As an aside, accesses to the various arrays that use BPF_PROGS_MAX as their size are not bounds-checked and whilst I have not added these checks here they might also make sense for a bit more robustness in the libs. (I am happy to add them if desired!) 
Fixes # …
> update(userspace/libscap): Makes BPF_PROGS_MAX configurable at compile time

- driver/bpf/filler_helpers.h
Co-authored-by: Jie Lin <jie.lin.fj@gmail.com>
/kind bug
First of all, I would thank @jie-lin for having spotted the following bug. This PR replace the #342  that now could be closed.
When a syscall has to manage a parameter of type `PT_BYTEBUF` that is already pushed on frame (`curarg_already_on_frame`) it usually calls the `__bpf_val_to_ring` function in this way: 
```     
data->curarg_already_on_frame = true;
res = __bpf_val_to_ring(data, 0, len, PT_BYTEBUF, -1, false);
```
The second parameter is `val`, so here `val=0`. If we check the `__bpf_val_to_ring` function we can notice that: …
> fix(driver/bpf): catch pushed on frame data when `val=0`

- cmake/modules/CompilerFlags.cmake
- userspace/libscap/CMakeLists.txt
- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/user.cpp
/kind bug
/area build
/area libsinsp
While testing the latest libs version on Falco, we noticed that user names were not correctly looked up. Digging into the problem, we discovered that a feature gate :point_down: was off when building Falco
https://github.com/falcosecurity/libs/blob/bd94f3189774e5298dd383bf913da7b3b620a94a/userspace/libsinsp/user.cpp#L151-L163
After a further investigation, we realized the root problem was that the `add_definition` was included in [CompilerFlags.cmake](https://github.com/falcosecurity/libs/blob/master/cmake/modules/CompilerFlags.cmake), which is not used by client projects (like Falco).
This PR moves relevant compiler definitions …
> fix: move definitions to inner CMakeLists.txt(s) and correct add_user/add_group

- userspace/libsinsp/filter/parser.cpp
- userspace/libsinsp/filter/parser.h
- userspace/libsinsp/test/filter_parser.ut.cpp
/kind bug
/kind feature
/area libsinsp
/area tests
This PR fixes the bug firstly reported by @dnwe in https://github.com/falcosecurity/falco/issues/2028 (thank you so much for spotting this! 🙏🏼 ). The parser incorrectly processed the `not` operator token, preventing macros/identifiers starting with `not` from being properly parsed. On top of that, this PR also fixes and unifies the parser position info updating logic, which now is more consistent and works across multiple line breaks. Unit tests have been updated accordingly.
Fixes https://github.com/falcosecurity/falco/issues/2028
**Does this …
> fix(userspace/libsinsp): solve filter parser 'not' and position ambiguities

- userspace/libsinsp/container_engine/bpm.cpp
- userspace/libsinsp/container_engine/libvirt_lxc.cpp
- userspace/libsinsp/container_engine/lxc.cpp
- userspace/libsinsp/container_engine/mesos.cpp
- userspace/libsinsp/container_engine/rkt.cpp
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
This PR addresses a behavioral change that happened in https://github.com/falcosecurity/libs/pull/231 : before, synchronous container engines were seeing their containers immediately stored in the list, therefore their info was suddenly available.
After, everything was async, pushing a container event and awaiting for the parser logic to add the new container.
This …
> fix(userspace/libsinsp): immediately add synchronously spotted containers to list of containers

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filterchecks.h
/kind cleanup
/area libsinsp
This should reduce the memory allocations when comparing filter checks.
```release-note
NONE
```
> fix(userspace/libsinsp): reduce mem allocs for filter comparisons

- userspace/libsinsp/plugin_filtercheck.cpp
- userspace/libsinsp/plugin_filtercheck.h
/kind cleanup
/area libsinsp
This PR avoids an unnecessary string copy when performing field extraction in plugins. As per documentation, plugins are responsible of owning the memory returned during extraction, so it is unnecessary to store it internally in the filtercheck.
```release-note
NONE
```
> fix(userspace/libsinsp): avoid string copy in plugin extraction

- driver/syscall_table.c
Signed-off-by: Sumit Dubey <sumit.dubey2@ibm.com>
/kind bug
> /kind design
> /area build
> /area tests
Both the socket family system calls, and …
> fix(driver): Remove __NR_socketcall check

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filter.h
- userspace/libsinsp/gen_filter.cpp
- userspace/libsinsp/gen_filter.h
/kind cleanup
/area libsinsp
Since merging https://github.com/falcosecurity/falco/pull/2017, the `set_check_id` and `get_check_id` methods are not required in events anymore. The check id was an historically instrumental for Falco to figure out _which_ rule and filtercheck matched a given event. This is now not used anymore because the rule-event matching is a responsiblity of the Falco Engine exclusively. Removing this also saves the cost of many memory writes at each filtercheck evaluation. …
> refactor(userspace/libsinsp): remove unused check_id from events

- driver/ppm_fillers.c
/kind bug
Fix driver build for kernel versions with old `io_uring_params` struct, lacking `features` attribute.
Fixes #
```release-note
fix(driver): io_uring_params features attribute
```
> fix(driver): io_uring_params features attribute

- userspace/libscap/scap.c
/kind bug
> /kind design
> /area build
/area libscap
> /area tests
It looks like the vtable function `free_handle` exists …
> fix(libscap): call vtable->free_handle at shutdown

- userspace/libsinsp/CMakeLists.txt
/kind bug
/area build
`HAVE_PWD_H` and `HAVE_GRP_H` represent feature gates in libsinsp, which are expected to be compiled in any non-windows system. However, those definitions are added depending on the presence of an include file using CMake, which seems to be non-totally predictable in all systems. In case this section is now compiled, libsinsp fails to consistently fetch user data and extract fields such as `user.name`.
```release-note
NONE
```
> fix(userspace/libsinsp): define HAVE_PWD_H and HAVE_GRP_H on every non-windows system

- userspace/libscap/test/CMakeLists.txt
Move CMAKE_THREAD_LIBS_INIT (e.g. the library found by the
find_package(Threads)) to after gtest so the unresolved pthread
symbols in gtest will be picked up.
The current version builds with the toolchain used by CI, but for
other toolchains, the difference matters.
/kind bug
> /kind design
> /area build
> /area …
> Move CMAKE_THREAD_LIBS_INIT to after gtest when linking

- cmake/modules/CompilerFlags.cmake
- userspace/chisel/chisel_fields_info.cpp
- userspace/common/types.h
- userspace/libscap/scap_fds.c
- userspace/libsinsp/event.cpp
- userspace/libsinsp/fdinfo.cpp
- userspace/libsinsp/plugin.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/version.h
/kind bug
/kind cleanup
/area build
/area libscap
/area libsinsp
This PR fixes the compilation issues reported in #346 by implementing the approach suggested by @FedeDP. Instead of defining `__STDC_FORMAT_MACROS` in many parts of the codebase, it is now defined as a compiler flag within CMake for non-windows builds.
Fixes #346
```release-note
NONE
```
> fix(build): make codebase more robust to __STDC_FORMAT_MACROS definitions

- userspace/libscap/examples/02-validatebuffer/test.c
- userspace/libscap/scap.c
- userspace/libscap/scap.def
- userspace/libscap/scap.h
- userspace/libscap/scap_engine_util.c
/kind bug
/kind cleanup
/area libscap
This solves 3 important issues:
* fix: if we don't initialize the `scap_open_args` at the beginning of  `scap_open_live_int()` we risk to use junk data. For example, I've spotted a bug due to the `udig` bool inside `scap_open_args`. If we don't set it to `false` at the beginning it could cause issues [here](https://github.com/falcosecurity/libs/blob/b3588963c3ed1a412028e69354ab1e322ab6cf16/userspace/libscap/engine/bpf/scap_bpf.c#L127) so the probe won't be correctly loaded.
* fix: check that `ppm_sc_of_interest` is not a NULL pointer when passed to `scap_open_live_int`. This causes problem when we use the `scap_open_live` …
> fix(libscap): bpf probe was not correctly loaded

- userspace/libscap/engine/source_plugin/source_plugin.c
- userspace/libscap/engine/source_plugin/source_plugin.h
/kind feature
/area libscap-engine-source-plugin
This enabled support for scap stats in the plugin use case. Although most syscall-related stats are not useful in the case of plugins, the total number of events is still a valuable metric.
```release-note
update(userspace/libscap): support scaps stats in source plugin engine
```
> update(userspace/libscap): support scaps stats in source plugin engine

- userspace/libscap/CMakeLists.txt
- userspace/libscap/macos/barrier.h
- userspace/libscap/macos/gettimeofday.h
- userspace/libscap/macos/sleep.h
Copy userspace/libscap/linux to userspace/libscap/macos.
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libscap
> /area tests
**What this PR does / why we …
> update(libscap): Add a macOS platform directory.

- userspace/libscap/engine/gvisor/gvisor.cpp
- userspace/libscap/engine/gvisor/gvisor.h
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libscap/scap_procs.c
- userspace/libscap/scap_vtable.h
- userspace/libsinsp/sinsp.cpp
/kind feature
/area libscap
This PR introduces the ability for a scap engine to provide functions to scan processes in the system. In addition, a placeholder implementation is added to gvisor to show how to use this API.
*Rationale for the API naming and functionality*
In general, we want to replicate the `/proc` scan functionality usually found in scap but in a generic way via vtables.
The API I implemented involves having two functions, `get_threadinfos()` and `get_fdinfos()` to retrieve thread information for all threads and fd information for a single one respectively. However, there are several possible alternative approaches. To …
> new(libscap): add /proc scan vtable functions, wire them to gvisor implementation

- userspace/libscap/engine/gvisor/CMakeLists.txt
- userspace/libscap/engine/gvisor/gvisor.cpp
- userspace/libscap/engine/gvisor/gvisor.h
- userspace/libscap/engine/gvisor/parsers.cpp
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libscap/scap.c
- userspace/libscap/scap_open.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area tests
This PR introduces the code used to set up new trace sessions for gVisor sandboxes. It does so by …
> new(libscap): gVisor sandboxes trace session set up with runsc 

- driver/syscall_table.c
/kind bug
/kind cleanup
This PR defines entries in our tables only when the syscall number is defined in that architecture. More precisely, this pull request fixes the bug on `riscv64` highlighted by @dkogan here :point_right:  https://github.com/falcosecurity/libs/issues/399
The changes proposed are just an extension of the patch suggested by @dkogan.
Please note: I would love to have the conditional compilation around every single syscall in our tables, right now I just addressed the `rename` family.
Fixes #399 
**Does this PR …
> fix(driver): check `rename` family syscalls are defined

- userspace/libscap/engine/gvisor/parsers.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area tests
Change UNIX socket path copying in the gvisor …
> fix(gvisor): use strlcpy to copy unix path strings

- CMakeLists.txt
- cmake/modules/GetGitRevisionDescription.cmake
- cmake/modules/GetGitRevisionDescription.cmake.in
Signed-off-by: Andrea Bonanno <andrea@bonanno.cloud>
/kind feature
/area build
Currently, FALCOSECURITY_LIBS_VERSION defaults to a "fake" version.
Considering the possibility to start applying versioning to libs, this features automatically populate FALCOSECURITY_LIBS_VERSION based on the checked-out git ref (commit or tag).
Fixes #139 
This feature leverages on the sam the [same cmake modules ](https://github.com/falcosecurity/falco/blob/master/cmake/modules/GetFalcoVersion.cmake) already used for Falco.
Test has been run via the creation of git tags on a local repo, and the script correctly …
> new(build): sets FALCOSECURITY_LIBS_VERSION on the checked-out git ref

- userspace/libscap/engine/gvisor/CMakeLists.txt
/kind bug
> /kind design
/area build
> /area tests
While developing Falco and changing libs versions you …
> fix(gvisor): add DEPENDS to proto generation command

- CMakeLists.txt
- README.md
- cmake/modules/versions.cmake
- userspace/libscap/CMakeLists.txt
/kind feature
/area build
This PR follows up #405 and #196 to implement the new versioning schemes as per [this proposal](https://github.com/falcosecurity/libs/blob/master/proposals/20220203-versioning-schema-amendment.md).
Fixes #
```release-note
build: libs and driver now use two different numbering scheme
build: `FALCOSECURITY_LIBS_VERSION` and `DRIVER_VERSION` are now automatically computed using git information
```
> build: versioning system

- userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
Clients of Falco libs will need to know if gvisor is …
> new(libsinsp): add is_gvisor()

- userspace/libscap/engine/gvisor/CMakeLists.txt
- userspace/libscap/engine/gvisor/gvisor.h
- userspace/libscap/engine/gvisor/parsers.cpp
- userspace/libscap/engine/gvisor/runsc.cpp
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libscap/test/scap_gvisor_parsers.ut.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area tests
This PR introduces support for retrieving and parsing procfs state information from gVisor. 
It …
> new(gvisor): retrieve procfs state from gvisor

- cmake/modules/openssl.cmake
> /kind bug
> /kind design
/area build
/area libsinsp
> /area tests
Update OpenSSL to the latest 1.1.1 patch released on …
> update(build): upgrade OpenSSL to 1.1.1p

- userspace/libsinsp/sinsp.cpp
/kind bug
/area libsinsp
Been playing around with [this repo](https://github.com/Molter73/falco-libs-qa) and was getting a segfault with the following backtrace:
```
#0  0x00007ffff6aa5bba in __strlen_sse2 () from /lib64/libc.so.6
#1  0x00000000007fae4f in std::char_traits<char>::length (__s=0x656d616e2e6466 <error: Cannot access memory at address 0x656d616e2e6466>)
at /usr/include/c++/12/bits/char_traits.h:395
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__a=...,
__s=0x656d616e2e6466 <error: Cannot access memory at address 0x656d616e2e6466>, this=0x7fffffffd500)
at …
```
> fix(gvisor): initialize missing variables

- userspace/libsinsp/async/async_key_value_source.h
- userspace/libsinsp/async/async_key_value_source.tpp
- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/async_key_value_source.ut.cpp
/kind bug
> /kind design
> /area build
/area libsinsp
/area tests
Add unit tests for async_key_value_source, along with some potential race conditions on startup found …
> Add async key value unit tests

- CMakeLists.txt
- driver/CMakeLists.txt
- userspace/libscap/CMakeLists.txt
> /kind bug
/kind cleanup
/kind design
/kind feature
/area build
/area libscap
> /area tests
This is mainly required to allow Falco to include different versions of libs and drivers. Falco can now …
> build: reorganize driver cmake vars

- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/gvisor_config.cpp
- userspace/libsinsp/gvisor_config.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
For the gVisor support, we need to be able to generate a configuration file on the fly, containing …
> update(libsinsp): add a way to generate gVisor trace session config file

- userspace/libsinsp/container.cpp
PR#231 caused a regression with container metadata:
When a container engine reported a failure *after* we have already
received the full metadata from a different engine, the call
to add_container for the failed lookup overwrote the metadata
coming from the good lookup.
Note: this brings the code into agreement with the comment
that says we should follow the same logic as parsing container
JSON events.
Note: based on code inspection, the issue was supposed to happen
only while the inspector isn't fully initialized, but we've observed
it also while the event loop was up and running.
/kind bug
> /kind design
**Any specific area of the project …
> fix(libsinsp): Don't overwrite good container metadata with bad

- driver/main.c
/kind bug
> /kind design
> /area build
> /area tests
Linux 5.18 in …
> fix(driver): fixed kmod build on linux kernels >= 5.18.

- driver/ppm_fillers.c
- driver/ppm_fillers.h
/kind bug
If we are on a `64-bit` architecture we need to enable the `_64BIT_ARGS_SINGLE_REGISTER` macro and this is done correctly in our drivers. The problem is that when we compile `scap` we enable this define only in `x86`
```c
#ifdef __x86_64__
#define _64BIT_ARGS_SINGLE_REGISTER
#endif /* __x86_64__ */
```
So on ARM64, when we fill the filler table in the libscap bpf engine we use the wrong fillers for some syscalls:
```c
#ifdef _64BIT_ARGS_SINGLE_REGISTER
[PPME_SYSCALL_PREAD_E] = {FILLER_REF(sys_autofill), 3, APT_REG, {{0}, {2}, {3} } },
#else …
```
> fix(scap_engine_bpf): enable `_64BIT_ARGS_SINGLE_REGISTER` on ARM64

- userspace/libscap/engine/gvisor/gvisor.h
- userspace/libscap/engine/gvisor/parsers.cpp
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area tests
This PR adds parsing implementation for …
> update(gvisor): implement parsing for procfs regular files

- userspace/libscap/engine/gvisor/gvisor.cpp
- userspace/libscap/engine/gvisor/gvisor.h
- userspace/libscap/engine/gvisor/parsers.cpp
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libscap/scap.c
- userspace/libscap/scap_open.h
- userspace/libscap/test/scap_gvisor_parsers.ut.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
/kind bug
> /kind design
/kind feature
> /area build
/area libscap
> /area tests
This PR adds some enhancements to gVisor support:
1. small change to the interface to be able to read …
> new(gvisor): get socket from configuration file, fix tests

- driver/ppm_flag_helpers.h
- userspace/libscap/engine/gvisor/parsers.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libscap
> /area tests
We'll need to add a few more syscalls in gvisor. Using numbers when necessary can lead to unnecessary …
> cleanup(gvisor): use SYS_ macros instead of syscall numbers

- cmake/modules/curl.cmake
> /kind bug
/kind cleanup
> /kind design
/area build
/area libsinsp
> /area tests
Upgrade libcurl to 7.84.0, released on Jun 27th 2022, …
> update(build): upgrade libcurl to 7.84.0

- driver/bpf/Makefile
- driver/bpf/filler_helpers.h
- driver/bpf/fillers.h
- driver/bpf/plumbing_helpers.h
- driver/bpf/probe.c
- driver/bpf/quirks.h
- driver/bpf/types.h
- driver/fillers_table.c
- driver/main.c
- driver/ppm_events.h
- driver/ppm_events_public.h
- driver/ppm_fillers.c
- driver/ppm_fillers.h
- userspace/libscap/engine/bpf/bpf.h
- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/scap-int.h
/kind bug
/kind feature
This PR wants to fix a known problem regarding `ARM64` architecture, described here in this [thread](https://www.spinics.net/lists/linux-trace/msg01001.html) of the kernel mailing list. In a nutshell the `exeve` exit event is not traced by the `syscalls:sys_exit` tracepoint and same thing for the `clone` child exit event. These 2 events are really important for the state of the so we implemented this workaround to catch this 2 missing events.  We have instrumented 2 new tracepoints:
*  [`sched_proc_exec`](https://github.com/torvalds/linux/commit/4ff16c25e2cc48cbe6956e356c38a25ac063a6 …
> Support `execve` exit events and `clone` child exit events on `ARM64`

- userspace/libscap/engine/gvisor/config.json
- userspace/libscap/engine/gvisor/parsers.cpp
- userspace/libscap/engine/gvisor/parsers.h
- userspace/libscap/engine/gvisor/proto/pkg/sentry/seccheck/points/common.proto
- userspace/libscap/engine/gvisor/proto/pkg/sentry/seccheck/points/sentry.proto
- userspace/libscap/engine/gvisor/proto/pkg/sentry/seccheck/points/syscall.proto
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libsinsp/gvisor_config.cpp
> /kind bug
> /kind design
> /area tests
This PR adds support for the syscalls added in https://github.com/google/gvisor/commit/45b06bbb763662579dcc35b9d70f56ce85cf3370 .
Also present the following refactors:
* network "one sided tuple" …
> new(gvisor): add new syscalls (update to gvisor 45b06bbb)

- userspace/libsinsp/sinsp.cpp
```
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>
```
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
The k8s client used `extensions/v1beta1` as api …
> fix(libsinsp/k8s): set api url path to "apps/v1"

- driver/bpf/fillers.h
/kind bug
This PR fixes a compilation issue on RHEL8 machine `4.18.0-193.75.1.el8_2.x86_64`. This `ifdef` is already used in the kernel module corresponding helper... we need to introduce it also here
```release-note
NONE
```
> fix(bpf): fix compilation issue on `4.18.0-193.75.1.el8_2.x86_64`

- userspace/libscap/scap.c
/kind bug
/area libscap
Errors regarding driver API checks and capture starting were not properly propagated due to the recent vtable-related refactoring.
```release-note
NONE
```
> fix(userspace/libscap): propagate scap open errors

- userspace/libsinsp/filterchecks.cpp
/kind bug
/area libsinsp
> /area tests
Fixes #
```release-note
fix(userspace/libsinsp): do not crash in TYPE_RESSTR filtercheck when EF_CREATES_FD event has no fd param
```
> fix(userspace/libsinsp): avoid crashing in TYPE_RESSTR when an EF_CREATES_FD event has no "fd" param

- userspace/libscap/engine/gvisor/gvisor.h
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
/kind bug
> /kind design
> /area build
> /area tests
This PR attempts to fix a use-after-free …
> fix(gvisor): fix epoll use-after-free

- userspace/libscap/engine/gvisor/gvisor.cpp
- userspace/libscap/engine/gvisor/gvisor.h
- userspace/libscap/engine/gvisor/parsers.cpp
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area tests
This PR implements the `get_stats` vtable …
> update(gvisor): implement get_stats for gVisor

- userspace/libsinsp/fdinfo.cpp
- userspace/libsinsp/fdinfo.h
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/utils.h
/kind feature
/area libsinsp
Add new filter / display fields 
```
fd.nameraw
proc.cmdnargs
proc.cmdlenargs
proc.pvpid
```
Why are new fields needed:
- `fd.nameraw` - Enables detections of Arbitrary File Reads using Directory Traversal Technique as file path is not normalized (e.g. `fd.name` like `/etc/passwd` vs `fd.nameraw` like `../../../../../.././etc/passwd`). However, for robustness duplicate `/` separators are removed as the OS ignores them when interpreting file paths.
- `proc.cmdnargs` - Number of cmd args - useful for behavioral / statistical filtering of cmds.
- `proc.cmdlenargs` - Length of all …
> new(userspace/libsinsp): extend filter/display fields

- driver/ppm_fillers.c
/kind bug
`inode_owner_or_capable` is only present since 2.6.39 onwards.
Fixes #
```release-note
fix(driver): fixed build of kmod on ancient < 2.6.39 kernels
```
> fix(driver): fixed build of kmod on ancient < 2.6.39 kernels.

- cmake/modules/libscap.cmake
Signed-off-by: Teryl <terylt@ibm.com>
/kind bug
/area build
/area libscap
The scap library was recently broken out into 10 separate libs, but they were not added to the installation script in cmake.  All 10 libraries are needed to build consumer applications.
It installs all 10 libraries.
```release-note
added scap engine related libs to install
```
> fix(install): install the 10 libscap related libraries

- driver/bpf/fillers.h
/kind bug
/area build
The config flag is either CONFIG_AUDITSYSCALL for kernels < 5.1.0, or CONFIG_AUDIT for newer ones.
See https://github.com/torvalds/linux/blob/master/include/linux/sched.h#L1104.
I caught this build issue while testing an archlinux builder for driverkit using a cross-build to arm through qemu, building kernel 4.17.0.
Possibly, the archlinux arm folks did not enable those flags in their kernel configs.
Fixes #
```release-note
NONE
```
> fix(driver/bpf): accessing loginuid depends upon a config flag in the kernel

- CMakeLists.txt
/kind bug
/area build
When we compile with `cmake -DCREATE_TEST_TARGETS=ON` the `gtest.cmake` search for local gtest lib if we use not bundled deps, the problem is that the bundled dep option is not defined in the root `CMakeLists.txt` causing:
```
CMake Error at cmake/modules/gtest.cmake:12 (message):
Couldn't find system gtest
Call Stack (most recent call first):
CMakeLists.txt:91 (include)
```
```release-note
NONE
```
> chore: fix gtest fatal error

- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/kmod/scap_kmod.c
- userspace/libscap/ringbuffer/devset.c
- userspace/libscap/ringbuffer/devset.h
/kind cleanup
/area libscap
This PR might be a little overkill, it started because of a very minor leak [here](https://github.com/falcosecurity/libs/blob/c2b89c1f715b660586a316e17d0f2dd9fc47ffea/userspace/libscap/engine/bpf/scap_bpf.c#L1282-L1300), `devset->m_devs` is not being free'd. I could've added the missing `free`, but instead chose to refactor `free`ing of `devsets` into its own function. This lead me to a few unhappy implementation choices, since we need the sizes of each `m_buffer` and `m_bufinfo`, I'm open to hearing alternatives for this.
If maintainers deem the PR as too much overkill, I'm happy to close it and open a new one adding the missing free …
> Refactor freeing of devices in scap

- userspace/libscap/engine/kmod/scap_kmod.c
/kind bug
> /kind design
> /area build
> /area tests
I was experiencing a …
> fix(libscap): fix call to ioctl when getting proclist

- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/examples/01-open/scap_open.c
- userspace/libscap/scap_open.h
/kind bug
/kind cleanup
/area libscap
This fixes two warnings that prevented libscap from compiling when warnings are considered as errors.
```
scap.c:926:2: error: enumeration value ‘SCAP_MODE_MODERN_BPF’ not handled in switch [-Werror=switch]
926 |  switch(args.mode)
|  ^~~~~~
```
```
scap_bpf.c:1563:51: error: pointer targets in passing argument 3 of ‘perf_event_mmap’ differ in signedness [-Werror=pointer-sign]
1563 |   dev->m_buffer = perf_event_mmap(handle, pmu_fd, &dev->m_buffer_size);
|                                                   ^~~~~~~~~~~~~~~~~~~
|                                                   |
| …
```
> fix(userspace/libscap): solve compilation warnings and errors

- README.md
> /kind bug
> /kind design
> /area build
> /area tests
Swap order of eBPF warning about clang7 …
> docs: fix order of eBPF warning and gVisor paragraph

- userspace/libscap/scap.h
/area libscap
/area libsinsp
/kind feature
This is change 1 of 3 (1 of 2 for this repository) for adding a new scap
return code for userspace filtering.
Currently, when libscap (or libsinsp) chooses to filter an event in
userspace, the libraries return SCAP_TIMEOUT. The intent behind this
decision is to force the client to retry (which is the behavior for
SCAP_TIMEOUT). However, SCAP_TIMEOUT implies that there are no events in
the pipeline, which is not true for the filter case and may lead to
client behavior that is not ideal.
Step 1: Add a new (unused) return code for filtered events (we are here)
Step 2: Handle the new return value in client code
Step 3: libsinsp / libscap begin returning the new code
Signed-off-by: Nathan Baker <nathanb@vt.edu> …
> feat: Add new return code for filtered events(1/3)

- userspace/libsinsp/async/async_key_value_source.h
- userspace/libsinsp/async/async_key_value_source.tpp
- userspace/libsinsp/container.cpp
- userspace/libsinsp/container.h
- userspace/libsinsp/container_engine/container_async_source.h
- userspace/libsinsp/container_engine/container_async_source.tpp
- userspace/libsinsp/container_engine/container_cache_interface.h
- userspace/libsinsp/container_engine/cri.cpp
- userspace/libsinsp/container_engine/cri.h
- userspace/libsinsp/container_engine/docker/async_source.cpp
- userspace/libsinsp/container_engine/docker/async_source.h
- userspace/libsinsp/container_engine/docker/base.cpp
- userspace/libsinsp/container_engine/docker/docker_linux.cpp
- userspace/libsinsp/container_info.h
- userspace/libsinsp/ifinfo.cpp
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
/kind bug
/kind feature
/area libsinsp
In Docker and in CRI-O (when started with `cri_timeout` 0 or with `async` false) it happens to have the lookup without any metadata for some containers (e.g. OWASP Juice Shop):
```
Debug, cri (fa94c3cc2006): Performing lookup
Debug, cri (fa94c3cc2006): Status from ContainerStatus: (could not find container "fa94c3cc2006": specified container fa94c3cc20063363a52ece696999e974d7472d4c76395ca5f19f55c883c8080a is not yet created)
Debug, cri (fa94c3cc2006): id is neither a container nor a pod sandbox
Debug, cri_async (fa94c3cc2006): Failed to get CRI metadata, returning successful=false
Debug, cri_async (fa94c3cc2006): Source …
```
> Lookup retry on asynchronous container engines

- .github/workflows/ci.yml
/kind feature
/area build
This PR adds GitHub actions workflow to test the modern BPF probe. More precisely:
* `build-modern-bpf-x86`:  compile the `scap-open` example e tries to inject the modern probe looking for verifier issues
* `test-modern-bpf-x86`: run the `gtest` framework (introduced here https://github.com/falcosecurity/libs/pull/484) looking for failing tests.
* `build-modern-bpf-arm64`: compile the `scap-open` example on ARM64 looking for compilation issues. Unfortunately, we are not able to inject the probe using QEMU, and GH doesn't …
> new(CI): add GH actions for modern BPF probe

- README.md
- driver/CMakeLists.txt
- driver/bpf/filler_helpers.h
- driver/bpf/plumbing_helpers.h
- driver/feature_gates.h
/kind bug
/kind feature
This PR introduces 2 main changes:
* enable support for BPF `raw_tracepoint` on `s390x` architectures. BPF has some problems with architectures like `s390x` as also described in this issue https://github.com/falcosecurity/libs/issues/497.  With this fix the BPF probe can works also on kernel versions >= `4.17`, but the problem is that there are many instrumentation drops due to the use of `bpf_probe_read()` and `bpf_probe_read_str()` that don't work at all on architectures like `s390x` as you can read …
> fix(kmod): support `clone child` exit events on `s390x`

- driver/bpf/quirks.h
/kind cleanup
On unsupported architectures, we don't perform argument retrieval in case of bpf raw tracepoint this will cause compilation problems as you can see [here](https://github.com/falcosecurity/libs/issues/360#issuecomment-1193846793). This PR should fix this kind of issue.
```release-note
NONE
```
> update(bpf): disable BPF raw tracepoints for not supported architectures

- userspace/libsinsp/filterchecks.cpp
/kind cleanup
/area libsinsp
I've looked around, it looks like this value is absolutely unused. In addition, it's technically a (harmless) read out of bounds since you can get in this function with a value that is _not_ a string, meaning that while attempting to interpret these bytes as a string the `std::string` constructor will read out of bounds until it finds a `\0`. This makes tools such as valgrind or asan complain when compiling expressions with `bcontains`, for example.
If this value is actually used and I missed it please let …
> cleanup(libsinsp): remove redundant string in validate_filter_value

- userspace/libsinsp/parsers.cpp
> /kind bug
> /kind design
> /area build
> /area tests
**Does this PR require a change in the driver …
> fix(libsinsp): retain compatibility with PPME_SYSCALL_DUP_X

- userspace/libscap/CMakeLists.txt
- userspace/libscap/engine/test_input/CMakeLists.txt
- userspace/libscap/engine/test_input/test_input.c
- userspace/libscap/scap.c
- userspace/libscap/scap.h
- userspace/libscap/scap_engines.h
- userspace/libscap/scap_open.h
- userspace/libscap/scap_test.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/test/sinsp.ut.cpp
- userspace/libsinsp/test/sinsp_with_test_input.h
/kind design
/area tests
I would like to propose to add the necessary plumbing to have event-based testing for libsinsp, based on scap events. This PR's goal is to give the reader an idea of what I'd like to do and how this could be accomplished with code in our libs and start a discussion on whether this is useful, how to do this properly, or maybe we want to approach the problem in a different way.
_Update_: people liked the idea and so the PR is now more than a WIP :)
*Goal:*
I propose to have tests to verify the following: given a specific machine initial state and a certain series of events, will the sinsp state be updated correctly? Will Falco or any other …
> new(sinsp/test): add event based tests

- userspace/libsinsp/sinsp.cpp
/kind feature
/area libsinsp
Today, in the kernel-side simple consumer mode, all the events related to syscalls marked with the flag `EF_DROP_SIMPLE_CONS` are not pushed to the ringbuffer unless they are marked with the flag `UF_NEVER_DROP`. The idea here is to drop also all events related to untracked syscalls (`PPM_SC_UNKNOWN` enum) since they don't seem to particularly enrich the capture with useful information. 
To do that, we could simply change the flag of the `PPM_SC_UNKNOWN` enum, from `EF_NONE` to `EF_DROP_SIMPLE_CONS` [here](https://github.com/falcosecurity/libs/blob/423235173187cd4629f1e1fd6409a013a …
> update(libsinsp): drop also untracked syscalls in kernel-side simple consumer mode

- driver/syscall_table.c
/kind feature
Since `getrlimit` and `ugetrlimit` events are getters and are used only in debug mode, we can add them to simple consumer mode. Anyway, if someone thinks they are necessary we can discuss about it here
```release-note
NONE
```
> update(driver): add `getrlimit` and `ugetrlimit` to simple consumer

- userspace/libsinsp/test/sinsp_with_test_input.h
With an old enough compiler this causes the following error:
sinsp_with_test_input.h:149:3: sorry, unimplemented: non-trivial designated initializers not supported
Signed-off-by: Grzegorz Nosek <grzegorz.nosek@sysdig.com>
/kind bug
> /kind design
/area build
> /area …
> Don't use C99 initializers in C++

- .github/workflows/ci.yml
/kind feature
/area build
This PR allows us to build also the `bpf_test` executable in CI, this could help us in not introducing tests not compatible with some architectures, like in this case https://github.com/falcosecurity/libs/pull/503/commits/bee4e7bbe54e3ab573e9dfd3a2a4844d15b0579a
```release-note
NONE
```
> update(CI): build also `bpf_test` in ARM64 job

- userspace/libsinsp/container.cpp
- userspace/libsinsp/container_engine/cri.cpp
- userspace/libsinsp/container_engine/docker/async_source.cpp
- userspace/libsinsp/container_info.cpp
- userspace/libsinsp/container_info.h
- userspace/libsinsp/cri.cpp
- userspace/libsinsp/cri.h
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/parsers.cpp
Changes to support tracking how a container was configured with an
initial user and make that info available as user.name for
CONTAINER_JSON events:
1. Add a "container user" field m_container_user to container_info. By
default, the value is "<NA>".
2. In the docker and cri container engine resolvers, parse any
configured user info out of the json response and set
m_container_user.
3. Serialize the parsed username to the json blob that comprises a
CONTAINER_JSON event, and parse it out of the json blob when parsing a
CONTAINER_JSON event.
4. When creating the fake threadinfo that is attached to a container
event, also set m_exe to "container:<id>".
5. For the proc.name filtercheck, if the event type is container_json,
return not the thread uid but the container user.
This ends up being …
> Track container user info and expose via user.name

- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/parsers.h
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/threadinfo.h
It's fairly uncommon to do an exec() from a multithreaded program, but
while doing some performance tests using "stress-ng -exec N", I
noticed that stress-ng does exactly that:
https://github.com/ColinIanKing/stress-ng/blob/master/stress-exec.c#L160.
This exposes some problems in event parsing that we need to fix:
- When the thread that does the exec is the main thread, the pid/tid
remain the same, but all child threads are killed and you may not see
procexit events for those threads. In the threadinfo for the main
thread, we need to reset the child thread count so when the main
thread exits it is properly removed.
- When the thread that does the exec is a non-main thread, the tid
changes back to the main process pid in the exec exit event. The
threadinfo for the tid in the enter event …
> Fix threadinfo leaks when threaded programs exec

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filterchecks.h
Add an optional metrics struct that if present, keeps track of the
efficacy of the extraction cache/evaluation cache.
The metrics count the number of times extract_cached() was called and
when it could use the cache, and the number of times comapre() was
called and when it could use the cache.
Like the caches, the memory for the pointer is assumed to be owned by
something else.
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area …
> feat(filterchecks): add optional metrics struct for caching

- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/filter/ast.cpp
- userspace/libsinsp/filter/ast.h
- userspace/libsinsp/filter/escaping.cpp
- userspace/libsinsp/filter/escaping.h
- userspace/libsinsp/filter/parser.cpp
- userspace/libsinsp/filter/parser.h
- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/filter_escaping.ut.cpp
- userspace/libsinsp/test/string_visitor.ut.cpp
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
/area tests
Add the ability to print an AST as a string. This is useful in code that works with ASTs that wants …
> Add ast as string

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/definitions/missing_definitions.h
- driver/modern_bpf/helpers/base/push_data.h
- driver/modern_bpf/helpers/extract/extract_from_kernel.h
- driver/modern_bpf/helpers/store/auxmap_store_params.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/mkdir.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/open.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/open_by_handle_at.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/openat.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/openat2.bpf.c
- test/modern_bpf/event_class/event_class.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/mkdir_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/open_by_handle_at_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/open_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/openat2_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/openat_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/mkdir_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/open_by_handle_at_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/open_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/openat2_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/openat_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
* `open`
* `openat`
* `openat2`
* `open_by_handle_at`
```release-note
new(modern_bpf): add support for `open` family syscalls
```
> new(modern_bpf): add support for `open` family syscalls

- userspace/libscap/engine/gvisor/parsers.cpp
- userspace/libscap/test/scap_gvisor_parsers.ut.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area tests
> …
> fix(gvisor): cleanup tests, consistent return values

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/close.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/copy_file_range.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/creat.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/dup.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/dup2.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/dup3.bpf.c
- test/modern_bpf/test_suites/syscall_enter_suite/close_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/copy_file_range_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/creat_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/dup2_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/dup3_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/dup_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/close_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/copy_file_range_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/creat_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/dup2_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/dup3_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/dup_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
* `close`
* `copy_file_range`
* `creat`
* `dup`
* `dup2`
* `dup3`
This PR is based on https://github.com/falcosecurity/libs/pull/503 I will rebase it against master and remove the `[WIP]` when the previous one will be merged
```release-note …
```
> new(modern_bpf): add support for some `file` related syscalls 

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/chdir.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/chmod.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/chroot.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fchdir.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fchmod.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fchmodat.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/mkdirat.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/rmdir.bpf.c
- test/modern_bpf/test_suites/syscall_enter_suite/chdir_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/chmod_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/chroot_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/fchdir_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/fchmod_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/fchmodat_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/mkdirat_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/rmdir_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/chdir_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/chmod_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/chroot_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/fchdir_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/fchmod_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/fchmodat_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/mkdirat_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/rmdir_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
* `chdir`
* `chmod`
* `chroot`
* `fchdir`
* `fchmod`
* `fchmodat`
* `mkdirat`
* `rmdir`
This PR is based on https://github.com/falcosecurity/libs/pull/503 I will rebase it against master and remove the `[WIP]` when the previous one will be merged …
> new(modern_bpf): add support for `chdir` family syscalls

- userspace/libscap/scap-int.h
This makes scap_dump_open_fd more usable for minimal builds.
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libscap
> /area tests
> /area …
> fix(libscap): Use fdopen if gzdopen isn't available.

- CMakeLists.txt
/kind feature
/area libscap
/area tests
Currently we only run tests for libsinsp in CI, I would like to run `libscap`'s too. We currently only have something generic and something for gvisor but the list may grow...
Fixes # …
> update(tests): automatically run libscap tests in CI

- userspace/libscap/examples/01-open/scap_open.c
/kind feature
/area libscap
The scap-open example, which we now use extensively for testing, did not properly handle the `SCAP_UNEXPECTED_BLOCK` and `SCAP_FILTERED_EVENT` scap return codes. The first is specifically useful when reading from trace files.
```release-note
NONE
```
> update(scap-open): handle all scap return codes

- userspace/libsinsp/filterchecks.cpp
/kind bug
/area libsinsp
This reverts a change of #493 that inverts the extracted values of `container.mount.source` and `container.mount.dest`, which caused an unwanted breaking change on libs consumers. Reminding the field documentation:
```
container.mount.source        (ARG_REQUIRED) the mount source, specified by number (e.g. container.mount.source[0]) or 
mount destination (container.mount.source[/host/lib/modules]). The pathname can be a 
glob. 
container.mount.dest          (ARG_REQUIRED) the mount destination, specified by number (e.g. container.mount.dest[0]) 
or mount source …
```
> fix(userspace/libsinsp): revert container.mount source and dest extraction

- .github/workflows/ci.yml
/kind bug
/area CI
This PR address the issue that CI jobs are not able to compute libs version during cmake configure step; see here for example (https://github.com/falcosecurity/libs/runs/7652420577?check_suite_focus=true)
>-- Libs version: **0.0.0**
> -- Driver version: **0.0.0**
> -- Driver API version 2.0.0
> -- Driver schema version 2.0.0
Fixes #
```release-note
NONE
```
> fix(ci): fixed checkout action fetch depth.

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/eventfd.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/inotify_init.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/signalfd.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/timerfd_create.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/userfaultfd.bpf.c
- test/modern_bpf/test_suites/syscall_enter_suite/eventfd2_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/eventfd_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/inotify_init1_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/inotify_init_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/signalfd4_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/signalfd_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/timerfd_create_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/userfaultfd_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/eventfd2_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/eventfd_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/inotify_init1_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/inotify_init_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/signalfd4_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/signalfd_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/timerfd_create_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/userfaultfd_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
* `eventfd`
* `eventfd2`
* `inotify_init`
* `inotify_init1`
* `timerfd_create`
* `userfaultfd`
* `signalfd`
* `signalfd4`
```release-note
new(modern_bpf): add support for `notify` syscalls 
```
> new(modern_bpf): add support for `notify` syscalls 

- userspace/libscap/scap_engine_util.c
/kind cleanup
/area libscap
Fixes error `snprintf` correctly using values used in the check.
Fixes #
```release-note
NONE
```
> chore(userspace/libscap): fixed printf on error when check_api_compatibility() fails

- .github/workflows/ci.yml
/kind bug
/kind feature
/area build
/area CI
/area tests
None.
Include s390x to the CI workflow  to build and run unit tests and build modern-bpf using the `run-on-arch` similar to aarch64. This PR is based on the discussion [here](https://github.com/falcosecurity/libs/pull/533#issuecomment-1205197373) in #533.
The `build-libs-s390x` uses ubuntu as host and build image. For `build-modern-bpf-s390x`, ubuntu is used for host but I had to use fedora for building the modern-bpf parts. There was an issue regarding bpf header definitions that might be sorted out separately. Details can be found …
> new(ci): build libs and modern-bpf for s390x

- driver/bpf/fillers.h
- driver/event_table.c
- driver/fillers_table.c
- driver/flags_table.c
- driver/ppm_compat_unistd_32.h
- driver/ppm_events_public.h
- driver/ppm_fillers.c
- driver/ppm_fillers.h
- driver/ppm_flag_helpers.h
- driver/syscall_table.c
- userspace/libscap/syscall_info_table.c
```
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>
```
> /kind bug
> /kind design
/kind feature
> /area build
/area libscap
/area libsinsp
> /area tests
This PR adds support for the `mlock2` system call.
falcosecurity/falco#1998
Fixes #
The `event_flag` for the sycall has been set to `EF_DROP_SIMPLE_CON`.
```release-note
update(driver): add support for …
```
> update(driver): add support for mlock2 syscall

- driver/ppm_events_public.h
- userspace/libscap/engine/savefile/scap_savefile.c
- userspace/libscap/scap_procs.c
- userspace/libscap/scap_savefile.c
- userspace/libscap/scap_userlist.c
- userspace/libsinsp/dns_manager.h
- userspace/libsinsp/fdinfo.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/threadinfo.cpp
_WIN32 is predefined by the compiler on both 32-bit and 64-bit Windows,
so checking for WIN32, _WIN64, and WIN64 isn't needed:
https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros
https://github.com/cpredef/predef/blob/master/OperatingSystems.md
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area …
> Fixup our Win32 checks.

- userspace/libsinsp/parsers.cpp
/kind bug
/area libsinsp
With some syscalls like `open`, `creat`, `openat`, we check if the enter event has correctly collected the parameters and when the exit event arrives we replace the exit params with the enter ones, this is done to prevent some possible TOCTOU attacks as described more in detail [here](https://github.com/falcosecurity/libs/pull/235). Look at the issue to obtain more information https://github.com/falcosecurity/libs/issues/477. Right now only `(NULL)` is considered as an empty param by userspace, but our drivers also send `<NA>` …
> fix(libsinsp): consider <NA> as an empty param

- userspace/libscap/engine/savefile/savefile.h
- userspace/libscap/engine/savefile/scap_savefile.c
- userspace/libscap/scap_open.h
- userspace/libscap/scap_savefile.h
- userspace/libsinsp/sinsp.cpp
/kind cleanup
/kind feature
/area libscap
This follows-up the changes of https://github.com/falcosecurity/libs/pull/525 by:
- Making the buffered `scap_reader` implementation optional and configurable through `scap_open_args`
- Avoiding all corner cases in which the scap reader needs to seek backwards
Again, the end goal is to allow stream scap data from sockets or pipe, which can be useful for automated tools and testing.
```release-note
NONE
```
> update(userspace/libscap): improve scap reader

- .github/workflows/ci.yml
- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/definitions/missing_definitions.h
- driver/modern_bpf/helpers/extract/extract_from_kernel.h
- driver/modern_bpf/helpers/store/auxmap_store_params.h
- driver/modern_bpf/helpers/store/ringbuf_store_params.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/capset.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/kill.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/ptrace.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/seccomp.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/tgkill.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/tkill.bpf.c
- test/modern_bpf/event_class/event_class.cpp
- test/modern_bpf/event_class/event_class.h
- test/modern_bpf/test_suites/syscall_enter_suite/capset_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/kill_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/ptrace_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/seccomp_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/tgkill_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/tkill_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/capset_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/kill_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/ptrace_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/seccomp_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/tgkill_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/tkill_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
* `kill`
* `tgkill`
* `tkill`
* `seccomp`
* `ptrace`
* `capset`
```release-note
new(modern_bpf): add support for `kill` family, `seccomp`, `ptrace`, `capset` syscalls 
```
> new(modern_bpf): add support for `kill` family, `seccomp`, `ptrace`, `capset` syscalls 

- userspace/libsinsp/event.cpp
- userspace/libsinsp/event.h
Signed-off-by: vadim.zyarko <vadim.zyarko@sysdig.com>
/kind feature
/area libsinsp
This PR creates a facility for cloning sinsp_evts, thus detaching it from the sinsp::next loop.  
```release-note
NONE
```
> create static method to clone existing sinsp_evt

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filter.h
- userspace/libsinsp/filter/ast.cpp
- userspace/libsinsp/filter/ast.h
- userspace/libsinsp/filter/parser.cpp
- userspace/libsinsp/filter/parser.h
- userspace/libsinsp/test/filter_parser.ut.cpp
/kind bug
/kind cleanup
/area libsinsp
/area tests
This refactor is also the larger part of the effort to make our tests pass under AddressSanitizer.
All the `ast::expr` classes were holding pointers or vectors of pointers allocated manually via `new` and removed via `delete`, sometimes through virtual destructors. This should be fine in the happy path where everything works as planned, but becomes an issue where any unexpected behavior happens, such as any `throw` in the parsers. In that case, any allocated memory would …
> refactor(libsinsp): manage memory in ast/parser via unique_ptrs

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/helpers/store/auxmap_store_params.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/accept.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/accept4.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/bind.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/connect.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/listen.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/socket.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/socketpair.bpf.c
- test/modern_bpf/event_class/event_class.cpp
- test/modern_bpf/event_class/event_class.h
- test/modern_bpf/event_class/network_utils.h
- test/modern_bpf/test_suites/syscall_enter_suite/accept4_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/accept_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/bind_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/connect_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/listen_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/socket_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/socketpair_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/accept4_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/accept_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/bind_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/connect_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/listen_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/socket_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/socketpair_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
* `socket`
* `connect`
* `socketpair`
* `accept`
* `accept4`
* `bind`
* `listen`
```release-note
new(modern_bpf): add support for some network family syscalls
```
> new(modern_bpf): add support for some `network` family syscalls

- cmake/modules/CompilerFlags.cmake
Remove compiler flags which fixed an issue for LuaJit 2.0 on macOS. That
particular library version + OS combination is no longer supported by
the LuaJIT project, and the flags are incompatible with Arm64.
Ping #321.
/kind bug
/kind cleanup
> /kind design
/area build
> /area CI …
> update(cmake): Remove old LuaJIT+macOS compiler flags.

- driver/bpf/filler_helpers.h
- driver/bpf/fillers.h
- driver/ppm_events.c
- driver/ppm_fillers.c
- userspace/libscap/scap_event.c
- userspace/libsinsp/event.cpp
- userspace/libsinsp/event.h
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/test/sinsp.ut.cpp
/kind cleanup
/kind feature
/area libscap
/area libsinsp
/area tests
This shouldn't require an API VERSION change since we have already bumped the major version [here](https://github.com/falcosecurity/libs/pull/492) 
To understand why we need this PR I need to provide you with a bit of context.
Some of our params send different values in case of failure:
**First group**
- `PT_CHARBUF`
- `PT_FSPATH`
- `PT_FSRELPATH`
could be:  `<NA>`, `(NULL)` or an empty param (`len=0`)
**Second group**
- `PT_BYTEBUF` 
could be: empty param (`len=0`) or **NOTHING**. What I mean with …
> update(libsinsp/drivers): send empty params from drivers and manage them in userspace

- userspace/libscap/scap_zlib.h
/kind bug
/area build
/area libscap
I had trouble compiling with the MINIMAL_BUILD option due to the gzerror fallback not being declared static.
```release-note
NONE
```
> fix(userspace/libscap): set gzerror fallback to static

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/test/sinsp_with_test_input.h
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> fix(userspace/libsinsp): fix parse_field_name() wrong check (size_t, aka uint32_t, cast of max_fldlen)

- userspace/libscap/engine/bpf/scap_bpf.c
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> …
> chore(userspace/libscap): give name to bpf programs

- userspace/libsinsp/test/sinsp_with_test_input.h
```
In file included from userspace/libsinsp/test/sinsp.ut.cpp:20:0:
userspace/libsinsp/test/sinsp_with_test_input.h: In member function 'sinsp_evt* sinsp_with_test_input::add_event_advance_ts(uint64_t, uint64_t, ppm_event_type, uint32_t, ...)':
userspace/libsinsp/test/sinsp_with_test_input.h:70:13: error: variable 'scap_event' set but not used [-Werror=unused-but-set-variable]
scap_evt *scap_event;
^
```
/kind bug
> /kind design
/area build
> /area CI
> /area …
> (fix) Fix compile error in sinsp_with_test_input

- driver/ppm_events_public.h
Make ppm_event_info and ppm_param_info naturally aligned.
Fixes #321.
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> …
> update(driver): Unpack a couple of structs.

- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/test/sinsp.ut.cpp
- userspace/libsinsp/threadinfo.h
/kind bug
/kind cleanup
/area libsinsp
/area tests
No
This PR fixes the retrieval of the `execveat` enter event when sinsp is parsing the `execve` exit event. Before this commit it was only possible to retrieve the enter event associated with the exit event we are parsing, so for example `PPME_SYSCALL_EXECVE_19_X` could only retrieve `PPME_SYSCALL_EXECVE_19_E` but not `PPME_SYSCALL_EXECVEAT_E` and this was a bug since in some cases the `PPME_SYSCALL_EXECVE_19_X` corresponds to a `PPME_SYSCALL_EXECVEAT_E` and not to a `PPME_SYSCALL_EXECVE_19_E`.
The `execveat` syscall is a wrapper of `execve`, when the call …
> fix(libsinsp): retrieve the correct `exepath` with `execveat` syscall

- userspace/libsinsp/filter/ast.cpp
- userspace/libsinsp/filter/ast.h
- userspace/libsinsp/test/string_visitor.ut.cpp
/kind cleanup
/area libsinsp
This makes the (yet unused) AST `as_string` signature use raw pointers instead of references in order to make it consistent with other AST related functions (e.g. `clone`, `is_equal`, etc.). Besides code consistency, ASTs factory constructors now always return unique_ptrs so it will be unlikely to have reference-compatible ASTs without additional and unneeded de-referencing.
```release-note
fix(userspace/libsinsp/filter)!: use raw pointers in AST as_string …
```
> fix(userspace/libsinsp/filter)!: use raw pointers in AST as_string signature

- userspace/libsinsp/sinsp.cpp
`res` is unused when `_DEBUG` is not defined.
> /kind bug
> /kind design
> /area build
> /area CI
> /area tests
**Does …
> fix(libsinsp): avoid unused variable

- README.md
Moreover, modern_bpf now supports s390x, even if it is itself a wip.
Fixes #
```release-note
NONE
```
> fix(readme): fixed small typo.

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/definitions/missing_definitions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/bpf.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/flock.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/ioctl.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/mount.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/quotactl.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/umount2.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/unshare.bpf.c
- test/modern_bpf/test_suites/syscall_enter_suite/bpf_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/flock_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/ioctl_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/mount_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/quotactl_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/umount2_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/unshare_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/bpf_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/flock_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/ioctl_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/mount_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/quotactl_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/umount2_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/unshare_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
* `bpf`
* `flock`
* `ioctl`
* `quotactl`
* `unshare`
* `mount`
* `umount2`
Today we define the events `PPME_SYSCALL_UMOUNT_E` and `PPME_SYSCALL_UMOUNT_X`, but we use them for the `umount2` syscall, we don't instrument the `umount`. This is probably due to the fact that in many x64 architectures …
> new(modern_bpf): add support for `bpf`, `flock`, `ioctl`, `quotactl`, `unshare`, `mount`, `umount2`

- driver/ppm_events.c
/kind bug
No
The previous way to add the string terminator `\0` was broken since even if the terminator was already present we pushed a further character, causing issues like the following
```
------------------ EVENT: 330 TID:128998
------ HEADER
timestamp: 1661879160280229084
tid: 128998
len: 50
type: 330
num params: 3
------
------ PARAMS
PARAM 0: -100
PARAM 1: testU  <---- This is a junk char
PARAM 2: 2
------
------------------
```
Instead of
```
------------------ EVENT: 330 TID:27963
------ HEADER
timestamp: 1661879495207653622
tid: 27963
len: 49
type: 330
num params: 3
------
------ …
```
> fix(kmod): add the string terminator if not present

- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/threadinfo.h
/kind bug
/area libsinsp
In https://github.com/falcosecurity/libs/pull/473 it was introduced a `cgroups` local variable in `sinsp_threadinfo::cgroups_to_iovec`, to have it work with a copy and avoid `sinsp_threadinfo::m_cgroups` being invalidated meanwhile.
Unfortunately, it slipped that `iovec` pointers reference the data owned by that local variable, thus becoming dangling at scope exit.
Fixes #
```release-note
NONE
```
> fix(libsinsp): keep the copy of cgroups alive across the write

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/helpers/store/auxmap_store_params.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvfrom.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvmsg.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendmsg.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendto.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/setsockopt.bpf.c
- test/modern_bpf/event_class/event_class.cpp
- test/modern_bpf/event_class/event_class.h
- test/modern_bpf/event_class/network_utils.h
- test/modern_bpf/test_suites/syscall_enter_suite/accept_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/connect_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/recvfrom_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/recvmsg_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/sendmsg_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/sendto_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/setsockopt_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/socketpair_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/accept4_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/accept_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/bind_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/connect_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/recvfrom_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/recvmsg_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/sendmsg_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/sendto_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/setsockopt_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/socketpair_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
This is the last PR of the https://github.com/falcosecurity/libs/issues/513, we have done it :tada: :tada: 
This PR introduces:
* `setsockopt`
* `sendmsg`
* `sendto`
* `recvmsg`
* `recvfrom`
```release-note
new(modern_bpf): add support for last `network` family syscalls
```
> new(modern_bpf): add support for last `network` family syscalls

- driver/ppm_events_public.h
- userspace/libscap/engine/savefile/scap_savefile.c
- userspace/libscap/scap.h
- userspace/libscap/scap_fds.c
- userspace/libsinsp/event.cpp
- userspace/libsinsp/fdinfo.cpp
- userspace/libsinsp/fdinfo.h
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/parsers.h
- userspace/libsinsp/test/sinsp.ut.cpp
- userspace/libsinsp/threadinfo.cpp
/kind bug
/area libscap
/area libsinsp
Moreover, properly state in EF_CREATES_FD and EF_DESTROYS_FD flags docs, that when used, a parser MUST always be created.
Practically, added parser for:
* bpf
* userfaultfd
* io_uring_setup
exit events.
Fixes #
```release-note
fix: properly parse and add to sinsp state FDs coming from bpf, userfaultfd and io_uring_setup events.
```
> fix(userspace/libscap,userspace/libsinsp): properly add parsers for multiple EF_CREATES_FD events.

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fcntl.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/shutdown.bpf.c
- test/modern_bpf/test_suites/syscall_enter_suite/fcntl_e.cpp
- test/modern_bpf/test_suites/syscall_enter_suite/shutdown_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/fcntl_x.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/shutdown_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
* `fcntl`
* `shutdown`
This syscall wasn't in the original set but probably it will be needed by the new `interesting` syscall approach
```release-note
new(modern_bpf): add `fcntl` and `shutdown` syscall
```
> new(modern_bpf): add `fcntl` and `shutdown` syscalls

- userspace/libsinsp/filterchecks.cpp
/kind feature
/area libsinsp
no
This is needed to advise our users that they can still have k8s metadata without the full k8s support (ref **https://github.com/falcosecurity/libs/pull/15).**
The message will be rendered on the official Falco documentation :point_down: , once a new version is out.
https://falco.org/docs/rules/supported-fields/#field-class-k8s
```release-note
NONE
```
> update(userspace/libsinsp): k8s filterchecks documentation desc

- userspace/libsinsp/test/sinsp.ut.cpp
> /kind bug
> /kind design
/kind feature
/area libsinsp
/area tests
Add more tests to the libsinsp suite for open, openat and creat:
1. check for NULL file name during open/openat/creat on entry event but present on exit. The exit name should …
> new(libsinsp/test): Test open/openat/creat NULL filenames and enter/exit string disagreements

- CMakeLists.txt
- test/e2e/CMakeLists.txt
- test/e2e/README.md
- test/e2e/containers/sinsp.Dockerfile
- test/e2e/containers/tests.Dockerfile
- test/e2e/tests/commons/setup.py
- test/e2e/tests/commons/sinspqa/__init__.py
- test/e2e/tests/commons/sinspqa/docker.py
- test/e2e/tests/commons/sinspqa/event_generator.py
- test/e2e/tests/commons/sinspqa/sinsp.py
- test/e2e/tests/conftest.py
- test/e2e/tests/requirements.txt
- test/e2e/tests/test_event_generator/test_db_program_spawned_process.py
- test/e2e/tests/test_event_generator/test_file_writes.py
- test/e2e/tests/test_event_generator/test_make_binary_dirs.py
- test/e2e/tests/test_event_generator/test_modify_binary_dirs.py
- test/e2e/tests/test_event_generator/test_network_activity.py
- test/e2e/tests/test_event_generator/test_non_sudo_setuid.py
- test/e2e/tests/test_event_generator/test_read_sensitive_file.py
- test/e2e/tests/test_event_generator/test_run_shell_untrusted.py
- test/e2e/tests/test_event_generator/test_system_user_interactive.py
- test/e2e/tests/test_network/test_network.py
- test/e2e/tests/test_process/test_container.py
- test/e2e/tests/test_process/test_process.py
- test/e2e/tests/test_process/test_sample.sh
- userspace/libsinsp/examples/test.cpp
/kind feature
/area tests
This PR adds the e2e tests previously held under [Molter73/falco-libs-qa](https://github.com/Molter73/falco-libs-qa) into the repository.
The way the tests work is by building the `sinsp-example` binary and embedding it into a container. Said container expects the binary to be built in an environment similar to the one used by the CI (so a `debian:buster` image). Then a separate container is built to run the actual tests using pytest and spawning containers using Docker-in-Docker, this approach was chosen as an OK way to limit events to the ones coming from a specific container, which should help diminish failures because of interference …
> Add e2e tests based on sinsp-example

- driver/main.c
/kind bug
Avoid some dmesg errors by keeping `g_tracepoints_attached` in sync with real values.
Extracted from #582 
Fixes #
```release-note
NONE
```
> fix(driver/kmod): fixed tracepoint detach to avoid dmesg errors.

- userspace/libscap/syscall_info_table.c
- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/sinsp_ppm_sc.cpp
/kind feature
Provide a `simple_ppm_sc_set` that is basically the same as previous simple consumer mode. Moreover, leveraging syscall_info_table categories, provide more default sets to be used in different environments.
Moreover in syscall_info_table, a couple of categories were fixed. 
Fixes #
```release-note
NONE
```
> new(userspace/libsinsp): provide multiple default sets for ppm_sc of interest

- userspace/libsinsp/sinsp.h
/kind cleanup
/area libsinsp
Fixes #
```release-note
NONE
```
> chore(userspace/libsinsp): move new `enforce_X_ppm_sc` near to `enforce_sinsp_state_ppm_sc`

- userspace/libsinsp/user.cpp
/kind bug
/area libsinsp
In sinsp_usergroup_manager::load_from_container, don't use the inspector's usergroup_manager instance.
Mind that in a real scenario the usergroup_manager gets created by the inspector, so it would be the same instance actually.
Fixes #
```release-note
NONE
```
> fix(userspace/libsinsp): use self instead of inspector's usergroup_manager

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/gen_filter.cpp
- userspace/libsinsp/gen_filter.h
>/kind feature
Add stat fields to `gen_event_filter_check` to maintain filters exec statistics.
This will help clients to analyze the performance of the filters and make runtime decisions for the checks optimization/rearrangements.  
the statistics may look this way:
```
rule:{ name: Linux Kernel Module Injection Detected, src: syscall, types: [230, 231, 292, 293]}
* NONE, 45941 0, LT, (6)
[
= NONE, 45941 45941, evt.type EQ (1)[ execve ]
= AND, 45941 45941, evt.dir EQ (1)[ < ]
= AND, 24288 0, evt.arg EQ (1)[ 0 ]
= AND, 20877 20877, container.id NE (1)[ host ]
= AND, 20877 20877, proc.name EQ (1)[ insmod ]
= AND_NOT, 0 0, proc.args IN (1)[  ]
]
```
here we can see …
> add filter execution statistics to be analyzed by the clients

- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/kmod/scap_kmod.c
- userspace/libscap/engine/udig/scap_udig.c
- userspace/libscap/ringbuffer/devset.c
- userspace/libscap/ringbuffer/devset.h
- userspace/libscap/ringbuffer/ringbuffer.c
- userspace/libscap/ringbuffer/ringbuffer.h
- userspace/libscap/scap.h
> /kind bug
/kind cleanup
/kind design
/area build
> /area CI
/area libscap-engine-udig
/area libscap
> /area tests
> /version …
> Don't use a global variable for the ring buffer size

- driver/main.c
- driver/modern_bpf/shared_definitions/struct_definitions.h
- driver/ppm.h
- driver/ppm_ringbuffer.h
- test/modern_bpf/start_tests.cpp
- userspace/libpman/include/libpman.h
- userspace/libpman/src/configuration.c
- userspace/libpman/src/ringbuffer.c
- userspace/libpman/src/state.h
- userspace/libscap/CMakeLists.txt
- userspace/libscap/engine/bpf/bpf_public.h
- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/kmod/kmod_public.h
- userspace/libscap/engine/kmod/scap_kmod.c
- userspace/libscap/engine/modern_bpf/modern_bpf_public.h
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
- userspace/libscap/engine/udig/scap_udig.c
- userspace/libscap/examples/01-open/scap_open.c
- userspace/libscap/ringbuffer/devset.c
- userspace/libscap/ringbuffer/devset.h
- userspace/libscap/ringbuffer/ringbuffer.c
- userspace/libscap/ringbuffer/ringbuffer.h
- userspace/libscap/scap.c
- userspace/libscap/scap.h
- userspace/libsinsp/examples/test.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
/kind feature
/area libpman
/area libsinsp
/version driver-API-version-major
But we have already bumped it here https://github.com/falcosecurity/libs/pull/492
As previously discussed [here](https://github.com/falcosecurity/libs/pull/414#issue-1277253587 ) and in various other issues this PR introduces the possibility of choosing the dimension of the shared buffers (between userspace/kernel) at initialization time. The rationale here is:
* `libsinsp` receives the number …
> new(libsinsp,engines): add support for variable shared buffer dimension 

- userspace/libscap/scap.c
- userspace/libscap/scap.h
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/sinsp_ppm_sc.cpp
/kind feature
/area libsinsp
No
This PR introduces a new API in sinps that can be used to obtain the set of events associated with a set of `ppm_sc`. The typical use case is when Falco needs to understand if all the events used in the rule are considered in our set of interesting `ppm_sc`
```release-note
new(libsinps): add a new API in sinsp to obtain the events associated with a set of `ppm_sc`
```
> new(libsinps): add a new API in sinsp to obtain the events associated with a set of `ppm_sc`

- userspace/libscap/scap.c
/kind cleanup
/area libscap
The API is very inconsistent about checking for NULL. Most of the time the handle is unchecked. There was one specific function which was checked, but then new code got added before the check: https://github.com/draios/agent-libs/commit/d98fb0761bc454230ca1f069cc393d0f0ff286ca#diff-c478647d3c515b80e0b8377839cfdb4936cf1b1f5999a89b56a72ccf42f76e04R2557
This new code ended up breaking a test which relied on the check. Rather than fix that one function, I thought the ideal fix would be to consistently check the handle for NULL at the top of each API function.
```release-note
NONE
```
> chore(libscap): Check handle for NULL in scap API

- .github/workflows/ci.yml
/kind feature
/area CI
This change solves two issues:
- Run the CI on PR based on branches other than `master` (that's legit, for example  :point_right: https://github.com/falcosecurity/libs/pull/611)
- Let maintainers use the CI for testing their code by pushing to a branch ( otherwise maintainers are forced to open dummy PRs like this :point_right: https://github.com/falcosecurity/libs/pull/618) 
```release-note
NONE
```
> build(.github): enable CI workflow on all branches

- driver/modern_bpf/programs/attached/dispatchers/syscall_enter.bpf.c
- driver/modern_bpf/programs/attached/dispatchers/syscall_exit.bpf.c
- userspace/libpman/src/programs.c
/kind feature
No
This PR changes the names of some BPF programs to allow better debugging with BPFTOOL, the max length of a bpf prog name before the truncation is `16`. We should try to use short names :) 
```release-note
NONE
```
> new(modern_bpf): change `sys_enter` and `sys_exit` prog names

- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/test/sinsp.ut.cpp
/kind bug
/area libsinsp
I noticed this behavior while writing tests. All the libsinsp UID/GID tracking use 32 bit integers, which is fine. However, when accessing the field through filterchecks the extracted field is 32 bit but the filtercheck will read an uint64, meaning it'll likely read 4 bytes from the adjacent string that holds the group name. This fixes it and adds the corresponding test.
Fixes # …
> fix(libsinsp): use consistent 32bit GID fields

- userspace/libsinsp/event.h
Some automated unit tests that use libs construct sinsp_evts directly using init() methods without using an inspector. One of the init() methods initializes the evtnum to 0, but the others did not.
When running those tests, valgrind reports errors about m_evtnum being uninitialized.
So initialize m_evtnum in all init() methods.
This doesn't affect uses of sinsp_evt via the inspector, as sinsp::next() sets m_evtnum.
> /kind bug
> /kind design
> /area build
> /area CI
> /area …
> Initialize evtnum in sinsp_evt::init methods

- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/test/sinsp.ut.cpp
- userspace/libsinsp/test/sinsp_with_test_input.h
/kind bug
/area libsinsp
Sometimes PIDs do not necessarily indicate host PIDs. This is true if we're monitoring sandboxes which do not map to a real kernel, such as gVisor. In order to maintain internal state consinstency sinsp will hold a PID that is larger than an actual one for those processes …
> fix(libsinsp): display invalid pids as <NA>

- userspace/libsinsp/sinsp.cpp
/kind bug
> /area build
> /area CI
/area libscap
The gVisor engine is able to set its root path is set to the default for Docker if it's empty. Remove the error so that it's still allowed.
Fixes #
```release-note
fix(engine/gvisor): allow empty (default) root path
```
> fix(engine/gvisor): allow empty (default) root path

- userspace/libsinsp/container_engine/docker/async_source.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/user.cpp
- userspace/libsinsp/user.h
/kind bug
/area libsinsp
This PR allows us to properly load users and groups from pre-existing containers on init 
```release-note
fix(libsinsp): properly load users and groups from pre-existing containers on init
```
> fix(userspace/libsinsp): properly load users and groups from pre-existing containers on init

- userspace/libsinsp/parsers.cpp
Synthetic events don't have a real tid but use -1 instead. We exclude the container events but missed the recently introduced user/group events
/kind bug
> /kind design
> /area build
> /area CI
> /area …
> fix(sinsp): don't look up thread -1 in the table

- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libsinsp/tracers.cpp
/kind cleanup
/area libsinsp
/area libscap
No
Fix warnings if you compile with `-DBUILD_WARNINGS_AS_ERRORS`
Fixes #
```release-note
NONE
```
> fix(libsinsp, libscap): fix compiler warning about uninitialized var

- userspace/libscap/scap.c
- userspace/libscap/scap.h
- userspace/libsinsp/sinsp.h
/kind feature
/area libscap
/area libsinsp
No
This PR adds a new sinsp API to get if the event is generated by the system during live capture.
```release-note
NONE
```
> new(libsinsp,libscap): add a new generable event API

- driver/ppm_events.c
/kind bug
No
This PR fixes a bug introduced here: https://github.com/falcosecurity/libs/pull/574
In that commit we relied on the fact that `strlcpy` could return at max `max_arg_size` but this is not the truth, so this fix adds a check to ensure `len<=max_arg_size`.
Without this check bad things could happen, if `len>max_arg_size` we could cause buffer corruption when we do `args->arg_data_size -= len;` here :point_down: 
https://github.com/falcosecurity/libs/blob/b4e9f97a3a30eabd45d737274a101070141d5512/driver/ppm_events.c#L1002 …
> fix(driver): avoid kmod buffer corruption in case of `len>max_arg_size`

- driver/event_table.c
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/test/public_sinsp_API/event_related.cpp
- userspace/libsinsp/test/sinsp.ut.cpp
- userspace/libsinsp/test/table/event_table.cpp
/kind cleanup
/area libsinsp
EF_UNUSED and EF_SKIPPARSERESET have two distinct semantics, and checks for those flags should be split in the two `sinsp::is_unused()` and `sinsp::is_skip_parse_reset()` methods.
```release-note
NONE
```
> fix(userspace): split is_unused from is_skip_parse_reset event checks

- .github/workflows/ci.yml
/kind feature
/area CI
no.
Adds a new github action to test the build of kmod and eBPF probe against multiple kernel releases, leveraging driverkit docker image.
TODO: 
Fixes #
```release-note
NONE
```
> chore(ci): add a driverkit job in CI to test drivers build against multiple kernelreleases

- userspace/libsinsp/sinsp.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> Make sinsp open methods virtual for tests

- driver/modern_bpf/helpers/base/push_data.h
- driver/modern_bpf/helpers/store/auxmap_store_params.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area tests
> …
> fix(driver-modern-bpf): fix execve USER vs MEMORY reads + cleanup + enforce upper bounds in push__bytebuf

- userspace/libsinsp/filterchecks.cpp
/kind bug
/area libsinsp
Mentioning the description, the `syscall.type` filtercheck should work as:
```
For system call events, the name of the system call (e.g. 'open').
Unset for other events  (e.g. switch or internal events). 
Use this field instead of evt.type if you need to make sure that
the filtered/printed value is actually a system call. 
```
However, given the recent event flag cleanup, this is not guaranteed to work as expected if not relying on the formal `sinsp::is_syscall_event` API. …
> fix(userspace/libsinsp): do proper checks on syscall.type filtercheck

- .github/workflows/ci.yml
/kind cleanup
/area CI
No 
Fixes #
```release-note
NONE
```
> chore(ci): added kernelurls parameter pointing to download.falco.org to driverkit CI job

- userspace/libscap/engine/savefile/scap_savefile.c
/kind bug
If new threads come between `scap_write_proclist` and `scap_write_fdlist`, we could have fdlist entries without their TID counterpart in the proclist: silently skip them.
It would be nice to have a warning, but there aren't any in scap so I won't risk adding one.
Fixes #
Relates to https://github.com/falcosecurity/libs/pull/473
```release-note
NONE
```
> fix(savefile-engine): skip unreferenced FD block

- userspace/libscap/engine/udig/scap_udig.c
Otherwise another thread can mmap something in the spot by accident.
This is *really* hard to hit as it requires:
* a different thread performing a memory allocation at the time the ring buffers are mmapped
* a significant amount of bad luck so that the other thread's allocated memory ends up in the hole created by the munmap
but the consequences are equally hard to debug (your other thread basically uses the ring buffer as its storage, so the ring buffer gets corrupted for no apparent reason).
Since we can easily mmap over an already mmapped memory, let's do just that instead.
/kind bug
> /kind design
**Any specific area of the project …
> Don't munmap the placeholder before mapping the ring buffer

- CMakeLists.txt
- cmake/modules/libscap.cmake
/kind bug
/area libscap
The HAVE_STRCPY have been moved to a common target in https://github.com/falcosecurity/libs/pull/659, however that currently happens inside CMakeLists, which is not included by all project. This caused projects based on top of libs to fail compilation due to the common_config.h not being generated. This PR fixes this by moving the cmake definitions inside the libscap.cmake module.
```release-note
NONE
```
> chore(libs): move strlcpy definition in libscap module

- userspace/libscap/scap.c
- userspace/libsinsp/sinsp.cpp
Ref #490
Now that the return code is in place (step 1) and handled in all the major libsinsp clients (step 2), it's time to actually start returning the code.
There should be no user-visible effect of this change. Rather, by providing additional information to the client, the caller should be able to better react to the behavior of the library. This change only affects clients using userspace filtering / suppression.
/kind feature
/area libscap
/area libsinsp
```release-note
new(libs): new return code from `scap::next` and `sinsp::next` which must be handled by the caller.
```
> feat(libs): Add new return code for filtered events(3/3)

- userspace/libsinsp/examples/test.cpp
/kind bug
/area tests
Adapt `sinsp-example` to https://github.com/falcosecurity/libs/pull/674 and restore its functionality
Fixes #
See https://github.com/falcosecurity/libs/pull/674
```release-note
NONE
```
> fix(sinsp-example): handle SCAP_FILTERED_EVENT

- driver/modern_bpf/helpers/base/read_from_task.h
- driver/modern_bpf/helpers/store/auxmap_store_params.h
/kind bug
No
enum `cgroup_subsys_id`, defined in [include/linux/cgroup-defs.h](https://github.com/torvalds/linux/blob/87066fdd2e30fe9dd531125d95257c118a74617e/include/linux/cgroup-defs.h#L43-L47), can differ depending on which cgroup features are enabled during kernel compilation (see [include/linux/cgroup_subsys.h](https://github.com/torvalds/linux/blob/87066fdd2e30fe9dd531125d95257c118a74617e/include/linux/cgroup_subsys.h) for details). So, to know the actual integer value of the `cgroup_subsys_id::...` we need the CO-RE …
> fix(modern_bpf): add some CO-RE relocations

- userspace/libsinsp/include/sinsp_external_processor.h
- userspace/libsinsp/sinsp.cpp
Apologies for the improper fraction. I missed some analysis earlier.
/kind feature
/area libsinsp
```release-note
Clients of libsinsp who are using external event processors will see EVENT_RETURN_FILTERED if using userspace filtering / tid suppression.
```
> feat: Add new return code for filtered events (4/3)

- userspace/libscap/scap_procs.c
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
> fix(libscap): raw syscalls return -errno, not just -1

- userspace/libscap/examples/01-open/scap_open.c
/kind feature
/area scap-open
This PR allows us to understand the number of times the userspace tries to poll the ring buffers but they are empty 
```release-note
NONE
```
> update(scap-open): count the number of timeouts if buffers are empty

- cmake/modules/find_static_library.cmake
- cmake/modules/libbpf.cmake
- cmake/modules/libscap.cmake
- userspace/libpman/CMakeLists.txt
- userspace/libscap/CMakeLists.txt
- userspace/libscap/engine/bpf/CMakeLists.txt
/kind feature
/area build
No
This PR ensures that `libelf` is statically linked when we build with `BUNDLED_DEPS`.  `BUNDLED_DEPS` are used when we build for example tar packages so we prefer to have always static libraries in order to ship the package without system dependencies
Moreover this PR adds `libbpf` as a cmake component since we don't want to use this folder during the packaging phase with `cpack`
```release-note
NONE
```
> chore(userspace): link static `libelf` when using `BUNDLED_DEPS`

- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
- userspace/libscap/examples/01-open/scap_open.c
/kind bug
No
Reduce the time to wait when the buffer is full to `500 us` instead of `500 ms`
```release-note
NONE
```
> fix(driver): reduce the wait time to `500` us

- userspace/libscap/engine/bpf/scap_bpf.c
/kind bug
This fixes running Falco with eBPF on raspberry PI devices.
See https://github.com/kubernetes/kubernetes/issues/95039#issuecomment-940976183 and https://github.com/falcosecurity/falco/issues/2246.
https://github.com/falcosecurity/falco/issues/2246
Fixes #
```release-note
NONE
```
> fix(userspace/libscap): fallback at considering cpus online when NUMA topology information is missing

- userspace/libscap/scap-int.h
- userspace/libscap/scap_procs.c
This reverts commit 7c433fc30a3ef834165a11d3d9978dacd7ee552d.
It turns out some tests calls these functions directly.
> /kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area …
> Revert "Make internal scap_procs.c functions static"

- cmake/modules/libbpf.cmake
/kind feature
/area build
No
This PR allows to include uapi headers when `libbpf` is compiled in bundled deps, in this way we compile also on old machines which don't have updated system uapi headers
```release-note
NONE
```
> chore(userspace): install also libbpf uapi headers in bundled deps

- driver/ppm_fillers.c
New sched_proc_fork tracepoint handler was created, to compensate for lack of sys_exit tracepoint generated when clone/fork system calls return to the child process.  The new sched_proc_fork handler builds the CLONE_20_X event which would have been built by the missing sys_exit tracepoint.
Two of the fields in the CLONE_20_X are vtid and vpid, the thread ID and process ID of the running thread, IN THE LOCAL PID NAMESPACE of that thread.  The new sched_proc_fork handler has a bug -- it uses the convenience functions task_pid_vnr() and task_tgid_vnr() to retrieve the vtid and vpid; but those functions assume the PID namespace of the executing thread, which in the case of the sched_proc_fork handler, is the parent thread, not the child thread.
Solution is to use task_pid_nr_ns() and …
> Fix vtid/vpid fields in CLONE_20_X event built by sched_proc_fork

- driver/report.md
This PR updates the list of supported syscalls from the latest kernel. Do not edit this PR.
/area driver
```release-note
NONE
```
> update(driver): update syscalls tables.

- userspace/libsinsp/threadinfo.h
> /kind bug
> 
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests …
> chore(userspace/libsinsp): Add getter for the m_parent_loop_detected

- userspace/libsinsp/sinsp.cpp
/kind bug
/area libsinsp
The current timestamp is generally obtained by using the timestamp of the last event received (not super reliable for plugins, but that's out of scope for this PR). Metaevents, which are generated internally by the libraries (and not by the kernel drivers), usually use the last event timestamp in order to break the assumption that events are received with `next()` with a monotonic timestamp.
Now, when creating creating `PPME_PROCINFO_E` metaevents, the event timestamp is set to be _before_ the actual current time. With the old …
> fix(userspace/libsinsp): set current time in procinfo metaevent

- userspace/libscap/engine/kmod/scap_kmod.c
/kind cleanup
When an user with an old driver runs Falco 0.33, Falco shows the wrong error message:
> Error: unable to open '/sys/module/falco/parameters/g_buffer_bytes_dim': Errno 2. Please ensure the kernel module is already loaded.
(See: https://github.com/falcosecurity/falco/issues/2280)
It should instead fail during the driver API/schema version check.
This patch allows the correct message to be displayed by the users, by faking "everything's good" behavior when `g_buffer_bytes_dim` file is missing.
Note: if the file is missing BUT the driver is the new one, it is a super odd …
> chore(userspace/libscap): let the g_buffer_bytes_dim file missing be properly managed during the API version check

- userspace/libsinsp/event.cpp
- userspace/libsinsp/event.h
- userspace/libsinsp/sinsp.cpp
/kind bug
/kind cleanup
/area libsinsp
The changes of https://github.com/falcosecurity/libs/pull/639 and https://github.com/falcosecurity/libs/pull/655 polished the `sinsp_evt` initialization by setting the evt number to 0, which however causes some troubles in case some parts of the inspector's state management logic rely on that value (e.g. plugin field extraction). This PRs fixes this by introducing proper constructors for that class, and reverting the changes of the previous two PRs. …
> fix(userspace/libsinsp): make sinsp_evt initialization consistent

- userspace/libsinsp/sinsp.cpp
Various sinsp logic sets m_tid_to_remove, to record the fact that a thread has been identified as ready-to-be-removed from the threadtable.  And if automatic threadtable purging is configured, sinsp::next() takes care of removing these threads by calling remove_thread(), then clearing m_tid_to_remove.
But remove_thread() may itself set m_tid_to_remove in certain situations. The current sinsp::next() logic loses track of this request; as a result, these threads will languish in the threadtable until the next remove_inactive_threads() interval, default value 20 minutes.
This fix changes the sinsp::next() logic to recognize and handle the case where remove_thread() records a thread for removal.
Signed-off-by: Joseph Pittman <joseph.pittman@sysdig.com>
> Uncomment …
> Fix neglect-to-remove bug in sinsp automatic threadtable purging logic

- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
- userspace/libscap/scap.c
- userspace/libscap/scap.h
/kind feature
/area libscap
No
This PR adds:
* a new API in scap to compute the `semver` check
* a new check in the modern probe engine to ensure that we are on a supported kernel
```release-note
update(modern_bpf_engine): add a check on the minimum kernel version
```
> update(modern_bpf_engine): add a check on the minimum kernel version

- userspace/libscap/engine/gvisor/scap_gvisor.cpp
/kind bug
no
There are several cases in which we could find invalid sandboxes, e.g.:
1. race condition between stopping and querying them
2. on k8s, the pause container
In those cases Falco should not crash, but rather not trace those sandboxes.
Fixes #
The `continue` may look redundant, but I wanted to be explicit when skipping over an error.
```release-note
fix(gvisor): …
```
> fix(gvisor): skip invalid/untraceable sandboxes at startup

- userspace/libscap/scap.c
- userspace/libscap/scap_procs.c
/kind bug
/area libscap
No
Sometimes, on capture start in gvisor and on procfs scan in some cases, errors were not properly passed to caller after the vtable call. This fixes it.
Fixes #
```release-note
fix(libscap,gvisor): fix error handling at capture start and proc scan in some cases
```
> fix(libscap,gvisor): correctly pass errors from init code

- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
/kind bug
No
We need to check that the actual kernel version is greater than the required one, we don't need to apply a semver check!
```release-note
NONE
```
> fix(userspace): check that the actual kernel version is greater than the required one

- userspace/libscap/engine/gvisor/config.json
- userspace/libsinsp/gvisor_config.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> …
> Add `ignore_missing` option to session configuration

- test/modern_bpf/event_class/event_class.cpp
- test/modern_bpf/event_class/network_utils.h
- test/modern_bpf/test_suites/syscall_enter_suite/connect_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/open_by_handle_at_x.cpp
- userspace/chisel/chisel_api.cpp
- userspace/libpman/src/capture.c
- userspace/libpman/src/maps.c
- userspace/libpman/src/ringbuffer.c
- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/savefile/scap_savefile.c
- userspace/libscap/examples/01-open/scap_open.c
- userspace/libscap/windows_hal.c
- userspace/libsinsp/event.cpp
- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/ifinfo.cpp
- userspace/libsinsp/ifinfo.h
- userspace/libsinsp/ifinfo_test.cpp
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/utils.cpp
- userspace/plugin/plugin_loader.c
/kind cleanup
/area libsinsp
/area libscap
/area tests
No
I would like to remove all usage of functions such as `strcpy`, `sprintf`, `strncpy` even if they are used safely. For copying strings we have a safer alternative called `strlcpy` (see the original [whitepaper](https://www.usenix.org/legacy/publications/library/proceedings/usenix99/full_papers/millert/millert.pdf) from 1999). It is way too easy to mess up when using the standard libc functions. Indeed, the main falco repo already removed that function usage via a …
> cleanup(libsinsp,libscap): remove error-prone string functions (even if used safely)

- userspace/libscap/engine/bpf/scap_bpf.c
/kind bug
NOPE
Revert a bug introduced in #374: use same code used by kmod engine to properly load all CPUs and online CPUs, to be later able to properly count online CPUs.
Fixes #720 
```release-note
fix(libscap): fixed loading of ebpf probe with offline CPUs
```
> fix(userspace/libscap): fixed loading of ebpf probe with offline CPUs

- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libscap/scap.c
- userspace/libscap/scap_procs.c
This PR updates the 0.9.2 release branch with the gVisor bugfixes.
```release-note
fix(gvisor): prevent libscap crashes by skipping invalid/untraceable sandboxes at startup
fix(libscap,gvisor): fix error handling at capture start and proc scan in some cases
```
> Sync changes for 0.9.2: gvisor bugfixes

- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.h
/kind feature
No
This PR reduces the number of timeouts in the modern bpf probe
```release-note
NONE
```
> update(driver): add a backoff in case of modern probe timeout

- userspace/libscap/engine/kmod/scap_kmod.c
- userspace/libscap/linux/scap_procs.c
- userspace/libscap/scap-int.h
- userspace/libscap/scap_procs.c
- userspace/libscap/win32/scap_procs.c
SCAP_HANDLE_T must be defined before including scap_open.h (which gets included from kmod.h)
Also, remove a few unnecessary `#include`s; in particular, including engine internal headers shouldn't be needed (any more; it was a temporary measure during the engine refactor)
```
/draios/falco-libs/userspace/libscap/engine/kmod/scap_kmod.c:26:0: error: "SCAP_HANDLE_T" redefined [-Werror]
#define SCAP_HANDLE_T struct kmod_engine
^
In file included from /draios/falco-libs/userspace/libscap/engine/kmod/kmod.h:21:0,
from /draios/falco-libs/userspace/libscap/engine/kmod/scap_kmod.c:25:
/draios/falco-libs/userspace/libscap/scap_open.h:24:0: note: this is the location of the previous definition
#define SCAP_HANDLE_T void
^
``` …
> Fix kmod build error

- userspace/libscap/engine/gvisor/runsc.cpp
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
/kind cleanup
no
I noticed we had a max string length. This is ok for now, but perhaps on big containers we may have a problem. Remove this issue by using C++ stream readers.
Fixes #
```release-note
cleanup(gvisor): remove max string length for runsc read
```
> cleanup(gvisor): remove max string length for runsc read

- test/e2e/containers/sinsp.Dockerfile
- test/e2e/tests/commons/sinspqa/sinsp.py
- test/e2e/tests/conftest.py
- test/e2e/tests/test_event_generator/test_db_program_spawned_process.py
- test/e2e/tests/test_event_generator/test_run_shell_untrusted.py
- test/e2e/tests/test_event_generator/test_system_user_interactive.py
- test/e2e/tests/test_process/test_container.py
- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/procfs_utils.cpp
- userspace/libsinsp/procfs_utils.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/test/user.ut.cpp
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/user.cpp
- userspace/libsinsp/user.h
/kind feature
/area libsinsp
/area tests
Introduce `add_container_user` and `add_container_group`.
Those are called by `sinsp_threadinfo` `set_user` / `set_group` and load the information from /proc/<pid>/root/etc.
For that to work, the process running sinsp has to be privileged and in the host pid namespace.
For more information see `man 5 proc`.
Fixes #
```release-note
NONE
```
> container users and groups from process root

- userspace/libscap/examples/01-open/scap_open.c
- userspace/libscap/scap.c
- userspace/libsinsp/examples/test.cpp
/kind cleanup
/area libscap
NOPE
Right now, `scap_open` does also start driver capture. `scap_close` instead, is not stopping the capture.
I think the best way is to allow consumers to open scap without starting any capture; therefore this PR forces consumers to manually call `scap_start_capture()` and `scap_stop_capture()`.
Fixes #
```release-note
cleanup(userspace/libscap): `scap_open` won't autostart the capture anymore. Instead, consumers should manually start it.
```
> cleanup(userspace/libscap): scap_open should not start capture.

- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libscap/scap.h
- userspace/libscap/scap_savefile.c
- userspace/libsinsp/sinsp.cpp
All the juggling we do with refresh_proc_table_when_saving can be simplified to the point where we remove the flag completely from libscap (and leave the corresponding flag in sinsp since it has multiple meanings)
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area …
> Remove refresh_proc_table_when_saving from scap_t

- userspace/libscap/linux/scap_procs.c
/kind bug
/area libscap
When going through the `/proc` directory in search of information for existing processes, there is an inconsistency in how the cgroup lines are captured. For cgroups v1, the newline character is discarded by this line: https://github.com/falcosecurity/libs/blob/0fedd768602c39ab9d07bfee73bbd46d0acc836c/userspace/libscap/linux/scap_procs.c#L466 
However, cgroup v2 uses the read string as is: https://github.com/falcosecurity/libs/blob/0fedd768602c39ab9d07bfee73bbd46d0acc836c/userspace/libscap/linux/scap_procs.c#L455
Ultimately, this would not be such a big deal, except when you find a …
> fix(libscap): consistently remove the newline character from cgroups read from proc

- test/e2e/CMakeLists.txt
- test/e2e/tests/test_process/test_container.py
- userspace/libsinsp/threadinfo.cpp
/kind bug
/area libsinsp
/area tests
Container events with uid / gid `0` have `<NA>`  for name and homedir. Set a fallback for those.
Fixes #
```release-note
fix(userspace/libsinsp): uid/gid 0 fallback to `root` in case of missing data from sinsp_usergroup_manager
```
> Fix user and group data for uid/gid 0 being reported as <NA>

- userspace/libscap/scap.h
- userspace/libscap/scap_const.h
- userspace/libscap/strerror.c
We're forcing the XSI-compliant version. It's complicated:
https://linux.die.net/man/3/strerror_r
Since the `_POSIX_C_SOURCE` and `_GNU_SOURCE` are fairly
fundamental, play it ultra safe and don't include scap.h with these
two set to a potentially different value from the rest of the code.
This is a good excuse to introduce scap_const.h, which only contains
a few `#define`s used all over the place. I'd expect many of the
`#include "scap.h"` occurrences are for these constants only
so we might be able to speed up rebuilds a  bit.
/kind bug
> /kind design
> Uncomment one (or more) `/area …
> fix(scap): use strerror_r return value

- userspace/libscap/engine/udig/scap_udig.c
- userspace/libscap/engine/udig/udig.h
- userspace/libscap/ringbuffer/devset.c
- userspace/libscap/ringbuffer/devset.h
- userspace/libscap/scap.h
```
D:\a\libs\libs\userspace\libscap\ringbuffer\../scap.h(67,1): warning C4005: 'MAP_FAILED': macro redefinition [D:\a\libs\libs\build\libscap\scap_engine_util.vcxproj]
D:\a\libs\libs\userspace\libscap\ringbuffer\devset.c(11): message : see previous definition of 'MAP_FAILED' [D:\a\libs\libs\build\libscap\scap_engine_util.vcxproj]
D:\a\libs\libs\userspace\libscap\ringbuffer\devset.c(20,20): warning C4267: '=': conversion from 'size_t' to 'uint32_t', possible loss of data [D:\a\libs\libs\build\libscap\scap_engine_util.vcxproj]
D:\a\libs\libs\userspace\libscap\ringbuffer\devset.c(75,4): warning C4013: 'close' undefined; assuming extern returning int [D:\a\libs\libs\build\libscap\scap_engine_util.vcxproj]
```
This change is more involved than the minimum fix, since it moves some of the …
> fix(scap): Fix Windows build warnings

- driver/bpf/fillers.h
- driver/flags_table.c
- driver/modern_bpf/helpers/extract/extract_from_kernel.h
- driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c
- driver/ppm_events_public.h
- driver/ppm_fillers.c
- driver/ppm_flag_helpers.h
- userspace/libscap/scap.h
- userspace/libscap/scap_savefile.c
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/threadinfo.h
> /kind bug
> /kind design
/kind feature
> /area build
/area libscap
/area libsinsp
> /area tests
This PR tries to deal with `overlayfs`, a union mount filesystem often used by container runtimes, to understand if a process is executing something that is part of the base image of a container or not. Monitoring this could be relevant from a security standpoint since best practices state that containers should be immutable. For this reason, in many use cases, we don't …
> new: introduce `is_exe_upper_layer`

- userspace/libsinsp/event.cpp
- userspace/libsinsp/user.cpp
- userspace/libsinsp/user.h
/kind bug
/area libsinsp
Having conditionals in public headers is not good: clients of libs will find that their linked libsinsp sees a `sizeof(foo)` different from what client sees including the headers, unless the macro is manually defined for client too.
In our case, Falco was seeing different sizes for usergroup_manager class than sinsp, because it hadn't got `HAVE_PWD_H` and `HAVE_GRP_H` defined. Therefore a SIGABRT was killing it (see https://github.com/falcosecurity/falco/pull/2302).
Fixes # …
> fix(userspace/libsinsp): avoid having compile time conditionals in public headers

- driver/modern_bpf/helpers/store/auxmap_store_params.h
- test/modern_bpf/event_class/event_class.cpp
/kind bug
This PR fixes an issue in the modern bpf probe. In the other 2 drivers (current bpf, kernel module) in network functions, we send the socket_tuple in the following way:
```
- ip
- port
- ip
- port
```
For some reason (:man_artist:) in the modern probe, I've chosen another other 
```
- ip
- ip
- port
- port
``` 
This PR updates the modern probe to use the first order like other drivers:
```
- ip
- port
- ip
- port
```
I've fixed also tests to follow this new order …
> fix(driver/modern_bpf): fix params order in modern probe network functions

- userspace/libscap/CMakeLists.txt
- userspace/libscap/scap.c
- userspace/libscap/scap_savefile.c
In most places, `HAS_CAPTURE` is only used to determine a better error message in a situation that shouldn't ever happen anyway (no handle->m_vtable).
In the last place, it's an elaborate replacement for `__linux__` (which should be cleaned up anyway but let it live for now).
`CYGWING_AGENT` is historical cruft, shouldn't be needed any more (including sinsp, but this PR does not touch it)
> /kind bug
/kind cleanup
> /kind design
/area build
> /area CI
> /area …
> Remove CYGWING_AGENT and HAS_CAPTURE from libscap

- userspace/libsinsp/gen_filter.cpp
- userspace/libsinsp/gen_filter.h
/kind cleanup
/area libsinsp
No
Fix a wrong license header introduced by mistake.
Fixes #
```release-note
NONE
```
> chore(libsinsp/gen_filter): correct wrong license header

- userspace/libsinsp/examples/test.cpp
/kind bug
/area libsinsp
None
sinsp-example cannot run with --modern_bpf option
[#756](https://github.com/falcosecurity/libs/issues/756)
```release-note
NONE
```
>  fix(sinsp-example): parse cli options missing -m

- userspace/libscap/linux/scap_procs.c
If Linux kernel is built with CONFIG_AUDIT=n, /proc loginuid file is not available to provide the loginuid of the process.  Instead of failing to add process into libscap thread table, record process loginuid=-1 instead.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
> fix(scap): Fill thread loginuid with default value -1, if /proc loginuid is unavailable

- userspace/libsinsp/parsers.cpp
This avoids a crash due to dereferencing a dangling pointer, in the rare case where parent thread_info is present but invalid
so the code deletes the object and tries to create a new one (get_thread_ref), but that function fails
/kind bug
> /kind design
> /area build
> /area CI
> /area …
> fix(sinsp): don't return invalid tinfos in clone events

- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fork.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/vfork.bpf.c
/kind bug
No
This PR fixes some typos, we need to extract the `gid` instead of the `uid`
```release-note
NONE
```
> fix(driver): use `extract__egid` instread of `extract__euid` helper

- userspace/libsinsp/container_info.h
This change increases the number of retries to retrieve container information from CRI API from 3 to 5, as several failures were observed with the maximum number of attempts set to 3.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
> fix: increase the number of attempts to retrieve container info from CRI

- driver/bpf/fillers.h
- driver/modern_bpf/helpers/extract/extract_from_kernel.h
- driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area tests
> …
> cleanup(driver):  cleanup nested lookups

- userspace/libsinsp/container_engine/cri.cpp
- userspace/libsinsp/container_info.h
- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/container_info.ut.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> fix: set max retries to 5 when using CRI only

- README.md
- driver/modern_bpf/CMakeLists.txt
- userspace/libpman/CMakeLists.txt
- userspace/libscap/engine/modern_bpf/CMakeLists.txt
/kind feature
/area build
No
This PR allows us to build the modern bpf skeleton on another machine and to include it inside another build flow, an example is the CI job in the PR... we craft the skeleton on an ubuntu 22.04 machine where we have all the toolchain and then we port the skeleton into a centos7 container to have a lower GLIBC version inside the `scap-open` executable
> NOTE: the CI job and the docker image will be removed before merging the PR I use them to test the correct behavior.
Fixes # …
> chore(driver): support external skeleton build for modern bpf

- cmake/modules/libelf.cmake
/kind cleanup
/area build
No
This PR should solve issues when not using bundled dependencies, for example here we allow other libraries to depend on `libelf` even if it is not bundled, in this way we don't have to manage the bundled case in a different way
```release-note
NONE
```
> chore(userspace): manage not bundled libelf dependency adding a custom target

- driver/modern_bpf/helpers/store/auxmap_store_params.h
- driver/modern_bpf/helpers/store/ringbuf_store_params.h
- userspace/libpman/src/capture.c
/kind bug
No
This PR carries 2 fixes:
* allow computing the sum of all drops (full ring buffer + event too large) like in all our drivers.
* unify the logic between our drivers. In our drivers `n_evts` is the number of events that the driver should send to userspace according to its configuration. So this counter includes also the number of drops (for example due to full buffers). Before this patch, the modern probe didn't consider drops inside the `n_evts`.
**Does this PR introduce …
> fix: unify dropping management in modern bpf probe

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/access.bpf.c
- test/modern_bpf/test_suites/syscall_enter_suite/access_e.cpp
- test/modern_bpf/test_suites/syscall_exit_suite/access_x.cpp
- userspace/libpman/src/events_prog_names.h
Add modern probe for access() system call.
> /kind bug
> /kind design
> /area build
> /area CI
> /area tests
**Does this PR require a change in the driver …
> new(modern_probe): Add access()

- test/e2e/tests/test_event_generator/test_non_sudo_setuid.py
- userspace/libsinsp/examples/test.cpp
- userspace/libsinsp/procfs_utils.cpp
- userspace/libsinsp/procfs_utils.h
- userspace/libsinsp/user.cpp
/kind feature
/area libsinsp
Instead of checking /proc/<pid>/ns/mnt, just check /proc/<pid>/root inode. The mount namespace gets created before the process actually gets into that namespace, so it was flaky and we also had a workaround getting it to work only for containers being created with non-root user.
Fixes #
```release-note
update(userspace/libsinsp): rely on proc root for user and group container lookup
```
> update(userspace/libsinsp): rely on proc root

- userspace/libsinsp/container_engine/cri.cpp
- userspace/libsinsp/cri.cpp
With the different CRI runtimes and the different ways to start
a container, it's not always trivial to find all the image metadata
(id, repo, tag, digest).
When running a container as `host/image@sha256:digest`, we have to
fetch the tag from the `Image` field, not `ImageRef`.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
> fix(sinsp): Get CRI image metadata both from image and imageRef

- cmake/modules/curl.cmake
- userspace/libsinsp/mesos_http.cpp
/kind feature
/area build
No
Update libcURL to the latest version, fixing 7 potential security vulnerabilities (none of them critically impacting Falco as far as I understand) disclosed in the last months, including CVE-2022-43551 and CVE-2022-43552 disclosed today. See: https://curl.se/docs/security.html .
Fixes #
```release-note
NONE
```
> update(build): update libcurl to 7.87.0

- userspace/libsinsp/parsers.cpp
Signed-off-by: Adnan Ali <adduali1310@hotmail.com>
/kind bug
/area libsinsp
This PR adds a safety check to validate if thread information is available before trying to dereference it when parsing the capset_exit event.
Should be a straightforward change and follows other such checks within the code file as mentioned in the issue.
Fixes #817 
NONE
> fix: handle capset_x missing thread_info

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/helpers/base/maps_getters.h
- driver/modern_bpf/maps/maps.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/generic.bpf.c
- test/drivers/event_class/event_class.cpp
- test/drivers/test_suites/syscall_enter_suite/generic_e.cpp
- test/drivers/test_suites/syscall_exit_suite/generic_x.cpp
- userspace/libpman/src/events_prog_names.h
- userspace/libpman/src/maps.c
/kind feature
/area tests
No
This PR allows us to send generic events (`PPME_GENERIC_E` and `PPME_GENERIC_X`) for not implemented syscalls like in the old drivers
```release-note
NONE
```
> new(driver): implement generic events support in modern bpf probe

- release.md
Instead of using current `release/0.10.0` naming, that enforces us to create a new release branch for each patch release in the `M.m` series, enforce the usage of `release/0.10.x` naming, so that multiple subsequent tags on the same release branch are allowed.
Fixes #
```release-note
NONE
```
> update(docs): updated release document to enforce `release/M.m.x` release branch names

- driver/modern_bpf/maps/maps.h
- userspace/libpman/include/libpman.h
- userspace/libpman/src/capture.c
- userspace/libpman/src/configuration.c
- userspace/libpman/src/lifecycle.c
- userspace/libpman/src/maps.c
- userspace/libpman/src/ringbuffer.c
- userspace/libpman/src/state.c
- userspace/libpman/src/state.h
- userspace/libscap/engine/modern_bpf/modern_bpf_public.h
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.h
- userspace/libscap/examples/01-open/scap_open.c
- userspace/libscap/test/CMakeLists.txt
- userspace/libscap/test/README.md
- userspace/libscap/test/test_suites/engines/modern_bpf/modern_bpf.cpp
- userspace/libsinsp/examples/test.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
I want to highlight that these features are experimental, which means they could change over libs releases. More in general all the modern probe is still experimental so don't expect to have a stable interface at least for this release :)
/kind feature
/area libpman
/area tests
No
The way in which the modern probe references memory is a little bit different from the old BPF probe.
Usually, we ask our drivers to open an 8 MB buffer for every CPU, so the kernel allocates 8 MB, and then the userspace map this memory 2 times in order to efficiently read …
> new(modern_bpf):  [EXPERIMENTAL] support variable number of ring buffers and online CPUs

- userspace/libsinsp/sinsp.cpp
/kind bug
/area libsinsp
When a node name is passed to the k8s client filtering, we throw an exception in case the node name is not found in the reconstructed k8s cluster state. However, this does not distinguish bad node names from unexpected/unpredictable parsing errors during the k8s cluster stare reconstruction. Since an exception can be blocking and cause consumers like Falco to terminate, the best option we have from a security/availability perspective is to log with error level instead of throwing an exception.
Of course, this is a workaround and not a concrete long-term solution. Here, we are giving …
> fix(userspace/libsinsp): avoid exception failure on unknown k8s node name

- driver/bpf/probe.c
/kind bug
Nope
This is an attempt to fix a build issue on some kernels, eg: https://gist.github.com/renescheepers/6b8b60d7d482490291ad0394b45a7afc
Since the `asm/rwonce.h` header is only present since kernel 5.9, i used the compiler extension `__has_include`.
This compiler extension is part of c++17 standard, and available in clang and gcc.
* GCC supports it since gcc5 (https://gcc.gnu.org/projects/cxx-status.html)
* Clang always supported it (or at the bare minimum, since clang5, that is the first version with full c++17 support) (https://clang.llvm.org/cxx_status.html)
Since bpf build uses …
> fix(driver/bpf): properly include asm/rwonce, that is sometimes needed.

- driver/syscall_table.c
Currently, getsockopt is *not* dropped when the driver is in dropping mode, while setsockopt is dropped (it has the UF_ALWAYS_DROP) flag.
There isn't any reason to treat the two syscalls differently with respect to dropping mode--they're both infrequent and most applications are going to do both if they do either.
So remove the UF_ALWAYS_DROP flag for setsockopt so both are included when in dropping mode, for consistency.
/kind bug
> /kind design
> /area build
> /area CI
/area …
> Align both {set,get}sockopt to be treated equally wrt UF_NEVER_DROP

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filter.h
- userspace/libsinsp/filter/ast.cpp
- userspace/libsinsp/filter/ast.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> Add const_expr_visitor, use it when compiling/cloning/stringing

- test/drivers/start_tests.cpp
/kind bug
/area tests
No
This PR allows us to pass arguments to the test executable with a space, for example, before this patch we can pass arguments only in the following way `-b./path/to/probe` now we can do also something like `-b ./path/to/probe`
```release-note …
```
> tests: allow user to pass arguments with a space

- .github/workflows/ci.yml
- driver/bpf/filler_helpers.h
- driver/bpf/fillers.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/getsockopt.bpf.c
- driver/ppm.h
- driver/ppm_events.c
- driver/ppm_events.h
- driver/ppm_fillers.c
- driver/ppm_flag_helpers.h
- test/drivers/event_class/event_class.cpp
- test/drivers/test_suites/syscall_enter_suite/prlimit64_e.cpp
- test/drivers/test_suites/syscall_exit_suite/clone3_x.cpp
- test/drivers/test_suites/syscall_exit_suite/clone_x.cpp
- test/drivers/test_suites/syscall_exit_suite/fork_x.cpp
- test/drivers/test_suites/syscall_exit_suite/mlock2_x.cpp
/kind bug
/kind feature
/area tests
No
This PR belongs to the https://github.com/falcosecurity/libs/pull/783 series. It fixes some differences between the 3 drivers. It tries also to simplify code paths where possible.
I've to check the CI part, but I've tested it locally on the following machines:
* 5.11.0-051100 (x86)
* 5.15.0-1023 (x86)
* 4.14.276 (x86)
* 4.14.276 (aarch64)
* 5.15.0-1019 (aarch64)
* 5.11.0-051100 (s390x)
* 5.15.0-56-generic (s390x) …
> fix(driver): extend modern bpf test framework to all drivers (part 5)

- userspace/libsinsp/parsers.cpp
Signed-off-by: Adnan Ali [adduali1310@hotmail.com]
/kind bug
/kind cleanup
/area libsinsp
no
This PR is made of 2 commits:
Commit1: (fix)
Adds a safety check to validate if thread information is available before trying to dereference it when parsing the unshare_setns_exit event. Follows https://github.com/falcosecurity/libs/pull/818 to avoid further segfaults I encountered in specific parsers.
Commit2: (chore)
Performs a cleanup and follows a consistent method of thread information validation rather than having multiple different ways to check the same condition within a file making it very confusing and …
> fix: handle unshare_setns_x missing thread_info, chore: thread_info check cleanups

- cmake/modules/grpc.cmake
When building with the bundled grpc on big-endian platforms, the`libabsl_random_internal_platform.a` needs to be after the other `libabsl_random_internal_*` libraries to avoid undefined references when linking.
Signed-off-by: Jonathan Albrecht <jonathan.albrecht@ibm.com>
/kind bug
/area build
no
Fixes the build on s390x when using `-DUSE_BUNDLED_DEPS=On` which has an error like:
```
[ 98%] Linking CXX executable unit-test-libsinsp
/usr/bin/ld: ../../grpc-prefix/src/grpc/third_party/abseil-cpp/absl/random/libabsl_random_internal_randen_slow.a(randen_slow.cc.o): in function …
```
> fix(cmake): fix bundled GRPC_LIBRARIES order

- README.md
`HAVE_SYSCALL_TRACEPOINTS` was added to arm64 in linux 3.16: https://github.com/torvalds/linux/commit/055b1212d141f1f398fca548f8147787c0b6253f
Properly bump minimum kver to build kmod on arm64.
Fixes #
```release-note
NONE
```
> fix(readme): minimum kver to build kmod on arm64 is 3.16.

- userspace/libscap/engine/noop/CMakeLists.txt
- userspace/libscap/linux/CMakeLists.txt
- userspace/libscap/macos/CMakeLists.txt
- userspace/libscap/win32/CMakeLists.txt
/kind bug
/area build
/area libscap
When building with a bundled zlib, in a system without system zlib headers installed (ie: an ubuntu:22.04 docker image), parallel build of scap fails with:
```
In file included from /libs/userspace/libscap/scap_savefile_api.h:24,
from /libs/userspace/libscap/scap.h:21,
from /libs/userspace/libscap/engine/noop/noop.c:29:
/libs/userspace/libscap/scap_zlib.h:23:10: fatal error: zlib.h: No such file or directory
23 | #include <zlib.h>
```
Or, with just the scap_noop engine patch applied, with:
```
In file included from /libs/userspace/libscap/scap_savefile_api.h:24,
from …
```
> fix(userspace/libscap): fix build with bundled zlib and `-jX` parallel build

- test/drivers/helpers/proc_parsing.cpp
- test/drivers/helpers/proc_parsing.h
- test/drivers/test_suites/generic_tracepoints_suite/sched_switch.cpp
- test/drivers/test_suites/syscall_exit_suite/clone3_x.cpp
- test/drivers/test_suites/syscall_exit_suite/clone_x.cpp
- test/drivers/test_suites/syscall_exit_suite/execve_x.cpp
- test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp
- test/drivers/test_suites/syscall_exit_suite/fork_x.cpp
/kind bug
/area tests
No
Some data extracted from proc are not so reliable like `vm_rss` `vm_size` `vm_swap`, the CI is failing for this reason. This is an example: https://github.com/falcosecurity/libs/actions/runs/4043114894/jobs/6951658048#step:6:537
```
/home/runner/work/libs/libs/test/drivers/event_class/event_class.cpp:506: Failure
Expected: (*(T*)(m_event_params[m_current_param].valptr)) >= (param), actual: 14116 vs 14120
```
When we extract the `vm_rss` from proc its value is `14120` but when we assert the value is lower, this is obviously possible, quite unfortunate but possible
Instead of using the …
> fix(tests): `vm_...` extracted from proc are not reliable

- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/kmod/scap_kmod.c
- userspace/libscap/linux/scap_fds.c
- userspace/libscap/linux/scap_procs.c
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/sinsp_auth.cpp
/kind cleanup
/area libscap
/area libsinsp
This brings a couple of minor cleanups on buffer reads and releasing allocated mem before returning with an error.
```release-note
NONE
```
> fix(userspace): release unused resources on error and cleanup buffer reads

- driver/bpf/fillers.h
- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/io_uring_enter.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/io_uring_register.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/io_uring_setup.bpf.c
- driver/ppm_fillers.c
- test/drivers/test_suites/syscall_enter_suite/io_uring_enter_e.cpp
- test/drivers/test_suites/syscall_enter_suite/io_uring_register_e.cpp
- test/drivers/test_suites/syscall_enter_suite/io_uring_setup_e.cpp
- test/drivers/test_suites/syscall_exit_suite/io_uring_enter_x.cpp
- test/drivers/test_suites/syscall_exit_suite/io_uring_register_x.cpp
- test/drivers/test_suites/syscall_exit_suite/io_uring_setup_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind feature
/area libpman
/area tests
No
On one side this PR supports 3 missing syscalls in the modern bpf probe https://github.com/falcosecurity/libs/issues/723:
*  `io_uring_enter`
*  `io_uring_register`
*  `io_uring_setup`
On the other side it unifies the behavior of this syscall between our 3 drivers:
* file descriptor managed on 64 bit
* send event even when the pointer to `struct io_uring_params` is invalid
```release-note …
```
> new(driver): unify support for `io_uring` syscall family between drivers

- userspace/libsinsp/filter/parser.h
- userspace/libsinsp/filter_value.h
/kind cleanup
/area libsinsp
No
Fixes a build error found by upcoming new GCC compiler ( 13.x release )
gcc 13 moved some [includes](https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes) around and as a result <cstdint> is no longer transitively included. Explicitly include it for uintXX_t.
Fixes #
```release-note
NONE
```
> Add <cstdint> for uintXX_t types

- .github/workflows/ci.yml
- CMakeLists.txt
- test/libscap/CMakeLists.txt
- test/libscap/README.md
- test/libscap/helpers/engines.cpp
- test/libscap/helpers/engines.h
- test/libscap/libscap_test_var.h.in
- test/libscap/test_suites/engines/bpf/bpf.cpp
- test/libscap/test_suites/engines/gvisor/gvisor_parsers.cpp
- test/libscap/test_suites/engines/kmod/kmod.cpp
- test/libscap/test_suites/engines/modern_bpf/modern_bpf.cpp
- test/libscap/test_suites/generic/scap_event.cpp
- userspace/libscap/engine/kmod/scap_kmod.c
- userspace/libscap/scap.c
/kind cleanup
/kind feature
/area CI
/area tests
No
This PR moves all libscap tests into the `test` folder and adds some tests for engines `modern_bpf`, `bpf`, `kmod`. The PR is just a proposal, if you have other ideas or suggestions on how to do that I'm all ears.
RIght now this PR moves only the existing tests to the new directory and add some new ones, the old libscap tests are still there because we need to change a little bit our CI job before doing the switch
```release-note
NONE
```
> tests(userspace/libscap): move libscap tests into `test` folder and add engine specific tests 

- driver/modern_bpf/CMakeLists.txt
- userspace/libpman/src/ringbuffer.c
- userspace/libpman/src/state.h
- userspace/libscap/engine/modern_bpf/CMakeLists.txt
/kind feature
No
This PR brings to the table some improvements in the modern  bpf build:
* check on minimum kernel version at build time (>=5.8), only if `MODERN_BPF_SKEL_DIR` is not specified
* check on clang version (>=12)
* `MODERN_CLANG_EXE` to specify a custom clang exe
* `MODERN_BPFTOOL_EXE` to specify a custom bpftool exe
```release-note
NONE
```
> chore: improve modern bpf probe build phase

- driver/bpf/bpf_helpers.h
- driver/bpf/filler_helpers.h
- driver/bpf/fillers.h
- driver/bpf/plumbing_helpers.h
- driver/feature_gates.h
- driver/ppm_fillers.c
/kind feature
/kind bug
tbd
This PR introduces the `bpf_probe_read_user` and `bpf_probe_read_kernel` variants to correctly read memory either from kernel or user space. This PR would also be the base to enable the BPF driver for the `s390x` architecture as well. Please note that for `s390x` there is yet another issue to be solved (here and in modern-bpf as well): …
> new(bpf-driver): Introduce `bpf_probe_read_user` and `bpf_probe_read_kernel` variants

- userspace/libscap/linux/scap_procs.c
- userspace/libscap/scap-int.h
- userspace/libsinsp/parsers.cpp
tid != vtid is not necessary (though sufficient) to check if a thread is in a child pid namespace. This leads to pidns_start_ts being wrong occasionally (when a thread happens to have tid == vtid by chance, even if it's in a child pidns).
Note: the name of the flag (`PPM_CL_CHILD_IN_PIDNS`) isn't the best for this use case but it effectively means what we want ("we *know* this thread is in a child pidns, even if tid == vtid")
/kind bug
> /kind design
> /area build
> /area CI
> /area …
> fix(scap): properly detect threads in child pidns during /proc scan

- .circleci/config.yml
/kind feature
/area CI
No
Now that we have a working framework test for all our 3 drivers it would be amazing to run it on all the supported architectures. Right now Github Actions don't support arm64 machine, for this reason, I would to introduce a very simple CircleCI job to run tests on arm64. If in the next future, we will find other solutions (like self-hosted runners) we can remove this job but right now it seems a good way to go, WDYT?
Unfortunately `s390x` is not supported by either GHA or circleCI, so we don't have any solution :( …
> new(ci): add a circleCI job to test drivers on arm64

- driver/bpf/fillers.h
/kind bug
This fixes a couple of issues spotted while running a probe built with clang 15:
```
clang -v
clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/12.2.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```
Below the verifier details:
```
math between map_value pointer and register …
```
> fix(bpf): fixed a couple of clang15 verifier issues.

- .circleci/config.yml
/kind bug
/area CI
No
For some reason yesterday we didn't need `DEBIAN_FRONTEND=noninteractive` in our jobs but today `circleCI` wants it otherwise the job will face a context deadline exceeded
```release-note
NONE
```
> fix(CI): add `DEBIAN_FRONTEND=noninteractive` in arm64 jobs

- cmake/modules/curl.cmake
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>
/kind bug
> /kind design
/area build
> /area CI
> /area tests
**Does this PR …
> fix(libcurl): set path to ca-certificates at build time for libcurl

- driver/CMakeLists.txt
- driver/bpf/CMakeLists.txt
- driver/modern_bpf/CMakeLists.txt
/kind cleanup
/area build
Adds a configure time check for:
* kmod
* ebpf
Much similar to the modern bpf one (added in #863).
Example output:
```
CMake Error at driver/bpf/CMakeLists.txt:18 (message):
[BPF] Linux kernel version should be >= 6.14 but actual kernel version is:
6.1.9-arch1-2
```
```
CMake Error at driver/CMakeLists.txt:27 (message):
[KMOD] Linux kernel version should be >= 6.6 but actual kernel version is:
6.1.9-arch1-2
```
(Notice i had to bump minimum kernel version to a version > than mine, to check ;) )
Fixes #
See …
> chore(driver): check minimum kernel versions for each driver.

- driver/bpf/plumbing_helpers.h
- driver/bpf/probe.c
- driver/main.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/vfork.bpf.c
/kind cleanup
No
* When `CAPTURE_SCHED_PROC_FORK` is enabled we generate `clone/fork-family` child exit events from a dedicated tracepoint, so we don't need to catch them from `sys_exit` tracepoint otherwise we will have duplicated events.
* When `CAPTURE_SCHED_PROC_EXEC` is enabled we generate `execve-family` successful events from a dedicated tracepoint, so we don't need to catch them from `sys_exit` tracepoint otherwise we will have duplicated events.
This PR should enforce the behavior between the 3 drivers 
See this conversation: …
> cleanup(driver): uniform feature gates between drivers

- driver/bpf/fillers.h
- driver/event_table.c
- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/helpers/base/push_data.h
- driver/modern_bpf/helpers/extract/extract_from_kernel.h
- driver/modern_bpf/helpers/store/auxmap_store_params.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/mmap2.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/poll.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/ppoll.bpf.c
- driver/ppm_fillers.c
- test/drivers/README.md
- test/drivers/event_class/event_class.cpp
- test/drivers/event_class/event_class.h
- test/drivers/test_suites/syscall_enter_suite/mmap2_e.cpp
- test/drivers/test_suites/syscall_enter_suite/poll_e.cpp
- test/drivers/test_suites/syscall_enter_suite/ppoll_e.cpp
- test/drivers/test_suites/syscall_exit_suite/mmap2_x.cpp
- test/drivers/test_suites/syscall_exit_suite/poll_x.cpp
- test/drivers/test_suites/syscall_exit_suite/ppoll_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind bug
/kind feature
/area tests
No
On one side this PR supports 3 missing syscalls in the modern bpf probe https://github.com/falcosecurity/libs/issues/723:
*  `poll`
*  `ppoll`
*  `mmap2`
On the other side, it unifies the behavior of this syscall between our 3 drivers:
* send event even when the pointer is invalid
```release-note
new(driver): unify support for some new syscalls between drivers
```
> new(driver): unify support for some new syscalls between drivers 1/n

- .github/workflows/ci.yml
/kind cleanup
/area CI
No
No we have arm64 jobs on circleCI so we don't need anymore these QEMU jobs
```release-note
NONE
```
> ci: remove arm64 jobs from GHA

- .github/workflows/ci.yml
- semgrep/insecure-api-gets.yaml
- semgrep/insecure-api-sprintf-vsprintf.yaml
- semgrep/insecure-api-strcpy-stpcpy-strcat.yaml
- semgrep/insecure-api-strncpy.yaml
/kind feature
/area CI
No
There are some functions that we prefer not to use in the Falco codebase, namely `strcpy()` (most of it), `sprintf()`... because it's way too easy to misuse them and introduce security issues in the process.
While it's possible to use these functions safely we prefer not to have them entirely. We devoted some efforts to remove all of their instances in the libs codebase but there's nothing preventing anyone from adding them again. To make contributors' …
> new(ci): add semgrep checks for insecure API usage

- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/helpers/base/common.h
- driver/modern_bpf/helpers/base/maps_getters.h
- driver/modern_bpf/helpers/extract/extract_from_kernel.h
- driver/modern_bpf/helpers/interfaces/attached_programs.h
- driver/modern_bpf/maps/maps.h
- driver/modern_bpf/programs/attached/dispatchers/syscall_enter.bpf.c
- driver/modern_bpf/programs/attached/dispatchers/syscall_exit.bpf.c
- driver/modern_bpf/programs/attached/events/sched_process_exit.bpf.c
- driver/modern_bpf/programs/attached/events/sched_switch.bpf.c
- driver/modern_bpf/shared_definitions/struct_definitions.h
- test/drivers/event_class/event_class.cpp
- test/drivers/event_class/event_class.h
- test/drivers/test_suites/actions_suite/sampling_ratio.cpp
- userspace/libpman/include/libpman.h
- userspace/libpman/src/maps.c
- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
- userspace/libscap/engine/udig/scap_udig.c
- userspace/libscap/scap.c
/kind feature
No
This PR implements the sampling ratio logic already present in the other 2 drivers (kmod,  bpf). Note that this logic is disabled by default like in the other 2 drivers, and you can enable it with the same `scap` APIs
This PR is part of the modern bpf feature parity issue: https://github.com/falcosecurity/libs/issues/723
```release-note
NONE
```
> new(driver): support sampling ratio in the modern bpf probe 

- .github/workflows/ci.yml
- .github/workflows/insecure-api.yml
/kind bug
/area CI
Fixes master CI. Insecure api job should only run on PRs.
Fixes #
```release-note
NONE
```
> fix(ci): split insecure-api check from ci; it will be triggered only on PRs

- driver/feature_gates.h
- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/definitions/missing_definitions.h
- driver/modern_bpf/programs/attached/events/page_fault_kernel.bpf.c
- driver/modern_bpf/programs/attached/events/page_fault_user.bpf.c
- driver/modern_bpf/programs/attached/events/sched_switch.bpf.c
- driver/modern_bpf/programs/attached/events/signal_deliver.bpf.c
- test/drivers/event_class/event_class.cpp
- test/drivers/event_class/event_class.h
- test/drivers/test_suites/generic_tracepoints_suite/page_fault_kernel.cpp
- test/drivers/test_suites/generic_tracepoints_suite/page_fault_user.cpp
- test/drivers/test_suites/generic_tracepoints_suite/sched_process_exec.cpp
- test/drivers/test_suites/generic_tracepoints_suite/sched_process_exit.cpp
- test/drivers/test_suites/generic_tracepoints_suite/sched_process_fork.cpp
- test/drivers/test_suites/generic_tracepoints_suite/sched_switch.cpp
- test/drivers/test_suites/generic_tracepoints_suite/signal_deliver.cpp
- userspace/libpman/include/libpman.h
- userspace/libpman/src/maps.c
- userspace/libpman/src/programs.c
/kind feature
/area tests
No
This PR introduces 3 new tracepoints:
*  `page_fault_user`
*  `page_fault_kernel`
*  `signal_deliver`
With these new tracepoints, we should have implemented all the tracepoints supported in other drivers :) 
Since we merged the sampling logic, I've added it also to these new tracepoints
Part of our porting issue: https://github.com/falcosecurity/libs/issues/723
```release-note
NONE
```
> new(driver): support additional tracepoints into the modern BPF probe

- userspace/libsinsp/async/async_key_value_source.h
- userspace/libsinsp/async/async_key_value_source.tpp
- userspace/libsinsp/container_engine/container_async_source.h
- userspace/libsinsp/container_engine/container_async_source.tpp
- userspace/libsinsp/test/async_key_value_source.ut.cpp
- userspace/libsinsp/test/container_info.ut.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> fix: dequeue_next_key breaks async_key_value_source TTL mechanism

- userspace/libsinsp/filterchecks.h
/kind bug
/area libsinsp
No
These 2 check types shouldn't be there, they were moved some time ago [here](https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/filterchecks.h#L442-L443) with a different name. We need to remove these 2 old definitions otherwise the [`sinsp_filter_check_event_fields`](https://github.com/falcosecurity/libs/blob/ca51f17c5f7ad3ae6d85f10598976eab16bdc223/userspace/libsinsp/filterchecks.cpp#L2789) table will be desynchronized if we append new `TYPE_...` after these ones …
> fix(userspace): remove 2 event check types not used

- driver/bpf/fillers.h
- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/helpers/store/ringbuf_store_params.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvmmsg.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/semop.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendfile.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendmmsg.bpf.c
- driver/ppm_fillers.c
- test/drivers/test_suites/syscall_enter_suite/recvmmsg_e.cpp
- test/drivers/test_suites/syscall_enter_suite/semop_e.cpp
- test/drivers/test_suites/syscall_enter_suite/sendfile_e.cpp
- test/drivers/test_suites/syscall_enter_suite/sendmmsg_e.cpp
- test/drivers/test_suites/syscall_exit_suite/recvmmsg_x.cpp
- test/drivers/test_suites/syscall_exit_suite/semop_x.cpp
- test/drivers/test_suites/syscall_exit_suite/sendfile_x.cpp
- test/drivers/test_suites/syscall_exit_suite/sendmmsg_x.cpp
- userspace/libpman/src/events_prog_names.h
/kind bug
/kind feature
/area tests
No
On one side this PR supports 4 missing syscalls in the modern bpf probe https://github.com/falcosecurity/libs/issues/723:
*  `sendmmsg`
*  `recvmmsg`
*  `semop`
*  `sendfile`
On the other side, it unifies the behavior of this syscall between our 3 drivers:
* send event even when the pointer is invalid
```release-note
new(driver): unify support for some new syscalls between drivers 2/n
```
> new(driver): unify support for some new syscalls between drivers 2/n

- test/drivers/test_suites/syscall_exit_suite/open_by_handle_at_x.cpp
- userspace/chisel/chisel_api.cpp
- userspace/chisel/chisel_utils.cpp
- userspace/libpman/src/ringbuffer.c
- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libscap/engine/savefile/scap_savefile.c
- userspace/libscap/engine/source_plugin/source_plugin.c
- userspace/libscap/linux/scap_fds.c
- userspace/libscap/linux/scap_userlist.c
- userspace/libscap/scap.c
- userspace/libscap/scap_savefile.c
- userspace/libscap/scap_suppress.c
- userspace/libsinsp/cyclewriter.cpp
- userspace/libsinsp/examples/test.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/socket_handler.h
- userspace/libsinsp/test/sinsp_with_test_input.h
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/tracers.cpp
/kind bug
/kind cleanup
/area libscap
/area libpman
/area libsinsp
No
This PR cumulates a number of stability fixes to check the following:
* Return values
* Memory allocation functions
* Potential invalid pointer access
Fixes #
```release-note
cleanup(libsinsp,libscap,libpman): cleanups, fixes for return values, memory management, allocations
```
> cleanup(libsinsp,libscap,libpman): cleanups, fixes for return values, memory management, allocations

- userspace/libscap/examples/01-open/scap_open.c
- userspace/libsinsp/events/sinsp_events.cpp
- userspace/libsinsp/events/sinsp_events.h
- userspace/libsinsp/events/sinsp_events_ppm_sc.cpp
- userspace/libsinsp/events/sinsp_events_set.h
- userspace/libsinsp/events/sinsp_events_tp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/test/filter_ppm_codes.ut.cpp
- userspace/libsinsp/test/public_sinsp_API/interesting_syscalls.cpp
- userspace/libsinsp/test/public_sinsp_API/interesting_tracepoints.cpp
/kind cleanup
/kind feature
/area libsinsp
No
This solves a couple of issues following-up the changes of #877. Moreover, this adds two new functions `libsinsp::events::is_generic` and `libsinsp::events::info`. The latter helps reducing and avoiding the use of the `g_infotables` tables. Moreover, the `libsinsp::events::set` implementation has been improved to have an interface compatible with the standard library, hence making it much easier to use.
```release-note
NONE
```
> update(userspace/libsinsp): improve event codes api 

- cmake/modules/curl.cmake
- test/modern_bpf/test_suites/syscall_exit_suite/open_by_handle_at_x.cpp
- userspace/chisel/chisel_api.cpp
- userspace/chisel/chisel_utils.cpp
- userspace/libpman/src/ringbuffer.c
- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libscap/engine/savefile/scap_savefile.c
- userspace/libscap/engine/source_plugin/source_plugin.c
- userspace/libscap/linux/scap_fds.c
- userspace/libscap/linux/scap_userlist.c
- userspace/libscap/scap.c
- userspace/libscap/scap_savefile.c
- userspace/libscap/scap_suppress.c
- userspace/libsinsp/cyclewriter.cpp
- userspace/libsinsp/examples/test.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/socket_handler.h
- userspace/libsinsp/test/sinsp_with_test_input.h
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/tracers.cpp
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libpman
/area libsinsp
/area tests
> …
> update branch 0.10.x

- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/parsers.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
/kind cleanup
/area libsinsp
No
This PR proposes to remove an old dropping logic that seems no more useful, we already have the simple consumer and the sampling ratio logic in our drivers so probably we don't need also this dropping logic in userspace
```release-note
NONE
```
> cleanup(userspace): remove unused `drop_event_flags` logic

- .circleci/config.yml
- driver/bpf/filler_helpers.h
- driver/bpf/fillers.h
- test/drivers/test_suites/syscall_enter_suite/io_uring_enter_e.cpp
- test/drivers/test_suites/syscall_enter_suite/io_uring_register_e.cpp
- test/drivers/test_suites/syscall_exit_suite/io_uring_enter_x.cpp
- test/drivers/test_suites/syscall_exit_suite/io_uring_register_x.cpp
- test/drivers/test_suites/syscall_exit_suite/io_uring_setup_x.cpp
/kind bug
/area tests
No
After recent changes in the old bpf probe, we are facing some stability issues. This is probably the moment to replace the old `bpf_val_to_ring`  helper with dedicated helpers like in the modern probe to reduce complexity and help the verifier.
This PR adds three new helpers:
* `bpf_push_u32_to_ring`
* `bpf_push_u64_to_ring`
* `bpf_push_s64_to_ring`
These helpers are still dirty because until we remove the `val_to_ring` we have to preserve some code patterns, I left some TODOs to address them in next PRs. This doesn't want to address all issues we have in one shot, …
> fix(driver): verifier issues on clang-7

- userspace/libscap/engine/savefile/CMakeLists.txt
/kind bug
/area build
This fixes a regression in the cmake setup introduced in https://github.com/falcosecurity/libs/pull/851 that caused the failure of a CI job in Falco (https://github.com/falcosecurity/falco/actions/runs/4206450519/jobs/7299948726).
```release-note
NONE
```
> fix(cmake): make scap_engine_savefile depend on zlib only if not in minimal build

- driver/bpf/fillers.h
- driver/event_table.c
- driver/fillers_table.c
- driver/flags_table.c
- driver/main.c
- driver/modern_bpf/definitions/events_dimensions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/chown.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fchown.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fchownat.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/lchown.bpf.c
- driver/ppm_events_public.h
- driver/ppm_fillers.c
- driver/ppm_fillers.h
- driver/ppm_flag_helpers.h
- driver/report.md
- driver/syscall_table.c
- test/drivers/test_suites/syscall_enter_suite/chown_e.cpp
- test/drivers/test_suites/syscall_enter_suite/fchown_e.cpp
- test/drivers/test_suites/syscall_enter_suite/fchownat_e.cpp
- test/drivers/test_suites/syscall_enter_suite/lchown_e.cpp
- test/drivers/test_suites/syscall_exit_suite/chown_x.cpp
- test/drivers/test_suites/syscall_exit_suite/fchown_x.cpp
- test/drivers/test_suites/syscall_exit_suite/fchownat_x.cpp
- test/drivers/test_suites/syscall_exit_suite/lchown_x.cpp
- userspace/libpman/src/events_prog_names.h
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/test/table/event_table.cpp
/kind feature
/area libpman
/area libsinsp
/version driver-API-version-minor
/version driver-SCHEMA-version-minor
Adds full processing for `chown`, `lchown`, `fchown`, `fchownat` syscalls extracting their parameters: filename, new user id and group id.
Fixes #892
```release-note
new: add support for chown, lchown, fchown, fchownat syscalls
```
> update(driver): add support for chown syscall family

- driver/main.c
/kind bug
Attributes in "struct device*" are const since kernel-6.2, so add a matching prototype for ppm_devnode().
Fixes #918 
Not sure about the driver version/ABI compatibility. Shouldn't impact ABI but then I don't really know whether a driver built for 6.1 is expected to work on 6.2. :shrug: 
```release-note
fix(driver): fixed kmod build on kernel >= 6.2
```
> fix(driver): fix build on linux-6.2

- driver/bpf/fillers.h
/kind bug
Fixes build of old bpf probe on kernel >= 6.2.0.
See: https://github.com/torvalds/linux/commit/f1a7941243c102a44e8847e3b94ff4ff3ec56f25
Fixes #
```release-note
fix(driver/bpf): fixed build of bpf probe on linux >= 6.2
```
> fix(driver/bpf): fixed bpf probe build on kernel >= 6.2

- userspace/libsinsp/user.cpp
When node is using NIS / nss_compat for user management, /etc/passwd entries can refer to NIS groups or users, which causes parser to return null pointers instead of c-strings.
This change includes checks agains those.
In addition, a check is added to /etc/group parsing.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
> fix(libsinsp): add nullpointer check to struct passwd parsing

- userspace/libsinsp/events/sinsp_events_set.h
- userspace/libsinsp/test/public_sinsp_API/events_set.cpp
/kind bug
/area libsinsp
/area tests
The `libsinsp::events::set` class computed a wrong size when inserting elements already present in the set, or when removing non-existing elements. Tests have been updated to assert this.
```release-note
NONE
```
> fix(userspace/libsinsp): properly compute set size

- userspace/libsinsp/filter/ppm_codes.cpp
- userspace/libsinsp/filter/ppm_codes.h
- userspace/libsinsp/test/filter_ppm_codes.ut.cpp
/kind feature
/area libsinsp
/area tests
This adds a new filter AST operation to search the set of ppm_sc_code matching a certain AST, just like we already had for ppm_event_code. This is required because relying entirely on ppm_event_codes might cause information loss on generic events (e.g. when finding PPME_GENERIC_E/X, we have no way to know _which_ generic event that really was).
Unit tests related to that code area have been extended to increase the coverage and avoid potential corner cases. …
> update(userspace/libsinsp): add ppm_sc_code search in filter ASTs 

- userspace/libpman/src/configuration.c
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> …
> new(modern_bpf): Relax required kernel version for modern bpf

- userspace/libsinsp/examples/test.cpp
If `-f` is not passed to sinsp-example, `get_filter_ast()` returns nullptr, so we immediately crash when trying to analyze the (non-existent) AST.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
> fix(scap): don't crash without filter in sinsp-example

- userspace/libscap/engine/savefile/scap_savefile.c
- userspace/libscap/linux/scap_procs.c
- userspace/libscap/scap.c
- userspace/libscap/scap.h
- userspace/libscap/scap_fds.c
- userspace/libscap/scap_procs.c
- userspace/libscap/scap_procs.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
/area libsinsp
> /area tests
> …
> Remove scap_t parameter from proc_callback

- userspace/libsinsp/events/sinsp_events_set.h
`sinsp_events.h` doesn't reside in the same directory as `event.h`, so include it with a relative path. This avoids including `event.h` from libevent here.
> /kind bug
/kind cleanup
> /kind design
/area build
> /area CI
> /area …
> fix(build): Fix an include path

- userspace/libpman/src/configuration.c
- userspace/libpman/src/state.c
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libpman
> /area tests
> …
> new(libpman): Improve error logging

- driver/syscall_table.c
- userspace/libsinsp/events/sinsp_events.cpp
- userspace/libsinsp/events/sinsp_events.h
- userspace/libsinsp/events/sinsp_events_ppm_sc.cpp
- userspace/libsinsp/test/public_sinsp_API/events_set.cpp
- userspace/libsinsp/test/public_sinsp_API/interesting_syscalls.cpp
/kind bug
kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> cleanup(libsinsp): Extension of ppm sc API for corner cases (e.g. `event_set_to_names` and `names_to_sc_set`)

- driver/modern_bpf/CMakeLists.txt
- userspace/libpman/src/maps.c
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> …
> new(driver/modern_bpf): Allow excluding tail-called programs

- cmake/modules/tbb.cmake
/kind bug
/area build
/area libsinsp
No
Surprisingly, this is not a security update. Instead, I noticed that with gcc 11.3.0, when building the libs with `-DBUILD_WARNINGS_AS_ERRORS` I was getting the following error
```
/home/ubuntu/dev/falcosecurity/libs/build-debug/tbb-prefix/src/tbb/include/tbb/internal/_concurrent_unordered_impl.h:1345:15: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct tbb::atomic<tbb::interface5::internal::flist_iterator<tbb::interface5::internal::split_ordered_list<std: …
```
> update(cmake): upgrade to libtbb v2021.8.0 (fixes building with gcc with warnings as errors)

- .github/workflows/ci.yml
- cmake/modules/GetGitRevisionDescription.cmake
- cmake/modules/versions.cmake
/kind bug
/area build
Fixes libs dev versioning by applying similar fixes as https://github.com/falcosecurity/falco/pull/2292.
Fixes #
```release-note
NONE
```
> fix(cmake): fixed git dev versioning.

- userspace/libsinsp/container_engine/docker/podman.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> fix(sinsp): use the right cgroup when detecting rootless podman

- userspace/chisel/chisel_table.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> fix(userspace/libsinsp): correct init of m_flags

- userspace/libsinsp/test/events_file.ut.cpp
- userspace/libsinsp/test/events_net.ut.cpp
- userspace/libsinsp/test/events_param.ut.cpp
- userspace/libsinsp/test/events_proc.ut.cpp
- userspace/libsinsp/test/events_user.ut.cpp
- userspace/libsinsp/test/sinsp_with_test_input.h
/kind bug
/area libsinsp
/area tests
No.
This PR fixes a fun bug in the libsinsp test suite that is simply an instance of this: https://stackoverflow.com/questions/727663/why-does-this-variadic-function-fail-on-4th-parameter-on-windows-x64 .
Essentially, passing an integer literal to a variadic function and expecting a 64 bit value is undefined behavior, as the integer literal is type `int` and not the correct 64 bit size. We caught this on ARM64 after the 8th parameter due to that specific implementation and parameter …
> fix(libsinsp,test): remove undefined behavior in test event generation

- .github/workflows/ci.yml
- test/e2e/tests/commons/sinspqa/__init__.py
- test/e2e/tests/commons/sinspqa/sinsp.py
- test/e2e/tests/test_event_generator/test_db_program_spawned_process.py
- test/e2e/tests/test_event_generator/test_run_shell_untrusted.py
- test/e2e/tests/test_network/test_network.py
/kind feature
/area CI
/area tests
With the modern BPF probe quickly reaching a production ready state, I think it's time we start running e2e tests with it. This PR achieves this by adding a new set of `sinsp-example` binaries to be run using this new driver to the tests. A small check was added to prevent the tests from being run on systems that are not supported by the driver.
There are currently 3 tests that are failing:
- 2 of them are due to the `exe_writable` flag not being supported yet on the modern probe.
- 1 test is failing because the test expects `proc.exe` to be `nginx: master proces`, but the …
> Run e2e tests with modern probe

- driver/bpf/fillers.h
- driver/modern_bpf/helpers/store/auxmap_store_params.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendmsg.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendto.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/write.bpf.c
- driver/ppm_fillers.c
- test/drivers/test_suites/syscall_exit_suite/sendmsg_x.cpp
- test/drivers/test_suites/syscall_exit_suite/sendto_x.cpp
- test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
- test/drivers/test_suites/syscall_exit_suite/write_x.cpp
/kind cleanup
No
This PR addresses some of the inconsistencies reported here https://github.com/falcosecurity/libs/issues/942#issuecomment-1463712325. More in detail, now we collect data also when the following syscalls fail:
This refactor will end I will close #942 when I will implement the last "write" syscalls `pwrite64`, `writev` ,`pwritev`
Fixes #
```release-note
NONE
```
> cleanup(driver): allow some "write-like" syscall to send data also when they fail

- userspace/libsinsp/events/sinsp_events.h
- userspace/libsinsp/events/sinsp_events_ppm_sc.cpp
- userspace/libsinsp/test/public_sinsp_API/interesting_syscalls.cpp
> /kind bug
/kind cleanup
/kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests …
> new(libsinsp): `sinsp_repair_state_sc_set` ppm sc API

- driver/CMakeLists.txt
- driver/ppm.h
- driver/ppm_consumer.h
- driver/ppm_events.h
/kind bug
It fixes the kmod build on ancient centos6.
`ppm_consumer_t` was `typedef`ed both in ppm.h and in ppm_events.h, both included in kmod main.c.
Fixes #
```release-note
fix(driver): avoid typedefing ppm_consumer_t twice
```
> fix(driver): avoid `ppm_consumer_t` being defined twice.

- .github/workflows/driver-api-version.yml
- .github/workflows/driver-schema-version.yml
/kind cleanup
/area CI
The PR switches the newly added driver API and SCHEMA version CI checks to use the `pull_request_target` trigger: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
This trigger is capable of commenting on PRs coming from forks:
> Warning: For workflows that are triggered by the pull_request_target event, the GITHUB_TOKEN is granted read/write repository permission unless the permissions key is specified and the workflow can access secrets, even when it is triggered from a fork. Although the workflow runs in the context of the base of …
> chore(ci): properly use `pull_request_target` trigger type for driver api and schema version ci checks

- userspace/libscap/engine/gvisor/gvisor.cpp
- userspace/libscap/engine/gvisor/gvisor.h
- userspace/libscap/engine/gvisor/gvisor_public.h
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libscap/engine/kmod/scap_kmod.c
- userspace/libscap/engine/nodriver/nodriver_public.h
- userspace/libscap/linux/scap_fds.c
- userspace/libscap/linux/scap_procs.c
- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libscap-engine-nodriver
> /area tests
> …
> new(scap): Support gVisor no_events mode/full proc scan for nodriver

- userspace/libsinsp/logger.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/test/public_sinsp_API/sinsp_logger.cpp
- userspace/libsinsp/utils.cpp
/kind feature
/area libsinsp
/area tests
No
This PR changes the default libsinsp verbosity from `SEV_TRACE` to `SEV_INFO`, this seems a more reasonable default value. 
Moreover, this PR adds a new helper method to check if there is at least an output configured for the logger.
I've added some minimal tests for this class but for sure we can improve the coverage in the next future
/hold 
```release-note
update!: change libsisnp default verbosity and add some helper methods
```
> update!: change libsisnp default verbosity and add some helper methods

- driver/syscall_table.c
/kind feature
Remove UF_ALWAYS_DROP from mmap to be able to use it in dropping mode
Fixes #
```release-note
update(driver): remove UF_ALWAYS_DROP from mmap
```
> update(driver): remove UF_ALWAYS_DROP from mmap

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filterchecks.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> Also save (pointers) to filtercheck values in order

- userspace/libsinsp/filter/ast.cpp
- userspace/libsinsp/filter/ast.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> Add a const base_expr_visitor

- driver/modern_bpf/definitions/missing_definitions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/bind.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/close.bpf.c
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fcntl.bpf.c
- test/drivers/test_suites/actions_suite/sampling_ratio.cpp
- test/drivers/test_suites/syscall_enter_suite/fcntl_e.cpp
/kind feature
/area tests
No
This PR supports the syscall-specific dropping logic we have in the other 2 drivers. This logic is disabled by default but it can be enabled by using `dropping_mode=true`
The code section that I'm implementing here is this one (in the old probe)
```c
switch (evt_type) {
case PPME_SYSCALL_CLOSE_X:
case PPME_SOCKET_BIND_X: {
long ret = bpf_syscall_get_retval(ctx);
if (ret < 0)
return true;
break;
}
case PPME_SYSCALL_CLOSE_E: {
struct sys_enter_args *args;
struct files_struct *files;
struct task_struct *task;
unsigned long *open_fds;
struct fdtable *fdt;
int …
```
> new(driver/modern_bpf): Support syscall specific dropping logic into modern bpf probe

- cmake/modules/libscap.cmake
/kind bug
> /kind design
/area build
> /area CI
/area libscap
> /area tests
> …
> fix(cmake): included GnuInstallDirs

- userspace/libscap/scap_suppress.h
- userspace/libscap/strerror.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
> cleanup(scap): minor header cleanups

- userspace/libsinsp/container.cpp
- userspace/libsinsp/container.h
- userspace/libsinsp/cyclewriter.cpp
- userspace/libsinsp/cyclewriter.h
- userspace/libsinsp/dumper.cpp
- userspace/libsinsp/dumper.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/user.cpp
- userspace/libsinsp/user.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> cleanup(sinsp): minor sinsp_dumper cleanups

- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/sinsp_utils.ut.cpp
- userspace/libsinsp/utils.cpp
/kind bug
/area libsinsp
No
This PR fixes a bug in the implementation of `copy_and_sanitize_path` in libsisnp causing system calls that copy filesystem paths to mishandle paths containing three or more consecutive dots. 
Fixes #974
Parts of the original function were refactored.
```release-note
fix: sanitization of paths containing three or more consecutive dots 
```
> fix(libsinsp): fix `copy_and_sanitize_path` function implementation

- test/e2e/tests/test_network/test_network.py
- userspace/libsinsp/event.cpp
- userspace/libsinsp/test/events_param.ut.cpp
/kind bug
/area libsinsp
NOPE
Since the introduction of PT_ENUMFLAGS types for enum-like flags (#289), `get_param_as_str` impl had a bug.
Indeed we had 2 bugs:
* given that the loop was `while(flags != NULL && flags->name != NULL && flags->value != initial_val)`, we never matched enum flags values (note the `flags->value != initial_val` loop condition)
* some enum flags (namely `socket_families` ones) can have multiple flags that have different names but same value (eg: `PPM_AF_UNIX` and `PPM_AF_LOCAL`)
This PR fixes both issues.
Fixes # …
> fix(userspace/libsinsp): fixed PT_ENUMFLAGS `get_param_as_{str,json}` impl

- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/kmod/scap_kmod.c
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
/kind cleanup
No
This PR covers the case in which some syscalls don't have an associated ppm_sc and so we cannot set them as (un)interesting. For this reason, we default them to 0.
```release-note
NONE
```
> update(userspace): add an extra checks to clear syscalls

- userspace/libsinsp/events/sinsp_events.cpp
- userspace/libsinsp/events/sinsp_events.h
- userspace/libsinsp/events/sinsp_events_ppm_sc.cpp
- userspace/libsinsp/filter/ppm_codes.cpp
- userspace/libsinsp/test/public_sinsp_API/interesting_syscalls.cpp
- userspace/libsinsp/test/public_sinsp_API/ppm_sc_codes.cpp
- userspace/libsinsp/test/test_utils.h
/kind cleanup
/kind feature
/area libscap
/area libsinsp
/area tests
No
This is (hopefully) the last code change required for the effort of https://github.com/falcosecurity/falco/issues/2443. This basically extends the sinsp API for handling event names <-> syscall sets conversions, while still supporting the old APIs as well. The API change is as follows:
- `names_to_sc_set` -> `event_names_to_sc_set` and `sc_names_to_sc_set`
- `sc_set_to_names` -> `sc_set_to_event_names` and `sc_set_to_sc_names`
With this step, we're able to finally solve the last few TODO's in the ppm_sc/interesting syscalls test suite. …
> update(userspace/libsinsp)!: support sc codes and event names bidirectional conversions

- .github/workflows/ci.yml
/kind cleanup
/area CI
By setting a proper concurrency group on the CI workflow, we can always only have in flights build for latest commit on a PR/branch.
Fixes #1028 
```release-note
NONE
```
> chore(ci): properly set gha concurrencty for CI workflow.

- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
- userspace/libscap/scap_engine_util.c
- userspace/libscap/scap_engine_util.h
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
> fix(scap): Use precise boot time for BPF engines

- userspace/libsinsp/examples/test.cpp
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> cleanup(libsinsp): add `ppm_sc_modifies_state` and `ppm_sc_repair_state` flags to sinsp-example

- userspace/libsinsp/plugin.cpp
- userspace/libsinsp/plugin.h
- userspace/libsinsp/plugin_filtercheck.cpp
- userspace/plugin/plugin_api.h
- userspace/plugin/plugin_types.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> feat: support for new field types in plugins

- userspace/libsinsp/event.h
Some tests rely on creating fake events without all of the overhead of an inspector, etc. To support new tests that rely on m_errorcode (generally maps to the res field of events), add a new initializer that passes in a scap + ppm header and errorcode, and just directly sets m_errorcode.
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area …
> Add addl(test-only) way to initialize events, setting errorcode

- driver/bpf/filler_helpers.h
- driver/bpf/fillers.h
/kind cleanup
/version driver-API-version-patch
This PR splits up all the integer-related cases from `bpf_val_to_ring`.
We still need to:
* figure out how to port `sys_autofill`
* figure out how to port `sys_single` -> we only have 3 syscalls using it nowadays; therefore it should be pretty simple to drop it completely.
* figure out what to do with `PT_DYN` params
Moreover, the PR also uses `CHECK_RES` macro in all fillers.
I think the TODO can be addressed in a subsequent PR since this is already pretty huge and will lead to multiple conflicts everytime a bpf touching PR gets merged in …
> cleanup(driver/bpf): split bpf_val_to_ring into many int-pushing helpers

- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/connect.bpf.c
/kind bug
> /kind design
> /area build
> /area CI
> /area tests
> …
> fix(modern_bpf): Fix connect_x prog

- userspace/libsinsp/test/filter_compiler.ut.cpp
/kind bug
/kind cleanup
/area tests
No.
This moves us a step closer to testing also for undefined behavior in our unit tests. Some tests rely on calling class methods with a NULL inspector. Since technically those methods do not access the sinsp state they work at runtime but I believe it's UB according to the standard.
Fixes #
```release-note
NONE
```
> fix(tests): use a non-null inspector for filter tests

- userspace/libsinsp/test/events_net.ut.cpp
/kind cleanup
/area tests
No.
as per title
Fixes #
```release-note
NONE
```
> cleanup(tests): do not assert_throw when we check if a field exists

- userspace/libsinsp/examples/test.cpp
/kind bug
/area libsinsp
`sinsp-example` treats EOF as an error, whereas the expected behavior is for it to interrupt the event capture. This can be easily reproduced with a capture file or a plugin.
```release-note
NONE
```
> fix(userspace/libsinsp): support EOF in sinsp-example

- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filterchecks.cpp
/kind bug
/area libsinsp
Floating point numbers are not handled when formatting fields as JSON, thus causing libsinsp to throw an exception. This allows formatting them both as integer or floating point numbers, and adapts the few existing fields accordingly.
```release-note
fix(userspace/libsinsp): properly format double numbers as json
```
> fix(userspace/libsinsp): properly format double numbers as json

- userspace/libscap/scap.h
- userspace/libscap/scap_event.c
- userspace/libscap/scap_machine_agent.c
- userspace/libsinsp/sinsp_resource_utilization.cpp
/kind cleanup
/area libsinsp
/area libscap
No.
When building Falco with warnings as errors these are halting the build.
Fixes #
```release-note
NONE
```
> fix(libsinsp,libscap): return value and fscanf warnings

- driver/bpf/CMakeLists.txt
- driver/bpf/Makefile
- driver/bpf/fillers.h
- driver/bpf/missing_definitions.h
- driver/ppm_fillers.c
- test/drivers/test_suites/syscall_exit_suite/execve_x.cpp
/kind bug
On kernels <5.x the field `is_exe_upper_layer` shows a wrong value. Prior of 5.x kernel the implementation of the overlayfs changed a couple of times and the previous implementation didn't take this problematic into account.
Fixes # …
> fix(driver): wrong is_exe_upper_layer on kernel <5.x

- .github/workflows/ci.yml
/kind feature
/area CI
No.
Recently we merged some code that had a couple minor warnings. Nothing serious but since the libs currently compile without warnings (except for a couple harmless ones we already excluded) it'd be great to keep it that way.
Fixes #
@FedeDP @Andreagit97 -- I wonder if we had this flag already and disabled it on purpose? If so which one?
```release-note
NONE
```
> update(ci): use BUILD_WARNINGS_AS_ERRORS

- driver/bpf/plumbing_helpers.h
- driver/kernel_hacks.h
- driver/main.c
- driver/modern_bpf/helpers/interfaces/syscalls_dispatcher.h
- driver/ppm_events.c
- driver/ppm_events.h
- driver/ppm_fillers.c
- test/drivers/test_suites/syscall_enter_suite/socketcall_e.cpp
- test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
/kind bug
/kind cleanup
/kind feature
NONE
This PR contains multiple improvements:
* fixed a bug in `socketcall` handling: socketcall resolved syscalls were not being checked against interesting set
* ported kmod socketcall code to follow similar structure to eBPF and modern eBPF
* given that since linux 5.1 `syscall_get_arguments` copies all the arguments of a syscall, try to give a boost to perf by preloading syscalls arguments and reusing them, instead of fetching them every time we want to access a single argument (see: https://elixir.bootlin.com/linux/latest/source/arch/arm64/include/as …
> new: kmod socketcall refactor

- userspace/libsinsp/event.h
- userspace/libsinsp/filter.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/gen_filter.cpp
- userspace/libsinsp/gen_filter.h
/kind cleanup
/area libsinsp
The mesos support has been deprecated: the mesos fields should no longer appear using `--list`.
Fixes #
```release-note
NONE
```
> chore(userspace/libsinsp): remove mesos fields from `--list`

- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/filterchecks.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/state/dynamic_struct.h
- userspace/libsinsp/state/static_struct.h
- userspace/libsinsp/state/table.h
- userspace/libsinsp/state/table_registry.h
- userspace/libsinsp/state/type_info.h
- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/state.ut.cpp
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/threadinfo.h
/kind design
/kind feature
/area libsinsp
/area tests
This PR initiates the effort required to solve #991 by defining a standard way for defining and accessing state tables inside libsinsp. The proposed solution is schemaless and enables dynamic programming. At runtime, libsinsp will allow to:
- Discovering all the tables registered in an inspector (a table is defined as a key-value store)
- Discovering their structure (e.g. the key type, all the fields available in the table entries)
- Extending their structure by defining new data fields later accessible in all the table entries (e.g. attaching extra …
> update(userspace): standard definitions for accessing state tables dynamically at runtime

- userspace/libsinsp/eventformatter.cpp
- userspace/libsinsp/eventformatter.h
- userspace/libsinsp/test/CMakeLists.txt
- userspace/libsinsp/test/eventformatter.ut.cpp
/kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> update: add function to retrieve fields used in output strings

- userspace/libsinsp/container_engine/cri.cpp
- userspace/libsinsp/cri.cpp
- userspace/libsinsp/cri.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> cleanup(cri): enhance robustness for container image retrieval

- userspace/libscap/engine/source_plugin/source_plugin.c
- userspace/libsinsp/plugin.cpp
- userspace/libsinsp/plugin.h
- userspace/libsinsp/plugin_filtercheck.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/test/plugins/syscall_async.cpp
- userspace/plugin/plugin_api.h
- userspace/plugin/plugin_types.h
/kind bug
/kind cleanup
/kind design
/area libsinsp
This polishes some inconsistencies in the plugin API and solves a data race in the async event handler of libsinsp.
```release-note
update(userspace): minor improvements on the plugin framework
```
> update(userspace): minor improvements on the plugin framework

- userspace/libsinsp/events/sinsp_events.cpp
- userspace/libsinsp/filter/ppm_codes.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/sinsp.cpp
/kind bug
/area libsinsp
If an inspector gets destroyed without ever being open, we don't want to reset the async event handlers on its plugins. Also, I added a couple of todos for better handling async events in the event codes <-> name conversion primitives in the future.
```release-note
fix(userspace/libsinsp): don't unset async evt handler if inspector was not open
```
> fix(userspace/libsinsp): don't unset async evt handler if inspector was not open

- userspace/plugin/plugin_loader.c
/kind bug
/area libsinsp
The plugin loader checker for broken capabilities is too much strict, whereas it should allow defining symbols for the static plugin info without throwing errors.
```release-note
fix(userspace/plugin): make plugin loader less strict when checking caps
```
> fix(userspace/plugin): make plugin loader less strict when checking caps

- test/drivers/start_tests.cpp
- userspace/libpman/src/stats.c
- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/plugin/plugin_loader.c
/kind bug
/area libsinsp
/area tests
Correct usage of `strncat` to avoid buffer overflows:
> If src contains n or more bytes, strncat() writes n+1 bytes to dest (n from src plus the terminating null byte). Therefore, the size of dest must be at least strlen(dest)+n+1. 
Fixes #
```release-note
NONE
```
> fix(test,userspace): fixed strncat usage.

- userspace/libsinsp/container.cpp
/kind bug
/area libsinsp
No.
There is a missing `return` on an error condition leading to reading garbage when trying to dereference `found` later on.
Fixes #
```release-note
fix(libsinsp): fixed segfault when update_container_with_size is called with a type not registered
```
> fix(libsinsp): return on error in update_container_with_size

- userspace/libsinsp/eventformatter.h
- userspace/libsinsp/gen_filter.h
/kind cleanup
/area libsinsp
When adding `get_field_names` to sinsp formatters, we forgot to make it a base virtual method of generic formatters.
```release-note
chore(userspace/libsinsp): make get_field_names a property of generic formatters
```
> chore(userspace/libsinsp): make get_field_names a property of generic formatters

- userspace/libpman/src/stats.c
/kind bug
> /kind design
> /area build
> /area CI
/area libpman
> /area tests
> …
> fix(libpman): do not close cnt map in scap stats v2 in absence of error

- driver/main.c
/kind bug
/version driver-API-version-patch
A kernel API change in 6.4 requires a build fix 
Fixes #1109
```release-note
NONE
```
> fix(driver): fixed 6.4 kernel build

- driver/CMakeLists.txt
- driver/Makefile.in
- driver/main.c
- driver/ppm_version.h
- driver/socketcall_to_syscall.c
- driver/socketcall_to_syscall.h
/kind bug
No
This PR fixes a regression on 32 bits socketcalls. Before this patch we sent syscalls codes on 64 bit even when config `CONFIG_IA32_EMULATION` was enabled.
```release-note
fix(driver): correctly convert socketcall codes on 32 bits
```
> fix(driver): correctly convert socketcall codes on 32 bits

- test/libscap/test_suites/engines/bpf/bpf.cpp
- test/libscap/test_suites/engines/kmod/kmod.cpp
- test/libscap/test_suites/engines/modern_bpf/modern_bpf.cpp
/kind feature
/area tests
no
This PR adds some tests to avoid regressions of this patch https://github.com/falcosecurity/libs/pull/1121
```release-note
NONE
```
> tests: add some engine tests on scap stats

- driver/main.c
- driver/socketcall_to_syscall.c
- driver/socketcall_to_syscall.h
- test/drivers/event_class/event_class.cpp
- test/drivers/event_class/event_class.h
- test/drivers/test_suites/syscall_enter_suite/socketcall_e.cpp
- test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
- userspace/libscap/engine/bpf/scap_bpf.c
- userspace/libscap/engine/kmod/scap_kmod.c
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
- userspace/libscap/linux/scap_userlist.c
- userspace/libscap/userspace_flag_helpers.h
/kind feature
/area libsinsp
This PR syncs the release branch with these PRs:
```release-note
NONE
```
> chore: sync release branch `0.11.x`

- userspace/libpman/src/ringbuffer.c
- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
/kind bug
/area build
/area libpman
Fix two more build warnings
With this PR, I can build libs with -DBUILD_WARNINGS_AS_ERRORS, though without this option tons and tons of warnings remain
```release-note
NONE
```
> Fix two more build warnings

- .github/workflows/latest-kernel.yml
- README.md
> new(ci): build latest mainline kernel (even RC!) in latest-kernel job.

- test/drivers/test_suites/syscall_exit_suite/execve_x.cpp
- test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area tests
> …
> update:  Remove drivers_test build warnings.

- userspace/libsinsp/filter_check_list.h
/kind bug
/area libsinsp
```release-note
fix(userspace/libsinsp): set filtercheck list desturctor as virtual
```
> fix(userspace/libsinsp): set filtercheck list desturctor as virtual

- driver/event_table.c
/kind cleanup
NOPE
The event_table check is not important in kernel mode; we can skip it.
It might happen that `_Static_assert` is not available thus failing the kmod build.
Fixes #
```release-note
NONE
```
> chore(driver): avoid static_assert event_table size while building kmod.

- driver/bpf/fillers.h
- test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area tests
> …
> fix(tests, bpf): correct build and test case failures on s390x

- driver/socketcall_to_syscall.c
- driver/syscall_table32.c
/kind bug
/version driver-API-version-patch 
but we already bumped it in https://github.com/falcosecurity/libs/pull/1147
This PR fixes the build on old Centos6 kernels
```
2023-06-14 10:54:53,213  fatal error: linux/kconfig.h: No such file or directory
2023-06-14 10:54:53,213  #include <linux/kconfig.h>
```
```release-note
NONE
```
> fix(driver): remove useless include which causes compilation issues on Centos6

- test/drivers/test_suites/generic_tracepoints_suite/sched_process_fork.cpp
- test/drivers/test_suites/syscall_exit_suite/clone3_x.cpp
/kind feature
/area tests
No
**NEW PR SCOPE**
Add some tests to clone3 and sched_proc_fork to assert correct behavior with tid/pids and flags 
**KEEP THIS DESCRIPTION JUST FOR REFERENCE BUT IT IS OUTDATED**
Looking at how we populate the `ptid` field in our `thread_info` struct it seems we use 2 different approaches depending on whether we use `/proc` or an event generated by our drivers:
* if we use `/proc` scan, we read the field `PPid` under `/proc/${pid}/task/${tid}/status` and so the `TGID` of the parent (thread group id of the parent process) -> this is the same thing …
> tests(driver): add some test to `clone3` to check ptid and flags value

- driver/modern_bpf/CMakeLists.txt
- driver/modern_bpf/helpers/extract/extract_from_kernel.h
/kind bug
This PR fixes the regression reported here https://github.com/falcosecurity/libs/issues/1157 as suggested by @FedeDP.
I want to highlight that this is just a temp workaround for tag 0.11.3 we need to find for sure a better solution, hoping to receive some inputs from kernel engineers https://lore.kernel.org/bpf/CAGQdkDvYU_e=_NX+6DRkL_-TeH3p+QtsdZwHkmH0w3Fuzw0C4w@mail.gmail.com/T/#u
```release-note
NONE
```
> fix: introduce a COS workaround to fix regression #1157

- userspace/libscap/CMakeLists.txt
- userspace/libscap/engine/gvisor/gvisor.cpp
- userspace/libscap/engine/gvisor/gvisor_platform.h
- userspace/libscap/engine/gvisor/gvisor_public.h
- userspace/libscap/engine/nodriver/nodriver.c
- userspace/libscap/engine/savefile/savefile_platform.h
- userspace/libscap/engine/savefile/savefile_public.h
- userspace/libscap/engine/savefile/scap_savefile.c
- userspace/libscap/linux/CMakeLists.txt
- userspace/libscap/linux/scap_linux_platform.c
- userspace/libscap/linux/scap_linux_platform.h
- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libscap/scap_platform.c
- userspace/libscap/scap_platform.h
- userspace/libscap/scap_platform_impl.h
- userspace/libscap/strerror.h
- userspace/libsinsp/sinsp.cpp
> /kind bug
/kind cleanup
/kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
> [1/n] new(scap): platform abstraction support

- userspace/libsinsp/parsers.cpp
/kind bug
/area libsinsp
`fchmod` is not `openat` :) We were missing a `break;` between the two switch cases
I found this by running the unit tests in a debug build, but we also should consider missing explicit fallthrough tags as a compile error (there's a flag for that and I have a branch somewhere that enables it but it's not quite finished IIRC)
```release-note
NONE
```
> fix(sinsp): don't call openat parser for fchmod

- userspace/libsinsp/event.cpp
- userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> fix(libsinsp): check return value from enter event retrieval.

- driver/modern_bpf/helpers/extract/extract_from_kernel.h
/kind bug
No
As suggested in the mailing list https://lore.kernel.org/bpf/CAGQdkDuoUp6QCztoF72uS+5OjB2PDLJ0y+aJC0Dou4iOK6MWuA@mail.gmail.com/T/#mf65b870f20b4ba367c9823a56eeb3ac1c196846b the previous approach checked only existence of
loginuid inside typeof(task_cos->audit), but it doesn't check that
task_struct has an audit field. In the end, this new approach should work better, already tested it on different GKE versions and it works :) 
```release-note
NONE
```
> fix(driver/modern-bpf): improve CO-RE detection

- driver/event_table.c
- userspace/libscap/scap.h
- userspace/libsinsp/fdinfo.cpp
- userspace/libsinsp/fdinfo.h
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/parsers.h
- userspace/libsinsp/test/events_file.ut.cpp
- userspace/libsinsp/test/public_sinsp_API/ppm_sc_codes.cpp
/kind feature
/area libscap
/area tests
Since `memfd_create` creates an anonymous file it would be useful to extract the filename. 
Also see https://github.com/falcosecurity/libs/pull/1127#discussion_r1229746432 
Fixes #
```release-note
update(parsers): Support userspace parsers for memfd_create syscall
```
> update(parsers): Support userspace parsers for memfd_create syscall.

- userspace/libscap/engine/savefile/scap_savefile.c
- userspace/libscap/linux/CMakeLists.txt
- userspace/libscap/linux/scap_cgroup.c
- userspace/libscap/linux/scap_cgroup.h
- userspace/libscap/linux/scap_procs.c
- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libscap/scap.h
- userspace/libscap/scap_cgroup_set.h
- userspace/libscap/scap_savefile.c
- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/cgroup_limits.cpp
- userspace/libsinsp/container_engine/docker/podman.cpp
- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/procfs_utils.cpp
- userspace/libsinsp/procfs_utils.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/sinsp_cgroup.cpp
- userspace/libsinsp/sinsp_cgroup.h
- userspace/libsinsp/sinsp_resource_utilization.cpp
- userspace/libsinsp/test/procfs_utils.ut.cpp
- userspace/libsinsp/test/sinsp_with_test_input.h
- userspace/libsinsp/threadinfo.cpp
- userspace/libsinsp/threadinfo.h
- userspace/libsinsp/user.cpp
/kind feature
/area libscap
/area libsinsp
1. Support cgroups v2. ~This mostly involves surfacing the cgroup version everywhere instead of hiding it and has some interesting consequences for scap files: for compatibility with existing captures, we store the cgroups in v1 format. This means that features requiring cgroup v2 one way or another won't work while reading scap files. It's easily fixable but would break compatibility when reading new scap files from old builds so I deferred it for now~. The major missing things about cgroups v2 were hardcoding a list of subsystems and assuming all subsystems have …
> new(scap,sinsp): cgroups v2 and cgroup namespace support

- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libscap/scap_procs.c
- userspace/libscap/scap_suppress.c
- userspace/libscap/scap_suppress.h
/kind feature
/area libscap
No.
Accelerates suppressed TID lookup if used at run-time.
Fixes #
In a benchmark at 300k events/s with 50k suppressed TID events/s, change reduced scap_check_suppressed() reported prof time from 17.51 to 7.24 seconds.
```release-note
NONE
```
> new(libscap): add cache accelerating suppressed TIDs

- userspace/libsinsp/filterchecks.cpp
/kind cleanup
/area libsinsp
This solves compilation issues related to a wrong type conversion occurring in the Falco musl static build:
```
error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
```
```release-note
NONE
```
> fix(userspace/libsinsp): solve wrong type conversion

- userspace/libsinsp/cyclewriter.cpp
- userspace/libsinsp/event.cpp
- userspace/libsinsp/socket_handler.h
- userspace/libsinsp/tuples.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> fix compiler -Wsign-compare warnings

- userspace/libscap/CMakeLists.txt
- userspace/libscap/engine/udig/scap_udig.c
- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libscap/scap_api_version.c
- userspace/libscap/scap_api_version.h
- userspace/libscap/scap_engine_util.c
- userspace/libscap/scap_engine_util.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
> [3/n] new(libscap): platform abstraction support: clean up scap_init_*_int

- userspace/libscap/scap-int.h
- userspace/libscap/scap.c
- userspace/libscap/scap_savefile.c
- userspace/libscap/scap_savefile_api.h
- userspace/libsinsp/dumper.cpp
/kind cleanup
/kind design
/area libscap
This is a "silence before the storm" episode in the platform saga: a few cleanups in savefile code. One cherry on top is that we can finally remove m_mode from the scap handle (there's nothing that depends on it any more, since everything should be properly abstracted via engines and platforms by now)
This builds on top of #1042 so looks huge right now. BTW I expect n>=6 at least but I hope I won't go into double digits :)
```release-note
NONE
```
> [4/n] new(libscap): platform abstraction support: clean up savefiles a little bit

- cmake/modules/libbpf.cmake
- driver/modern_bpf/helpers/base/common.h
/kind cleanup
/area build
Cleaned up some now useless lines in `modern_bpf/helpers/base/common.h` to fix some build warnings when building with newer libbpf versions (see https://github.com/libbpf/libbpf/blob/master/src/bpf_tracing.h and the https://github.com/libbpf/libbpf/commit/672401ae0916d41a3626f5281988f6e763a335d3 commit)
Fixes #
```release-note
update(cmake): bumped libbpf to 1.2.2.
```
> update(cmake,driver): bumped libbpf to latest release (1.2.2).

- cmake/modules/curl.cmake
/kind feature
/area build
No.
Update libcURL to the latest version including the most up to date security fixes
```release-note
NONE
```
> update(cmake): update libcurl to 8.1.0

- userspace/libscap/engine/gvisor/gvisor_platform.h
/kind bug
No
This fixes errors when including this header (namespace std does not contain make_unique)
```release-note
fix(gvisor): fixed compilation issue due to missing memory header
```
> fix(gvisor): include memory header for smart pointers

- userspace/libscap/engine/gvisor/gvisor.cpp
- userspace/libscap/engine/gvisor/gvisor.h
- userspace/libscap/engine/gvisor/gvisor_public.h
- userspace/libscap/engine/gvisor/scap_gvisor.cpp
- userspace/libsinsp/gvisor_config.h
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
gvisor's next() calls epoll_wait to wait for the next event,
with an infinite timeout. Other engines don't block in next()
forever, so to remain compatible (and allow other things in
the main thread except for a scap_next() loop), make the timeout
configurable (still defaults to infinite at the sinsp layer).
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area …
> new(scap,gvisor): configurable epoll_wait timeout

- userspace/libsinsp/ifinfo.cpp
- userspace/libsinsp/ifinfo.h
/kind bug
/area libsinsp
No
Always use network byte order when processing addresses coming from the driver. This helps with big endian architectures.
Fixes #
This is the porting of a patch made by @jcpittman144 
cc @hbrueckner 
```release-note
fix(libsinsp): always use network byte order when printing ip addrs
```
> fix(libsinsp): network address printing endianness

- driver/bpf/Makefile
/kind bug
/area build
No
In some cases we use clang 7 to build the eBPF probe. That version of clang is too old to support some of the compiler attributes which appear in the source code for more modern kernel versions.  So disable warnings associated with unknown attributes.
Fixes #
This PR is a porting of a patch made by @jcpittman144 
```release-note
NONE
```
> fix(bpf): Compile eBPF probe with -Wno-unknown-attributes

- userspace/libscap/engine/test_input/test_input_platform.c
- userspace/libscap/scap.c
- userspace/libscap/scap_platform_impl.h
While it's cleaner to have the engine handle fully working before we
pass it to the platform init method, it's not strictly necessary:
the only use of the engine_handle is to store it in linux_platform
to call linux_vtable methods.
Initializing the platform before the engine fixes an issue with
the savefile engine, where we were putting data into the proclist
(in engine init) before the proclist callback was set (in platform init).
/kind bug
> /kind design
> /area build
> /area CI
> …
> fix(scap): initialize the platform before the engine

- driver/syscall_table.c
Libsinsp contains a parser for the SETSID_X event, and updates the m_sid for the threadinfo object.  But the current ALWAYS_DROP setting for the SETSID syscall_table entry, means this parsing never happens, in the case where dropping mode is enabled in the kernel module/BPF probe.
This change removes the ALWAYS_DROP setting for SETSID, so applications which rely on thread session IDs will have access to accurate information.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
> Remove ALWAYS_DROP setting for setsid system call

- cmake/modules/curl.cmake
/kind feature
/area build
No
Update libcURL with the latest security fixes: https://daniel.haxx.se/blog/2023/07/19/curl-8-2-0/ . There should be no breaking changes.
Fixes #
```release-note
NONE
```
> update(build): update curl to 8.2.0

- userspace/libscap/linux/scap_machine_info.c
/kind bug
/area libscap
No
We had two definitions of `SECOND_TO_NS`, one in the driver and the other in libscap. I believe it's perfectly fine to duplicate this because this is a real physical constant that will never change (if it ever does, I will certainly not want to ever work on computers again). However, we set it to `ULL` in the driver and so we should do the same in userspace otherwise we get warnings or errors if the two header files are included at the same time.
Fixes #
```release-note
fix(libscap): fix warning about SECOND_TO_NS definition
```
> fix(libscap): consistent SECOND_TO_NS definition

- userspace/libsinsp/filterchecks.cpp
- userspace/libsinsp/plugin_table_api.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/state/dynamic_struct.h
- userspace/libsinsp/state/static_struct.h
- userspace/libsinsp/state/table.h
- userspace/libsinsp/state/type_info.h
- userspace/libsinsp/test/plugins.ut.cpp
- userspace/libsinsp/test/plugins/sample_table.h
- userspace/libsinsp/test/plugins/tables.cpp
- userspace/libsinsp/test/plugins/test_plugins.h
- userspace/libsinsp/test/state.ut.cpp
- userspace/libsinsp/threadinfo.h
/kind bug
/kind cleanup
/kind feature
/area libsinsp
/area tests
No
Since introducing the plugin API v3.0.0, and supporting the notion of "state tables" in both libsinsp and the plugin API, there was one major limitation:
- Libsinsp (and its clients) and plugins could both declare their own state tables
- Plugins could access tables declared through libsinsp
- Plugins could access tables declared by other plugins
- Libsinsp **could not** access tables declared by other plugins
This limitation was enforced as a restricted feature rollout for Falco 0.35, and was also a safety measure for potential technical …
> update(userspace/libsinsp): bidirectional state access with plugins, bug fixes, improved error reporting

- userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
- userspace/libscap/examples/01-open/scap_open.c
/kind feature
No
A different return code in case of failed validation allows consumers (like scap-open) to understand that the modern bpf is not supported due to missing requirements
```release-note
NONE
```
> new: return ENOTSUP when the modern probe is not supported

- userspace/libsinsp/plugin.cpp
- userspace/libsinsp/plugin.h
- userspace/libsinsp/plugin_table_api.cpp
- userspace/libsinsp/test/plugins.ut.cpp
- userspace/libsinsp/test/plugins/plugin_extract.cpp
- userspace/libsinsp/test/plugins/sample_table.h
- userspace/libsinsp/test/plugins/syscall_extract.cpp
- userspace/libsinsp/test/plugins/syscall_parse.cpp
- userspace/libsinsp/test/plugins/tables.cpp
- userspace/plugin/plugin_api.h
/kind cleanup
/kind feature
/area libsinsp
/area tests
Yet another plugin PR. This time, we add some new features and we fix a design flaw. The plugin API has been bumped to v3.1.0 (no braking changes, current plugins will keep working as expected even after updating), bringing the following changes:
- Ability to iterate over state tables, both from plugins accessing sinsp's tables and the other way around
- When a state table entry gets acquired through the plugin API (when doing `add_entry` or `get_entry`), the invoker will now have available a `release_entry` function for releasing an entry after it …
> update: support iterating tables in plugin system, post-init event code filters, fixes

- .github/workflows/kernel_tests.yaml
/kind cleanup
/area CI
Fixes #
```release-note
NONE
```
> update(ci): bumped kernel_tests to kernel-testing v0.2.0.

- userspace/libscap/scap.c
- userspace/libscap/scap_platform.c
- userspace/libscap/scap_platform.h
- userspace/libscap/scap_platform_impl.h
While we need the proclist callback to be initialized before the engine (which calls for initializing the platform first), we also call linux_vtable methods (get_vtid) during the /proc scan (which happens inside linux platform_init). That implies initializing the engine first. Given this situation, we can only split the platform setup into two parts:
- initializing the generic part (which engines may depend on)
- initializing the platform specific part (on which no engine should ever depend)
With the engine initialization in between the two. 656be921a5a6ab7cacb1cd4b370c1593a2c2a02f was a previous attempt to fix the initialization order and this commit (mostly) reverts it.
/kind bug
> /kind design
> …
> fix(scap): fix platform initalization order (again)

- .github/workflows/kernel_tests.yaml
- .github/workflows/release-body.yml
/kind feature
/area CI
This PR adds a new pipeline to generate github release body for `driver` tags.
The release-body is autogenerated from latest tag diff; moreover, [kernel testing matrixes](https://falcosecurity.github.io/libs/matrix/) are prepended, so that each driver release is quickly linked to its kernel testing matrix results.
Fixes #
```release-note
NONE
```
> new(ci): add a release-body CI for drivers releases.

- .github/workflows/release-body.yml
/kind bug
/area CI
Do not use `ed` in release-body workflow. It was returning `1` (even if it was working!).
Fixes #
```release-note
NONE
```
> fix(ci): fixed release-body workflow to avoid using ed.

- .github/workflows/release-body.yml
/kind bug
/area CI
Workarounds a limitation of `workflow_run` workflows: they do not inherit `github` context (thus no `github.{ref,ref_name,...}`
We were seeing this error in the ci: https://github.com/softprops/action-gh-release/blob/master/src/main.ts#L23
For more info about the limitation, see: https://github.com/orgs/community/discussions/27124
For the solution, see: https://github.com/orgs/community/discussions/27124#discussioncomment-3254715
For the full properties of `workflow_run` event, see: https://github.com/github/docs/issues/4612#issuecomment-856182852
Fixes # …
> fix(ci): force tag_name in release-body workflow.

- .github/workflows/release-body.yml
/kind cleanup
/area CI
This PR does 2 things:
* only trigger the release-body workflow when `kernel_tests` were triggered on a `release/` branch; before, if `kernel_tests` was triggered from a branch (and not master), this would have triggered the `release-body` workflow too...
* Always append our matrixes to existing release body, so that the releaser has added the release notes (or autogenerates them through github GUI), we do not overwrite data, instead we append matrixes. See https://github.com/softprops/action-gh-release/blob/master/src/github.ts#L241 for the behavior …
> fix(ci): match release branches in release-body

- driver/modern_bpf/programs/attached/events/signal_deliver.bpf.c
as per title
Release Notes:
```release-note
fix(modern_bpf): fix NULL dereference in signal_deliver filler
```
> Port ebpf null fix to 0.12.x branch

- userspace/libsinsp/fdinfo.cpp
- userspace/libsinsp/fdinfo.h
- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/sinsp.cpp
- userspace/libsinsp/sinsp.h
- userspace/libsinsp/threadinfo.cpp
/kind bug
/kind cleanup
/area libsinsp
The libsinsp class struct size is currently dependent on some compilation flags masked under #ifdef definitions. This is troublesome for whoever imports the libs headers, as they may see a different struct size compared to the libsinsp object files, which inherently can lead to out-of-memory access and segfaults.
```release-note
fix(userspace/libsinsp): make sinsp struct size independent from compilation flags
```
> fix(userspace/libsinsp): make sinsp struct size independent from compilation flags

- userspace/libsinsp/plugin_table_api.cpp
/kind bug
/kind cleanup
/area libsinsp
The changed line causes trouble when enforcing stricter compilation warnings due to an ambiguous move casting.
```release-note
fix(userspace/libsinsp): solve ambiguous move casting
```
> fix(userspace/libsinsp): solve ambiguous move casting

- userspace/libscap/linux/scap_cgroup.c
/kind bug
/area libscap
No
This off-by-one error results in an empty set of v1 cgroups. `p` points at a `:`, but then the search for another `:` causes 'q' to always point at the same one as `p`, causing `p` to always be an empty string when `q` is cleared. The loop is exited when `p` is found to be an empty string, adding no new cgroup subsystems to the set:
```c
char *p = strchr(line, ':');
if (!p)
{
// ...
}
char *q = strchr(p, ':');
if (!q)
{
// ...
}
*q = 0;
if (strlen(p) == 0)
{
continue;
}
```
This patch advances `p` to point at the first character of the subsystem string, _then_ begin `q's` search, …
> fix(libscap): off-by-one bug in cgroup v1 parser

- userspace/libscap/linux/scap_cgroup.c
`get_cgroup_subsystems_v2` already returns subsystem names only, not `subsys=path`, so the strchr won't ever return anything else than NULL.
In fact, the whole `subsys` variable is unnecessary, we can use `cgset_subsys` directly.
/kind bug
> /kind design
> /area build
> /area CI
> …
> fix(scap): remove unnecessary and harmful strchr(`=`)

- .github/workflows/release-body.yml
/kind bug
/area CI
Ensure that `release-body` CI runs on new driver tags.
This is a bit cumbersome because `workflow_run` does not support `tags` filter.
So, we have a CI (kernel_tests` that is triggered by new drivers tags, and then we want to trigger the `release-body` workflow when it completes.
We always trigger the release-body workflow (except when coming from a `master` run of kernel_tests`, small optimization), but check that `head_ref` is indeed a driver tag.
Fixes # …
> fix(ci): fixed release-body CI trigger.

- .github/workflows/release-body.yml
/kind cleanup
Cherrypicks https://github.com/falcosecurity/libs/pull/1264 onto release/0.12.x branch.
Fixes #
```release-note
NONE
```
> sync: release 0.12.x

- cmake/modules/openssl.cmake
/kind feature
/area build
No
OpenSSL 1.x will be supported until September 7th: https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/ so we need to upgrade before next release. I'm surprised to see Falco building fine with a major version bump but we need to
1. make sure that it actually works and test Falco properly before release
2. remove deprecated APIs (you can see build warnings for those)
So it's probably better to merge this sooner rather than later. I noticed some pretty long time for compiling the new OpenSSL but that's about the only difference.
Fixes #1038
**Special notes …
> new(build): upgrade to OpenSSL 3.1.1

- userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
> cleanup(libsinsp): swap check order in is_in_pid_namespace()

- userspace/libsinsp/test/CMakeLists.txt
/kind cleanup
/area build
This avoids downloading the same SCAP files over and over everytime we configure the project with `cmake ..`.
```release-note
NONE
```
> chore(userspace/libsinsp/test): skip scap file download if already present

- userspace/libsinsp/CMakeLists.txt
- userspace/libsinsp/sinsp_debug/CMakeLists.txt
- userspace/libsinsp/sinsp_debug/README.md
- userspace/libsinsp/sinsp_debug/sinsp_debug.cpp
/kind feature
/area libsinsp
No
This PR introduces a simple binary to debug a scap-file. I used this binary during the process lineage feature https://github.com/falcosecurity/libs/pull/1182 and i found it very helpful! The output is inspired by another tool that is able to catch the state of system's tasks (https://github.com/Andreagit97/bpftree). In this way, it should be quite easy to check our thread state against the system one :) 
```release-note
NONE
```
> new: introduce a new sinsp binary to improve scap-file debugging

- userspace/libsinsp/parsers.cpp
- userspace/libsinsp/sinsp_debug/sinsp_debug.cpp
- userspace/libsinsp/test/parsers/parse_clone.cpp
/kind bug
/area libsinsp
No
This is yet another corner case with clone flags :/ I discovered it by using the falco e2e framework with old scap-files.
`PPM_CL_CLONE_PARENT` is set by `runc:[0:PARENT]` when it creates the first process in the new pid namespace. In new sinsp versions `PPM_CL_CHILD_IN_PIDNS` is enough to detect this behavior but in old scap-files where we don't have this custom flag, we should leave the event to the child parser when `PPM_CL_CLONE_PARENT` is set since we don't know if the new child is in a pid namespace or not.
Moreover when `PPM_CL_CLONE_PARENT` is set, `PPM_CL_CLONE_NEWPID` …
> fix(sinsp): correctly manage `runc` process in old scap-files

- .github/workflows/pages.yml
- requirements.txt
/kind cleanup
/area CI
No
This PR removes the `requirements.txt` file using explicit dependencies in the `deploy-pages` job
```release-note
NONE
```
> cleanup: remove `requirements.txt` file

- userspace/libsinsp/CMakeLists.txt
Migrated 'sinsp' CMake target_link_libraies() commands to the scoped PRIVATE / PUBLIC / INTERFACE signature.  This is to minimize the potential for symbol conflicts in applications that use the library.
/kind cleanup
/area build
/area libsinsp
> /area tests
Migrates `libsinsp` `target_link_library()` commands to the scoped …
> Scoped target_link_libraries() commands for libsinsp

- driver/README.VERSION.md
> /kind bug
/kind cleanup
> /kind design
/area API-version
> /area build
> /area CI
> /area tests
> …
> docs(README.VERSION.md): clarify when internal version must not be bumped and general improvements

- cmake/modules/GetVersionFromGit.cmake
/area build
> /area CI
> /area tests
> /version …
> fix(cmake/modules): make GetVersionFromGit when no git info

- driver/ppm_fillers.c
/kind bug
/kind cleanup
/area API-version
This unused variable causes a build failure when we use warning as errors
```release-note
NONE
```
> fix: remove an unused variable in the kmod

- userspace/libscap/linux/scap_linux_platform.c
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
> fix(scap): initialize cgroup interface during platform init.

- driver/bpf/fillers.h
- driver/modern_bpf/definitions/missing_definitions.h
- driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/umount2.bpf.c
- driver/ppm_fillers.c
- driver/ppm_flag_helpers.h
- change the flags (param 1) from u32 to s32
- add a userspace to scap flag conversion helper routine
Reported by: github issue #515
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area …
> fix umount2 syscall flags type, add conversion helper function

- userspace/libsinsp/container_engine/docker/connection_linux.cpp
/kind bug
/area libsinsp
Set a maximum time in seconds that you allow the entire transfer operation to take when trying to retrieve docker info.
Fixes #1292 
https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html :
> Default timeout is 0 (zero) which means it never times out during transfer. 
```release-note
NONE
```
> fix(userspace/libsinsp): set a timeout on the curl handle when retrieving docker info

- docs/index.md
- docs/matrix.md
- docs/syscalls.md
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area tests …
> cleanup(docs): edit libs page content for technical clarity
