.github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
=> docs: pull requests template

.clang_format
Co-Authored-By: Leonardo Di Donato <leodidonato@gmail.com>
Signed-off-by: Lorenzo Fontana <lo@linux.com>
/kind cleanup
/area build
Clang format based out to our coding conventions.
```release-note
NONE
```
=> chore: clang format based on coding conventions

userspace/libscap/scap.c
Signed-off-by: Lorenzo Fontana <lo@linux.com>
Udig should not deal with bpf handle type.
/kind cleanup
Fixes #
```release-note
NONE
```
=> chore: remove bpf from udig scap_next_udig

userspace/libsinsp/sinsp.h, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
Signed-off-by: Grzegorz Nosek <grzegorz.nosek@sysdig.com>
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area tests
Just fixing a few typos and formatting issues that apparently weren't merged upstream yet.
```release-note
NONE
```
=> Fix some typos and indentation

userspace/chisel/chisel_utils.cpp
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Fixes #
Special thanks to @gnosek for having discovered this issue :+1: 
```release-note
NONE
```
=> fix(userspace/chisel): loading time initializations

userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/examples/CMakeLists.txt, userspace/libsinsp/examples/README.md, userspace/libsinsp/examples/test.cpp, userspace/libsinsp/examples/util.cpp, userspace/libsinsp/examples/util.h
Signed-off-by: David Windsor <dwindsor@secureworks.com>
/area libsinsp
add libsinsp example code and documentation
**Which issue(s) this PR fixes**: 
https://github.com/falcosecurity/libs/issues/31
Fixes #
```release-note
new: added libsinsp example code and documentation
```
=> docs: add libsinsp example code and documentation

CMakeLists.txt, coding_conventions.md, driver/main.c, driver/ppm_events_public.h, userspace/libscap/scap.h, userspace/libscap/scap_bpf.c, userspace/libscap/scap_savefile.c, userspace/libsinsp/event.h, userspace/libsinsp/fields_info.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/k8s.h, userspace/libsinsp/logger.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
/kind cleanup
/area build
/area libscap
/area libsinsp
It just refactors and adjusts the wording of comments and documentation comments around the project.
NONE
No API changes have been made.
No changes to variable names have been made.
```release-note
NONE
```
=> Wording and refactoring of docs

.github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
NONE
Missing proposals area in the PR template.
```release-note
NONE
```
=> docs(.github): add proposals area to PR template

proposals/20210524-versioning-and-release-of-the-libs-artifacts.md
Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
NONE
Please notice this is a WIP.
It'll serve as a baseline to discuss this topic with the other maintainers during Wednesday's community call.
```release-note
docs(proposals): versioning and release process
```
=> new(proposals): versioning + release process of the libs artifacts

userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h
> /kind bug
> /kind design
kind feature
> /area build
area libsinsp
> /area tests
**What this PR does / why we need it**: Currently clients are diretly modifying this value. It should instead be modified via an API
**Which issue(s) this PR fixes**: Code cleanliness. Avoiding adding "friends"
Fixes #
```release-note
NONE
```
=> expose setting track connection status on sinsp parser

CMakeLists.txt
Co-authored-by: Mark Stemm <mark.stemm@gmail.com>
/kind bug
> /kind design
/area build
/area libscap
/area libsinsp
> /area tests
Allow proper `strlcpy` detection and handling by moving the cmake check before inclusion of the libs directory.
Fixes #
```release-note
NONE
```
=> fix(cmake): set cflags before including the libs dir

userspace/libsinsp/filter.cpp, userspace/libsinsp/value_parser.cpp
/kind feature
/area libsinsp
Fixes #112
```release-note
new: support filtering on rawarg.(rel)path. 
```
=> new(userspace/libsinsp): properly support filtering on rawarg.(rel)path.

OWNERS
I know the code fairly well and would be happy to help out with
reviewing PRs.
> /kind bug
/kind cleanup
> /kind design
/area build
> /area tests
Fixes #
```release-note
NONE
```
=> Add Mark Stemm as libs OWNER

cmake/modules/gtest.cmake, userspace/libsinsp/test/CMakeListsGtestInclude.cmake
/kind bug
> /kind design
/area build
> /area tests
Fixes #
```release-note
NONE
```
=> fix(build): switch gtest to use main branch instead of master

driver/main.c
sysdig-CLA-1.0-signed-off-by: Bernhard M. Wiedemann <bwiedemann@suse.de>
note: not tested here, but in the context of [sysdig-0.27.1](https://github.com/draios/sysdig/pull/1717) and re-submitting as proposed by @FedeDP  ;  patch applied cleanly.
/kind bug
> /area build
without this patch, compilation failed with
```
ERROR: modpost: "__umoddi3" [/home/abuild/rpmbuild/BUILD/sysdig-0.27.0/build/driver/src/sysdig-probe.ko] undefined!
```
Fixes # N/A
```release-note
kernel module now also builds on i586 and armv7l
```
=> Fix compilation on i586

OWNERS
> /kind bug
> /kind design
/area build
> /area tests
I am proposing myself as a maintainer: during the last few months i have been quite busy fixing eBPF issues, improving overall code quality and implementing both fixes and new features on the libs repository.
Moreover, i engaged as much as i could with the community by answering issues both on github and on the …
=> update(OWNERS): add Federico Di Pierro (fededp) to OWNERS

userspace/libscap/plugin_info.h, userspace/libsinsp/fields_info.cpp, userspace/libsinsp/filter.cpp, userspace/libsinsp/gen_filter.cpp, userspace/libsinsp/gen_filter.h, userspace/libsinsp/plugin.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libsinsp
> /area tests
Fixes #
```release-note
NONE
```
=> Field properties changes

README.md
> /kind bug
> /kind design
/area build
> /area tests
Fixes #
```release-note
NONE
```
=> update: update readme with more informations

userspace/libsinsp/plugin.cpp
`Signed-off-by: Federico Di Pierro <nierro92@gmail.com>`
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): fix a wreorder warning that caused errors on centos7 build for Falco

proposals/20210524-versioning-and-release-of-the-libs-artifacts.md, proposals/20220203-versioning-schema-amendment.md
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
> /kind bug
/kind design
> /area build
> /area tests
Fixes #
```release-note
NONE
```
=> docs(proposals): versioning schema amendment

userspace/libsinsp/container.cpp, userspace/libsinsp/container.h, userspace/libsinsp/container_engine/cri.cpp, userspace/libsinsp/container_engine/cri.h, userspace/libsinsp/cri.cpp, userspace/libsinsp/cri.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
/area libsinsp
> /area tests
This allows to pass multiple "--cri" option in Falco and be sure that the first socket that works will be used.
A PR in Falco is needed to manage multiple "--cri" options though.
Fixes #
```release-note
new: support setting multiple cri socket …
```
=> new(userspace/libsinsp): allow to specify a list of cri socket paths to be tried in fallback manner.

userspace/libsinsp/filter.cpp
/kind bug
/area libsinsp
This PR fixes a bug that caused fields to be formatted incorrectly, and that is related to the extraction of list types.
Fixes #
```release-note
NONE
```
=> fix(libsinsp): format list fields correctly

userspace/libsinsp/utils.cpp
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
In some cases, the source IP for IPv6 was printed instead of the destination in the socket info structure.
Related to issue #260
Fixes #
```release-note
fix(libsinsp): fix ipv6 destination ip printing …
```
=> fix(libsinsp): fix ipv6 destination ip printing

OWNERS
As said in today's community call, in this PR I want to propose myself as a libs maintainer: during the last few months, I have been quite busy fixing issues around the repo, mainly in our drivers. By the way, I have also good knowledge about how our library works and I can help the actual maintainers in reviewing the code since every day we have more and more PRs in the libs repo.  I offer here my support, let me know if it can be useful for you or not, remember that this is just a proposal. Thank you. …
=> update(OWNERS): add Andrea Terzolo (andreagit97) to OWNERS

driver/ppm_flag_helpers.h
/kind bug
Deal with clang quirkiness and make it use the proper register
Fixes #
No
```release-note
NONE
```
=> fix(driver/bpf): sys_open_e verifier issue on aarch64

cmake/modules/CompilerFlags.cmake, userspace/libsinsp/user.cpp
Add checks for pwd.h and grp.h, which aren't available in the Windows SDK.
> /kind bug
/kind cleanup
> /kind design
> /area build
/area libsinsp
> /area tests
This adds checks for pwd.h and grp.h, which aren't available in the Windows SDK.
Fixes #
```release-note
NONE
```
=> update(userspace/libsinsp): Fix building on Windows.

userspace/libscap/scap_event.c
/kind bug
> /kind design
> /area build
/area libscap
> /area tests
Add the relevant `PT_ENUMFLAGS` 8, 16, 32 to the respective cases when encoding events.
Fixes #
```release-note
NONE
```
=> fix(libscap): add support for PT_ENUMFLAGS to scap_event_encode

userspace/libsinsp/threadinfo.cpp
/kind bug
> /kind design
> /area build
/area libsinsp
> /area tests
Fix uninitialized m_ptid in threadinfo
Fixes #
```release-note
NONE
```
=> Initialize m_ptid when initializing other vars

cmake/modules/CompilerFlags.cmake, userspace/libsinsp/event.h, userspace/libsinsp/plugin.cpp, userspace/libsinsp/sinsp_int.h, userspace/libsinsp/version.h
> /kind bug
/kind cleanup
> /kind design
/area build
/area libsinsp
> /area tests
Fixes a couple of build issues on Windows.
Fixes #
```release-note
NONE
```
=> Fix windows includes

cmake/modules/openssl.cmake
/kind bug
> /kind design
> /area build
/area libscap
/area libsinsp
> /area tests
Update OpenSSL to the latest version for the 1.1.1 Series, also fixing the following vulnerabilities:
* CVE-2022-1292
* CVE-2022-0778
* CVE-2021-4160
Fixes #
```release-note
update(cmake): Update OpenSSL …
```
=> update(cmake): bump OpenSSL to 1.1.1o

userspace/libscap/examples/01-open/test.c
> /kind bug
> /kind design
/kind feature
> /area build
/area tests
Fixes #
```release-note
NONE
```
=> new(userspace/libscap): add a --scap_file option to scap-open test.

userspace/chisel/chisel_api.cpp, userspace/libsinsp/filter.cpp, userspace/libsinsp/filterchecks.h, userspace/libsinsp/table.cpp
/kind bug
/area libsinsp
This follows-up the changes of https://github.com/falcosecurity/libs/pull/368 and hunts down all the cases in which the unwanted allocation was present.
```release-note
NONE
```
=> fix(userspace/libsinsp): reduce mem allocs for field extraction in chisels and formatting

userspace/libsinsp/plugin.cpp
/kind cleanup
/area libsinsp
Fixes #243
```release-note
chore(userspace/libsinsp): improve messages of plugin version errors
```
=> chore(userspace/libsinsp): improve messages of plugin version errors

userspace/libscap/engine/gvisor/CMakeLists.txt, userspace/libscap/engine/gvisor/config.json, userspace/libscap/engine/gvisor/gvisor.cpp, userspace/libscap/engine/gvisor/gvisor.h, userspace/libscap/engine/gvisor/parsers.cpp, userspace/libscap/engine/gvisor/proto/pkg/sentry/seccheck/points/common.proto, userspace/libscap/engine/gvisor/scap_gvisor.cpp, userspace/libscap/engine/kmod/scap_kmod.c, userspace/libscap/engine/noop/noop.c, userspace/libscap/engine/noop/noop.h, userspace/libscap/scap.c, userspace/libscap/scap_engines.h, userspace/libscap/scap_open.h, userspace/libscap/scap_procs.c, userspace/libscap/scap_vtable.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
/area libscap
> /area tests
This PR continues the work required to get gVisor events into Falco. This PR adds a C++ class that can be used to manage the state, connections and required memory for the engine that can connect to gVisor seccheck. In order to be complete it will require the additions in https://github.com/falcosecurity/libs/pull/213 , but I'm publishing it already so maintainers …
=> new(libscap): add gVisor scap engine

userspace/libscap/scap_open.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h
/kind bug
> /kind design
> /area build
> /area tests
Right now the process would crash if the user forgets …
=> fix(gvisor): handle empty root path or socket

release.md
/area build
Although the releases process is not fully implemented, I believe it's time to add release instructions since we are planning to tag releases very soon.
Fixes #
The document reflects the current development state. Most of the manual checks described in the document may be automated in future.
```release-note
NONE
```
=> docs: initial release.md

driver/ppm_events_public.h
/kind bug
/area build
Fix for custom builds where a certain header is included in C++ code.
Fixes #439
```release-note
NONE
```
=> Fix 'declaration changes meaning' error when compiling in C++

userspace/libscap/engine/gvisor/scap_gvisor.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area tests
This little PR introduces a default root …
=> update(gvisor): introduce default root path

userspace/libscap/scap.h
/kind bug
/area libscap
This PR superseds #443.
The minimum schema version in the libscap needs to be bumped in order for it to be compatible with the bump to `2.0.0` in the drivers.
Fixes #
```release-note
NONE
```
=> fix(libscap): bump minimum schema version to 2.0.0

.gitignore, userspace/libscap/engine/udig/udig.h, userspace/libsinsp/plugin.cpp
> /kind bug
/kind cleanup
> /kind design
/area build
/area libscap
/area libsinsp
> /area tests
Fixes the build under Visual C++ and allows for a CMake presets file. …
=> Fix windows build

CMakeListsGtestInclude.cmake
/kind bug
> /kind design
/area build
> /area tests
This PR sets GoogleTest to v1.12.1, which is also the …
=> fix(build): set gtest tag instead of using main

.github/PULL_REQUEST_TEMPLATE.md
This PR updates the `PULL_REQUEST_TEMPLATE.md` with a new `libpman` area.
```release-note
NONE
```
=> docs: add `libpman` label

cmake/modules/curl.cmake
Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>
/kind bug
/area build
Removing 2 configuration flags for curl that was making it unable to verify HTTPs certificate when Falco, compiled in bundled mode, runs with http output and an HTTPS url
Fixes #441
```release-note
NONE
```
=> fix(curl-https-fail): Removing 2 configuration flags for lib curl

driver/bpf/fillers.h, driver/flags_table.c
Issues spotted with `cppcheck`.
/kind cleanup
Fixes #
```release-note
NONE
```
=> fix(driver): fixed a couple of possible (yet unlikely) uninitialized vars in driver

OWNERS
As discussed during today's community call, I've been contributing with reviews and fixes in the repository over the last couple of months, I feel it is time for me to make a bigger commitment with the project so I'm proposing myself as maintainer for it.
Fixes #
```release-note
NONE
```
=> update(OWNERS): add Mauro Moltrasio (Molter73) to OWNERS

userspace/libscap/scap-int.h, userspace/libscap/scap.h, userspace/libscap/scap_savefile.c, userspace/libsinsp/container_engine/bpm.cpp, userspace/libsinsp/container_engine/docker/podman.cpp, userspace/libsinsp/container_engine/libvirt_lxc.cpp, userspace/libsinsp/container_engine/lxc.cpp, userspace/libsinsp/container_engine/mesos.cpp, userspace/libsinsp/container_engine/rkt.cpp, userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/runc.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
Since the proclist is not thread-safe, we had some corrupted captures
because the length was pre-computed and then when the actual item was
written it was different, hence the total was off.
Reduce the likelihood of this by using a secondary dumper, summing up
the lengths in a single loop and then writing everything at once.
Signed-off-by: Angelo Puglisi <angelopuglisi86@gmail.com>
/kind bug
> /kind design
> /area build
> …
=> fix: thread-safety issue in proclist savefile

.github/workflows/ci.yml, cmake/modules/libscap.cmake, userspace/libscap/CMakeLists.txt, userspace/libscap/engine/udig/CMakeLists.txt, userspace/libscap/ringbuffer/devset.c, userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/examples/CMakeLists.txt, userspace/libsinsp/examples/test.cpp
/kind bug
/area build
/area libscap
Fixes #
```release-note
NONE
```
=> fix(userspace/libscap): fix windows and macos linking of binaries.

.github/install-valijson.sh, .github/workflows/ci.yml, cmake/modules/Findvalijson.cmake, cmake/modules/valijson.cmake
/kind feature
/area build
When not building valijson ourselves, it automatically detects where valijson is installed on the system.
Before that, it was necessary to specify the install prefix during configuration.
```release-note
NONE
```
=> Detect valijson on the system and use it when requested

.github/PULL_REQUEST_TEMPLATE.md
=> chore(PULL_REQUEST_TEMPLATE.md): add savefile engine entry

userspace/libsinsp/test/filter_compiler.ut.cpp, userspace/libsinsp/test/filter_op_bcontains.ut.cpp
/kind bug
/kind cleanup
> /area build
> /area CI
/area libsinsp
/area tests
> …
=> fix(libsinsp/tests): fix two simple memory leaks in tests

userspace/chisel/chisel.cpp, userspace/chisel/chisel_utils.cpp, userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/container_engine/docker/async_source.cpp, userspace/libsinsp/container_info.h, userspace/libsinsp/k8s_event_handler.cpp, userspace/libsinsp/user_event.h
/kind cleanup
/area build
/area libsinsp
This cleans up legacy references that are not used anymore in the codebase.
```release-note
NONE
```
=> cleanup(userspace/libsinsp): remove legacy references

OWNERS
As we discussed in yesterday's (Aug 3rd 2022) Falco community call and given the positive feedback from other current maintainers present, since I worked over the course of the past few months on new features, bugfixes, releases, security content, reviews and refactoring on the Falco libraries I would like to bring my contributions to this project to the next level by proposing myself as a maintainer.
Fixes #
**Does this PR …
=> update(OWNERS): add Luca Guerra (LucaGuerra) to owners

userspace/libsinsp/test/sinsp.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
/area tests
> …
=> new(libsinsp/tests): add basic dup/dup2/dup3 tests

userspace/libsinsp/filter.cpp, userspace/libsinsp/filter/parser.cpp, userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/utils.cpp
improve parser performance by statically precompiling regex
/kind design
/kind feature
/area libsinsp
NO
improving falco parsing performance
Fixes #
NO
```release-note
NONE
```
=> improve fields parsing performance by eliminating temp strings.

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind bug
/area libsinsp
/area tests
Fixes #
```release-note
NONE
```
=> fix(userspace/libsinsp): solve assert errors in unit tests

userspace/libsinsp/examples/test.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests …
=> cleanup(sinsp): add output format option to sinsp-example

.github/workflows/ci.yml
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area tests
**Does this PR …
=> new(ci): run tests with AddressSanitizer on x86_64

README.md
/kind cleanup
Fixes #
```release-note
NONE
```
=> update(readme): add a beautiful archs badge that links to proper section in readme

OWNERS
Signed-off-by: Hendrik Brueckner <brueckner@de.ibm.com>
None
Based the very nice discussion [#569](https://github.com/falcosecurity/libs/pull/569#issuecomment-1239312157) and
@Andreagit97 and @FedeDP feedback:
> I fully agree with Andrea; @hbrueckner you are doing such a tremendous job in reviewing and testing every modern-bpf related PR, it's really stunning! Please take a moment and think about joining us :) it would be great to have such a domain expert helping us with code reviews!
I am delighted to join your team as reviewer! Many thanks for this offer and looking …
=> update(OWNERS): add Hendrik Brueckner (hbrueckner) as reviewer

userspace/libsinsp/filter.cpp, userspace/libsinsp/filter.h, userspace/libsinsp/filter/ast.cpp, userspace/libsinsp/filter/ast.h, userspace/libsinsp/filter/parser.cpp, userspace/libsinsp/filter/parser.h, userspace/libsinsp/test/filter_parser.ut.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> Save parser positions ast

userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/user.ut.cpp, userspace/libsinsp/user.cpp, userspace/libsinsp/user.h
/area libsinsp
/area tests
sinsp_usergroup_manager unit test
Fixes #
See also https://github.com/falcosecurity/libs/pull/542
```release-note
NONE
```
=> new(sinsp/tests): introduce sinsp_usergroup_manager test

userspace/libscap/engine/bpf/scap_bpf.c
/kind bug
No
Old kernels don't support BPF prog names so in this PR we add a fallback to support these corner cases.
The problem was introduced in this commit  https://github.com/falcosecurity/libs/pull/559/commits/38ba7bdd1e5e65c9f4cf621e3d6c81cbfeebbf58
```release-note
NONE
```
=> fix(bpf): fallback for unsupported prog_names

userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
/kind bug
No
This PR fixes a broken CI job
```release-note
NONE
```
=> fix(CI): remove an old reference

userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/sinsp.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h, userspace/libsinsp/test/test_utils.cpp, userspace/libsinsp/test/test_utils.h
/kind feature
/area libsinsp
/area tests
This PR adds a convenience function plus the first test that checks process spawn tracking. This increases libsinsp coverage from ~17% to ~19% . This also should serve as a simple case that can be made more complex to test more edge cases.
Fixes #
```release-note
NONE
```
=> new(libsinsp/test): add spawn process test

userspace/libscap/examples/01-open/scap_open.c
/kind feature
No
This PR adds the possibility to start the scap-open with a set of the most interesting syscalls :) 
```release-note
new(scap-open): add the `simple_set` mode
```
=> new(scap-open): add the `simple_set` mode

userspace/libsinsp/parsers.cpp
/kind bug
Correctly report container user / group information.
The use case is the Falco rule "Terminal shell in container". I created a container like that:
```Dockerfile
FROM busybox:stable
USER 37
CMD [ "sleep", "3600" ]
```
and after running it, I did `docker exec -it test sh -c 'exit 0'`.
If user 37 ("operator" in busybox) is in the host, it will be reported with the corresponding name (wrong), or else it will be `<NA>`.
Debugging it, I found `sinsp_usergroup_manager::add_user` gets called by `sinsp_parser::parse_setuid_exit`, when we don't have the container id yet.
With this change, we update user and group data after we detect we got a …
=> fix(libsinsp): refresh user / group when detecting a container

driver/ppm_events.c
Filler functions run under RCU read lock, where use of blocking locks (or any reschedule) is forbidden.  Filler functions currently call sock->getname(), but this is unsafe because in some kernel versions, inet_getname() uses blocking locks; this results in loss of lock protection, and specifically a use-after-free kernel panic due to ppm_release() freeing a consumer object while it is still in use by the tracepoint handler/filler function.
Solution is to follow the method used by the eBPF probe, and use private logic to retrieve the necessary information from the socket.
Signed-off-by: Joseph Pittman <joseph.pittman@sysdig.com>
/kind bug
> /kind design
> …
=> Avoid calls to sock->getname() from kernel module fillers

driver/main.c
/kind bug
No
This PR fixes a compatibility problem on old kernels
```release-note
NONE
```
=> fix(kmod): check use of `kstrtoul`

driver/main.c, driver/ppm_events.c
=> fix(kmod): fix `kmod` build on some kernels

driver/main.c, driver/ppm_events.c, userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/scap.c, userspace/libscap/scap.h, userspace/libsinsp/event.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/tracers.cpp
/kind cleanup
Synching release branch with commits from (see https://github.com/falcosecurity/libs/issues/626):
- https://github.com/falcosecurity/libs/pull/653
- https://github.com/falcosecurity/libs/pull/652
- https://github.com/falcosecurity/libs/pull/655
- https://github.com/falcosecurity/libs/pull/656
```release-note
NONE
```
=> update(release): sync commits from master

userspace/libscap/engine/kmod/scap_kmod.c
/kind feature
No
This PR avoid to write into the `/sys/module/scap/parameters/g_buffer_bytes_dim` when not necessary, so when the user provided dim is the same written into the `/sys/module/scap/parameters/g_buffer_bytes_dim` file.
We have 2 advantages from this:
* Only read operation in case the default buffer size is used.
* Some system mounts the `/sys/module/...` as read-only by default, if the user doesn't need to update this shared dimension there is no need to put this mount this `fs` in reading and writing. Right now the default buffer size for the `kmod` is `8 MB`
**Which …
=> update(libscap-engine-kmod): avoid a write operation when not necessary

userspace/libsinsp/sinsp_ppm_sc.cpp
/kind bug
/area libsinsp
```release-note
NONE
```
=> fix(userspace/sinsp): return event names of generic syscall events

cmake/modules/libbpf.cmake
/kind cleanup
/area build
Fixes #
```release-note
update(cmake): bumped bundled libbpf to 1.0.1.
```
=> update(cmake): bumped bundled libbpf to 1.0.1, latest version.

userspace/libsinsp/filterchecks.cpp
/kind cleanup
Synching release branch with commits from (see https://github.com/falcosecurity/libs/issues/626):
- https://github.com/falcosecurity/libs/pull/669
```release-note
NONE
```
=> update(release): sync commits from master 

.github/workflows/ci.yml, test/e2e/CMakeLists.txt, test/e2e/containers/sinsp.Dockerfile
/kind feature
/area CI
/area tests
Trying to run the e2e tests on github actions.
The tests have been added to an existing workflow that already builds the userspace library and the drivers in an effort to make them a bit faster than rebuilding everything from scratch.
Additionally, a number of mounts and options have been added to the container running the tests, those are needed for everything to build using the headers from the host and allowing the tests to insert and remove the drivers.
The auto-generated report for the tests is automatically uploaded to GH, for ease of debugging in case of an error.
I've also excluded the `minimal` build from the current …
=> Run e2e tests on CI

README.md
No
This PR adds the required version for `bpftool`
```release-note
NONE
```
=> docs(modern_bpf): add some info about bpftool version

userspace/libsinsp/container.cpp, userspace/libsinsp/container_engine/container_async_source.tpp, userspace/libsinsp/container_engine/docker/base.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> Fix container info lookups no early info

userspace/libsinsp/event.cpp, userspace/libsinsp/event.h, userspace/libsinsp/sinsp.cpp
/kind bug
/kind cleanup
/area libscap
/area libsinsp
Looking forward to a 0.9.1 patch tag, this syncs the release branch with the changes of https://github.com/falcosecurity/libs/pull/699
```release-note
NONE
```
=> update: sync commits on 0.9 branch release 

userspace/libscap/engine/gvisor/parsers.cpp
/kind bug
> /kind design
/area build
> /area CI
> /area tests
> …
=> Make sure O_TMPFILE is defined in gvisor/parsers.cpp

userspace/libscap/scap-int.h, userspace/libscap/scap.c
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
=> scap_t->m_win_*_handle are never used

userspace/libscap/linux/scap_fds.c, userspace/libscap/linux/scap_procs.c
/kind bug
/kind cleanup
/area libscap
No
This PR should solve some issues highlighted by the CodeQL job in Falco:
- https://github.com/falcosecurity/falco/security/code-scanning/18
- https://github.com/falcosecurity/falco/security/code-scanning/19
```release-note
NONE
```
=> fix(userspace): resolve some alerts generated by the Falco CodeQL job

userspace/libsinsp/async/async_key_value_source.h, userspace/libsinsp/async/async_key_value_source.tpp, userspace/libsinsp/container_engine/container_async_source.tpp, userspace/libsinsp/container_engine/cri.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> Fix container engine retry logic

userspace/libscap/engine/bpf/scap_bpf.c
Update 0.9.2 release branch with the eBPF fixes
```release-note
fix(libscap): fixed loading of ebpf probe with offline CPUs
```
=> Sync changes for 0.9.2: bpf bugfixes

driver/ppm.h, driver/ppm_events.h, driver/ppm_events_public.h, userspace/libscap/engine/savefile/savefile.h, userspace/libscap/engine/udig/udig.h, userspace/libscap/linux/scap_fds.c, userspace/libscap/scap-int.h, userspace/libscap/scap.h, userspace/libscap/scap_fds.c
Late November is as good time as any for some spring cleaning :)
This removes some unused includes and declarations and moves some engine-specific stuff (macros, structs) into the engine itself (savefile and udig)
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area …
=> Spring cleaning

userspace/libscap/linux/scap_userlist.c
34e8c2723b554d15981a96b9e07e2dc9d1361367 went a little bit too far with introducing a dedicated variable for the userlist, so in one error path we ended up with a dangling pointer in the handle
/kind bug
> /kind design
> /area build
> /area CI
> …
=> fix(scap): Properly reset handle->m_userlist

userspace/libscap/engine/modern_bpf/scap_modern_bpf.c
/kind bug
> /kind design
/area build
> /area CI
> /area tests
> …
=> Define SCAP_HANDLE_T before including scap_open.h

NOTICES
Signed-off-by: Luca Guerra <35580196+LucaGuerra@users.noreply.github.com>
/area libsinsp
/area libscap
No.
The license NOTICE file contained references to inttypes_win which was since removed with commit bc36892f06099604ca242d6421a0d4997eba9d28 . Remove it from the file as well.
Fixes #
```release-note
NONE
```
=> update(docs): remove inttypes_win from NOTICE

userspace/libscap/linux/scap_procs.c, userspace/libscap/scap-int.h, userspace/libscap/scap.c, userspace/libscap/scap_procs.c, userspace/libscap/scap_savefile.c
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
=> Fix use-after-free when deleting the process table

.github/workflows/ci.yml, userspace/libsinsp/event.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/user.ut.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/user.cpp, userspace/libsinsp/user.h
/kind cleanup
/area libsinsp
NOPE
Fixes #
```release-note
NONE
```
=> cleanup(userspace/libsinsp): small cleanups in user_group_manager API.

driver/OWNERS
No
@hbrueckner helped us a lot in reviewing and fixing drivers in the last months, for this reason, I would propose him as a falcosecurity driver maintainer.  According to our governance https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#maintainership, we need a majority vote to take a decision.
Here you can find the rules for the majority vote :point_down: 
https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#majority-vote
Apart from this bureaucratic stuff, thank you for all the effort you put into …
=> vote: propose `hbrueckner` as a driver libs maintainer

userspace/libscap/CMakeLists.txt, userspace/libscap/linux/scap_procs.c, userspace/libscap/scap-int.h, userspace/libscap/scap.c, userspace/libscap/scap_procs.c, userspace/libscap/scap_suppress.c, userspace/libscap/scap_suppress.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
=> cleanup(userspace): Encapsulate suppressed tid logic in a separate struct

userspace/libsinsp/filter/ast.h, userspace/libsinsp/test/filter_parser.ut.cpp
/kind cleanup
/kind feature
/area libsinsp
Follows up point at https://github.com/falcosecurity/falco/pull/2216#discussion_r1036958583
```release-note
NONE
```
=> update(userspace/libsinsp/filter): add constructor and operators to pos_info

test/e2e/tests/commons/sinspqa/sinsp.py
/kind bug
/area CI
This PR fixes e2e test removing a no more used `sinsp-example` option
```release-note
NONE
```
=> fix(ci): update e2e test with new sinsp example

userspace/libscap/scap.c
/kind cleanup
/kind feature
/area libscap
This PR ensures the capture stop before closing the engine.
```release-note
NONE
```
=> update(userspace): stop capture before closing the engine

userspace/libsinsp/event.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> fix(sinsp): format PT_ABSTIME values

.github/workflows/ci.yml
/kind feature
/area CI
This PR allows maintainers to create upstream branches to test new features. The testing branch must start with `maintainers/` prefix
```release-note
NONE
```
=> update(ci): enable gh actions jobs on `maintainers/` branches

.github/workflows/ci.yml, README.md, cmake/modules/libelf.cmake, driver/bpf/fillers.h, driver/modern_bpf/CMakeLists.txt, driver/modern_bpf/helpers/extract/extract_from_kernel.h, driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/fork.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/vfork.bpf.c, userspace/libpman/CMakeLists.txt, userspace/libscap/engine/modern_bpf/CMakeLists.txt, userspace/libscap/engine/test_input/test_input.c, userspace/libsinsp/container_engine/cri.cpp, userspace/libsinsp/container_info.h, userspace/libsinsp/event.cpp, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/container_info.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
/kind bug
Bugfix only given we have master frozen :) 
Fixes #
```release-note
NONE
```
=> sync(release): sync commits for release/0.10.0 from master

userspace/libsinsp/container_engine/docker/async_source.cpp
Apparently at least the RHEL9 version of podman doesn't properly respond to /images/json?digests=1, while it does return all the info we need without the query parameter. Since ?digests=1 is defined in the Docker API, prefer this as the default, but also try the podman variant.
Note: the API does not return an HTTP error but instead an empty 200 response, so checking the HTTP status is not enough.
Signed-off-by: Grzegorz Nosek <grzegorz.nosek@sysdig.com>
/kind bug
> /kind design
> /area build
> /area CI
> …
=> fix(sinsp): Try /images/json (without ?digests=1) for podman

userspace/libscap/engine/bpf/scap_bpf.c
/kind feature
No
This PR improve logging when we are not able to correctly load out bpf program, in this way we can understand if we a simple tracepoint or a raw_tracepoint
```release-note
update(driver): improve logging in case of failed bpf loading
```
=> update(driver): improve logging in case of failed bpf loading

userspace/libsinsp/container_engine/static_container.cpp
Given the image name for the static container engine, we can parse it into repo/tag/digest to provide a bit more context for consumers.
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> …
=> new(sinsp): Parse other container variables in static container

driver/modern_bpf/helpers/store/auxmap_store_params.h, driver/modern_bpf/helpers/store/ringbuf_store_params.h, userspace/libpman/src/capture.c
/kind cleanup
/area libpman
NOPE
Sync https://github.com/falcosecurity/libs/pull/802 to the release/0.10.0 branch.
Fixes #
```release-note
NONE
```
=> sync: release/0.10.0 #802

userspace/libsinsp/container.cpp, userspace/libsinsp/container.h, userspace/libsinsp/sinsp.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> new(sinsp): Allow enabling/disabling individual container engines on startup

driver/modern_bpf/definitions/events_dimensions.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/mprotect.bpf.c, test/drivers/event_class/event_class.cpp, test/drivers/test_suites/syscall_enter_suite/mprotect_e.cpp, test/drivers/test_suites/syscall_exit_suite/mprotect_x.cpp, userspace/libpman/src/events_prog_names.h
Signed-off-by: David Windsor <dwindsor@secureworks.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests …
=> new(modern_probe): Add mprotect

release.md
Signed-off-by: Leonardo Grasso <me@leonardograsso.com>
> /kind bug
> /kind design
> /area build
> /area CI
> /area tests …
=>  docs(release.md): remove typo

cmake/modules/openssl.cmake
/kind bug
/area build
No.
Update OpenSSL to 1.1.1q, fixing any known potential security issues
Fixes #
```release-note
NONE
```
=> update(build): update openssl to 1.1.1q

driver/modern_bpf/definitions/events_dimensions.h, driver/modern_bpf/definitions/missing_definitions.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/mlock.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/mlock2.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/mlockall.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/munlock.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/munlockall.bpf.c, test/drivers/test_suites/syscall_enter_suite/mlock2_e.cpp, test/drivers/test_suites/syscall_enter_suite/mlock_e.cpp, test/drivers/test_suites/syscall_enter_suite/mlockall_e.cpp, test/drivers/test_suites/syscall_enter_suite/munlock_e.cpp, test/drivers/test_suites/syscall_enter_suite/munlockall_e.cpp, test/drivers/test_suites/syscall_exit_suite/mlock2_x.cpp, test/drivers/test_suites/syscall_exit_suite/mlock_x.cpp, test/drivers/test_suites/syscall_exit_suite/mlockall_x.cpp, test/drivers/test_suites/syscall_exit_suite/munlock_x.cpp, test/drivers/test_suites/syscall_exit_suite/munlockall_x.cpp, userspace/libpman/src/events_prog_names.h
Signed-off-by: David Windsor <dwindsor@secureworks.com>
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests …
=> new(modern_probe): Add mlock, mlock2, munlock, mlockall, munlockall

driver/bpf/filler_helpers.h, driver/bpf/fillers.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/quotactl.bpf.c, driver/ppm_events.c, driver/ppm_fillers.c, test/drivers/test_suites/generic_tracepoints_suite/sched_process_exec.cpp, test/drivers/test_suites/generic_tracepoints_suite/sched_process_fork.cpp, test/drivers/test_suites/syscall_enter_suite/connect_e.cpp, test/drivers/test_suites/syscall_exit_suite/clone3_x.cpp, test/drivers/test_suites/syscall_exit_suite/clone_x.cpp, test/drivers/test_suites/syscall_exit_suite/execve_x.cpp, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp, test/drivers/test_suites/syscall_exit_suite/fork_x.cpp, test/drivers/test_suites/syscall_exit_suite/ioctl_x.cpp, test/drivers/test_suites/syscall_exit_suite/open_by_handle_at_x.cpp, test/drivers/test_suites/syscall_exit_suite/recvfrom_x.cpp, test/drivers/test_suites/syscall_exit_suite/recvmsg_x.cpp
/kind bug
/kind feature
No
This PR belongs to the https://github.com/falcosecurity/libs/pull/783 series. It fixes some differences between the 3 drivers. It tries also to simplify code paths where possible.
```release-note
NONE
```
=> fix(driver): extend modern bpf test framework to all drivers (part 4)

driver/modern_bpf/helpers/store/auxmap_store_params.h, driver/modern_bpf/helpers/store/ringbuf_store_params.h, userspace/libpman/src/capture.c
/kind cleanup
It reverts a couple of commits on the release/0.10.0 branch; that release branch will be left as-is, while we will be opening a release/0.10.x soon, given the new procedure highlighted in https://github.com/falcosecurity/libs/pull/821 .
Fixes #
```release-note
NONE
```
=> reset release 0.10.0 branch to 0.10.0 tag

OWNERS
As discussed in the community call of 2023-01-11, I'd like to propose myself as an approver in this repository. I worked on the codebase for a while and gained good knowledge of it, so I'd like to help the group of maintainers managing the repo with all its ever-growing PRs and issues.
```release-note
NONE
```
=> vote: update(OWNERS): add jasondellaluce to approvers

userspace/libsinsp/container_engine/docker/podman.cpp
When rootless podman containers are run as a service,
there's nothing identifying podman in the cgroup as it looks like:
`/user.slice/user-<uid>.slice/user@<uid>.service/<unit>/<container_id>`
where <unit> is whatever started the container, e.g. foo.service.
Let's hope for the best and assume that all such cgroups are
podman containers.
We can probably narrow the prefix down to ".service/" in the typical
case but as we're already basically guessing, let's keep it generic.
/kind bug
> /kind design
> /area build
> /area CI
> …
=> fix(sinsp): support rootless podman containers in systemd services

userspace/libsinsp/parsers.cpp
/kind bug
/area libsinsp
Cherrypicks #841 for 0.10.2 release.
Fixes #
```release-note
NONE
```
=> Sync/release 0.10.2

.github/workflows/ci.yml, userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/kmod/scap_kmod.c, userspace/libscap/linux/scap_fds.c, userspace/libscap/linux/scap_procs.c, userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_auth.cpp
/kind bug
Cherrypicks PR #850 
Fixes #
```release-note
NONE
```
=> sync: release 0.10.3

.github/workflows/update-syscalls.yml
/kind feature
/area CI
No
Porting of update-syscalls Prow job.
Waiting for Poiana token (missing at the moment).
```release-note
NONE
```
=> new(ci): added update-syscalls gha.

cmake/modules/openssl.cmake
/kind bug
/area build
/area libsinsp
No
Keep our OpenSSL dependencies updated with the latest security fixes. Nothing that looks critical for Falco: https://www.openssl.org/news/secadv/20230207.txt
Fixes #
```release-note
NONE
```
=> update(build): upgrade openssl to 1.1.1t

userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_ppm_sc.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests …
=> cleanup(libsinsp): extend ppm_sc sinsp API

driver/modern_bpf/definitions/events_dimensions.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/semctl.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/semget.bpf.c, test/drivers/test_suites/syscall_enter_suite/semctl_e.cpp, test/drivers/test_suites/syscall_enter_suite/semget_e.cpp, test/drivers/test_suites/syscall_exit_suite/semctl_x.cpp, test/drivers/test_suites/syscall_exit_suite/semget_x.cpp, userspace/libpman/src/events_prog_names.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests …
=> new(modern_bpf): add support for semget and semctl syscall

driver/modern_bpf/programs/attached/events/sched_switch.bpf.c
/kind bug
> /kind design
> /area build
> /area CI
> /area tests …
=> fix(modern_bpf): actually extract minor page fault number

userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests …
=> cleanup(libsinsp): introduce set operations utils functions

userspace/libpman/src/ringbuffer.c
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libpman
> /area tests
> …
=> fix(libpman): fix fclose

driver/report.md
No
This PR highlights the meaning of 🟡  and 🟢 in the report and tries to be more user-friendly without technical terms like `event_table` and `generic` events
```release-note
NONE
```
=> doc: update syscall report

driver/modern_bpf/definitions/events_dimensions.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/futex.bpf.c, test/drivers/test_suites/syscall_enter_suite/futex_e.cpp, test/drivers/test_suites/syscall_exit_suite/futex_x.cpp, userspace/libpman/src/events_prog_names.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> …
=> new(modern_bpf): add support for futex syscall

userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/tracers.cpp
/kind bug
/kind cleanup
/area libsinsp
No.
As per title, probably happened during a botched copy-paste while we were working on cleanups. I would like to correct the variable names to make the code a little more readable.
Fixes #
```release-note
NONE
```
=> update(libsinsp): fix reduced_ variable names

driver/bpf/fillers.h, driver/modern_bpf/definitions/events_dimensions.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/llseek.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/lseek.bpf.c, driver/ppm_fillers.c, test/drivers/test_suites/syscall_enter_suite/llseek_e.cpp, test/drivers/test_suites/syscall_enter_suite/lseek_e.cpp, test/drivers/test_suites/syscall_exit_suite/llseek_x.cpp, test/drivers/test_suites/syscall_exit_suite/lseek_x.cpp, userspace/libpman/src/events_prog_names.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> …
=> new(modern_bpf): add support for lseek and llseek system calls

userspace/libsinsp/CMakeLists.txt, userspace/libsinsp/events/sinsp_events.cpp
/kind bug
/kind cleanup
/area build
/area libsinsp
This fixes a couple of issues encountered while trying to sync Falco with the latest changes in libs.
```release-note
NONE
```
=> fix: build issues and minor fixes

driver/modern_bpf/definitions/events_dimensions.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/getresgid.bpf.c, test/drivers/test_suites/syscall_enter_suite/getresgid_e.cpp, test/drivers/test_suites/syscall_exit_suite/getresgid_x.cpp, userspace/libpman/src/events_prog_names.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libpman
> /area tests
> …
=> new(modern_probe): Add getresgid

userspace/libsinsp/events/sinsp_events.cpp, userspace/libsinsp/events/sinsp_events_ppm_sc.cpp, userspace/libsinsp/events/sinsp_events_set.h, userspace/libsinsp/events/sinsp_events_tp.cpp, userspace/libsinsp/test/public_sinsp_API/interesting_syscalls.cpp
/kind bug
/area libsinsp
By letting others write directly to our inner vector, we did not update size.
```release-note
NONE
```
=> fix(libsinsp): removed libsinsp::events::set.data() writable method.

README.md
Fixes #
```release-note
NONE
```
=> chore(docs): add badge for new `Test build latest kernel available in arch`

userspace/libsinsp/test/public_sinsp_API/events_set.cpp, userspace/libsinsp/test/public_sinsp_API/interesting_syscalls.cpp, userspace/libsinsp/test/test_utils.h
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
/area tests
> …
=> cleanup(unit_tests): ppm sc API + point out outstanding fixes needed for `event_set_to_sc_set` and `event_set_to_names` 

driver/bpf/fillers.h, driver/modern_bpf/definitions/events_dimensions.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/nanosleep.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/ppoll.bpf.c, driver/ppm_fillers.c, test/drivers/test_suites/syscall_enter_suite/nanosleep_e.cpp, test/drivers/test_suites/syscall_enter_suite/ppoll_e.cpp, test/drivers/test_suites/syscall_exit_suite/nanosleep_x.cpp, userspace/libpman/src/events_prog_names.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
> /area tests
> …
=> new(modern_probe): Add nanosleep

driver/bpf/plumbing_helpers.h, driver/modern_bpf/helpers/interfaces/syscalls_dispatcher.h, driver/ppm_fillers.c
/kind bug
/kind cleanup
No
This PR addresses some comments relative to #811
* https://github.com/falcosecurity/libs/pull/811#pullrequestreview-1287983817
```release-note
NONE
```
=> fix(driver): address some minor comments relative to #811

userspace/libsinsp/test/filter_ppm_codes.ut.cpp
/kind cleanup
/area libsinsp
/area tests
This finishes up the ppm_sc and event set codes tests for libsinsp filters, which furthermore stress the conversions between ppm_sc and event sets and confirm that the mapping is now consisten.
```release-note
NONE
```
=> test(userspace/libsinsp/test): finish-up ppm_codes filter tests

userspace/chisel/chisel_table.cpp, userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/filterchecks.h
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> sync: release 0.10.5

.github/workflows/ci.yml, .github/workflows/driverkit.yml
/kind cleanup
/area CI
The PR extracts a driverkit workflow from the main ci workflow (that is indeed getting too big).
Fixes #
```release-note
NONE
```
=> cleanup(ci): split a driverkit workflow from main ci workflow.

.github/workflows/driver-api-version.yml, .github/workflows/driver-schema-version.yml
/kind feature
/area CI
Fixes #
```release-note
NONE
```
=> chore(ci): added a ci check for driver schema and api version.

userspace/libscap/engine/gvisor/parsers.cpp
/kind bug
No.
Same changes as https://github.com/falcosecurity/libs/pull/969 , same reason. Luckily, since gVisor support is only currently present in Linux x86_64 we shouldn't have issues currently but that's just out of luck.
Fixes #
```release-note
fix(gvisor): add int64 literals where necessary (remove undefined behavior)
```
=> fix(gvisor): add int64 literals where necessary (remove undefined behavior)

test/e2e/README.md, test/e2e/scripts/run_tests.sh, test/e2e/tests/commons/sinspqa/sinsp.py, test/e2e/tests/conftest.py
/kind cleanup
/kind feature
/area tests
This PR makes a few improvements to the e2e tests:
- Fix a threading issue that prevented the tests from properly finishing when the last test threw an exception.
- Modify the `run-tests.sh` script so that parameters can be passed to `pytest`
- Add flags to skip tests using specific drivers.
Fixes #
```release-note
NONE
```
=> Miscellaneous e2e tests improvements

userspace/libsinsp/examples/README.md, userspace/libsinsp/examples/test.cpp
/kind feature
/area libsinsp
Moreover, print some perf info at the end of the program and updated docs.
Fixes #
```release-note
NONE
```
=> new(userspace/libsinsp): add a `num-events` cmd line option to `sinsp-example`

userspace/libsinsp/examples/test.cpp
/kind bug
/area tests
/area libsinsp
No.
If you try to run e2e tests with Asan you will get LeakSanitizer complaining about the memory that was lost here. Easy fix with a `unique_ptr`.
Fixes #
```release-note
NONE
```
=> fix(test): fix memleak in sinsp-example formatters

.github/workflows/ci.yml
/kind feature
/area tests
No.
Add AddressSanitizer support to the e2e tests as well.
Fixes #
```release-note
NONE
```
=> new(tests): add ASan to e2e tests

cmake/modules/curl.cmake
/kind feature
/area build
No
Update libcurl to fix recent vulnerabilities. As usual, for details check the libcurl website: https://curl.se/docs/security.html
Fixes #
```release-note
update(build): update libcurl to 8.0.1
```
=> update(build): update libcurl to 8.0.1

driver/modern_bpf/definitions/missing_definitions.h, driver/modern_bpf/helpers/extract/extract_from_kernel.h, driver/modern_bpf/programs/attached/events/sched_process_exec.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execve.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/execveat.bpf.c, test/drivers/test_suites/generic_tracepoints_suite/sched_process_exec.cpp, test/drivers/test_suites/syscall_exit_suite/execve_x.cpp, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp, test/e2e/tests/test_event_generator/test_db_program_spawned_process.py, test/e2e/tests/test_event_generator/test_run_shell_untrusted.py
/kind feature
/area tests
No
This PR supports `exe_writable` flag into the modern probe
```release-note
NONE
```
=> new(driver/modern_bpf): support `exe_writable` flag into the modern probe

.github/workflows/update-syscalls.yml, driver/event_stats.h, userspace/libsinsp/test/public_sinsp_API/ppm_sc_codes.cpp
/kind cleanup
/area CI
/area libsinsp
Fixes #
```release-note
NONE
```
=> chore(ci,userspace): improve update syscalls automation

userspace/libscap/scap-int.h, userspace/libscap/scap.c, userspace/libscap/scap_machine_agent.c
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
=> cleanup(scap): clean up scap_machine_agent.c

userspace/libsinsp/events/sinsp_events.h, userspace/libsinsp/events/sinsp_events_ppm_sc.cpp, userspace/libsinsp/examples/test.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> cleanup(libsinsp): `remove-io-sc-state` option for sinsp-example

userspace/libsinsp/plugin.h, userspace/libsinsp/plugin_filtercheck.cpp
/kind feature
/area libsinsp
The `PT_IPNET` was missing and is the only IP network type used.
Fixes #
```release-note
NONE
```
=> new(userspace/libsisnp): support for PT_IPNET type in plugins

userspace/libscap/scap_stats_v2.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_resource_utilization.cpp, userspace/libsinsp/sinsp_resource_utilization.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> cleanup(libsinsp): refactor resource_utilization, adopt scap_stats_v2 schema

driver/bpf/fillers.h, driver/modern_bpf/definitions/missing_definitions.h, driver/modern_bpf/definitions/struct_flavors.h, driver/modern_bpf/helpers/extract/extract_from_kernel.h, driver/ppm_fillers.c
/kind bug
/version driver-API-version-patch
It fixes issues with the 6.3 kernel.
Fixes #1063 
```release-note
fix(driver): fix build and verifier for linux 6.3.
```
=> fix(driver): fixed 6.3 kernel build and verifier issues.

README.md
Fixes #
```release-note
NONE
```
=> update(readme): modern eBPF probe has feature parity and is out of wip.

userspace/libscap/scap.c
/kind bug
/area tests
This PR allows the engine to use the correct mode
```release-note
NONE
```
=> tests(userspace): fix test mode

.github/workflows/ci.yml, driver/modern_bpf/CMakeLists.txt
/kind bug
/kind cleanup
/area build
/area CI
No
This PR should fix the s390x job that is failing. Moreover, I took the chance to merge the 2 s390x jobs in just one, in this way we should also save some time as proposed here https://github.com/falcosecurity/libs/issues/782
```release-note
NONE
```
=> fix(ci): fix s390x CI and remove a duplicated job

README.md
Fixes #
```release-note
NONE
```
=> chore(docs): updated README properly stating that any new kernel release might break drivers build

driver/bpf/filler_helpers.h, driver/modern_bpf/helpers/store/auxmap_store_params.h, test/drivers/test_suites/actions_suite/dynamic_snaplen.cpp, test/drivers/test_suites/syscall_exit_suite/socketcall_x.cpp
/area tests
No
This PR fixes a missing parameter in socketcall tests (https://github.com/falcosecurity/libs/pull/1059/files) and tries to increase the stability of dynamic snaplen tests
```release-note
NONE
```
=> update(tests): fix a broken socketcall test

.clang-format, test/drivers/test_suites/syscall_exit_suite/prctl_x.cpp, userspace/libscap/linux/scap_procs.c, userspace/libsinsp/settings.h
/kind cleanup
/area libscap
/area tests
No
This PR brings really small improvements :) 
```release-note
NONE
```
=> update(userspace): small improvements

userspace/libsinsp/filter.cpp
/kind bug
/kind feature
/area libsinsp
Since we added new field types support in the plugin system, we should support also their comparison operations in case they are defined as list-type fields. This used to be locked-in to only u64s and strings, which were the only previously-supported field types for plugins. Moreover, we also previously forgot to support the `exists` operator for lists 🤭 
Operators `in` and `intersects` are implemented using set-search for list-type fields, by doing comparisons with simple memcmp. Although it's ugly and duplicates the logic of `flt_compare`, it is still aligned with its logic and avoids the need of …
=> update(userspace/libsinsp): support lists of new field types

cmake/modules/cares.cmake
/kind cleanup
/area build
/area libsinsp
No.
Brings it up to date with the latest security enhancements.
Fixes #
```release-note
NONE
```
=> update(cmake): update c-ares to 1.19.1

userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/modern_bpf/scap_modern_bpf.c, userspace/libscap/linux/scap_userlist.c, userspace/libscap/userspace_flag_helpers.h
> /area build
This PR fixes a bunch of warnings I hit. Nothing too groundbreaking, but a tiny step forward to building with -Werror :)
```release-note
NONE
```
=> Fix random build warnings

driver/main.c
/kind cleanup
Fixes #
```release-note
NONE
```
=> chore(driver): avoid useless structure copy in syscall_enter/exit_probe.

.github/workflows/latest-kernel.yml
/kind cleanup
/area CI
Upload generated driverkit config yaml so that it is accessible for future usages
Fixes #
```release-note
NONE
```
=> cleanup(ci): improve latest-kernel workflow.

userspace/libsinsp/filter_check_list.h
/kind bug
/area libsinsp
```release-note
fix(userspace/libsinsp): set filtercheck list desturctor as virtual
```
=> fix(userspace/libsinsp): set filtercheck list desturctor as virtual

userspace/libpman/src/configuration.c
/kind bug
No
This PR fixes an issue with libbpf. This issue is reported here: https://lore.kernel.org/netdev/20220610112648.29695-1-quentin@isovalent.com/T/. We are applying the same patch of bpftool, i.e. we bump `RLIMIT_MEMLOCK` in any case even when the system uses a memcg-based memory accounting.
https://github.com/falcosecurity/falco/issues/2626
```release-note
NONE
```
=> fix(userspace): bump `RLIMIT_MEMLOCK` in any case

userspace/libsinsp/prefix_search.cpp, userspace/libsinsp/prefix_search.h, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/filter_compiler.h, userspace/libsinsp/test/filter_op_bcontains.ut.cpp, userspace/libsinsp/test/filter_op_pmatch.ut.cpp, userspace/libsinsp/test/prefix_search.ut.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> Allow pmatch right hand side to include globs

userspace/libscap/engine/savefile/scap_savefile.c
exe_from_memfd flag added in https://github.com/falcosecurity/libs/pull/1066 is not loaded from scap files. This PR fixes this bug.
/kind bug
> /kind design
> /area build
> /area CI
> /area …
=> Load missing exe_from_memfd file from savefile

cmake/modules/openssl.cmake
/kind bug
/area build
/area libsinsp
No
Keep our OpenSSL dependencies updated with the latest security fixes.
Fixes #
```release-note
NONE
```
=> update(cmake/modules): bump openssl to 1.1.1u

driver/ppm_events_public.h, userspace/libscap/CMakeLists.txt, userspace/libscap/engine/savefile/savefile.h, userspace/libscap/scap.h, userspace/libscap/scap_savefile.h, userspace/plugin/plugin_types.h
/kind cleanup
/area build
/area libscap
Remove the remnants of (consumer side) SunOS support
```release-note
cleanup(scap): remove SunOS support
```
=> cleanup(scap): Remove SunOS support

userspace/libscap/scap.c, userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/filterchecks.h, userspace/libsinsp/test/CMakeLists.txt, userspace/libsinsp/test/events_evt.ut.cpp, userspace/libsinsp/test/events_param.ut.cpp, userspace/libsinsp/test/sinsp_with_test_input.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> cleanup(libsinsp): add `evt.hostname` filter option

driver/modern_bpf/helpers/extract/extract_from_kernel.h, driver/ppm_fillers.c, test/drivers/test_suites/generic_tracepoints_suite/sched_process_exec.cpp, test/drivers/test_suites/syscall_exit_suite/execve_x.cpp, test/drivers/test_suites/syscall_exit_suite/execveat_x.cpp
/kind bug
/area tests
Already bumped
This PR adds some test to memfd detection and fix a bug in the kmod (tests -> :heart: )
```release-note
NONE
```
=> fix(driver): fix memfd detection in the kmod 

userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/test/events_fspath.ut.cpp, userspace/libsinsp/test/filter_compiler.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> Fspath fields make null termination consistent

.gitignore
/kind feature
/area build
No
The `third_party` folder is created by our script `install-deps.sh`, so seems reasonable to ignore it
```release-note
NONE
```
=> new: add `third_party` in gitignore

userspace/libsinsp/container.cpp, userspace/libsinsp/event.h, userspace/libsinsp/fdinfo.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_int.h, userspace/libsinsp/sinsp_observer.h
Introduce `sinsp_observer`, taking over `sinsp_fd_listener`, and have it at `sinsp` level, plus some minor cleanups.
Fixes #
```release-note
refactor(userspace/libsinsp)!: introduce sinsp_observer, taking over sinsp_fd_listener
update(userspace/libsinsp): track_connection_status getter/setter in sinsp
update(userspace/libsinsp): introduce sinsp_evt::get_errorcode()
update(userspace/libsinsp): make sinsp_fdinfo all public and drop friends …
```
=> sinsp_observer

userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/scap_procs.c, userspace/libscap/scap_suppress.c
/kind cleanup
/area libscap
No
This PR disable the suppressed comm logic if not necessary
```release-note
NONE
```
=> cleanup: avoid suppressed logic if not necessary

README.md
/kind cleanup
Properly state in README architectures that we guarantee to be supported and stable (ie: we run CI tests against it) and architectures whose support is experimental.
Fixes #
```release-note
NONE
```
=> chore(docs): add support status for architectures.

.github/workflows/driverkit.yml
/kind feature
/area CI
Fixes #
```release-note
NONE
```
=> new(ci:) add driverkit tests for arm64

.github/workflows/latest-kernel.yml, README.md
/kind feature
/area CI
Fixes #
This PR is using a gist created from my `FedeDP` github account. Github does not support organization gists (https://github.com/orgs/community/discussions/7923). 
We might want to move this under Poiana account in the future.
```release-note
NONE
```
=> new(ci): dynamic badge for latest kernel workflow

README.md
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area tests
> …
=> chore(README.md): add link to the Drivers badge

.github/workflows/kernel_tests.yaml, .github/workflows/pages.yml, README.md, docs/index.md, docs/matrix.md, docs/report.md, docs/syscalls.md, mkdocs.yml, requirements.txt
/kind feature
/area CI
Fixes #1191 
```release-note
new(ci): added drivers testing matrixes and gh pages around them
```
=> new: kernel testing matrix

README.md, mkdocs.yml
/kind bug
Fixes #
```release-note
NONE
```
=> chore(docs): update gh pages urls and title.

README.md
/kind bug
Fixes #
```release-note
NONE
```
=> fix(docs): fixed readme link to kenrel_tests workflow.

.github/workflows/kernel_tests.yaml
> /kind bug
> /kind design
> /area build
/area CI
> /area tests …
=> update(ci/kernel-tests): run kernel tests step by step

.github/workflows/kernel_tests.yaml
/kind cleanup
/area CI
Fixes #
```release-note
NONE
```
=> chore(ci): switch kernel_tests repo to falcosecurity org.

cmake/modules/libscap.cmake, userspace/libscap/CMakeLists.txt, userspace/libscap/libscap.pc.in
Use the same LIBSCAP_INSTALL_LIBS for our install targets and as the starting point for our pkgconfig linker flags.
> /kind bug
/kind cleanup
> /kind design
/area build
> /area CI
/area libscap
> /area …
=> update(cmake): Make sure libscap.pc matches our install behavior

.github/workflows/kernel_tests.yaml
> /kind bug
> /kind design
> /area build
/area CI
> /area tests …
=> update(ci): bump kernel-testing to v.2.2

README.md
/area libscap
This is related to improvement to links between repos and the main documentation website, plus removes some information that was relevant perhaps 2-3 years ago and is not anymore :) 
Fixes #
```release-note
NONE
```
=> update(readme): update readme, link to the falco website

.github/workflows/release-body.yml
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> fix(ci): fixed release-body matrixes path.

userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/fdinfo.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/plugin_table_api.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/threadinfo.cpp
As per title, this syncs the release branch for v0.12.x with #1245 and #1246.
```release-note
NONE
```
=> sync: port #1245 and #1246 to the release-0.12.x branch

.github/workflows/kernel_tests.yaml
/kind cleanup
/area CI
Fixes #
```release-note
NONE
```
=> update(ci): bumped kernel_tests to v0.2.3

.github/workflows/kernel_tests.yaml, .github/workflows/release-body.yml
/kind cleanup
/area ci
Port `5.1.0+driver`  PRs to release branch:
* https://github.com/falcosecurity/libs/pull/1234
* https://github.com/falcosecurity/libs/pull/1238
* https://github.com/falcosecurity/libs/pull/1239
* https://github.com/falcosecurity/libs/pull/1240
* https://github.com/falcosecurity/libs/pull/1241
* https://github.com/falcosecurity/libs/pull/1243
* https://github.com/falcosecurity/libs/pull/1247
Fixes #
```release-note
NONE
```
=> sync: release 0.12.x

cmake/modules/luajit.cmake
/kind bug
> /kind design
/area build
> /area CI
> /area tests
> …
=> update(cmake/modules): bump luajit

driver/bpf/probe.c, driver/main.c, driver/modern_bpf/license/license.bpf.c
No
Since these files are dual licensed under either the MIT or GPL 2, I fixed the inconsistency in our drivers macro. It won't change anything in the way drivers work
```release-note
NONE
```
=> chore: realign drivers license

.github/workflows/driver-schema-version.yml
/kind bug
/kind cleanup
/area CI
This amends a refactor mistake merged in #1273.
```release-note
fix(.github): read right file for schema version checks
```
=> fix(.github): read right file for schema version checks

userspace/libsinsp/examples/test.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> cleanup(libsinsp): add libs g_logger to sinsp-example

userspace/libsinsp/filterchecks.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> cleanup(libsinsp): improve evt.hostname docs

test/vm/README.md, test/vm/containers/ubuntu2204.Dockerfile, test/vm/scripts/compile_drivers.sh, test/vm/scripts/plot_matrix.py, test/vm/scripts/requirements.txt, test/vm/scripts/vm_result.sh
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area tests
> …
=> cleanup(test/vm): remove py matplotlib

.github/workflows/ci.yml, userspace/libsinsp/examples/CMakeLists.txt, userspace/libsinsp/sinsp_debug/CMakeLists.txt
/kind bug
/area CI
/area libsinsp
This makes sure that all targets are built on the emscripten build CI jobs, and that all linking issues are solved.
```release-note
NONE
```
=> fix: solve issues with emscripten build

userspace/libsinsp/examples/CMakeLists.txt, userspace/libsinsp/sinsp_debug/CMakeLists.txt
/kind bug
/area build
Follow-up to my previous PR for fixing a typo. My bad 🤦 .
```release-note
NONE
```
=> fix(userspace/libsinsp): solve cmake link typo

userspace/libsinsp/plugin_manager.h
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> fix(libsinsp): typo in source_idx_by_plugin_id iterator

cmake/modules/libelf.cmake, cmake/modules/openssl.cmake, cmake/modules/tbb.cmake, userspace/libscap/engine/savefile/scap_savefile.c, userspace/libscap/linux/scap_fds.c, userspace/libscap/scap_savefile.c, userspace/libsinsp/event.cpp, userspace/libsinsp/threadinfo.cpp
/kind cleanup
Cherry picks:
* https://github.com/falcosecurity/libs/pull/1321
* https://github.com/falcosecurity/libs/pull/1322
* https://github.com/falcosecurity/libs/pull/1323
* https://github.com/falcosecurity/libs/pull/1324
* https://github.com/falcosecurity/libs/pull/1329
Fixes #
```release-note
NONE
```
=> sync: release 0.13.x

userspace/libscap/scap.c
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
=> fix(scap): don't use generic platform for nodriver full proc scan

userspace/libsinsp/sinsp.h
Give consumers random access to scap files.
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
**Does this PR …
=> update(libsinsp): Make sinsp::fseek public

.github/workflows/ci.yml
/kind cleanup
/area CI
Fixes #
```release-note
NONE
```
=> chore(ci): enforce bundled deps generated binary (sinsp-example) to be as static as possible

.github/workflows/release-body.yml
/kind bug
/area CI
Fixes double quotes usage in release-body workflow; see https://github.com/actions/runner/issues/866
Fixes #
```release-note
NONE
```
=> fix(ci): fixed release-body double quoted string usage.

userspace/libsinsp/CMakeLists.txt
Make the base sinsp dependency scopes PRIVATE. This fixes compilation here on macOS when BUILD_SHARED_LIBS=ON.
> /kind bug
/kind cleanup
> /kind design
/area build
> /area CI
> /area …
=> fix(cmake): Make some dependency scopes private

.github/install-deps.sh, .github/workflows/ci.yml, cmake/modules/libsinsp.cmake
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> chore(cmake): include tinydir

.github/workflows/insecure-api.yml
/kind bug
/area CI
No.
Semgrep 1.42.0 exits the following error in the libs repo. In addition, if a diff between commits is required it exits with error 2, while a full scan returns 0. Since it is a best practice to use a specific version and not automatically the latest, I'm pinning the version and I should probably also open a bug report :sweat_smile: 
```
[ERROR] Fatal error at line /src/userspace/libsinsp/parsers.cpp:1:
Failure: ii_of_name: IdDeref
====[ BEGIN error trace ]====
Failure: ii_of_name: IdDeref
Raised at …
```
=> fix(ci): pin semgrep to 1.41.0

.github/workflows/pages.yml, .github/workflows/release-body-driver.yml
/kind bug
/area CI
I always forget that `actions/download-artifact` does not support regexes.
Fixes #
```release-note
NONE
```
=> fix(ci): fixed download matrixes step for pages and relase-body-driver.

.github/workflows/pages.yml, .github/workflows/release-body-driver.yml, .github/workflows/reusable_kernel_tests.yaml
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> fix(ci): fixed download-artifacts for kernel testing matrixes.

.github/workflows/pages.yml, .github/workflows/release-body-driver.yml, .github/workflows/reusable_kernel_tests.yaml
/kind cleanup
/area CI
Putting the name (master or tagname, or whatever branch name when triggered against a branch), can fail if eg: using a branch name like `new/foo` since `/` is not an accepted char.
Since it is useless, remove the specific altogether.
Fixes #
```release-note
NONE
```
=> chore(ci): there is no need to add specific artifact name for kernel testing matrixes

userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> fix(libsinsp): Add a couple of NULL checks

.github/workflows/ci.yml
Add build-shared-libs-others-amd64 based on build-libs-others-amd64. Only build for macOS for now; Windows will require some nontrivial work.
> /kind bug
/kind cleanup
> /kind design
> /area build
/area CI …
=> update(ci): Add a build-shared-libs-others-amd64 job

userspace/libsinsp/filterchecks.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> fix(libsinsp): Add a NULL check

README.md
/kind cleanup
Drop an unused (non-existent nowadays) badge in the README.
Fixes #
```release-note
NONE
```
=> cleanup(readme): drop unused badge.

userspace/libscap/engine/savefile/scap_savefile.c
This lets us read captures written with newer versions that add new fd types.
/kind bug
> /kind design
> /area build
> /area CI
> /area tests …
=> fix(scap): map unsupported fd types to SCAP_FD_UNSUPPORTED

userspace/libsinsp/plugin_filtercheck.cpp
/kind bug
/area libsinsp
The plugin filtercheck parsing function used when compiling filters was faulted in corner cases involving field arguments. For reference, assuming a valid plugin field `some.field` allowing an argument, both the following used to be accepted whereas the second case is wrong:
- `some.field[some_arg]`
- `some.field_that_does_not_exist[some_arg]`
```release-note
NONE
```
=> fix(userspace/libsinsp): make plugin_filtercheck arg parsing more resilient

.github/workflows/reusable_kernel_tests.yaml
/kind feature
/area CI
Fixes #
```release-note
NONE
```
=> chore(ci): allow to specify a fork for kernel-testing framework.

.github/workflows/reusable_kernel_tests.yaml
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> fix: kernel tests ci

.github/workflows/insecure-api.yml, cmake/modules/curl.cmake, userspace/libpman/src/ringbuffer.c, userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/kmod/scap_kmod.c, userspace/libscap/engine/savefile/scap_savefile.c, userspace/libsinsp/filterchecks.cpp, userspace/libsinsp/parsers.cpp, userspace/libsinsp/plugin_filtercheck.cpp
/kind feature
Backports 
from master.
```release-note
NONE
```
=> sync: release 0.13.2

userspace/libscap/linux/scap_procs.c
/kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests
> …
=> fix(userspace/libscap): use %lu for uint64 as modifier

userspace/libscap/scap_platform_api.c
> /kind bug
> /kind design
> /area build
> /area CI
/area libscap
> /area tests …
=> fix(userspace/libscap): ensure scap_get_fdlist can return SCAP_SUCCESS

userspace/libsinsp/plugin_filtercheck.cpp
/kind bug
/area libsinsp
This amends an issue introduced in https://github.com/falcosecurity/libs/pull/1405 that broke event formatting.
```release-note
NONE
```
=> fix(userspace/libsinsp): make plugin formatter work again

userspace/libsinsp/test/sinsp_with_test_input.h
/kind feature
/area tests
No
This PR adds the possibility to customize the cgroups and in `generate_clone_x_event` there is also the possibility to choose between
```c
PPME_SYSCALL_CLONE_20_X
PPME_SYSCALL_FORK_20_X
PPME_SYSCALL_VFORK_20_X
PPME_SYSCALL_CLONE3_X
```
```release-note
NONE
```
=> test(sinsp): add support for cgroups in clone and execve events

userspace/libscap/engine/savefile/scap_savefile.c
The comment indicate "interface list" in the "user list" function
/area libscap
No
Fix comment in the code.
Fixes #
```release-note
NONE
```
=> docs: fix comment on user list function

.github/workflows/ci.yml, .github/workflows/driver-api-version.yml, .github/workflows/driver-schema-version.yml, .github/workflows/insecure-api.yml, .github/workflows/latest-kernel.yml, .github/workflows/pages.yml, .github/workflows/release-body-driver.yml, .github/workflows/release-body-libs.yml, .github/workflows/reusable_kernel_tests.yaml, .github/workflows/update-syscalls.yml
/kind cleanup
/area CI
No
Like we did in Falco, replace tags with hashes. After this first manual change we can set up dependabot to perform upgrades without having to change hashes manually.
Fixes #
```release-note
NONE
```
=> chore(gha): replace tags with hashes

.github/workflows/driver-api-version.yml, .github/workflows/driver-schema-version.yml, .github/workflows/pages.yml, .github/workflows/release-body-driver.yml
/kind cleanup
/area CI
No.
As per title. Messed up a couple fixes plus upgrade.
Fixes #
```release-note
NONE
```
=> fix(gha): fix bad c&p, upgrade missing actions

userspace/libscap/engine/bpf/scap_bpf.c
/kind cleanup
Cherry picks https://github.com/falcosecurity/libs/pull/1449 from master.
Fixes #
```release-note
sync(release/0.13.x): cherry pick #1449 from master
```
=> sync: release 0.13.4

userspace/libscap/engine/savefile/scap_savefile.c
/area libscap
no
fix a comment in file descriptor list reader function
no
```release-note
NONE
```
=> docs(libscap): fix comment for file descriptor list reader function

userspace/libsinsp/container.h
/kind feature
/area libsinsp
Exposing the list of container engines allows for more control over what is loaded. This would allow adopters to load custom container engines that might not fit in Falco. An example of such a container engine can be found [here](https://github.com/stackrox/collector/blob/e10bebe79d78d50710b204739f124a10451e4d40/collector/lib/ContainerEngine.h), in our use case we only care about the container ID, so we built a catch all engine and used it in place of the default engines.
Fixes # …
=> feature(sinsp): expose container engine list.

userspace/libscap/settings.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/settings.h, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_int.h, userspace/libsinsp/sinsp_public.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libscap
/area libsinsp
> /area tests
> …
=> refactor(userspace): define cleanup

README.md
Fixes #
```release-note
NONE
```
=> chore(docs): add `ppc64le` arch to architectures badge.

.github/workflows/update-syscalls.yml
/kind cleanup
/area CI
Fixes #
```release-note
NONE
```
=> chore(ci): use syscalls-bumper composite action.

userspace/libsinsp/parsers.cpp
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp): fix possible segv in parse_connect_exit + cleanups

test/drivers/test_suites/syscall_exit_suite/recvmsg_x.cpp
Correct s390x build break by using `__NR_accept4` instead of `__NR_accept`.
/kind bug
> /kind design
/area build
> /area CI
/area tests
**Does this PR require a change in the …
=> fix(update/drivers): correct `s390x` build break

userspace/chisel/chisel.cpp
/kind bug
> /kind design
/area build
> /area CI
> /area tests
> /version …
=> fix(chisel): resolve compilation issue on win32

.github/workflows/update-syscalls.yml
/kind bug
/area CI
Should fix failing ci: https://github.com/falcosecurity/libs/actions/runs/7054960824/job/19204648324
Fixes #
```release-note
NONE
```
=> fix(ci): fixed update-syscalls syscalls-bumper action version.

test/libscap/test_suites/engines/gvisor/gvisor_parsers.cpp, userspace/libscap/engine/gvisor/gvisor.h, userspace/libscap/engine/gvisor/parsers.cpp
/kind bug
no
A recent PR that I pushed might introduce corner cases where a few variables are left uninitialized. This change fixes that. 
Fixes #
```release-note
NONE
```
=> fix: potentially uninitialized variables

cmake/modules/CompilerFlags.cmake, driver/dynamic_params_table.c, driver/event_table.c, driver/fillers_table.c, test/libscap/helpers/engines.cpp, userspace/libscap/linux/scap_cgroup.c, userspace/libsinsp/events/sinsp_events_ppm_sc.cpp, userspace/libsinsp/ifinfo_test.cpp, userspace/libsinsp/plugin.h, userspace/libsinsp/plugin_manager.h, userspace/libsinsp/procinfo_test.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/sinsp_filtercheck_syslog.cpp, userspace/libsinsp/sinsp_filtercheck_syslog.h, userspace/libsinsp/sinsp_syslog.cpp, userspace/libsinsp/sinsp_syslog.h, userspace/libsinsp/test/container_info.ut.cpp, userspace/libsinsp/test/plugins/sample_table.h, userspace/libsinsp/tuples.cpp, userspace/libsinsp/utils.cpp
/kind cleanup
/area build
no
The change removes a bunch of compiler warnings emerged during an experimental build with Clang 17. Some of these do detect potentially serious bugs.
Fixes #
```release-note
NONE
```
=> build: Fix Clang warnings

userspace/libsinsp/event.h
Event extraction can be cached based on the event number. Add a setter so that externally constructed events can be cached correctly.
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI …
=> update(libsinsp): Add sinsp_evt::set_num

userspace/libsinsp/test/filterchecks/k8s.cpp
/kind feature
/area tests
No
This PR adds a test to check the syntax of  `k8s.pod.label`. See https://kubernetes.slack.com/archives/CMWH3EH32/p1701545841475519
```release-note
NONE
```
=> new(test): check `k8s.pod.label` syntax

userspace/libsinsp/cri.hpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> chore(libsinsp): remove redundant semicolon

userspace/libscap/libscap.pc.in, userspace/libsinsp/libsinsp.pc.in
Set the various paths in our .pc files based on the `pcfiledir` variable instead of using absolute paths. This should make it possible to install using a DESTDIR that differs from CMAKE_INSTALL_PREFIX.
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
> /area …
=> update(libsinsp,libscap): Make our .pc file paths relative

.github/workflows/ssh.yaml
/kind feature
/area CI
Enable actuated ssh workflow: https://docs.actuated.dev/tasks/debug-ssh/
Fixes #
```release-note
NONE
```
=> new(ci): added actuated ssh workflow.

cmake/modules/re2.cmake
We build re2.lib on Windows; make sure we install that. We don't expose the re2 includes externally, so it shouldn't be necessary to install them.
> /kind bug
/kind cleanup
> /kind design
/area build
> /area CI
> …
=> update(cmake): Make sure we install our library on Windows

userspace/libsinsp/fdinfo.h, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/test/filterchecks/fd.cpp
/kind cleanup
/area libsinsp
No
This PR removes some dead code and add some `inline` and `const`
```release-note
NONE
```
=> cleanup(sinsp): remove some dead code

userspace/libscap/scap_procs.c, userspace/libsinsp/fdinfo.cpp
/kind bug
/area libscap
/area libsinsp
Fix some issues raised by clang-tidy with `clang-analyzer-cplusplus-*` checks.
Fixes #
```release-note
NONE
```
=> Fix some issues raised by clang-tidy

userspace/chisel/chisel_api.cpp, userspace/chisel/chisel_viewinfo.cpp, userspace/libsinsp/async/async_key_value_source.tpp, userspace/libsinsp/cgroup_limits.cpp, userspace/libsinsp/cgroup_list_counter.h, userspace/libsinsp/container.cpp, userspace/libsinsp/container_engine/container_async_source.tpp, userspace/libsinsp/container_engine/container_engine_base.cpp, userspace/libsinsp/container_engine/cri.cpp, userspace/libsinsp/container_engine/docker/async_source.cpp, userspace/libsinsp/container_engine/docker/base.cpp, userspace/libsinsp/container_engine/docker/connection_linux.cpp, userspace/libsinsp/container_engine/docker/docker_linux.cpp, userspace/libsinsp/container_engine/mesos.cpp, userspace/libsinsp/container_info.cpp, userspace/libsinsp/cri.hpp, userspace/libsinsp/examples/test.cpp, userspace/libsinsp/ifinfo.cpp, userspace/libsinsp/logger.cpp, userspace/libsinsp/logger.h, userspace/libsinsp/logger_macros.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/procfs_utils.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_int.h, userspace/libsinsp/test/public_sinsp_API/sinsp_logger.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/user.cpp, userspace/libsinsp/utils.cpp
> /kind bug
/kind cleanup
/kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor: new sinsp logger implementation

userspace/libscap/debug_log_helpers.h, userspace/libscap/engine/gvisor/gvisor.cpp, userspace/libscap/engine/kmod/scap_kmod.c, userspace/libsinsp/event.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp_filtercheck_container.cpp, userspace/libsinsp/sinsp_suppress.cpp, userspace/libsinsp/threadinfo.cpp
/kind feature
/area build
No
This PR sync the release branch with latest commits
- https://github.com/falcosecurity/libs/pull/1597
- https://github.com/falcosecurity/libs/pull/1598
- https://github.com/falcosecurity/libs/pull/1599
- https://github.com/falcosecurity/libs/pull/1603
- https://github.com/falcosecurity/libs/pull/1604
- https://github.com/falcosecurity/libs/pull/1606
- https://github.com/falcosecurity/libs/pull/1607
```release-note
NONE
```
=> chore: sync for 0.14.1

.github/workflows/release-body-driver.yml, .github/workflows/release-body-libs.yml
/kind bug
/area CI
Bumps rn2md to latest master that fixes a couple of issues. See https://github.com/leodido/rn2md/pull/13.
Fixes #
```release-note
NONE
```
=> chore(ci): bumped rn2md to latest master.

.github/workflows/drivers_ci.yml
/kind cleanup
/area CI
Fixes #
```release-note
NONE
```
=> chore(ci): properly use actuated helper action to install arm64 headers.

cmake/modules/engine_config.cmake
> /kind bug
> /kind design
/kind feature
/area build
> /area CI
> /area tests
> /version …
=> feat(cmake): selectively disable bpf and kmod engines

userspace/libsinsp/logger.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp): check on requested severity

userspace/libsinsp/cri.hpp, userspace/libsinsp/test/plugins.ut.cpp
/kind cleanup
/area libsinsp
When doing a debug build, I encountered a couple of warnings and failed test assertions that I think should be addressed.
```release-note
NONE
```
=> fix(userspace/libsinsp): fix some warnings and failed assertions in debug mode

userspace/libsinsp/filter/parser.cpp, userspace/libsinsp/filter/parser.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(userspace/libsinsp): modularize parse_check and split into different helpers

userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> cleanup(libsinsp): adjust setting max_thread_table_size

.github/workflows/ci.yml, cmake/modules/libelf.cmake, test/e2e/tests/commons/sinspqa/event_generator.py
/kind cleanup
Syncs:
* https://github.com/falcosecurity/libs/pull/1666
* https://github.com/falcosecurity/libs/pull/1664
from master into release/0.14.x branch.
The latter is useful to fix CI tests.
Fixes #
```release-note
NONE
```
=> sync: release 0.14.3

.github/workflows/pages.yml
/kind bug
/area CI
The new `reusable_kernel_tests` workflow: https://github.com/falcosecurity/libs/blob/master/.github/workflows/reusable_kernel_tests.yaml makes use of kernel-testing provided composite action that just names matrix artifacts as `matrix.md` since it does not use arch-specific names.
Fix for this in the `pages` workflow.
Fixes #
```release-note
NONE
```
=> fix(ci): fixed pages workflow.

.github/workflows/update-syscalls.yml
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> fix(ci): fixed update-syscalls input.

cmake/modules/valijson.cmake
/kind cleanup
/area build
Fixes #
```release-note
NONE
```
=> update(cmake): bumped valijson to latest version.

test/drivers/test_suites/syscall_exit_suite/process_vm_readv_x.cpp
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area tests
> /version …
=> fix(test): improve process_vm_readvX failure test

test/drivers/test_suites/syscall_exit_suite/process_vm_readv_x.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area tests
> /version …
=> fix(test/driver): fix process_vm_readv concurrency

.github/workflows/ci.yml, cmake/modules/luajit.cmake
> /kind bug
> /kind design
> /area build
> /area CI
> /area tests
> /version …
=> chore(ci): enable chisels on win32 build

userspace/libpman/src/stats.c
/kind bug
> /kind design
> /area build
> /area CI
/area libpman
> /area tests
> /version …
=> fix(libpman): fix compilation issue with -Werror

.github/workflows/ci.yml, .github/workflows/e2e_ci.yml, test/libsinsp_e2e/container/container.cpp, test/libsinsp_e2e/event_capture.cpp, test/libsinsp_e2e/event_capture.h, test/libsinsp_e2e/sys_call_test.cpp, userspace/libscap/examples/01-open/scap_open.c, userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/fdinfo.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/threadinfo.cpp
/kind cleanup
/area libsinsp
Cherry picks https://github.com/falcosecurity/libs/pull/1753  and https://github.com/falcosecurity/libs/pull/1754 from master to release/0.15.x branch.
Fixes #
```release-note
NONE
```
=> sync: release 0.15.x

cmake/modules/curl.cmake
/kind feature
/area build
No
Yesterday a an update with security content was released for libcurl. This integrates the latest fixes.
Fixes #
```release-note
NONE
```
=> update(build): update libcurl to 8.7.1

cmake/modules/re2.cmake
/kind bug
> /kind design
/area build
> /area CI
> /area tests
> /version …
=> fix(cmake/modules/re2): fix configure issue on cmake >=3.29.1

cmake/modules/re2.cmake
/kind bug
> /kind design
/area build
> /area CI
> /area tests
> /version …
=> fix(cmake/modules/re2): use sed compatible syntax w/ macos

driver/modern_bpf/helpers/extract/extract_from_kernel.h
/kind bug
No
This PR fixes the cases in which the `struct task_struct` doesn't contain the field `thread_info` returning always `false`. If task_struct has no embedded thread_info, we cannot deduce anything. We just return `false`.
NOTE: this means that emulated 32bit syscalls will be parsed as 64bits syscalls.
Fixes https://github.com/falcosecurity/libs/issues/1804
```release-note
NONE
```
=> fix(driver/modern_bpf): address task_struct has no embedded thread_info

.github/workflows/e2e_ci.yml
/kind bug
> /kind design
> /area build
/area CI
> /area tests
> /version …
=> fix(e2e_ci): always update apt index

userspace/libscap/linux/scap_procs.c, userspace/libsinsp/test/sinsp_utils.ut.cpp, userspace/libsinsp/utils.cpp
/kind feature
/area libscap
/area libsinsp
Sync the following PRs:
* https://github.com/falcosecurity/libs/pull/1818
```release-note
NONE
```
=> sync release 0.16.x

.github/workflows/release-body-driver.yml
/kind bug
/area CI
This is exact same fix as https://github.com/falcosecurity/libs/pull/1684 but for release-body-driver workflow.
Fixes #
```release-note
NONE
```
=> fix(ci): fixed release-body-driver workflow.

userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/user.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp): avoid unintented copies

userspace/libsinsp/sinsp.cpp
/kind cleanup
/area libsinsp
No
Function `sinsp::get_file_size` has two implementation depending on the architecture: Linux or Windows. The C++ standard library allows to get the size of a file in a portable way and has been used to refactor this function.
Fixes #
```release-note
NONE
```
=> refactor: use C++ std lib for sinsp::get_file_size

userspace/libpman/src/ringbuffer.c
/kind bug
/area libpman
No
This is not a real bug for us since in the modern probe we don't use the `bpf_ringbuf_discard` helper but if we decide to do it, this could become a huge bug. 
```release-note
NONE
```
=> fix(libpman): manage discarded events

userspace/libsinsp/parsers.cpp, userspace/libsinsp/sinsp_filtercheck_container.cpp, userspace/libsinsp/sinsp_filtercheck_event.cpp, userspace/libsinsp/sinsp_filtercheck_evtin.cpp, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/sinsp_filtercheck_k8s.cpp, userspace/libsinsp/sinsp_filtercheck_mesos.cpp, userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/sinsp_filtercheck_tracer.cpp
/kind bug
/area libsinsp
While bumping the libs dependency in Falco I noticed a bunch of rightful complaints about unsafe OOB access to string views elements.
/milestone 0.17.0
```release-note
NONE
```
=> fix(userspace/libsinsp): solve cases of unsafe string_view access

.github/workflows/drivers_ci.yml, .github/workflows/e2e_ci.yml
/kind bug
/area CI
```release-note
NONE
```
=> fix(ci): fix drivers_ci trigger and update get-kernel-sources sha

userspace/libsinsp/filter.cpp, userspace/libsinsp/sinsp_filtercheck.cpp, userspace/libsinsp/state/dynamic_struct.h
/kind bug
/area libsinsp
The sanitizers in Falco exposed many subtle points where we did the wrong thing in the libsinsp code area related to filter checks. This fixes a bunch of them, and should supposedly unblock the libs version bump in Falco.
```release-note
fix(userspace/libsinsp): solve a bunch of bugs in the filter checks area
```
=> fix(userspace/libsinsp): solve a bunch of bugs in the filter checks area

userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> cleanup(libsinsp): remove unused member from threadinfo

userspace/libsinsp/test/parsers/parse_connect.cpp
/kind feature
/area tests
No
While I was trying other things I added this test. Nothing to shout about but it is better than nothing.
```release-note
NONE
```
=> new(test): add a test for a bind with unix socket

test/e2e/tests/conftest.py
/kind cleanup
/area tests
When e2e test fails it would be great to be able to check full sinsp log (stderr too!)
Fixes #
```release-note
NONE
```
=> chore(test/e2e): redirect stderr to stdout.

.github/actions/composite-perf/action.yml
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> chore(ci): small fix in output names.

.github/actions/composite-perf/action.yml, .github/workflows/perf.yml
/kind bug
/area CI
Fixes #
```release-note
NONE
```
=> fix(ci): fixed heaptrack data path (zst extension).

cmake/modules/zlib.cmake
> /kind bug
/kind cleanup
> /kind design
/area build
> /area CI
> /area tests
> /version …
=> chore(cmake/modules): bump zlib to 1.3.1

driver/main.c
/kind cleanup
Cherry picks #1884 from master.
Fixes #
```release-note
NONE
```
=> sync: release 0.17.x

.github/workflows/create-comment-kernel-testing.yml
/kind cleanup
/area CI
Same as #2017 for kernel testing create comment workflow.
Fixes #
```release-note
NONE
```
=> chore(ci): update kernel-testing related matrix comment if already existent

.git-blame-ignore-revs
/kind cleanup
/area build
This PR ignores the commit used for formatting
```release-note
NONE
```
=> chore: ignore the commit used for formatting

.github/workflows/format.yml
> /kind bug
/kind cleanup
> /kind design
> /area build
/area CI
> /area tests
> /version …
=> ci: pin dependencies

.github/workflows/perf.yml
/kind cleanup
/area CI
Same threshold used for google benchmarks.
Sometimes it fails spuriously with only 1% threshold: https://github.com/falcosecurity/libs/actions/runs/10879002020/job/30182876688?pr=2069
Fixes #
```release-note
NONE
```
=> chore(ci): bumped perf unit tests threshold to 5% (relative) slowdown.

userspace/libsinsp/container.cpp, userspace/libsinsp/sinsp.cpp
/kind cleanup
/area libsinsp
N/A
We've found that the "Flushing..." log messages appear very frequently in the logs, but don't provide much information in themselves. I've downgraded the messages to SEV_DEBUG to clean up the logs a little.
N/A
Fixes #
No
```release-note
NONE
```
=> chore: downgrade flushing log messages to debug

userspace/libsinsp/parsers.cpp
/kind bug
/area libsinsp
Fixes #
```release-note
fix(userspace/libsinsp): avoid dereferencing a possible nullptr in parsers
```
=> fix(userspace/libsinsp): avoid dereferencing a possible nullptr in parsers

userspace/libsinsp/sinsp_filter_transformer.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> update(libsinsp): introduce a description to sinsp_filter_transformer

userspace/libsinsp/sinsp.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(libsinsp): allow reading scap from stdin

userspace/libsinsp/state/table.cpp
/kind feature
/area libsinsp
No
Allows creating built-in tables of string type.
Fixes #
```release-note
NONE
```
=> chore(state): add string specialization for built_in_table

userspace/libsinsp/fdinfo.cpp, userspace/libsinsp/fdinfo.h, userspace/libsinsp/parsers.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(libsinsp): simplify `set_net_role_by_guessing` in fdinfo

userspace/libsinsp/ifinfo.cpp, userspace/libsinsp/ifinfo.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(libsinsp): improve ifinfo immutability checks and readability

userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_fdinfo_factory.h, userspace/libsinsp/sinsp_threadinfo_factory.h
> /kind bug
/kind cleanup
/kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(libsinsp/parser): isolate `sinsp_parser` component

userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> perf(sinsp/parsers): restructure recvmsg `SCM_RIGHTS` processing

.github/workflows/drivers_ci.yml, test/libscap/helpers/engines.cpp, test/libscap/test_suites/userspace/scap_event.cpp, test/libscap/test_suites/userspace/scap_ppm_sc.cpp, userspace/libscap/engine/source_plugin/CMakeLists.txt, userspace/libscap/engine/source_plugin/source_plugin.c, userspace/libscap/linux/scap_ppm_sc.c, userspace/libscap/scap.def, userspace/libscap/scap.h, userspace/libscap/scap_event.c, userspace/libsinsp/events/sinsp_events_ppm_sc.cpp, userspace/libsinsp/test/public_sinsp_API/ppm_sc_codes.cpp
/kind cleanup
/area CI
As stated in #2271 enable ubsan in libscap tests CI.
Fixes #
```release-note
NONE
```
=> chore(ci): enable ubsan for libscap tests

.gitignore
> /kind bug
/kind cleanup
> /kind design
/area build
> /area CI
> /area tests
> /version …
=> cleanup: Add .DS_Store to .gitignore

userspace/libsinsp/sinsp_fdinfo_factory.h, userspace/libsinsp/sinsp_mode.h, userspace/libsinsp/sinsp_threadinfo_factory.h
> /kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> docs(userspace/libsinsp): add missing licenses

userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(userspace/libsinsp): ignore malformed recvmsg ancillary data

userspace/libsinsp/filter/escaping.cpp, userspace/libsinsp/test/string_visitor.ut.cpp
/kind bug
/area libsinsp
No.
Properly escape `=` characters in condition expressions when printing the condition as a string.
Fixes #2323
no
```release-note
Properly escape `=` characters in condition expressions when printing the condition as a string.
```
=> Escape equals ast values

cmake/modules/container_plugin.cmake
/kind cleanup
/area build
Fixes #
```release-note
NONE
```
=> update(cmake): bumped container_plugin.

.github/actions/install-zig/action.yml
/kind bug
> /kind design
> /area build
/area CI
> /area tests
> /version …
=> fix(ci): fix zig download link

userspace/libsinsp/fdtable.cpp, userspace/libsinsp/fdtable.h, userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp_fdtable_factory.h, userspace/libsinsp/sinsp_threadinfo_factory.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(userspace/libsinsp): convert some double pointers to ref

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/thread_manager.h, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: move host and port res flag into signature

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(libsinsp)!: move fd filtering logic out of `add_fd_from_scap`

userspace/libsinsp/event.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/utils.cpp, userspace/libsinsp/utils.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: pass references to `*_to_string` utils

userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/threadinfo.cpp, userspace/libsinsp/threadinfo.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: pass ipv4 server ports as func parameter

userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(userspace/libsinsp): fix type mismatch warning in `parsers.cpp`

userspace/libsinsp/threadinfo.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(userspace/libsinsp): remove unneeded `this` lambda capture

userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/thread_manager.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(libsinsp/userspace): simplify thread mgr reference chains

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/thread_manager.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: extract thread mgr accessors/tables logics

userspace/libsinsp/thread_manager.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(userspace/libsinsp): pass references to internal thread manager utilities

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/classes/sinsp_thread_manager.cpp, userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/thread_manager.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: remove dependency on parser from thread mgr

.github/workflows/release-body.yml
/kind feature
/area CI
The PR adds a badge pointing out latest kernel release successful build for our drivers in the release body.
I find it useful to know for each driver version which is the latest officially supported kernel release.
Fixes #
```release-note
NONE
```
=> new(ci): add latest_kernel badge to driver release body.

userspace/libsinsp/sinsp.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: remove unused `sinsp` public APIs

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/test/classes/sinsp_thread_manager.cpp, userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/thread_manager.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: use `timestamper` in thread mgr

userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(userspace/libsinsp): add const/static to parser's methods

userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_thread_manager_factory.h, userspace/libsinsp/test/classes/sinsp_thread_manager.cpp, userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/thread_manager.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: isolate `sinsp_thread_manager` from `sinsp`

.github/workflows/e2e_ci.yml
> /kind bug
/kind cleanup
> /kind design
> /area build
/area CI
> /area tests
> /version …
=> ci: remove duplicate clang line in e2e_ci.yml

userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_parser_verdict.h, userspace/libsinsp/thread_manager.cpp
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: introduce parser verdict

.github/workflows/drivers_ci.yml
/kind bug
/area CI
Same fix as https://github.com/falcosecurity/falco/pull/3537
Fixes #
```release-note
NONE
```
=> fix(ci): fixed drivers_ci fedora container usage.

userspace/libsinsp/parsers.cpp, userspace/libsinsp/parsers.h, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp_filtercheck_fd.cpp, userspace/libsinsp/sinsp_filtercheck_fspath.cpp
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsisnp)!: clean `sinsp_parser` component

userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/test/events_proc.ut.cpp
> /kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> update(libsinsp): support indexed proc.args access

userspace/libsinsp/dumper.h
> /kind bug
/kind cleanup
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp)!: remove unused `sinsp_dumper::m_inspector`

test/libsinsp_e2e/thread_state.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/test/thread_table.ut.cpp
> /kind bug
/kind cleanup
/kind design
/kind feature
> /area build
> /area CI
/area libsinsp
/area tests …
=> feat(userspace/libsinsp)!: remove `sinsp::{add, remove}_thread()`

userspace/libsinsp/parsers.cpp
/kind bug
/kind cleanup
> /kind design
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> refactor(userspace/libsinsp): cleanup `sinsp_parser::reset()`

test/e2e/tests/commons/sinspqa/sinsp.py
/kind bug
/area tests
Finally fixes e2e tests CI flakiness :)
Already restarted the CI many times; all failures i see come from container plugin 0.2.1 bug with podman, that will be solved with 0.2.2 (https://github.com/falcosecurity/libs/pull/2394); see CI runs: https://github.com/falcosecurity/libs/actions/runs/14865106080
Fixes #
```release-note
NONE
```
=> fix(test/e2e): rewrite `assert_events` to avoid ending too soon sinsp-example log matching

driver/modern_bpf/helpers/base/maps_getters.h, driver/modern_bpf/helpers/base/shared_size.h, driver/modern_bpf/helpers/interfaces/syscalls_dispatcher.h, driver/modern_bpf/maps/maps.h, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/recvmmsg.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/sendmmsg.bpf.c, driver/modern_bpf/programs/tail_called/events/syscall_dispatched_events/socket.bpf.c, userspace/libpman/include/libpman.h, userspace/libpman/src/maps.c, userspace/libpman/src/sc_set.c, userspace/libscap/engine/source_plugin/source_plugin.c
/kind cleanup
Cherry picks:
* https://github.com/falcosecurity/libs/pull/2397 
* https://github.com/falcosecurity/libs/pull/2401
* https://github.com/falcosecurity/libs/pull/2399
from master.
Fixes #
```release-note
NONE
```
=> sync: release 0.21.x

test/libsinsp_e2e/forking.cpp, test/libsinsp_e2e/fs.cpp, test/libsinsp_e2e/process.cpp, test/libsinsp_e2e/suppress_events.cpp, test/libsinsp_e2e/tcp_client_server_ipv4_mapped.cpp, test/libsinsp_e2e/thread_state.cpp, userspace/libsinsp/event.cpp, userspace/libsinsp/sinsp.cpp, userspace/libsinsp/sinsp.h, userspace/libsinsp/sinsp_filtercheck_thread.cpp, userspace/libsinsp/test/classes/sinsp_thread_manager.cpp, userspace/libsinsp/test/classes/sinsp_threadinfo.cpp, userspace/libsinsp/test/filterchecks/proc.cpp, userspace/libsinsp/test/helpers/threads_helpers.h, userspace/libsinsp/test/parsers/parse_brk.cpp, userspace/libsinsp/test/parsers/parse_clone.cpp, userspace/libsinsp/test/parsers/parse_connect.cpp, userspace/libsinsp/test/parsers/parse_execve.cpp, userspace/libsinsp/test/parsers/parse_prctl.cpp, userspace/libsinsp/test/parsers/parse_proc_exit.cpp, userspace/libsinsp/test/parsers/parse_setregid.cpp, userspace/libsinsp/test/parsers/parse_setreuid.cpp, userspace/libsinsp/test/scap_files/kexec_arm64/kexec_arm64.cpp, userspace/libsinsp/test/scap_files/kexec_x86/kexec_x86.cpp, userspace/libsinsp/test/sinsp_with_test_input.cpp, userspace/libsinsp/test/suppress.ut.cpp, userspace/libsinsp/test/thread_table.ut.cpp
> /kind bug
/kind cleanup
/kind design
/kind feature
> /area build
> /area CI
/area libscap
/area tests …
=> feat(userspace/libsinsp)!: remove `sinsp::get_thread_ref()`

userspace/libsinsp/test/scap_files/converter_tests.cpp
> /kind bug
> /kind design
/kind feature
> /area build
> /area CI
/area libsinsp
/area tests
> /version …
=> test(sinsp/scap_files): add accept events conversion tests

userspace/libscap/scap_print_event.c
> /kind bug
> /kind design
> /kind test
/kind feature
> /area build
> /area CI
/area libscap
> /area tests
> /version …
=> feat(userpace/libscap): add printing support for `PT_DYN` parameters

OWNERS
> /kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> vote: doc(OWNERS): add `ekoops` to approvers

userspace/libsinsp/value_parser.cpp
Avoid repeating `getservbyname` call in `sinsp_filter_value_parser::string_to_rawval`.
> /kind bug
> /kind design
> /kind test
> /area build
> /area CI
/area libsinsp
> /area tests
> …
=> chore(libsinsp): avoid repeating getservbyname

OWNERS
> /kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> doc(OWNERS): move incertum (Melissa Kilby) to emeritus_approvers

userspace/libsinsp/event.h, userspace/libsinsp/parsers.cpp
/kind cleanup
/area libsinsp
Remove some unused `sinsp_evt` init methods, and some cleanup to improve readability.
Fixes #
```release-note
NONE
```
=> sinsp_evt init cleanup

userspace/libsinsp/thread_manager.cpp, userspace/libsinsp/thread_manager.h
/kind feature
/area libsinsp
Implement timed reset for proc lookup counters
Fixes #
```release-note
feat(libsinsp): implement timed reset for proc lookup counters
```
=> feat(libsinsp): implement timed reset for proc lookup counters

userspace/libsinsp/test/scap_files/converter_tests.cpp
> /kind bug
> /kind design
/kind test
> /area build
> /area CI
/area tests
> /version …
=> test(userpsace/libsinsp): add scap conversion test for `splice_x`

userspace/libsinsp/examples/test.cpp
/kind feature
/area libsinsp
Add -T option to sinsp-example, to report the tables structure. Needless to say, when used in combination with `-p` will prints out all the tables defined by the plugin, and the added dynamic fields.
Fixes #
```release-note
NONE
```
=> feat(userspace/libsinsp/example): add -T option to print available tables

userspace/libsinsp/parsers.cpp
/area libsinsp
Missed from https://github.com/falcosecurity/libs/pull/2207, the comment makes no sense now. Drop it.
Fixes #
```release-note
NONE
```
=> chore(libsinsp): clean "detect container id" comments

userspace/libsinsp/sinsp_external_processor.h
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(userspace/libsinsp): fix threadinfo ctor params forward decl

userspace/libsinsp/parsers.cpp
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> fix(userspace/libsinsp): fix recv data buffer index

test/libsinsp_e2e/process.cpp
> /kind bug
> /kind design
/kind test
> /area build
> /area CI
/area tests
> /version …
=> test(libsinsp_e2e): increase context switching to reduce flakyness

.github/actions/install-zig/action.yml
> /kind bug
> /kind design
> /kind test
> /area build
/area CI
> /area tests
> /version …
=> ci: bump zig version from `0.14.1` to `0.15.1`

OWNERS
> /kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> vote: update(OWNERS): add Gerald Combs (geraldcombs) to approvers

OWNERS
> /kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> update(OWNERS): add Iacopo Rozzo (irozzo-1A) as reviewer

userspace/libsinsp/examples/CMakeLists.txt, userspace/libsinsp/examples/perftest.cpp, userspace/libsinsp/examples/perftest.h, userspace/libsinsp/examples/test.cpp
> /kind bug
> /kind design
/kind test
/kind feature
> /area build
> /area CI
/area libsinsp
> /area tests
> /version …
=> feat(userspace/libsinsp/examples): add memory usage stats

OWNERS
> /kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> update(OWNERS): add Tero Kauppinen (terror96) as reviewer

driver/bpf/probe.c, driver/main.c, driver/socketcall_to_syscall.h
> /kind bug
/kind cleanup
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> refactor(driver): simplify socketcall handling logic

proposals/20250923-plugin-system-event-schema-versioning.md
> /kind bug
/kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> doc: add plugin driver event schema check proposal

userspace/libscap/engine/bpf/scap_bpf.c, userspace/libscap/engine/bpf/scap_bpf.h
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> fix(ebpf): do not map overlapping perf event buffers

userspace/libpman/src/lifecycle.c
> /kind bug
/kind cleanup
> /kind design
> /kind test
> /area build
> /area CI
/area libpman
> /area tests
> /version …
=> chore(userpsace/libpman): disable logging while searching for ksym btf

userspace/libscap/engine/savefile/converter/converter.cpp, userspace/libscap/engine/savefile/converter/table.cpp, userspace/libscap/engine/savefile/converter/types.h
/kind bug
> /kind design
> /kind test
> /area build
> /area CI
> /area tests
> /version …
=> fix(userspace/libscap/engine/savefile): fall back in case of exception
